### ISSUE TITLE
Earth Defense Force 4.1 (410320)

### ISSUE THREAD

**Issue by nentibusarchitectura** [ValveSoftware/Proton#1193]
Earth Defense Force 4.1 runs on my computer at 60fps solid.

However:

* There is no audio at all
* The fonts are wrong (see attached screenshot) and some options can't be read.
![edf screenshot](https://user-images.githubusercontent.com/6814626/44961026-caf9d980-af01-11e8-8488-1c665439f2e1.png)

[System Gist](https://gist.github.com/nentibusarchitectura/652dbdaecc32f3ca5f625a0e921c96c9#file-gistfile1-txt)

I haven't tested network co-op yet.

**Comment by setsunati** [comment]
Try installing xact with Protrontricks. https://github.com/Sirmentio/protontricks
If audio is crackling, popping, echoing, etc. try this. https://www.youtube.com/watch?v=UQ-Ml78kiEE

**Comment by nentibusarchitectura** [comment]
Tried the game again today and surprise, the audio now works somehow.

Local co-op works perfectly using two xbox wireless controllers
Online co-op works perfectly too.

The game is solid 60fps, it runs a bit smoother than it does in windows!

**Comment by Zlopez** [comment]
# Compatibility Report
- Name of the game with compatibility issues: EARTH DEFENSE FORCE 4.1 The Shadow of New Despair
- Steam AppID of the game: 410320

## System Information
- GPU: Radeon RX 590
- Driver/LLVM version: 4.5 Mesa 18.3.2
- Kernel version: 4.20.13-200.fc29.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Zlopez/1433022f5f75aebc3155a622997b2997
- Proton version: 3.16-8

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Proton log: [steam-410320.txt](https://github.com/ValveSoftware/Proton/files/2949253/steam-410320.txt)

## Symptoms
The game freezes when clicking on game slot. It also shows error that it can't find directory for save data.
![Screenshot from 2019-03-10 10-09-01](https://user-images.githubusercontent.com/6943409/54082892-90438480-431c-11e9-9c38-df342fe2178a.png)
![Screenshot from 2019-03-10 10-09-32](https://user-images.githubusercontent.com/6943409/54082896-a05b6400-431c-11e9-827b-093c1a8082cf.png)

## Reproduction
1. Start the game
2. Choose the slot for game

**Comment by kisak-valve** [comment]
Hello @Zlopez, your log is missing a header that was added with Proton 3.16-7, which hints you're not using the version of Proton you expected. Please opt into Steam's beta client and/or go to Steam -> Library dropdown -> Tools and install Proton 3.16 beta from the list.

**Comment by Zlopez** [comment]
@kisak-valve 
Strange, Steam is telling me that I'm using 3.16-8 (See screenshot). How can I know which version I'm actually running?
![Screenshot from 2019-03-10 15-31-34](https://user-images.githubusercontent.com/6943409/54086429-9ef46080-4349-11e9-9757-6389951874cd.png)

EDIT: I even checked how the game is started and I see this:
`python3 /var/home/zlopez/.local/share/Steam/steamapps/common/Proton 3.16 Beta/proton waitforexitandrun /var/home/zlopez/.local/share/Steam/steamapps/common/Earth Defense Force 4.1/EDF41.exe`
So it looks like I'm running at least Proton 3.16 Beta. But I'm not sure which version exactly.

EDIT2: Ok, this is what I found in the `/var/home/zlopez/.local/share/Steam/steamapps/common/Proton 3.16 Beta/proton` script:
`CURRENT_PREFIX_VERSION="3.16-1"`

So I'm wondering why the version wasn't updated.

EDIT3: I opt in to Steam beta and the Proton 3.16-8 Beta was downloaded, but in the script I still see:
`CURRENT_PREFIX_VERSION="3.16-1"`

**Comment by Zlopez** [comment]
@kisak-valve 
I tried to remove `/var/home/zlopez/.local/share/Steam/steamapps/common/Proton 3.16 Beta/` and verify local files.

The proton was downloaded again, but the `proton` script still has CURRENT_PREFIX_VERSION="3.16-1".

It looks like the 3.16-8 installation contains wrong `proton` script.

I found it here in github - https://github.com/ValveSoftware/Proton/blob/proton_3.16/proton#L22

**Comment by Zlopez** [comment]
I fixed the prefix by manually changing `CURRENT_PREFIX_VERSION` to `3.16-8`. Here is the [proton log](https://github.com/ValveSoftware/Proton/files/2949651/steam-410320.txt)

**Comment by ryliejamesthomas** [comment]
I have an additional issue with this game. I've seen other people reporting the same, but there's no mention of it here.

Game runs great!, but in addition to the missing font (which in online mode makes determining stage difficulty a pain) whenever I try to use the in-game text chat it crashes. Using the pre-configured messages you can pull-up with the arrows/dpad works fine, the issue is with directly typing text.

**Comment by lucifertdark** [comment]
[steam-410320.log](https://github.com/ValveSoftware/Proton/files/3013712/steam-410320.log)
https://gist.github.com/lucifertdark/584c14275612e8e3c4a8070d428d8a02
Game freezes on save selection screen for me too, latest drivers & Proton versions.

**Comment by junglerobba** [comment]
There's been a regression with Proton 4.11 where some parts of the UI aren't showing up that were visible with 4.2.

4.11:
![2019-10-14-204926_grim](https://user-images.githubusercontent.com/18437660/66775555-9efea500-eec4-11e9-8e38-d431cdabc6c4.png)

![2019-10-14-204936_grim](https://user-images.githubusercontent.com/18437660/66775537-9017f280-eec4-11e9-9f9e-38828b114e6b.png)

[steam-410320-4.11.log](https://github.com/ValveSoftware/Proton/files/3725975/steam-410320-4.11.log)

4.2:
![2019-10-14-192337_grim](https://user-images.githubusercontent.com/18437660/66775622-c05f9100-eec4-11e9-851a-de43de369e70.png)

![2019-10-14-192400_grim](https://user-images.githubusercontent.com/18437660/66775611-ba69b000-eec4-11e9-9b67-e176656df17e.png)

[steam-410320-4.2.log](https://github.com/ValveSoftware/Proton/files/3725976/steam-410320-4.2.log)

**Comment by doitsujin** [comment]
Should be fixed as of https://github.com/doitsujin/dxvk/commit/31baf3529a65a3cb9dc1fe2668795b571b23f6a0.

In the meantime, repeatedly changing graphics settings might make it work. Note that the bug was already present in Proton 4.2, not sure why no one ever had problems with that before.

**Comment by ghost** [comment]
This game plays flawlessly with DXVK enabled so long as you disable anti aliasing in the graphic settings. Otherwise you're missing a lot of graphics, including the crosshair, various parts of the HUD, etc.

Which is great because wined3d is very slow, especially when you destroy buildings I can go down to below 20fps.

DXVK gives me rock solid 60fps.

**Comment by ryliejamesthomas** [comment]
[Release notes for 4.11-2](https://github.com/ValveSoftware/Proton/releases/tag/proton-4.11-2) say:

> Earth Defense Force 5 and Earth Defense Force 4.1 will no longer freeze when prompted to input text.

But I still get those freezes :(

**Comment by WildPenquin** [comment]
With 5.0-6 I get intermittent crashes to desktop. They happen at a frequency of ~1x/1-2 missions, which is a bit of a bummer. Luckily with 4.11 series (4.11-3) I do not get those crashes. Also I didn't get crashes with an earlier 5.0 series proton, but forgot which one it was. 

On other than version 5.0-6 recent-ish protons EDF 4.1 runs just fine - except the font issue in some menus is still there (difficulty, anti-aliasing etc - luckily one can guess what is supposed to be there).

Also, my friend gets very poor (near-unplayable) framerates with DXVK enabled on an NVidia GPU if DXVK is used. Using PROTON_USE_WINED3D get's better frame rates. On amdgpu DXVK is best left enabled, as while both are usable, here DXVK has better frame rates and on WINED3D one can not enable anti-aliasing.

**Comment by cpuccino** [comment]
I'm getting unplayable framerates as well on an rtx 2070...

**Comment by simifor** [comment]
On proton 8.0-3 I don't see any font issues like I used to, played a couple of missions and had no crashes, music and sound effects working correctly as well. No issue with the framerate or frame times but a 5600g and a rx 6600 are more than the game asks for, so you can't really draw performance conclusions from it.

**Comment by ryliejamesthomas** [comment]
Been playing this a bit again using Proton Experimental. Text chat works perfectly now, but:—

- Frame rate drops dramatically (maybe single-digits per-second) in the menus where you select weapons (also people reporting this on ProtonDB).
- Fonts are still busted in the same places
- Connection issues haven't improved.

I have none of these issues with EDF 5 fwiw.

Can post a full report if needed.

**Comment by simifor** [comment]
@ryliejamesthomas Tried proton stable, experimental, and experimental bleeding edge, and they all had the same performance in the main menu and weapon selection menu. Tried changing characters to see if it only happened with some of them, but I saw nothing out of the ordinary.

The places I remember having missing fonts at some points were the difficulty selection screen, and some settings, but those are rendering fine for me on all 3 tested versions. Have you tried deleting the prefix to see if it changes anything?

**Comment by ryliejamesthomas** [comment]
@simifor Interesting. I don't get it in the main menu, just the weapon select and mission select (just noticed this). It doesn't seem to happen if no one else is in the lobby.

Thanks for the suggestion for fixing the font. What exactly do you mean by deleting the prefix; uninstall the Proton version that's in the tools part of my library, or the `[…] steamapps/common/Proton - Experimental` or `[…] steamapps/compatdata/410320/pfx` directories?

I have only recently reinstalled 4.1, but I do use the same Experimental Proton branch for most games.

**Comment by simifor** [comment]
I meant deleting the steamapps/compatdata/410320 folder

**Comment by ryliejamesthomas** [comment]
Thanks. Unfortunately that hasn't fixed anything.

I notice the `config_info` file references `[…] steamapps/common/Proton 6.3/dist/share/fonts/`, I wonder if I'm missing something from there. I tried copying over files from the equivalent Experimental branch font directory, but that didn't help.

Also I noticed i do get main menu slowdown in single player, just not multiplayer.

**Comment by simifor** [comment]
@ryliejamesthomas 6.3 shouldn't be referenced there. Try deleting the prefix again (410320 with everything inside it), then add `PROTON_LOG=1 %command%` to the game's launch parameters, this can be added in the game's properties. Then run the game again and see if the issues are still there, if they are, then grab the file steam will have made for this game in your home folder, it'll be called steam-410320.log, if it's too big to upload then zip it first. If the issues are gone then you should remove PROTON_LOG=1

**Comment by ryliejamesthomas** [comment]
I thought the version 6.2 references were a bit odd. So I did some tests wiping the file, deleting it, deleting the profile again, all with no luck.

So I double-checked my Steam settings and I had it set to globally use Proton 6.3. So sorry for all the bother, I'm afraid I just made a silly mistake in my settings. Fonts are working fine now.

The slowdown all seem to be gone on Experimental too, in single and multiplayer.

Thanks for spending your time trying to help.

**Comment by simifor** [comment]
@ryliejamesthomas Are you saying that the global proton version was interfering with what you set for the game? That isn't supposed to happen, so it's not surprising you got tripped. In your library you can search for the proton versions you have installed, you may try to verify the installed files for proton 6.3

**Comment by ryliejamesthomas** [comment]
No. I had the game set to use the default, global Proton version, and had the default, global version accidentally set to 6.3. I don't think there's any issue apart from my mistake.
