### ISSUE TITLE
Steam Play don't launch any games

### ISSUE THREAD

**Issue by KvaGram** [ValveSoftware/Proton#1402]
For some reason, nothing launches when I attempt to launch a game with steam play.
I have tried several windows games I got installed.
Banished, Fallout Shelter, Frostpunk, Myst III to name a few.

They all behave the same. Steam starts launching the game, most often with the small "preparing to launch" window. Then the steam library marks the game as running, after the few seconds, it goes back to normal (somethings doing a sync first).
I tried adding the launch option as suggested. No such log file has been found on my system after launching a game with those launch options.

I honestly have no idea of what is wrong. I have not yet found anyone else who experience this.
I compiled a system report using HardInfo. [Link](https://gist.github.com/KvaGram/497a06001a96138754ae9db763df43a4)
Please help.

**Comment by OvermindDL1** [comment]
Whats the result of running `vulkaninfo` (I think that was the name)?

**Comment by KvaGram** [comment]
Never heard of vulkaninfo. I installed and used it. [Got this wall of text.](https://gist.github.com/KvaGram/9b50d53007dc58fc1653361f54b9cc2a) Is it of any help?

**Comment by kisak-valve** [comment]
Hello @KvaGram, can you check if your system has python 2.7?

**Comment by KvaGram** [comment]
Yes, I ran python --version. Output was Python 2.7.15rc1

**Comment by ghost** [comment]
Just to be certain:

You need to make sure to use "PROTON_LOG=1 %command%" without quotes with the command options and it should produce even an empty file using name of the pid of the game in your user home directory. If it doesn't, then its failing before the log can be created.

Also some quick notes from the great big totally ugly wall of text system info link (for those who don't want to dl):
Ubuntu 18.04.1 LTS
GeForce GTX 680 NVIDIA 396.54
Monitor 0 1920x1080 pixels
Monitor 1 1680x1050 pixels
Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
16382MB (3316MB used)
Linux 4.15.0-34-generic

**Comment by KvaGram** [comment]
Disconnected a monitor and tried again. No change.
Triple-checked the command. Not even an empty file generated.

**Comment by mirh** [comment]
I was having the same problem the first time. 
I [rebooted](https://github.com/ValveSoftware/Proton/issues/82#issuecomment-415064847) and it worked.

**Comment by ghost** [comment]
There's also this since you're using multi storage devices:
https://www.reddit.com/r/linuxmint/comments/99llqx/steam_play_proton_not_working/

https://github.com/ValveSoftware/Proton/issues/35

**Comment by KvaGram** [comment]
I don't think a reboot will help. I tested Steam play day one with this issue, and figured whatever it was, it would be quickly patched. Some days later I tried again, and started researching the issue, to no help. I don't leave my computer on during the night, so there have been multiple reboots without improvements.

Only now did I decide to ask for help here.

**Comment by KvaGram** [comment]
Good suggestion, Byte. I have had issues with setting up my secondary HDD, where my primary steam library is. 
Here is a screenshot of my drive's mounting info. I have no idea how to set it right, but it works for normal steam games.
![screenshot from 2018-09-11 23-27-33](https://user-images.githubusercontent.com/13942418/45388790-5702b400-b61a-11e8-9f47-4f550ae1a397.png)

**Comment by thunder1410** [comment]
do native linux started from that HDD work?

**Comment by ipkpjersi** [comment]
I doubt it is a hard drive issue as all of my games are on a very slow external hard drive and it works just fine for me.

**Comment by ghost** [comment]
Referencing: https://github.com/ValveSoftware/Proton/issues/474 Mainly "If there is an existing folder with the game downloaded and it is in the library, when you try to launch it nothing happens."

> Here is a screenshot of my drive's mounting info. I have no idea how to set it right, but it works for normal steam games.

About the drives. If you are dual booting with Windows and using the game installations from there or otherwise possibly using a drive with NTFS and the games are installed on that then you need to look at the links about fixing that.*

*The use of /media with the drive photo above makes me think you are doing that or the last reference with example of Myst3.

Indeed, looking at Ubuntu 18.04 on my laptop it has mount point of / (though that it what I use - my home is not separated) but a mount point of media is definitely not the same. And does not make use of defaults.umask... also filesystem type auto is not that of ext4 or something native to linux. I see auto associated with Windows NTFS partition. So if I'm correct, you do need the referenced links and at least one of the referenced links will be your problem because it seems you may be doing more than one thing to break things.

You can try starting a game from the terminal and see if it says anything useful "steam steam://rungameid/*the-game-pid/appId*"
Example: to start fallout shelter $ steam steam://rungameid/588430

AppId/Pid can be found by creating a desktop shortcut then looking at properties of the shortcut, using steamdb.info, or even pulling up the store page in steam and looking at the url

If you're bringing over a game not on Steam such as Myst 3 then see reference here: https://github.com/ValveSoftware/Proton/issues/122

> I doubt it is a hard drive issue as all of my games are on a very slow external hard drive and it works just fine for me.

There's a difference if it involved Windows or possibly NTFS formatting. Unfortunately, little or nothing is that simple and non-complex, but I agree it would be nice if it works for me then it should work for you. There are many times that would be nice.

**Comment by ICEFIR** [comment]
I am using dual boot with win10 and Manjaro (Arch), storing all my steam games in the same NTFS drive. No problem so far other than win10 will lock down permission during shutdown - which I have to use restart instead. Other than that, everything works just fine, proton works as intended.

That said, I've redownloaded every (Windows) game under Linux. Not using the same library folder, to prevent some wired mess up.

And obvious I have more than one storage device. 4 physical and 5 logical, in fact.
Have not tested duel monitor yet - waiting for my second monitor to get repared and delivered.

**Comment by KvaGram** [comment]
Wow.. that's quite a bit overnight. So, here's a rundown.

The drive uses FAT32, as you can see on this screenshot.
![screenshot from 2018-09-12 12-16-19](https://user-images.githubusercontent.com/13942418/45418794-ba75fb80-b685-11e8-80b8-6b48f9585f4c.png)
Native linux games from steam launch from the drive without any issues.
I chose FAT becouse it seems fairly universal, so If I needed to dual boot Windows or something, it should be easy with that.
The 500GB SSD is my main drive with Ubuntu.
The 240GB SSD is my old drive with Linux Mint. I rarely use it now, but this is a dual boot setup.

Uh, and Myst3 is indeed on steam(appID 925930), all the Myst games are, they just aren't on sale yet. I got the key from a KS-campaign. Sorry for the confusion.

**Comment by mirh** [comment]
FAT32 doesn't support more than 2TB disks (aside of also having quite a lot more limitations that don't make it fit for anything other than stupid small usb keys)
That's reeeeeeally screwed up.

**Comment by KvaGram** [comment]
I admit I know little of disk formats, and this may be irrelevant for the issue all together, however according to [wikipedia](https://en.wikipedia.org/wiki/File_Allocation_Table#FAT32), the limits for FAT32 are:
> Max. volume size | 2 TiB (with 512 byte sectors)8 TiB (with 2 KiB sectors and 32 KiB clusters)16 TiB (with 4 KiB sectors and 64 KiB clusters)

Evidently, my disk uses larger sized sectors and clusters (whatever that means) than the minimal.

Regardless, I tried moving a windows game to my SSD and ran it. Same symptoms. The question of the disk may have been a red herring.

**Comment by aeikum** [comment]
What proton version are you using?  What do "python" and "python3" do in a Terminal?

**Comment by ghost** [comment]
In that case what happens when you do:
$ steam steam://rungameid/925930

Does anything look odd when you try to start Myst 3?

It should look like this and nothing else:
$ steam steam://rungameid/925930
Running Steam on fedora 28 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!

Also fat32 kind of stinks (its best not to use it, but yes, maybe here it isn't a problem, but its not a normal setup either. You should be using something like ntfs or ext4): https://www.genie9.com/support/kb/KnowledgeArticle.aspx?KBID=113 As soon as you run into a 4GB+ file you have a problem.

Further on fat32 however is that Steam in 2018 should already take care of making sure the game files fit: https://github.com/ValveSoftware/steam-for-linux/issues/1786 so I guess you shouldn't bother to change it =)

OK, so I mounted my ntfs drive with Steam games installed from Windows and Pronton is playing them without problems so either you have done something differently like with the fat32 but something else still or its not the issue (still in the uncertain bin =) ... another thing different is that your user dir appears to be on the fat32 drive - if that means that Steam is installed there then more differences.

**Comment by KvaGram** [comment]
While steam is running:
```
grambo@grambo-MS-7971:~$ steam steam://rungameid/925930
Running Steam on ubuntu 18.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
grambo@grambo-MS-7971:~$ 
```
The terminal goes back to normal almost instantly. Steam tries to launch the game.
No changes.

Trying while steam is shut down:
```
grambo@grambo-MS-7971:~$ steam steam://rungameid/925930
Running Steam on ubuntu 18.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
[2018-09-12 19:16:35] Startup - updater built Sep  8 2018 19:20:58
[2018-09-12 19:16:35] Opted in to client beta 'publicbeta' via beta file
You are in the 'publicbeta' client beta.
[2018-09-12 19:16:35] Verifying installation...
[2018-09-12 19:16:35] Verification complete
html_chrome.cpp (394) : Assertion Failed: CefCrashReportingEnabled()
```
Steam is launched minimized, with the above output. Steam then tries to launch the game. No change. Tried to re-launch the game after it fails. No new lines appear when attempting to re-launch the game. The console then rest in this state until I close it, terminating Steam.

**Regarding Python:**
Both python commands, surprisingly enough, opens a python session. But they do differ.
```
grambo@grambo-MS-7971:~$ python
Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
grambo@grambo-MS-7971:~$ python3
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
grambo@grambo-MS-7971:~$ 
```
**Regarding above screenshot:**
Never mind text behind it. It is cropping failure from screenshot. The text is a ghost. I do not know if it can be cleaned up post-upload.

**Comment by ghost** [comment]
Yeah, when Steam is not running it should go into a bunch more stuff and then into something like this:

ExecCommandLine: "'/home/user/.local/share/Steam/ubuntu12_32/steam' 'steam://rungameid/207170'"
ExecuteSteamURL: "steam://rungameid/207170"

And then a bunch more stuff as it begins to start the game.

I'm not sure if its a problem with Steam being on that drive or something else. You can also pick one to reinstall and try that to see if it fixes it since you have nothing else happening. I've had this happen a few times, but still since you don't have a log being created, it seems to be even earlier and looks to be a problem with Steam being unable to do whatever it needs to do. I have no idea why. You're on Ubuntu so it should work, but your drive situation again is different so I don't know in the end.

**Comment by ghost** [comment]
Actually, an update on that. While using the ntfs drive and trying to figure this out...
The computer locked up on starting a Proton game and went to the lock screen after a minute (Myst Masterpiece Edition) So rebooted.

On reboot tried to start the game without Steam running and ran into an error box "Failed to start game with shared conent. Please update these games first 244430"

So there's obviously problems with running Steam Proton games this way.

I've played a whole game through and have tested a bunch before this without anything like this happening.

And so I started Steam GUI and then tried to run the game and now i get what you get: prepare to launch and then nothing =)

I suggest you [do things differently] or wait to see if they can improve running games like this.

Installing it new from Steam on Linux or trying file verification might help for you.

**Comment by NickZ** [comment]
I just wanted to add that I too have been having issues with trying to launch certain games from NTFS partitions (DOOM in particular, it would just boot up a blank screen). Moving it to an ext4 drive fixed the issue.

**Comment by ghost** [comment]
Also I just found out [or realized] that using Proton 3.7.6 tool for all games should create a log file but having that unchecked, the version of Proton with the game did not create a log file.

3.7-4: Some useful default logging can be enabled with PROTON_LOG=1 %command% 

So you must use a version >= 3.7.4

**Comment by KvaGram** [comment]
Switching to the beta was among my first troubleshooting attempts.
![screenshot from 2018-09-13 11-17-58](https://user-images.githubusercontent.com/13942418/45479418-b8c03c80-b746-11e8-9ffe-cf6389289135.png)

**Comment by jvschiavo** [comment]
You could try a whitelisted game to be sure. Like Doki Doki Literature Club, it is free.

**Comment by KvaGram** [comment]
Two of the games I initially tried, Fallout Shelter and Banished, are on the whitelist.
Those are also those I most frequently tried on many of the attempts during this whole thing.

**Comment by jvschiavo** [comment]
Sorry, my bad.

(btw, Banished is not on the whitelist, but Fallout Shelter is:
Beat Saber
Bejeweled 2 Deluxe
Doki Doki Literature Club!
DOOM
DOOM II: Hell on Earth
DOOM VFR
Fallout Shelter
FATE
FINAL FANTASY VI
Geometry Dash
Google Earth VR
Into The Breach
Magic: The Gathering - Duels of the Planeswalkers 2012
Magic: The Gathering - Duels of the Planeswalkers 2013
Mount & Blade
Mount & Blade: With Fire & Sword
NieR: Automata
PAYDAY: The Heist
QUAKE
S.T.A.L.K.E.R.: Shadow of Chernobyl
Star Wars: Battlefront 2
Tekken 7
The Last Remnant
Tropico 4
Ultimate Doom
Warhammer® 40,000: Dawn of War® - Dark Crusade
Warhammer® 40,000: Dawn of War® - Soulstorm)

**Comment by gbdlin** [comment]
Try to mount your hard drive on directory that doesn't have any uppercase letters, whitespaces, special characters etc.

**Comment by Rika-chan** [comment]
I'm having the same issue on ext4.

ERROR: ld.so: object '/home/rika-chan/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/rika-chan/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/rika-chan/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/rika-chan/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
1412.837:0008:0009:trace:module:load_builtin_callback loaded ntdll.dll 0x10790 0x7bc20000
1412.837:0008:0009:trace:module:load_builtin_dll Trying built-in L"kernel32.dll"
1412.838:0008:0009:trace:module:load_dll looking for L"ntdll.dll" in L""
1412.838:0008:0009:trace:module:load_dll Found L"C:\\windows\\system32\\ntdll.dll" for L"ntdll.dll" at 0x7bc20000, count=2
1412.838:0008:0009:trace:module:load_builtin_callback loaded KERNEL32.dll 0x10900 0x7b420000
1412.838:0008:0009:trace:module:LdrGetDllHandle L"kernel32" -> 0x7b420000 (load path (null))
1412.838:0008:0009:err:process:init_windows_dirs directory L"C:\\windows" could not be created, error 2
1412.838:0008:0009:err:process:init_windows_dirs directory L"C:\\windows\\system32" could not be created, error 3
1412.838:0008:0009:err:process:init_windows_dirs directory L"C:\\windows\\syswow64" could not be created, error 3
wine: cannot find '/home/rika-chan/.steam/steam/steamapps/common/Hyperdimension Neptunia Re;Birth3/NeptuniaReBirth3.exe'
1412.838:0008:0009:trace:module:LdrShutdownProcess ()
pid 8750 != 8749, skipping destruction (fork without exec?)

**Comment by Rika-chan** [comment]
Ah, I've solved it. I at one point had moved stuff from an ntfs drive to ext4, had to umount my ntfs drive as it kept trying to install proton there, then remove ~/.steam/steam/steamapps/compatdata, and ~/.steam/legacycompat/

For some reason that solved the issue, I guess.

**Comment by KvaGram** [comment]
Well, I don't know what is wrong with my setup, but I booted into my old Linux Mint (as I mentioned I am dual booting), and tried from there.
I tested Fallout shelter, and the game started, and looked fine.
So, the issue must have been something I messed up on my Ubuntu.

I don't suppose anyone has an idea on how I can clean my system? I have done a lot of messy things, so it would be nice if someone could help with a troubleshooting list for that.
I'd hate having to go nuclear with a full re-install of the OS.

**Comment by zqcSplatoon** [comment]
I have a secondary hdd and I have the same problem too.Umount the hdd really works.

**Comment by jokatzke** [comment]
I had the same issue and fixed it by disabling "Prevent focus stealing" in Cinnamon's Windows-options (I'm running Linux Mint 19.1 Cinnamon).

Hope that helps.

**Comment by kisak-valve** [comment]
Hello @KvaGram, the root cause of your issue was found on #2439. I've heard from a Proton dev that we are not going to support FAT32 due to the lack of support for symlinks and the max file size of 4GB. Please use a linux native filesystem for the best experience.

If you have follow up issues with a native filesystem, feel free open a new issue report and we can go from there.

Closing as the original issue tracked here is about running games with Proton on a FAT32 Steam library.

**Comment by KvaGram** [comment]
Thanks @kisak-valve. I figured something like that had to have been the case long ago. 
I have since reformatted my drive.

**Comment by mirh** [comment]
I thought this bug was also covering whatever problems people had on ntfs disks?
EDIT: though I wonder if it couldn't have been related to [this base steam bug](https://www.reddit.com/r/linux_gaming/comments/b95i2h/steam_beta_update_of_april_3_improves_support_for/ekb6c3e/?context=2)

**Comment by meltingscales** [comment]
I fixed this issue I had with "The Ultimate DOOM" by moving the install directory of the game from an external NTFS disk mounted at 

`/media/henryfbp/games/linux/SteamLibrary/steamapps/common/Ultimate Doom` 

to my OS' EXT4 steam install directory located at 

`~/.steam/debian-installation/steamapps/common/Ultimate Doom`

It does seem to be an NTFS/mounting/external drive issue.

**Comment by zhiyuanzhai** [comment]
Wait a minute... What if I really need my external drive to be formatted as, for example, exFAT, and use it as my steam library? 

The problem still exists even today - 2020.10.2.

**Comment by praksharma** [comment]
Yeah, the problem still exists in Jan 2022.

**Comment by meltingscales** [comment]
> Yeah, the problem still exists in Jan 2022.

Ah, this appears to be due to Proton devs choosing (for good reason) to not support FAT32 filesystems due to issues implementing, "due to the lack of support for symlinks and the max file size of 4GB" -- see https://github.com/ValveSoftware/Proton/issues/2439#issuecomment-475743504

It probably won't get fixed unless a hack-y workaround is coded, like file splitting and "fake" symlinks, or a virtual filesystem embedded within the FAT32 drive... it might be the only choice to not use FAT32, for now, sadly :(

**Comment by KvaGram** [comment]
Wow! Glory to the necropost.
This was a while ago. 

> Ah, this appears to be due to Proton devs choosing (for good reason) to not support FAT32 filesystems due to issues implementing, "due to the lack of support for symlinks and the max file size of 4GB" -- see [#2439 (comment)](https://github.com/ValveSoftware/Proton/issues/2439#issuecomment-475743504)

In that case, I think the fair thing to do, is simply to warn users though Steam's UI that the disk format is unsupported for Proton. It's not a solution, but at least it will let users know it is an issue without any other workaround than reformating, or using another drive.
