### ISSUE TITLE
ONE PIECE PIRATE WARRIORS 3 (331600)

### ISSUE THREAD

**Issue by liberodark** [ValveSoftware/Proton#1649]
# Whitelist Request
- Name of the game to be whitelisted: ONE PIECE PIRATE WARRIORS 3
- Steam AppID of the game: 331600

## System Information
- GPU: Intel HD Graphics 520
- Driver/LLVM version: Mesa 18.2.1
- Kernel version: 4.18.9
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/liberodark/750b0b814031b92ec65622b6bc7884f3
- Proton version: 3.7-7 Beta

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options)
      are necessary to run the game.
- [x] that no workarounds other than the mentioned ones are necessary.

## Issues
- [x] I haven't experienced any issues.
- [x] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are
      remaining issues:

**Comment by rcgamer29** [comment]
I will second this one. Works flawlessly.

**Comment by basxto** [comment]
The game does not work flawless, all video cut scenes are missing.
In wine this game needs Quartz, Windows Media Player 10 and Devenum installed.
WMP10 can only be installed in a 32bit prefix and therefore this can’t even be fixed with protontricks.

I furthermore wasn’t able to remap my xbox 360 gamepad satisfactorily without xboxdrv.
With default xpad driver the trigger will continuously scroll down in some submenues, because it got bound treaded as a analog stick or something like that.

[System Information](https://gist.github.com/basxto/2d1a13d46007397b24ecd24c5fba991d)
Tested with Proton 3.16-4

**Comment by williamd1k0** [comment]
I started playing this game recently, so here are my results:
- Using Proton (tested only with experimental version yet), the game works perfectly, but the cutscenes still don't work.
- Using Proton-GE (tested with v6.8 and v6.10), both game and cutscenes are working, but it's unplayable on a controller, there is some issue with Steam Input (Steam Input is required for this game because the built-in controller support is partial and somewhat broken).

So, is there a way to find out how Proton-GE fixed the cutscenes, or why Steam Input doesn't seem to work with Proton-GE?

**Comment by basxto** [comment]
I downloaded a 100% savegame and clicked through all the cutscenes in the event log.
So cutscenes should work soon-ish with steam’s proton.

> So, is there a way to find out how Proton-GE fixed the cutscenes

Proton does/did not use gstreamer … or something like that.

**Comment by Cederick** [comment]
Just downloaded the game and it works fine besides audio stutters in cutscenes which really ruin the game for me. Issues are still there even with proton experimental sadly. Valve pls fix.
