### ISSUE TITLE
Ty the Tasmanian Tiger 3 (411980)

### ISSUE THREAD

**Issue by Zero86Sk** [ValveSoftware/Proton#2271]
# Whitelist Request
- Name of the game to be whitelisted: Ty the Tasmanian Tiger 3
- Steam AppID of the game: 411980

## System Information
- GPU:  GTX 1070
- Driver/LLVM version:  Nvidia driver 415.27
- Distro version:  Linux Mint 19.1
- Kernel version:  4.18.0-13
- Link to full system information report [Gist](https://gist.github.com/Zero86Sk/849961ad66438e3e6240198d06fbce5c)
- Proton version: 3.16-6 beta

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [x] that no workarounds other than PROTON_* env variables are necessary.

## Issues
- [x] I haven't experienced any issues.
- [x] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are remaining issues:

Game runs nicely out of the box

**Comment by kisak-valve** [comment]
Ty the Tasmanian Tiger 3 (411980)

Issue transferred from https://github.com/ValveSoftware/Proton/issues/4891.
@CalebQ42 posted on 2021-06-09T04:51:39:

# Compatibility Report
- Name of the game with compatibility issues: Ty the Tasmanian Tiger 3
- Steam AppID of the game: 411980

## System Information
- GPU: RTX 3070
- Driver/LLVM version: 465.31-1
- Kernel version: 5.12.9.zen1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/CalebQ42/261ef1ed69d127c2d68ef841e1c32cd2
- Proton version: All of them.

## I confirm:
- [ X ] that I haven't found an existing compatibility report for this game.
- [ X ] that I have checked whether there are updates for my system available.

[steam-411980.log](https://github.com/ValveSoftware/Proton/files/6621149/steam-411980.log)

## Symptoms

The game fails to launch. After a bit of experimentation, it seems the game might not be able to communicate with the Steam api. This problem also seems to affect the second game, but not the first. Varified to be working on Windows.

## Reproduction

Try to run the game. Tried on all available Proton versions including the latest GE version.

**Comment by kisak-valve** [comment]
Hello @CalebQ42, `err:module:import_dll Library steam_api.dll (which is needed by L"Z:\\games\\SteamLibrary\\steamapps\\common\\TY the Tasmanian Tiger 3\\TY3.exe") not found` in your log looks like the line of interest. It looks like steam_api.dll should be provided by depot 411981 right beside the game executable, TY3.exe. Maybe try verifying the game's files?

Out of mild curiousity, what filesystem are you using with `/games/SteamLibrary`?

**Comment by CalebQ42** [comment]
@kisak-valve Ooops, that's my bad. I had been trying a bunch of things to try to get it working and forgot to verify my files before reporting. [steam-411980.log](https://github.com/ValveSoftware/Proton/files/6624273/steam-411980.log)

`/games` is using ntfs with `uid=1000,gid=1000,rw,user,exec,umask=000,x-gvfs-show` as mount options, but I've also tried it on my main partition that's f2fs with the same result.

**Comment by kisak-valve** [comment]
Thanks, Proton interacting with NTFS is known to be temperamental, but I guess that the log is hinting there's an issue elsewhere with `warn:seh:dispatch_exception EXCEPTION_FLT_DIVIDE_BY_ZERO exception (code=c000008e) raised` being a possible line of interest.

**Comment by RibShark** [comment]
The game works when using an unofficial steam_api.dll and then loading as a non-Steam game. Given this worked on earlier versions of Steam, and no longer works even on the same Proton versions, could this be a regression in the Steam client?

It also works when installing the Windows version of the Steam client inside a Proton prefix, and then installing/running the game from that client.

**Comment by Viesta2021** [comment]
Game booted up and got past the title screen but when you change settings to high and reboot it wont launch anymore.
(using experimental)

**Comment by JimScript** [comment]
> Game booted up and got past the title screen but when you change settings to high and reboot it wont launch anymore. (using experimental)

Ah, that's due to MSAA for some reason, you delete the value(but not the line)in the config file and the game starts again. However you won't get far in as the Dennis cutscene crashes to desktop before you can even skip it. Here is a Proton log for each type of crash:
[steam-411980-MSAA.log](https://github.com/ValveSoftware/Proton/files/13543525/steam-411980-MSAA.log)
[steam-411980-Dennis.log](https://github.com/ValveSoftware/Proton/files/13543527/steam-411980-Dennis.log)

**Comment by tarceri** [comment]
Hi, I've fixed the crash on launch in the radeonsi driver with this MR: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/26661

**Comment by JimScript** [comment]
> Hi, I've fixed the crash on launch in the radeonsi driver with this MR: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/26661

It still crashes on startup with MSAA, but the log file is a _bit_ longer so I wonder if there's another thing crashing it too:
[steam-411980.log](https://github.com/ValveSoftware/Proton/files/14441706/steam-411980.log)

**Comment by tarceri** [comment]
> > Hi, I've fixed the crash on launch in the radeonsi driver with this MR: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/26661
> 
> It still crashes on startup with MSAA, but the log file is a _bit_ longer so I wonder if there's another thing crashing it too: [steam-411980.log](https://github.com/ValveSoftware/Proton/files/14441706/steam-411980.log)

You are using Mesa 23.1.3 (git-87ebaf765d) 23.1.3 was released in June 22, 2023. For the bug fix you need to use Mesa 24.0.* or 23.3.2 or higher

**Comment by JimScript** [comment]
Ah I see, SteamOS hasn't updated its Mesa drivers with the fix yet. I assumed that the Mesa downloads from the Discover store were system wide, but now I realize that they're only for Flatpak's sandboxing.

**Comment by JimScript** [comment]
Well I'm happy to say the new SteamOS preview with Mesa 24.1 did indeed fix the game launching with MSAA on, however it didn't fix the crash at the Dennis cutscene, so here's a more recent log for that:
[steam-411980-Dennis-2.zip](https://github.com/ValveSoftware/Proton/files/15339665/steam-411980-Dennis-2.zip)

**Comment by SecularSteve** [comment]
It's back again!

**Comment by tarceri** [comment]
> It's back again!

Can you be more specific? The game doesn't crash for me on startup.

**Comment by tarceri** [comment]
> Well I'm happy to say the new SteamOS preview with Mesa 24.1 did indeed fix the game launching with MSAA on, however it didn't fix the crash at the Dennis cutscene, so here's a more recent log for that: [steam-411980-Dennis-2.zip](https://github.com/ValveSoftware/Proton/files/15339665/steam-411980-Dennis-2.zip)

What is the "Dennis cutscene" is this early in the game? If not are you able to provide me with a save file to get to it?

**Comment by JimScript** [comment]
> > Well I'm happy to say the new SteamOS preview with Mesa 24.1 did indeed fix the game launching with MSAA on, however it didn't fix the crash at the Dennis cutscene, so here's a more recent log for that: [steam-411980-Dennis-2.zip](https://github.com/ValveSoftware/Proton/files/15339665/steam-411980-Dennis-2.zip)
> 
> What is the "Dennis cutscene" is this early in the game? If not are you able to provide me with a save file to get to it?

Well you see early on in the game after you go back from the tutorial in another dimension you defend a town from some monsters, and after that you successfully defend the town you get a cutscene introducing the general for the resistance. Immediately after that cutscene is another cutscene that properly talks to him about how things are going and that cutscene always crashes to desktop half a second after it starts before you can even skip it making the game impossible to complete. I can provide you with a save but it really is early on in the game, and you have to defend the town every time you want to test this crash, so you might want to know how the combat works beforehand.

**Comment by tarceri** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/2271#issuecomment-3231713815

Thanks. Someone posted a save file for me https://gitlab.freedesktop.org/mesa/mesa/-/issues/13790

**Comment by mathew2214** [comment]
i can confirm, ty 3 is unplayable on all builds of proton. crashes almost immediately after tutorial. 
valve, please fix.

**Comment by JimScript** [comment]
Last month a user on the Steam discussion for this game said that you can bypass the crashes by enabling Zink: `MESA_LOADER_DRIVER_OVERRIDE=zink ZINK_DEBUG=flushsync %command%`
And I can say that so far it has allowed me to get past the Dennis cutscene without a CTD, although with some performance loss. Here is a log of me using Zink to bypass the first crash:

[steam-411980-zink.zip](https://github.com/user-attachments/files/27365002/steam-411980-zink.zip)
