### ISSUE TITLE
Prey (2017) (480490)

### ISSUE THREAD

**Issue by omicron-b** [ValveSoftware/Proton#251]
There are white and black splotches on some NPCs in cut-scenes only - was not able to fix that changing in-game settings, also on the first run mouse was not captured, after first run it is fine. No other issues, I think it can be whitelisted.

Arch Linux (4.18)
Nvidia GTX 1060 with 396.51 driver

**Comment by NoXPhasma** [comment]
BTW It's actually Prey 2017, not 2016 (Release date March 2017).

But I can confirm that it runs very good, I didn't have had any issue with the mouse.

However I can confirm that there are sometimes small graphical glitches. Nothing big, but reflections on some windows can disappear in a specific view port. Nothing the gameplay would break and I'm not sure if this is really specific to the Steam Play/Proton version.

Systeminfo: https://gist.github.com/NoXPhasma/5637df6e219e953c609cf7263a25d55b

**Comment by omicron-b** [comment]
@NoXPhasma thanks, fixed the title

**Comment by nilleairbar** [comment]
Was performance terrible in the beginning for you? The game launches right away for me but even in the menu the performance jumps between 15 and 60 FPS on a per second base.

**Comment by NoXPhasma** [comment]
The performance was and is pretty great, beside some smaller stutters, probably because of shader loading, it runs at 60FPS on highest settings.

**Comment by omicron-b** [comment]
On first run I had huge FPS drops in menu, but I thought settings not configured properly. Tried just now, I can have a stable 24-38 FPS in 4k medium settings and 58-100 FPS in 1920x1080 res medium on slightly OC GTX 1060 6g. No sudden drops, no stutters. Although I noticed now I don\`t have 2560x1440 available, but I am positive I played in it before. I don\`t have Windows, but I will check in Wine and update this comment. There was an update to the game so Bethesda could have broken it.

Edit: apparently there is an issue in Proton. In Wine staging 3.12 2560x1440 is available and playable, in Proton 3.7-3 it is not available.
Edit: same with 3.7-4 Beta, 2560x1440 not available

**Comment by omicron-b** [comment]
updated my system today, now I have crashes, freezes and stutters in Prey. Already downgraded nvidia driver and lib32-nvidia-utils but it did not help. https://gist.github.com/omicron-b/f697ca5bd4b8e25a98cb1d721e10edfd and 
[svo_stdout.txt](https://github.com/ValveSoftware/Proton/files/2321007/svo_stdout.txt)

**Comment by nilleairbar** [comment]
I noticed that performance in itself is actually pretty good, but the moment I start to move the mouse the performance absolutely tanks. Like going down from 60 FPS at 1440p on medium to high settings down to single digits.
I'll test different mouse polling settings tomorrow to see if that has any effect. 
What DE are you using? Because we have pretty similar setups, though I have a Ryzen 7 1700 and a GTX 1070 and am also on 396.54.

**Comment by omicron-b** [comment]
@nilleairbar I have KDE.
Switching to Proton 3.7-3 and downgrading kernel to 4.18-1 also did not help.

**Comment by NoXPhasma** [comment]
@m-svo You have an error about too many opened files: `eventfd: Too many open files`.  Look into issue https://github.com/ValveSoftware/Proton/issues/32, it's explained how to fix it.

**Comment by omicron-b** [comment]
@NoXPhasma thanks, that solved the crashes!

**Comment by nilleairbar** [comment]
Okay, it seems it was actually a mouse polling problem. Now with a mouse polling rate of 250Hz the game performs at like 95% of the level it does under Win10.
For good measure I tested it again and can confirm that a mouse polling rate of 500Hz totally tanks performance for me.

**Comment by omicron-b** [comment]
@nilleairbar Interesting, do you set your polling interval like [that](https://wiki.archlinux.org/index.php/mouse_polling_rate#Set_polling_interval)? I have a hardware switch on the mouse and can use any one from 125 to 1000 with no issues (and it is actually used), but as soon as I launch `evhz` to monitor polling it tanks the performance for as long as I have `evhz` running, on any mode. But Steam still reports normal FPS, although it\`s clearly single digits.

**Comment by nilleairbar** [comment]
Yep, I did it via the modprobe config file. Just remember that the DPI settings of the mouse are different from the polling rate. 
Only problem I have right now is that the game somehow refuses to load my old Win10 savegames. They are right in there in the ../pfx for Prey but somehow the game always loads a basic ass savegame right from the game start that's saved nowhere in the pfx.

**Comment by omicron-b** [comment]
check both `drive_c/users/steamuser/My Documents/Arkane Studios/` and `drive_c/users/steamuser/Saved Games/Arkane Studios/`  
I was not able to understand how the game switches between those, but it does sometimes.

**Comment by nilleairbar** [comment]
Thank you. Now I got my savegame back.
Performance is not as stable as on Windows with jumps between 45 and 60 FPS but at the same high generally higher than on Windows. I'm running the game at 1440p with settings on maximum right now and FPS are mostly between 55 and 60.

**Comment by NoXPhasma** [comment]
I've finished the game after 12 hours of playtime. There were no real obvious bugs I encountered and the performance was good. I would say it runs at ~75% of the Windows performance for me.

**Comment by flibitijibibo** [comment]
@kisak-valve Requesting an XAudio2 label for this game... this is a Wwise title but they still use an XAudio2 context for the output stream.

**Comment by liberodark** [comment]
For me not work on 1050Ti just have White Screen with bethesda no more :(
On Proton 3.7-8 and 3.16-3 Beta

**Comment by NoXPhasma** [comment]
@liberodark Please provide your full system information.

**Comment by liberodark** [comment]
But work on Proton 3.16-4 Beta xbox controller not work

**Comment by SleepingSloth** [comment]
@liberodark If you go to Prey - Properties and "Force on" (Steam Input Per-Game Setting) the game should work with xbox one controller I can't say for the xbox 360 controller though.

**Comment by Bloodaxe95** [comment]
Steam Input/Steam Controller functionality is not working as intended. Glyphs (for the Steam Controller at least) does not display correctly, and for some reason the game keeps turning off my controller for no apparent reason.

**Comment by KaryotypeB** [comment]
I can confirm that Glyphs with Steam Controller do not display correctly, I get colored static images with "IMG:" superimposed on them, instead of normal glyphs. Controller works fine for me otherwise. Running Arch Linux w/ KDE Plasma & Proton 3.16-4. Sys info: https://gist.github.com/KaryotypeB/8041b0c09d18a8d695997a0d91fa18f2

**Comment by Phil-Ba** [comment]
I'm having issues starting the game. Denuvo seem to try to connect to a server and fails.

**Comment by NoXPhasma** [comment]
@Phil-Ba Please provide a log file, proton version and your system information. The game still starts up fine for me and I can play without any error.

Proton Version: 3.16-4
Sysinfo: https://gist.github.com/NoXPhasma/9ed85e6b0602b656c812acd013ee121f

**Comment by Phil-Ba** [comment]
https://gist.github.com/Phil-Ba/7d82f86a824603d5a0ea27abf69324af
I noticed I had the native steam runtime active. I'll try with the steam-runtime instead.
Which logs do you need, and where can I find them?

**Comment by Phil-Ba** [comment]
Yes, sees to work after removing steam-native-runtime!

**Comment by NoXPhasma** [comment]
In the [Proton FAQ](https://github.com/ValveSoftware/Proton/wiki/Proton-FAQ#how-to-enable-proton-logs) you will find how to enable logs and more. To enable logs only for a single game, change the launch parameter to `PROTON_LOG=1 %command%`.

**Comment by omicron-b** [comment]
The [z-fighting issue](https://en.wikipedia.org/wiki/Z-fighting) which resulted in white and black splotches on NPCs is gone with Nvidia moving vulkan beta fixes to mainline driver 415.22
The issues left are XAudio2 support (I got distorted sound multiple times after playing for 5 hours) and, as reported, Steam Controller support.

**Comment by ghost** [comment]
Same problem with glyphs using Steam Controller.

**Comment by omicron-b** [comment]
@Dablim are you on Proton 3.16-5 Beta? According to log, this version has [fixes](https://github.com/ValveSoftware/Proton/wiki/Changelog#316-5) for Steam Controller images.

**Comment by ghost** [comment]
@m-svo Tried all version of Proton but no glyphs for me.
I'm on Manjaro with i3 and Linux 4.19.9.

**Comment by KaryotypeB** [comment]
I also still don't have glyphs on 3.16-5 with the Steam Controller. 
Arch linux w/ KDE plasma & Linux 4.19.8

**Comment by omicron-b** [comment]
Proton 3.16-5 Beta (FAudio) fixes sound distortion for me.

**Comment by mimattr** [comment]
> I can confirm that Glyphs with Steam Controller do not display correctly, I get colored static images with "IMG:" superimposed on them, instead of normal glyphs. Controller works fine for me otherwise.

Agreed, testing with **Proton 3.16-6 Beta** the CRYENGINE log also suggests an issue binding select input actions which may/may not be related:

- [Game.log](https://gist.github.com/mimattr/7c86e402c06eaebb9ab783c95fa35c9c#file-game-log-L168)
- [steam-480490.log](https://gist.github.com/mimattr/612c6305d147bd845534b10cdc19dd18)

As an aside the official wired **Xbox 360 Controller** is not detected/working in this application either (XInput).

[Steam System Information](https://gist.github.com/mimattr/b0b7f46366e31e254460b9593ce87e51)

**Comment by GloriousEggroll** [comment]
I was able to play through the entire game on Proton 3.16-6 Beta with no noticeable problems graphically or game play wise. Both PS4 and Xbox one controller inputs worked fine

-Arch Linux
-Vega 64 on mesa-git + llvm-svn
-TR 1950x

**Comment by RussianNeuroMancer** [comment]
I also can't get controller detected, unless it enabled and configured in Big Picture mode.

Interestingly, I have similar issues with camera control from both of controller and mouse - after some time in game, I can only rotate for 180 degrees, so turning around became impossible. It's easily get fixed by visiting menu - but there must be separate bugreport about this issue, right?

**Comment by omicron-b** [comment]
@RussianNeuroMancer it was closed as fixed in https://github.com/ValveSoftware/Proton/issues/53

**Comment by RussianNeuroMancer** [comment]
@m-svo any idea why I still have this on two devices with Proton 3.16-8 Beta? One of these devices was setup for usage with Proton for a first time, so Steam downloaded very latest version of Proton, for sure.

**Comment by omicron-b** [comment]
@RussianNeuroMancer no idea, but I will try to reproduce this. How long do you play until this happens?
Meanwhile you can provide [log](https://github.com/ValveSoftware/Proton#runtime-config-options) with this happening and your system info as per [issue template](https://github.com/ValveSoftware/Proton/blob/proton_3.16/.github/ISSUE_TEMPLATE/compatibility-report.md) , maybe this will help

**Comment by RussianNeuroMancer** [comment]
@m-svo yesterday, I was able to reproduce it in 15 minutes or so. Try to play for half-hour without opening Esc menu. I will try to pay attention next time if other menus (like inventory or recycler) also workaround issue. 

Today I wasn't able to reproduce this, so probably there is no point in running it with enable logging, unless I have reliable way to reproduce this.

**Comment by RussianNeuroMancer** [comment]
> I will try to pay attention next time if other menus (like inventory or recycler) also workaround issue.

I found that other menus is also workaround this issue. Maybe you don't see this issue because you access these screens more frequently than I sometimes do?

**Comment by mimattr** [comment]
# Whitelist Request

## System Information
- GPU: **RTX 2060**
- Driver/LLVM version: **NVIDIA 430.40**
- Kernel version: **5.0.0-23-generic**
- [Link to full system information report as Gist](https://gist.github.com/mimattr/b0b7f46366e31e254460b9593ce87e51)
- Proton version: **4.11-2**

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [ ] that no workarounds other than PROTON_* env variables are necessary.

## Issues
- [x] I haven't experienced any issues.
- [x] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are remaining issues:

_**NOTE:** Not tested **Prey 2017 Demo** (#1189)_

**Comment by kisak-valve** [comment]
Hello, is anyone seeing an issue with this game and Proton 4.11 that would block it from being whitelisted?

**Comment by flibitijibibo** [comment]
I believe there are still issues with the game's Steam Controller mode, but I haven't checked recently (maybe a month or so?).

**Comment by RussianNeuroMancer** [comment]
@kisak-valve 

"after some time in game, I can only rotate for 180 degrees, so turning around became impossible" from [this comment](https://github.com/ValveSoftware/Proton/issues/251#issuecomment-476061431) was present with 3.16, but I can't remember if it was here with 4.2 (or maybe I just more frequently access inventory/save screens near the end of the game, which workaround this issue for some reason).

**Comment by CSahajdacny** [comment]
> Hello, is anyone seeing an issue with this game and Proton 4.11 that would block it from being whitelisted?

I think games must be tested with at least the minimum official hardware requirements... 

>Processor: Intel i5-2400, AMD FX-8320
Memory: 8 GB RAM
Graphics: GTX 660 2GB, AMD Radeon 7850 2G

Was that the case?

**Comment by NoXPhasma** [comment]
I was playing the Mooncrash DLC for a few hours with Proton 4.11-2 and Fsync enabled on a patched Kernel. Performance wise it ran pretty good, no issue on that. However I experienced a game hang after I've finished a run and was supposed to get a new message, probably a sequence was a bout to be shown. It was needed to kill the process. I have a log file of that: [steam-480490.log](https://github.com/ValveSoftware/Proton/files/3496983/steam-480490.log)

I also experienced a case where suddenly textures were missing, like the wrench in my hand and the device in front of me:
![20190813143358_1](https://user-images.githubusercontent.com/7719590/62943305-7251e280-bdda-11e9-9d62-4b61b93e83e0.jpg)

There was also a complete fabricator missing, except for it's monitor:
![20190813143534_1](https://user-images.githubusercontent.com/7719590/62943348-8e558400-bdda-11e9-8a36-723c29837c99.jpg)

I didn't had log enabled when the missing textures happened and I don't know if this is specific to Proton.

Sysinfo: https://gist.github.com/NoXPhasma/762a936325653d46d3b5d42a4433f0b1

**Comment by NoXPhasma** [comment]
I got the missing textures again, this time I had logging enabled: [steam-480490.log](https://github.com/ValveSoftware/Proton/files/3498341/steam-480490.log)

**Comment by doitsujin** [comment]
@NoXPhasma is there a reliable way to reproduce this, preferably with the demo?

**Comment by NoXPhasma** [comment]
I haven't found a way to reproduce it but I have an idea when it might happen. For the first time I have no clue what causes it. For the second time I know exactly when it happened. I got a new device and it was installed to me in a sequence where I was out of control. When the sequence ended I had an invisible wrench.

Since Mooncrash is a rogue-like experience, there is no way to have easy steps to reproduce, as it changes every run.

I can't remember to have had this happen to me in the base game, but I haven't done a playthrough with Proton 4.11.

**Comment by RussianNeuroMancer** [comment]
> When the sequence ended I had an invisible wrench.

Now I remember I seen this issue too. Not only with wrench, but with all guns. Not in Mooncrash, but in single player game. When it's happen it usually better to restart the game, because when I don't do this in-games scripts eventually stop working.

**Comment by omicron-b** [comment]
> I believe there are still issues with the game's Steam Controller mode, but I haven't checked recently (maybe a month or so?).

Tested Steam Controller, do not see any issue with glyphs.
![20190817120501_1](https://user-images.githubusercontent.com/32303844/63209329-088e4d00-c0e8-11e9-8be5-0129dab91a28.jpg)

## System Information
- GPU: GTX 1060
- Driver/LLVM version: nvidia 430.40
- Kernel version: 5.2.8-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/omicron-b/3c2fea70f0575f498e278c4e1934c361)
- Proton version: 4.11-2

**Comment by kisak-valve** [comment]
Prey (2017) (appid 480490) - green screen during cut-scene "black-outs" 

Issue transferred from https://github.com/ValveSoftware/Proton/issues/4939.
@thomasfsteeples posted on 2021-07-03T13:44:01:

# Compatibility Report
- Name of the game with compatibility issues: Prey (2017)
- Steam AppID of the game:  480490

## System Information
- GPU: Radeon RX 6900 XT
- Driver/LLVM version:  4.6 (Compatibility Profile) Mesa 21.1.3
- Kernel version: 5.12.14-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/thomasfsteeples/c8f4dedb47db9b3dd1a59cb540c6a337
- Proton version: Experimental (have also tried numbered versions, but same result)

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Log File

[steam-480490.log](https://github.com/ValveSoftware/Proton/files/6758487/steam-480490.log)

## Symptoms 

Recently downloaded Prey but am experiencing this really annoying visual bug where in cut-scenes where the screen "blacks out", I instead get a screen with green lines. The HUD is preserved, and when the screen actually renders something non-trivial, it's fine.

As an example, I've attached two images from the intro - when Alex has their eyes closed, I get the green screen, but when they go to turn off their alarm clock, rendering kicks in.

![Screenshot from 2021-07-03 13-59-35](https://user-images.githubusercontent.com/32720359/124356262-f864b580-dc0c-11eb-8925-94a7d74acc44.png)
![Screenshot from 2021-07-03 13-59-46](https://user-images.githubusercontent.com/32720359/124356263-f8fd4c00-dc0c-11eb-84f4-b0b306260d08.png)

It's not an absolute deal-breaker, but it's definitely breaking immersion. Has anyone else come up against this problem before? Does anyone have any tips for troubleshooting this? I'm experiencing it both on X and Wayland. Any help would be greatly appreciated.

**Comment by kisak-valve** [comment]
Hello @thomasfsteeples, it looks like you're using AMDVLK with the game. Can you test if mesa/RADV is equally affected?

**Comment by thomasfsteeples** [comment]
Hi @kisak-valve - can confirm that lauching steam with `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.i686.json:/usr/share/vulkan/icd.d/radeon_icd.x86_64.json steam` causes Prey to run "normally" (i.e. no green-screen artefacts). Does this imply the issue is upstream with AMDVLK?

**Comment by kisak-valve** [comment]
Yes, that's a strong indicator that there is a driver vendor specific issue. It may be worthwhile to mention the render quirk directly to the AMDVLK devs.

**Comment by thomasfsteeples** [comment]
Will do - cheers for troubleshooting!

**Comment by vide0hanz** [comment]
Performance regression in Proton Experimental, but pretty sure I've narrowed it down to dxvk 1.10 specifically. 

I'm getting some odd stuttering with Prey using Experimental/DXVK 1.10; not the typical shader compilation stuttering but more of a "rubber banding" type effect. I'm not exactly sure how to relay this in terms that are actually helpful for debugging. 

However, manually modifying the prefix created via Experimental by replacing the DLL files with DXVK 1.9.4 versions clears the issue up. This leads me to believe the issue isn't entirely with Proton so much as it is with dxvk. 

Please let me know if there is anything else I can provide that might be more helpful.

**Comment by NoXPhasma** [comment]
@vide0hanz You should report this directly at the [DXVK developers](https://github.com/doitsujin/dxvk/issues).

**Comment by vide0hanz** [comment]
[done](https://github.com/doitsujin/dxvk/issues/2555)

**Comment by Steamvoker** [comment]
I have some weird issues with lighting/reflections. 
[example.webm](https://github.com/ValveSoftware/Proton/assets/23413050/7a7e3bde-2237-4ca7-9eb8-e4f9846d94d6)

Distro: EndeavourOS
Kernel version: 6.4.10-arch1-1
GPU: RTX 4090
Driver/LLVM version: nvidia 535.98
Proton version: experimental, 8.0-3, 7.0-6, 6.3-8
CPU: AMD Ryzen 9 7950X
RAM: 2x32GB DDR5 6000MHz

Edit: Disregard this issue. This is a mangohud issue https://github.com/flightlessmango/MangoHud/issues/1106

**Comment by GunpowderGuy** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/251#issuecomment-520824576

I have the same issue, except its present both in the main game and mooncrash, but seems much more prevalent in the latter. 

I am running the epic game store version through lutris and tried both proton and wine. My os is opensuse tumbleweed

Edit: My gpu is amd rx 6800

**Comment by nlgranger** [comment]
Aiming is bugged for me, the camera starts spinning in all direction with the slightest of movements (both mouse and gamepad with steam input). It worked once for some reason while tweaking settings but I cannot reproduce it.

**Comment by kisak-valve** [comment]
Prey (480490)

Issue transferred from https://github.com/ValveSoftware/Proton/issues/8456.
@NTF121 posted on 2025-02-15T12:41:47:

# Compatibility Report
- Name of the game with compatibility issues: Prey
- Steam AppID of the game: 480490

## System Information
- GPU: GTX 1060 6GB
- Video driver version: nvidia 565.77
- Kernel version: 6.12.13-200.fc41.x86_64
- Link to full system information report as [Gist](https://gist.github.com/NTF121/010c3d1bab43c5fb0192fbf5074ed6c8):
- Proton version: Proton Hotfix, Proton Experimental, Proton 9.0-4, Proton 8.0-5

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-480490.log](https://github.com/user-attachments/files/18810221/steam-480490.log)



## Symptoms 

wine crashed with SIGSEGV instead of normal exit with return code 0

## Reproduction

1. enable virtual desktop in winecfg with resolution 1920x1080
2. launch game
3. quit from program by using ingame menu option

**Comment by NTF121** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/251#issuecomment-2660933714

Addition to reproduction 
1. enable virtual desktop in winecfg with resolution 1920x1080 or use launch parametrs: mangohud %command%
2. launch game
3. switch to other window in desktop environment session
4. return to game window
5. quit from program by using ingame menu option

**Comment by NTF121** [comment]
[MangoHud.conf.txt](https://github.com/user-attachments/files/18985114/MangoHud.conf.txt)
