### ISSUE TITLE
Blade & Sorcery (629730)

### ISSUE THREAD

**Issue by alexcrow89** [ValveSoftware/Proton#2620]
# Compatibility Report
- Name of the game with compatibility issues: Blade & Sorcery
- Steam AppID of the game: 629730

## System Information
- GPU: NVidia GTX 1080 Ti
- Driver/LLVM version: NVidia 418.56
- Kernel version: x86_64 Linux 4.9.0-9-amd64
- Link to full system information report as [Gist](https://gist.github.com/alexcrow89/9631a071545e3350bd96fdf5c41f4597):
- Proton version: 4.2-3

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-629730.log](https://github.com/ValveSoftware/Proton/files/3133418/steam-629730.log)

## Symptoms 
A black window launches briefly, followed by a smaller window with what appears to be the Blade and Sorcery logo with a red exclamation-mark in the upper left corner. This smaller window has a loading progress bar, that upon reaching the end, simply exits the smaller window and thusly the larger window. The game never starts.

## Reproduction
This symptom is reproduced every time I try to run the game.

**Comment by kisak-valve** [comment]
Hello @alexcrow89, what version of SteamVR are you using? If you're using 1.4.5, please opt out of the SteamVR beta branch and retest.

**Comment by kisak-valve** [comment]
The null pointer issue in the log should have been fixed yesterday with the [SteamVR Beta 1.4.6](https://steamcommunity.com/games/250820/announcements/detail/1611636823900827873) update.

**Comment by alexcrow89** [comment]
> Hello @alexcrow89, what version of SteamVR are you using? If you're using 1.4.5, please opt out of the SteamVR beta branch and retest.

Hello, and thanks for reaching out to me so quickly. Unfortunately, the problem persists even on the non-beta branch of SteamVR.

**Comment by Zamundaaa** [comment]
Blade and Sorcery was working for me just fine until the last update. But I still get more than a black screen (see https://github.com/ValveSoftware/SteamVR-for-Linux/issues/204).
Here's my current proton log: 
[steam-629730.log](https://github.com/ValveSoftware/Proton/files/3345678/steam-629730.log)

**Comment by Zamundaaa** [comment]
Okay now I do get the same issue. But with Arizona Sunshine (at least with the Index Controllers). It does load and it gives me the logos in the beginning, and then it's all just black. Here's the log: 
[steam-342180.log](https://github.com/ValveSoftware/Proton/files/3346399/steam-342180.log)

**Comment by aeikum** [comment]
We updated our openvr support in Proton 4.11. Can you please retest with 4.11 and see if this is working now?

**Comment by Zamundaaa** [comment]
I have tested this and it works flawlessly. Can't speak for above though.

**Comment by zaggynl** [comment]
Appears to crash shortly after loading, I see a log then exits back to SteamVR Home.
[steam-629730.log](https://github.com/ValveSoftware/Proton/files/4176883/steam-629730.log)

**Comment by mimattr** [comment]
> I have tested this and it works flawlessly. Can't speak for above though.

@Zamundaaa Agreed, this application now appears to work as expected, can you confirm @alexcrow89 ?

## System Information
- GPU: **RTX 2060**
- Driver/LLVM version: **NVIDIA 455.38**
- Distro version: **Ubuntu 20.04 LTS**
- [Link to full system information report as Gist](https://gist.github.com/mimattr/b0b7f46366e31e254460b9593ce87e51)
- Proton version: **5.13-2**
- SteamVR version: **1.15.10**

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.

## Issues
- [x] I haven't experienced any issues.
- [x] There are no issues left open for this game.

**Comment by HadetTheUndying** [comment]
Application is now rendering only one eye for me in the latest update. Mesa-20.3.4

**Comment by HadetTheUndying** [comment]
> Application is now rendering only one eye for me in the latest update. Mesa-20.3.4

This is still happening what log files do i need to provide to help get this fixed?

**Comment by h8672** [comment]
@HadetTheUndying "PROTON_LOG=1 %command%" add this to your launch options, log is created to your home folder as a text file called steam-629730.log (game Id.log)

## Testing

Headset: Valve Index
OS: Pop OS: 21.10 (Fixed installation with usb-drive since upgrade failed from 20.04. Looked like fresh installation)
Kernel: 5.15.8-76051508-generic
GPU: GTX 1060 6GB (470.86)
Proton: 8.3-8

<details>
<summary>SteamVR(linux 1.14)</summary>

I cannot launch this game currently as SteamVR(linux 1.14) crashes on start when game tries to load.
(I guess using older proton would have yielded better results...)

Loading shows on both eye, but right side is moving in Z axis(forward/backward) instead of X axis(left/right), and I'm pretty sure it is caused by application reading the json settings file wrong.
I fixed it in SteamVR(beta) once by changing resolution scale value in the game after crash
(caused by in-game setting changes, especially those that change resolution scale).

</details>

<details>
<summary>SteamVR(beta) testing results earlier</summary>

### SteamVR and some in-game settings
Basically removed all automatic settings from SteamVR app I found, feels less laggy, I think?
Closed the app and added changes to the steamvr.vrsettings file and restarted it.
SteamVR likes to stay on, so stopping the processes and killing SteamVR and then restarting steam client fixes it most of the time, sometimes have to restart pc.
Closing SteamVR with Quit is actually better than using restart button in SteamVR->Settings window.

Without the settings below SteamVR cuts overlay short, leaving random pixellines at random intervals in either left or right eye monitors. Right one seems to finish better.
Disabling async I found from other topic, which said reprojection causes most issues for the lag.
https://github.com/ValveSoftware/SteamVR-for-Linux/issues/227#issuecomment-520459572
This settings file may change on new SteamVR update.

```
I can get this to work flawlessly with SteamVR(beta) by disabling vulkan async from SteamVR and disable async from app id in

$HOME/.steam/steam/config/steamvr.vrsettings
...
   "steam.app.629730" : {
      "disableAsync" : false, <--- I don't know why it changes to false at times... didn't seem to change performance yet.
   },
   "steamvr" : {
      "enableLinuxVulkanAsync" : false, <--- Disabled async, SteamVR seems to lag or not draw correctly.
   }
...

Game settings file is located in...
.../steamapps/compatdata/629730/pfx/drive_c/users/steamuser/My Documents/My Games/BladeandSorcery/Saves/Default/Options.opt
I think they just apply at start of the game, game doesn't seem to fully load all settings even by reloading json files from in-game console.
in-game settings doesn't change reliably either. Atleast the ones affecting graphics...

```

### Other stuff with SteamVR(beta)

I also installed gamemode from apt manager (ubuntu library) and added "gamemoderun %command%", which doesn't seem to have much difference in this game.    
I wonder if 

> gamemoderun "PROTON_LOG=1 %command%"

as launch option would work...

Games I've tested that disabling vulkan async helped are:
- Beat Saber
- Blade & Sorcery
- SteamVR Home
- VRChat
</details>

Testing results 29.12.2021. I still get nauseated with this game and ai seems laggy so you get a slow motion when against many of them at once.

**Comment by HadetTheUndying** [comment]
Here are my specs.

CPU: Ryzen 7 2700X
RAM: 32GB
GPU: RX Vega 56
Mesa Version: 21.3.2
Distro: Void Linux

The game is only rendering the left eye, the right eye is mirrored of that. I am going to try to fully reinstall the game and delete the prefix now, but this will take some time and I believe I've already done this once. I've been having this issue since u9.0 with, the version of SteamVR doesn't seem to effect it.
[steam-629730.log](https://github.com/ValveSoftware/Proton/files/7794805/steam-629730.log)

**Comment by gofman** [comment]
> Proton: 1603141982 proton-5.0-10b

Can you please try it with the latest Proton 6.8 or Experimental? I recall fixing some one eye issues in the other games since then.

**Comment by HadetTheUndying** [comment]
> > Proton: 1603141982 proton-5.0-10b
> 
> 
> 
> Can you please try it with the latest Proton 6.8 or Experimental? I recall fixing some one eye issues in the other games since then.

Experimental works. Thank you.

**Comment by Zamundaaa** [comment]
I now get double vision too; it looks like the eyes are swapped around. This is on Proton Experimental with Blade and Sorcery U12.1; same happens on older versions of Proton and of the game too though, so I'm not sure if this is a Proton or SteamVR issue. It does not happen with any other games.

[steam-629730.log](https://github.com/ValveSoftware/Proton/files/11171646/steam-629730.log)
