### ISSUE TITLE
Far Cry® Primal (371660)

### ISSUE THREAD

**Issue by NTMan** [ValveSoftware/Proton#2840]
# Compatibility Report
- Name of the game with compatibility issues: Far Cry® Primal
- Steam AppID of the game: 371660

## System Information
- GPU: AMD Radeon VII
- Driver/LLVM version: Mesa 19.1.0/8.0.0
- Kernel version: 5.1.0
- Link to full system information report as [Gist](https://gist.github.com/NTMan/33cca4906328793206218192820779ec)
- Proton version: 4.2-8

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-371660.log](https://github.com/ValveSoftware/Proton/files/3335974/steam-371660.log)

## Symptoms 
Instead of running the game pops error message "Unable to locate Uplay PC. Please reinstall Uplay PC"

![Screenshot from 2019-06-27 22-26-40](https://user-images.githubusercontent.com/200750/60287521-89706a00-992b-11e9-840f-f4c06b2f560a.png)

## Reproduction
Every time when I try launch the game.

**Comment by ChrisLauinger77** [comment]
I could get rid of this error by installing uplay into the proton prefix with protontricks.
nevertheless it still does not start. now it hangs in the splash

**Comment by ChrisLauinger77** [comment]
now it starts and benchmark brings me unfortunate 2 fps - but it starts - so we have progress

**Comment by ChrisLauinger77** [comment]
with this (https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/5.6-GE-2) custom proton it starts and FPS are OK.
no sound though and flickering in GFX

**Comment by ryao** [comment]
@ChrisLauinger77 The flickering issue is this:
https://github.com/doitsujin/dxvk/issues/1257

**Comment by sethdusek** [comment]
The flickering issue can be fixed with a one line patch to dxvk, according to the issue in the dxvk issue tracker. However, applying it may cause hangs in other games like Dirt Rally 

https://gist.github.com/SethDusek/73b2783c878cff2f91a245d4efd486dd

**Comment by kakra** [comment]
> The flickering issue can be fixed with a one line patch to dxvk, according to the issue in the dxvk issue tracker

I won't call that a fix (if it even reliably works), it's more like working around some undefined/weird expectations of the game engine.

It's more likely that ANY code change around that part of the code/accessed memory triggers some (valid) state modification of memory that the engine expects to have some implied value, and just by coincidence that happens to have just the right values for the game's expectations in some cases. I'm not sure if it's possible to run this through valgrind to analyze memory access. If it is, it probably generates huge amounts of data and runs exceptionally slow, and analyzing the data will probably be horrible. But it may point to some invalid memory access patterns. Or maybe some memory allocation is just not zero-initialized in wine/dxvk when in Windows it is.

**Comment by ChrisLauinger77** [comment]
With proton 5.13-4 it starts, audio is there, gfx are nice and FPS good. However it does not connect to UBISOFT servers and it also does not autosave. When I restart the game there is no option to load or contnue. Only start a new game.
No idea if this has something to do with the connection to UBISOFT servers but it is still unplayable
EDIT: after verifying game cache it connects also to UBISOFT connect and the saves work as well

**Comment by kakra** [comment]
Except the flickering in the benchmark, the game seems to run fine with Proton Experimental: Ubisoft Connect works, audio works. But the game won't detect my Xbox One S game controller. Any ideas?

**Comment by AldoLinx** [comment]
After installing uplay with protontricks the game launch correctly and plays nicely with proton 5.13-4.
The only problem I saw so far is that the game won't detect my Steam Controller.

**Comment by kakra** [comment]
@aeikum Seems like the game doesn't detect gamepads...

**Comment by kakra** [comment]
Some research shows that the game actually only detects the original Xbox 360 controller connected via USB. I don't have such a controller to test but people report that x360ce (an xinput emulator providing dinput and xinput dlls) can work around this (tho it's not easy to get this to work with Proton/wine). So I assume what we would need in Proton is a hack that exposes any gamepad exactly as the original Xbox 360 wired controller.

Would this be possible to implement? A first implementation could force this mode via environment variable, later Proton version could detect the Steam game ID and automatically enable the hack on a per-game basis.

**Comment by aeikum** [comment]
@kakra That is pretty much exactly what the Steam controller mapping feature is for. It turns any joystick into an Xbox 360 joystick. It should be working pretty well with Proton, did you give it a try? E.g. Steam->Settings->Controller->General Controller Settings->[Controller Type] Configuration Support.

**Comment by kakra** [comment]
@aeikum Yes, I tried. If just ticking the box "Xbox Controller Configuration Support" (and maybe adjusting the game properties to respect that setting) is enough, then it doesn't work for this game. (Proton Experimental)

**Comment by kakra** [comment]
@aeikum Well, I could enable general gamepad support, and it *somehow* works for some games but the games actually still do not detect the controller, instead, Steam input just emulates a mouse/keyboard from the controller inputs. This is pretty much unusable for camera adjustments / targeting. It mostly works for walking around. But that's it. That's not what I would call "pretty much exactly what the Steam controller mapping feature is for": Mapping the controller to keyboard/mouse input doesn't make it a proper controller in the game. But in a sense it's probably something that x360ce can also do. But turning on Steam input didn't make my controller map to a standard Xbox 360 "joystick" - it just mapped my controller to keyboard/mouse inputs for those games. BTW: That's why I don't like Steam input for my controller: It maps some games to keyboard/mouse by default which simply doesn't work well - even for games that properly support the controller natively.

**Comment by kakra** [comment]
@aeikum @ivyl I can confirm that as of the latest Proton 6.3 Experimental (2021-05-04) update, the controller is now detected. But only if I disable Steam input support. I have no idea why but hey, it works. :-)

**Comment by ivyl** [comment]
@kakra good to know that there are still some problems with Steam's controller mapping for that game. I'll add that to the list. Thanks!

There's also a super weird issue where the controller is detected (i.e. you get the prompt, and the game polls `XInputGetState()`) but inputs from it are ignored. This happens only on NVIDIA + Gnome combo :shrug:

**Comment by kakra** [comment]
> This happens only on NVIDIA + Gnome combo

@ivyl Then let's add: NVIDIA + KDE here (with Plasma systemd startup mode enabled if that matters)

**Comment by kakra** [comment]
The game runs generally fine but I'm seeing overexposed glare in many cutscenes, sometimes across the whole screen:
![20210602000145_1](https://user-images.githubusercontent.com/17684/120441221-a407b500-c384-11eb-93fe-d786bc8fa349.jpg)
![20210602000139_1](https://user-images.githubusercontent.com/17684/120441227-a538e200-c384-11eb-94ed-a6ae10cf70d0.jpg)
![20210602000125_1](https://user-images.githubusercontent.com/17684/120441228-a538e200-c384-11eb-84aa-895b6caeb222.jpg)
(these are from the second time you enter the shaman's hut)

**Comment by ipr** [comment]
Installing from scratch result in error message about Uplay not being found. So the installer for that is not run correctly or it is confused when there is (newer) UbisoftConnect in existence?

Edit: Ubisoft should update the install script?

Running the installer manually fixes it:
...
WINEPREFIX=/path/compatdata/371660/pfx /path/Proton\ -\ Experimental/files/bin/wine64 /path/Far\ Cry\ Primal/Support/Software/GameLauncher/UplayInstaller.exe
...

**Comment by ruineka** [comment]
Launchers being launchers by breaking the launching of a game again. When trying to play this game I get a message saying Uplay was not found. Most likely because they moved to Ubisoft Connect.

:(

**Comment by jazztickets** [comment]
Running the game in XFCE with Proton Experimental and it's impossible to Alt-Tab or "Show Desktop" out of the game. The window keeps refocusing, even in windowed mode.

**Comment by kisak-valve** [comment]
Far Cry Primal grabbing all RAM and killed by OOM

Issue transferred from https://github.com/ValveSoftware/Proton/issues/9618.
@sub205 posted on 2026-03-26T10:00:56:

# Compatibility Report
- Name of the game with compatibility issues: Far Cry Primal, Far Cry 4, Far Cry 5
- Steam AppID of the game: 371660

## System Information
- GPU: 9070XT
- Video driver version: Mesa 25.2.6-1~bpo13+1
- Kernel version: 6.19.9-x64v3-xanmod1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/sub205/38f572c45cd454d06f43dcf38bf05ce5
- Proton version: tried several (hotfix, experimental, 9.0)

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.



## Symptoms 

Upon start, the games exe allocates all memory and swap after some seconds until the kernel kills it (oom)
Happens to the Ubisoft- and the Steam version. Problem also happening on Far Cry 4/5.

Don't know if related to hardware change (5800X3D -> 9950X3D)
Both systems have/had 64GB RAM.

Also happens with Lutris and regular Wine.

System is Debian13 with upstream Mesa (for compatibility with Doom Dark Ages)

## Reproduction

1. Install game
2. Run game
3. Gets killed by OOM
***
@sub205 commented on 2026-03-26T10:06:02:

[steam-371660.log](https://github.com/user-attachments/files/26270254/steam-371660.log)

**Comment by sub205** [comment]
It seems i've found the issue:

https://github.com/ValveSoftware/Proton/issues/5927

Limiting Corecount to 4 (first test) and the game runs.
BUT: It complains it's unable to activate, so i had to install it a second time trough the bundled ubisoft connect client.

Anyway, looks promising! Will report when i have tested further.

BTW: It would be great to have some option in the steam game settings to limit CPU / RAM-assignment via GUI. I never came across this option before you moved my bugreport to this thread! This should be a basic option (maybe with defaults like 8 therads for games before like 2017 or similar intelligent values). Took me hours to figure it out by my self!
