### ISSUE TITLE
Tekken 7 (389730) not detecting controller on Proton newer than 3.16

### ISSUE THREAD

**Issue by Shotweb** [ValveSoftware/Proton#2930]
#### Your system information

* Steam client version (build number or date): Jul 17 2019
* Distribution (e.g. Ubuntu): GeckoLinux Rolling (Opensuse Tumbleweed) - but this was also an issue on Ubuntu (16.04 and 18.04)
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Using Proton older than 4.x series, ie. 3.16, Tekken 7 correctly detects my controller as "Mad catz Inc. Mad Catz Fightstick Alpha PS4" and everything works. On Proton 4.2 or 4.11, it can't find it and simply says "No controller detected".

I have tried to check the boxes for Generic and Playstation controllers in Steam Settings, with no difference. Steam itself doesn't seem to detect it at all, as "Guide button chord configuration" also says "No controller attached".

#### Steps for reproducing this issue:

1. Use Proton newer than 3.16

**Comment by kisak-valve** [comment]
Hello @Shotweb, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options, reproduce the regression, and drag and drop the generated $HOME/steam-$APPID.log into the comment box.

**Comment by Shotweb** [comment]
[steam-389730.log](https://github.com/ValveSoftware/Proton/files/3453897/steam-389730.log)

**Comment by Shotweb** [comment]
Additional info:

I started Steam from terminal and it correctly finds the controller. Then, leaving Steam open, it slowly spams the terminal with the part about finding the controller:

Local Device Found

  type: 0738 8180

  path: sdl://0

  serial_number:  - 0

  Manufacturer: 

  Product:      Mad catz Inc. Mad Catz FightStick Alpha PS4

  Release:      111

  Interface:    -1

**Comment by aeikum** [comment]
Hello, Proton 4.11-3 had a major re-work of how we report controllers to applications. I believe fighting pads should be working better. Please retest and let us know if things have improved.

**Comment by Shotweb** [comment]
[steam-389730.log](https://github.com/ValveSoftware/Proton/files/3549677/steam-389730.log)

I can now report that my fightstick works when I put it into PS3 mode (it has a switch), however still not in PS4 mode. I think I also did test PS3 mode before but I'm not 100% sure, so maybe it has worked all the time. New log with 4.11-3 and the fightstick in PS4 mode attached.

**Comment by Shotweb** [comment]
[steam-389730.log](https://github.com/ValveSoftware/Proton/files/3612958/steam-389730.log)

I don't know what's changed, but Tekken 7 updated (not season 3 update), and now PS3 mode doesn't work either.

**Comment by Shotweb** [comment]
Regarding my last post, I think Proton must have updated that time. So, it was working in 4.11-3, so maybe if you could take the part from that version, it would be great.

**Comment by Shotweb** [comment]
I have just found out that it works in 4.2-9 with the fightstick in PS3 mode (after unchecking all boxes in "General controller settings"), but not in 4.11-12 at all. So that's a bit better I guess.

**Comment by Shotweb** [comment]
I have got it working with Proton 5.0-9 by setting "Steam Input Per-Game Setting" to "Forced Off".
