### ISSUE TITLE
[Doom 2016] freeze when looking at (large) Medikit (379720)

### ISSUE THREAD

**Issue by Termuellinator** [ValveSoftware/Proton#3029]
# Compatibility Report
- Name of the game with compatibility issues: Doom
- Steam AppID of the game: 379720

## System Information
- GPU: Powercolor 5700xt Red Devil
- Driver/LLVM version: mesa-git 1:19.3.0_devel.114992.3664a6600eb-1/ llvm-libs-git 10.0.0_r325795.7238353da24-1
- Kernel version: linux53 5.3rc6.d0826.ga55aa89-1
- Link to full system information report https://gist.github.com/Termuellinator/e7a7d27c2ebaad492c0c82ade1035981
- Proton version: 4.11-3

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

Proton-Log is almost 70MB, so i can't upload it here -> https://www.dropbox.com/s/j02uevrcjab8cn4/steam-379720.log?dl=0

## Symptoms: 
Hard System freeze - no TTY, soundloop

## Reproduction: 
Start game, look at a Large Medipack (https://doomwiki.org/w/images/d/d2/Supplies_LargeMedikit.png) from nearby. It doesn't happen, when you see it from a distance, so i assume it is only the full-LOD Modell that causes it. Also, approaching the Medipack backwards doesn't trigger the freeze, it has to be seen.

I'm noticing it in the level "the Well" - haven't had this issue before, but that was on a rx580 with mesa 19.1/LLVM8.

**Comment by jtheoof** [comment]
Not sure if that might help someone else, but I found a workaround in my case with DOOM.  I tried the following:

- In Steam, I disabled the In Game Steam Overlay
- I switched the Graphics API from OpenGL to Vulkan

I did not have any crash so far. But I haven't tried to isolate one or the other.

```
# uname -a
Linux ansan 5.3.1-arch1-1-ARCH #1 SMP PREEMPT Sat Sep 21 11:33:49 UTC 2019 x86_64 GNU/Linux
```

Packages:
```
linux 5.3.arch1-1
linux-firmware-agd5f-radeon-navi10 2019.09.13.18.36-1
mesa-git 1:19.3.0_devel.115574.40087ffc5b9-1
vulkan-radeon-git 1:19.3.0_devel.115574.40087ffc5b9-1
libdrm 2.4.99-1
lib32-mesa-git 1:19.3.0_devel.115574.40087ffc5b9-1
lib32-vulkan-radeon-git 1:19.3.0_devel.115574.40087ffc5b9-1
lib32-libdrm 2.4.99-1
```

I have an RX 5700 XT.

**Comment by Termuellinator** [comment]
Strange, Doom crashes for me on startup when trying to use vulkan - both on my old system (rx580) and on the new one - did you do anything special to get it to run?

**Comment by jtheoof** [comment]
@Termuellinator maybe try to clean to the config file (after backup).

`rm -rf ~/.local/share/Steam/steamapps/compatdata/$APP_ID/pfx/drive_c/users/steamuser/Saved Games/id Software/DOOM/base/DOOMConfig.local`

In my case (I think it's the same for everyone) `APP_ID` is `379720`

**Comment by jtheoof** [comment]
There is an [update of Steam Beta](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1591383946838639778) today with potential fixes. 

> Linux:
> Fix GPU crashes and overlay corruption with games that use Vulkan async compute, such as DOOM 2016.

I haven't tried yet. If anyone could try and report it would be nice.

**Comment by Termuellinator** [comment]
removing DOOMConfig.local lets the game launch again - with openGL. After setting it to vulkan, it crashes on launch again, even with the new beta :/

**Comment by hakzsam** [comment]
Can you please retry with recent mesa? I fixed an issue, see https://gitlab.freedesktop.org/mesa/mesa/commit/ad96c4987cb2b23a9314a0a01fea8153843de8ef

**Comment by Termuellinator** [comment]
Still freezes with mesa-git 1:19.3.0_devel.115908.6309c31fd81-1 when looking at medipack.
The comment on this patch refers to crash on startup anyways, plus i can't use freesync because my second monitor does not support it.

**Comment by kisak-valve** [comment]
Hello @Termuellinator, 6309c31fd815285dab4d6e79dcbdd4773350e50f is older than the commit in question, so that test doesn't really tell us if ad96c4987cb2b23a9314a0a01fea8153843de8ef helped.

**Comment by Termuellinator** [comment]
I've now got mesa-git 1:19.3.0_devel.116087.e6986bcb733-1 installed - excuse the noob-question, but how can you tell which commit is older? The commit list is confusing me as it is listing for example e6986bcb733 for yesterday, but in the commit it is saying two weeks ago?

**Comment by kisak-valve** [comment]
I'm guessing you were looking at the [author date on Gitlab](https://gitlab.freedesktop.org/mesa/mesa/commit/e6986bcb733), instead of [the commit date](https://cgit.freedesktop.org/mesa/mesa/commit/?id=e6986bcb733) which is yesterday for e6986bcb733.

**Comment by Termuellinator** [comment]
Ah, so i just looked in the wrong place, thank you!
But e6986bcb733 still freezes the system unfortunately.

**Comment by hakzsam** [comment]
@Termuellinator Does this still happen with Mesa 19.3?

**Comment by Termuellinator** [comment]
haven't tried yet, i'll try to do so during the holidays :)

**Comment by Termuellinator** [comment]
It's fine now with proton 4.11-11, Mesa 19.3.1, LLVM 9, Linux 5.4.6 and linux-firmware 20191220.6871bff
