### ISSUE TITLE
Sid Meier's Civilization III: Complete (3910)

### ISSUE THREAD

**Issue by edmondo** [ValveSoftware/Proton#315]
**Sid Meier's Civilization III: Complete** runs well.

Screen resolution workaround for correct mouse input needed:
- Add following line to _.../Sid Meier's Civilization III Complete/Conquests/conquests.ini_
  `KeepRes=1`

Tested on:
- Gentoo Linux
- Proton 3.7
- Radeon RX 470 (POLARIS10)
- Mesa 18.3.0-devel (git-8a87138885)

[steam_systeminfo.txt](https://github.com/ValveSoftware/Proton/files/2315899/steam_systeminfo.txt)

**Comment by neuromancer** [comment]
I tested without the workaround and it's very unstable, so make sure you use it.

**Comment by vandergail** [comment]
I'm having audio issues with this game. I know there seems to be issues on Windows, as well, because the game uses a deprecated audio API but it's worse with Proton. Some of the sounds don't work at all and others, such as the bird chirps and citizen cheers, just loop endlessly. Everything else works fine though.

**Comment by Newbytee** [comment]
With Proton 5.13 and up (tested every version above, including Experimental) my cursor refuses to go inside the game window when playing in fullscreen (I didn't test windowed) once I reach the main menu. With Proton 5.0 (and presumably older) it correctly goes inside the window.

Worth noting is that the game seems to lock your cursor inside the game window when you're viewing the main menu, maybe this is related?

Relevant information:

 - nvidia 460.67
 - GNOME 3.36 X11
 - Fedora 32

Log from experimental: [steam-3910.log](https://github.com/ValveSoftware/Proton/files/6277937/steam-3910.log)

**Comment by Newbytee** [comment]
I also wouldn't really consider this whitelist-quality considering the audio issues also mentioned by vandergail. A short section of the music suddenly started looping and while it sounded … interesting, it definitely didn't sound right and made the game quite unpleasant to play.

**Comment by ModProg** [comment]
In a multi monitor setup I needed to disable auto capturing of the cursor in the winecfg settings (`protontricks 3910 winecfg`).

I also needed to use 3.7-8, because in newer versions the map would randomly scroll when the game was not on my right most screen. 

In 3.7-8 I also did not have the black terrain issue. Could that old version be made the default version for the game?

**Comment by waspennator** [comment]
Game still has an issue on my oled deck on latest Experimental where the map will go completely black clicking around on my deck.

[steam-3910.log.txt](https://github.com/ValveSoftware/Proton/files/14814002/steam-3910.log.txt)
![download](https://github.com/ValveSoftware/Proton/assets/78768499/1eb1606c-1c9e-445b-914f-2330de634fb7)

**Comment by ModProg** [comment]
> Game still has an issue on my oled deck on latest Experimental where the map will go completely black clicking around on my deck.

Works on `5.0-10` for me.

**Comment by vandergail** [comment]
> Game still has an issue on my oled deck on latest Experimental where the map will go completely black clicking around on my deck.

This bug can also be fixed by installing the C3X mod. You will have to run the batch installation script with Proton. [C3X Github Page](https://github.com/maxpetul/C3X)

A contributor on WineHQ has been able to pin down the audio issues to specific WAV files be affected. They have provided an imperfect workaround by replacing these files with a dummy file. Most of the audio is functional with their solution. [WineHQ - Bug 51502](https://bugs.winehq.org/show_bug.cgi?id=51502)

**Comment by BlastBlaster17** [comment]
I am running the game on Manjaro with the kernel version 6.12.4-1-MANJARO, and when I try running the game with its default settings, I get this:
![Screenshot_20241224_195522](https://github.com/user-attachments/assets/7d6ac95e-cf3c-4e25-aeba-953860496bec)
Here you can see that, for whatever reason, the game isn't being drawn over the entire desktop. I'm using Wayland, BTW, but I don't think that should be a problem.

When I put the line "KeepRes=1" inside the conquests.ini file, I get this:
![Screenshot_20241224_200105](https://github.com/user-attachments/assets/b92dd1e2-4be8-4426-946d-3a612738ab93)
It's the same issue, except it doesn't seem to be scaling anything this time.

And when I add the windowed-mode option configuration mentioned on PCGamingWiki, this is what I get:
![Screenshot_20241224_201334](https://github.com/user-attachments/assets/1086cc41-c649-4732-ba3e-78a57811bc60)
Not only is the game not actually windowed, but it is confined to the top-left corner of the screen.

Launching the game with Gamescope in full-screen just seemed to screw around with the cursor and the buttons and rendered me unable to actually click on anything. I had to use the arrow keys just to navigate my way over to the exit button. This is all on Hotfix, BTW.

**Comment by steve7233** [comment]
Look at this:
**SYSTEM REQUIREMENTS
Operating System:	Windows(r) 98/Me/2000/XP**
Notice the OS requirements? Isn't wine currently defaulting to Win10?
How do we tell wine to use Win XP?

**Comment by steve7233** [comment]
I did a google search about switching to windows xp in steam to try to get this game working and found this:
It is not possible to directly switch to Windows XP in Steam on Linux as Steam no longer supports Windows XP on any platform, including through compatibility layers like Proton; you will need to use a more recent Windows operating system to run Steam and your games on a Windows system. 
I suspect we will need Fireaxis to redo the SDK or something.

**Comment by ModProg** [comment]
@steve7233 did you try older versions of Proton?

In the past I used 3.7-8 and later 5.0-10.

Not sure if that might be a way to get "old windows".

**Comment by steve7233** [comment]
I just tried Proton 5.0-10. The intro video is about 1/8th my screen and in the top left corner. After the video, I get the main menu in a small square in the middle of my screen. I can't find a way to change the resolution via the GUI. I will try a game and see how that works. Thanks ModProg.

**Comment by steve7233** [comment]
The display is too small to play!

**Comment by steve7233** [comment]
The best solution I found for large monitors is to replace the keepRes command with "VideoMode=1792." Unfortunately, that is the highest resolution for the game that I could find support for. There is no widescreen support unless you find a mod. That makes the game reasonably playable. You don't enter the complete resolution just the first number. Ether that or lower.

**Comment by ModProg** [comment]
I thought setting "KeepRes=1" should keep the resolution, if that is not enough you could try to run it with game scope and scale it

**Comment by winterheart** [comment]
Black terrain bug is fixed in upstream Wine 10.13, need backported Proton 10.13 (or better?) to fix this in Steam environment. Still, there other issues like sound stutter and no lines in Diplomacy screen.

**Comment by alehel** [comment]
Still having the terrain bug in Proton 11. That said, it goes a bit back and forth between being black and showing the terrain. Not seeing a clear pattern in what makes it come and go.

proton-cachyos seems to work perfectly however if someone wants a quick and easy solution to get it running.
