### ISSUE TITLE
Proton 4.11-8 - Gamepad input causing game to lag

### ISSUE THREAD

**Issue by RonnieTiger** [ValveSoftware/Proton#3211]
The recent 4.11-8 update that came through has had a huge impact on gamepad support. 

Confirmed the issue does not exist in 4.2-9 and i don't recall it existing in a previous version of 4.11-? but i don't recall which version of 4.11 i was previously using, and it's not showing in my version listing. 

However using Keyboard and mouse remains unaffected. Issue only happens using controller.

Attached a video (Zipped) Of the problem.

[video_2019-11-11_18-41-50.mp4.zip](https://github.com/ValveSoftware/Proton/files/3832880/video_2019-11-11_18-41-50.mp4.zip)

I have tried Kernel version 4.11 and 5.x and the issue remains. 
Tried different controllers, same problem.

**Comment by aeikum** [comment]
What game(s) are affected? What type of controller are you using?

**Comment by RonnieTiger** [comment]
> What game(s) are affected? What type of controller are you using?

Xbox 360 controller and XBox One controller both affected. Game i've tested this on is ESO.

**Comment by RonnieTiger** [comment]
If it helps any, the last time i used it was a week ago (Sunday 3rd September) And i believe at the time i was using whatever the latest version of 4.11 was at the time and things were working fine then, so it's an update between then and this Sunday (10th) when the last client update came through that pushed me to 4.11-8
(4.11-2 or 6 maybe?)  if there is a way to pull specific versions of proton below -8 and run, I'm willing to back-track and find which version the issue appears, as i see from change logs a lot of gamepad work has occurred through these dash releases.

Edit: that goes for proton logs too, if you need me to re-create the problem again and gather logs.

**Comment by aeikum** [comment]
Thanks. This might possibly be due to the same problem that is causing #3198, which I'm looking into right now. Will keep you updated.

**Comment by yuiiio** [comment]
Is it really same issue?
Please try https://github.com/yuiiio/Proton/releases/tag/proton-4.11-9-alpha
I have revert "user32: Implement WM_INPUT/RIM_TYPEHID message handling."

**Comment by aeikum** [comment]
Hi @ronlaws86. Unfortunately we haven't been able to reproduce this. Can you upload a log here after setting `WINEDEBUG=+dinput,+xinput,+rawinput,+hid,+setupapi,+timestamp,+tid`? You can set this either in the Steam launch options or in `user_settings.py`. Let me know if you need any more instructions.

**Comment by yuiiio** [comment]
I can repro cuphead and dualshock4.
I have replaced dxvk to github release page's one for another bug.
[steam-268910.log](https://github.com/ValveSoftware/Proton/files/3879470/steam-268910.log)

**Comment by aeikum** [comment]
This might be fixed in 4.11-9. Please retest and let us know. We still haven't been able to reproduce on our end.

**Comment by yuiiio** [comment]
[steam-268910.log](https://github.com/ValveSoftware/Proton/files/3903153/steam-268910.log)
bug still alive.
without controller
![Screenshot from 2019-11-29 07-04-18](https://user-images.githubusercontent.com/36093713/69834238-9c8dba00-127c-11ea-9904-b0a1e1af32a5.png)
with controller
![Screenshot from 2019-11-29 07-05-26](https://user-images.githubusercontent.com/36093713/69834246-ab746c80-127c-11ea-85f5-ce83f17d9268.png)

**Comment by aeikum** [comment]
@yuiiio Thanks very much for the log. That had enough information for me to be able to reproduce the problem. This should be fixed in the next Proton release.

**Comment by RonnieTiger** [comment]
Confirmed here, bug still present in 4.11-9

(sorry not sure why i didn't get an e-mail alert for the request, looks like someone else managed to get a log in though)

**Comment by RonnieTiger** [comment]
[steam-306130.log](https://github.com/ValveSoftware/Proton/files/3935436/steam-306130.log)
My log just in case, I didn't load fully in to the game but could see the FPS dropping from 100 to 80~ on title screen just by mashing the controller.

**Comment by aeikum** [comment]
This should be fixed in 4.11-10. Please restart your Steam client to update Proton and retest!

**Comment by yuiiio** [comment]
I can confirm fix this.
thanks again :)

**Comment by RonnieTiger** [comment]
Looking good here on ESO! not seeing the drop from 100 to 80 on title screen when mashing controller (FPS stays 100 solid as it should) and in-game performance looks good. Tested in the same area as the video for consistency, only seeing mild movement-related frame rate loss which is still above 80fps and within expected range for an MMORPG (Normal behaviour) 

No hitching, 
no freezing
-- Butter smooth. 

Well done guys!

**Comment by aeikum** [comment]
Great, thanks for reporting and retesting.
