### ISSUE TITLE
Mirror's Edge (17410)

### ISSUE THREAD

**Issue by unlimitedbacon** [ValveSoftware/Proton#355]
This game has been running great under Wine for many years. It runs well with Proton, too. Only issue is that it lags during some sequences when you have PhysX enabled.
https://appdb.winehq.org/objectManager.php?sClass=version&iId=21159

[Steam System Info](https://gist.github.com/unlimitedbacon/bd3cb34fbedc3e5e9355024e9c29e474)

**Comment by tingvarsson** [comment]
Can confirm.
[SysInfo](https://gist.github.com/tingvarsson/dc2eec45ac3e1b67cc5316b61f32bd75)

**Comment by Frans-Willem** [comment]
Can confirm too
[Sys info](https://gist.github.com/Frans-Willem/8af8df2b61666ba21fa7a300b15dc00e)

**Comment by pprotonrep** [comment]
I had some issues with the resolution during first start (https://github.com/ValveSoftware/Proton/issues/141) but otherwise it works very well.

**Comment by ghost** [comment]
Also fine on my [Debian testing](https://gist.github.com/DrWindu/1a10ea5e4305d2f4716bc75fdf6fdfff).

**Comment by kforney** [comment]
Can also confirm on Fedora 28.  Only problems were PhysX and the resolution being too low on first start.

**Comment by diegogangl** [comment]
Can confirm on KDE Neon (Ubuntu 16.04). I also got low resolution/settings on the first run.

Specs:
- GTX 980
- Nvidia drivers 396.51
- Kernel 4.15.0

**Comment by kakra** [comment]
Game experience is not very good for me with Proton. The games runs fine, yes, but movement is sluggish and it looks like FPS are very inconsistent. This doesn't happen with my own build of wine which includes some bits of Proton and Staging (in the branches):
https://github.com/kakra/wine

So I guess it's either related to Proton being based on quite old Wine 3.7, or some of the Staging cherry-picks I'm using. In my own Wine build, I didn't include the full-screen hacks, yet, so this game is somewhat complicated to start (because the game minimizes on start and would freeze when you click it, you can get around this with alt+tab'ing to the game).

PhysX is turned off.

I see similar behavior in other games when comparing both implementations.

**Comment by swick** [comment]
Performance isn't good but it works. Much better experience with gallium nine.

    OpenGL renderer string: AMD Radeon(TM) HD 8800 Series (PITCAIRN, DRM 3.26.0, 4.18.0, LLVM 6.0.1)
    OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.1.6

**Comment by edn9** [comment]
Work with lag for me even in the low, maybe because my hardware.

Arch Linux
Kernel 4.18.3
Proton 3.7
bspwm 0.9.5
CPU Intel Core i3-2350m @ 4x 2.3GHz
RAM 4gb
GPU Intel(R) HD Graphics 3000

**Comment by TomJansen** [comment]
For me the cursor in the Steam Overlay does not show up, but that is the only thing. See #678

**Comment by andrebadaia** [comment]
Confirmed.

Distro: Linux Mint 19 Tara
Processor: AMD Ryzen 7 1700
GPU: GTX 1070, Nvidia proprietary driver 396.54
RAM: 32GB
Kernel (custom) - 4.17.14 (optimized for Ryzen)
Resolution: 1920x1080
Proton 3.7-3

**Comment by DoubyCz** [comment]
Confirmed, works great incl. nvidia PhysX supoort [SysInfo](https://gist.github.com/DoubyCz/ddfa8a99e121fc3213206aa2db8a1ff3)

**Comment by kakra** [comment]
@DoubyCz Please check the scene when first meeting her sister... Does it still work great when the glass shatters?

**Comment by geraintwhite** [comment]
I get a crash every time launching the game as soon as the first loading chapter finishes. It happens both with PhysX turned off and on.

https://gist.github.com/grit96/ff9f43bb8d42a4a86dd1bd9ac9b7d9f1

**Comment by hswhite33** [comment]
Gave this a go because so many people had reported it working flawlessly, and I had a very different experience:

* Black screen on launch - in order to get it to launch correctly I have to switch to a different desktop until I hear the intro start, then switch back
* Performance not great (though it's a while since I played it in Windows so I can't really compare)
* Mouse doesn't get captured properly so I can only turn so far to the right, and if i move too far left the cursor goes onto my other monitor
* If the window loses focus, I get a black screen with a tiny bit of game in the top left corner ([image](https://i.imgur.com/mKedaYd.png)), which is completely unresponsive (I have to kill it with xkill, it doesn't respond to my window manager's window close events)
    * if I do this during a cutscene, it seems to correct itself when the cutscene ends
    * It's worth noting that this is the case with most of the games I've tried running in proton so far

[System Info](https://gist.github.com/hswhite33/d5872273b13aa91e29a7104c1c4866a9)

Proton 3.7-5 Beta

[steam-17410.log](https://github.com/ValveSoftware/Proton/files/2347616/steam-17410.log)

**Comment by kakra** [comment]
@hswhite33 Could you test this build: https://github.com/kakra/wine/releases/tag/wine-proton-3.7-unofficial
(you need to be familiar with how to replace Proton with a custom build)

**Comment by hswhite33** [comment]
@kakra I tried out your build - the performance is noticeably improved and the mouse capture issue seems to be fixed. All of the other issues I mentioned are still present though. Great work!

**Comment by kakra** [comment]
I'm having a similar issue: The game starts in minimized mode 99 out of 100 times. I need to hold alt key and press tab twice to focus the window into foreground as soon as sound starts. I usually do not leave the focus so I never noticed your other issue. Currently I know no way around it. I think both issues have a very similar root cause in wine.

**Comment by kisak-valve** [comment]
Mirror's Edge™

Issue transferred from https://github.com/ValveSoftware/Proton/issues/1336.
@NTMan posted on 2018-09-08T21:01:46:

# Whitelist Request
- Name of the game to be whitelisted: Mirror's Edge™
- Steam AppID of the game: 17410

## System Information
- GPU: AMD Vega 56
- Driver/LLVM version: 18.2.0-rc5/7.0.0
- Kernel version: 4.19.0-0.rc2.git2.1
- Link to full system information report as [Gist](https://gist.github.com/NTMan/33cca4906328793206218192820779ec)
- Proton version: 3.7-6 Beta

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [x] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options)
      are necessary to run the game.
- [x] that no workarounds other than the mentioned ones are necessary.

## Issues
- [x] I haven't experienced any issues.
- [x] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are
      remaining issues:

May be insufficient FPS for comfort playing in some scenes on high settings and 4K

![screenshot from 2018-09-09 01-55-27](https://user-images.githubusercontent.com/200750/45258639-49f48380-b3d4-11e8-8f9b-7608d4930cb5.png)

**Comment by kakra** [comment]
@hswhite33 Would you like to retry this build which is Proton 3.7 rebased to Wine 3.12 plus some more performance patches:
https://github.com/kakra/wine/releases/tag/wine-proton_3.7-3.12-unofficial

**Comment by hswhite33** [comment]
Hi @kakra , the same issues are still present with this build. Performance is about the same as with your previous build (averaging around 55-60fps)

**Comment by hypothermic** [comment]
Can confirm. Worked out of the box for me.
[Sys info](https://gist.github.com/hypothermic/4692e7fa757a8be01ea165301dd14445)

**Comment by kakra** [comment]
@hswhite33 I probably cannot fix the remaining problems because I don't know enough about the inner workings of wine, or how the full-screen hack works. But I think I'm seeing the same issues:

1. Loosing focus hides the window and freezes the game (sound may continue to play). Restoring from this state may end up in a tiny, icon-sized window in the top left corner, maybe even with screen activity still going on. The rest of the screen stays black/frozen.
2. Game starts minimized and out of focus (no window has focus), Alt+Tab can fix this but only when you Alt+Tab directly to the game, otherwise results in 1.

Is this it?

I think, mouse capture was fixed already. And I cannot see any issues with the cutscenes here as long as you do not unfocus the game window.

Many games suffer from 1 so it's a more general problem. Very few games show issue 2 behavior, one other is Dishonored (at least in earlier Wine versions, usually it works now). I suspect this has to do with splash logo windows shown by some games on the desktop during startup, and then wine doesn't catch the switch to fullscren later correctly, i.e. Mirror's Edge shows such a loading screen before going fullscreen.

**Comment by hswhite33** [comment]
@kakra Yes that summarizes my experiences. The mouse capture issue was fixed in your build; I haven't tried the 3.7-6 beta build to see if it's fixed there. 

I've actually configured my window manager to force all wine windows to start in fullscreen on the correct monitor because in a couple of other games having them start as floating/tiling windows and then manually moving them was causing your issue 1. too.

**Comment by BlitzKraft** [comment]
@kakra: Is there a workaround for the icon sized game window? I am facing this issue exactly as described by hswhite33. However, their fix doesn't work for me. Losing focus still makes the game icon sized.

I understand a fix might take some time. Looking for some clue to skip having restart a game just because it lost focus.

**Comment by kakra** [comment]
I think this is up to the experts from Valve because I don't understand the code yet behind the full-screen hacks. Maybe just try not to loose focus from the game and it should work (I completed the story that way, so it's possible, it crashed just once). This problem also occurs with vanilla wine here.

**Comment by kakra** [comment]
@BlitzKraft @hswhite33 Here's a new build by me which should fix the issues:
https://github.com/kakra/wine/releases/tag/wine-proton_3.7-3.16-unofficial-1

**Comment by ghost** [comment]
@kisak-valve 
# Whitelist Request
- Mirror's Edge
- 17410

## System Information
- GPU: RX 570
- Driver/LLVM version: Mesa 18.3 & LLVM 7
- Distro: Sabayon
- Link to full system information report as [Gist](https://gist.github.com/Alexander88207/72c104e4d0f59898cc4ede2fce2de25a):
- Proton version: 3.16-5

## I confirm:
- [✔] that pressing the `Play` button in the Steam client is sufficient.
- [✔] that no workarounds other than PROTON_* env variables are necessary.

## Issues
- [✔] I haven't experienced any issues.
- [⌛] There are no issues left open for this game. Some have problems, some don't have problems. Needs more reports with the latest proton version.

**Comment by hswhite33** [comment]
Confirming that of the issues I listed [here](https://github.com/ValveSoftware/Proton/issues/355#issuecomment-418272173), the only one that is fixed with Proton 3.16-5Beta is the mouse capture. This game is **not** whitelist-ready.

[System info](https://gist.github.com/hswhite33/35ee33c169a2676847266fc5bf4ceb03)

**Comment by kakra** [comment]
@hswhite33 Do all those issues still occur in my version of wine-proton?
https://github.com/kakra/wine-proton

If some are fixed, we could try to isolate the patches that solve the problems and suggest those to Valve for inclusion into official Proton.

I know at least one patch in my tree that fixes an issue regarding window management.

**Comment by Arucard1983** [comment]
A much better solution to gain better framerate:
Install dgVoodoo2 WIP, which also translates DirectX 9 to 11, where in turn DXVK takes the rest (Vulkan).
Then override ddraw, d3d9, d3d8 on winecfg to complete the configuration. (It may need to open the Registry Editor to fix "ddrawex" to "ddraw" on DllOverrides.)
Use dgvoodoo2cpl.exe to complete the configuration.

The video are not mine, but shows that the game will be more fluid, as the game engine had finally a multithreading graphic pipeline (delivered by dgvoodoo2 + DXVK ).

https://www.youtube.com/watch?v=GgGMCTLr1Iw

**Comment by jonlap** [comment]
Briefly tested this before uninstalling, with proton 5.0-2, mesa 19.3.3 and rx480. While technically everything works and I get steady 60fps, gameplay does not feel as fluid as I remember it being when I played this game on PS3. It's more or less playable though but obviously there's some performance issues left. No logs for now, sorry, but I'll retest it properly later.

**Comment by soredake** [comment]
Game works completely fine with proton 5.0-2.

**Comment by aufkrawall** [comment]
I've tested this with wine-staging, but should work similarly for Proton.

To fix GPU PhysX performance, install a more recent PhysX version via winetricks/protontricks and copy and replace the dlls from

`drive_c/Program Files (x86)/NVIDIA Corporation/PhysX/Common`
to 
`/drive_c/Program Files (x86)/Steam/steamapps/common/mirrors edge/Binaries"` and `"/drive_c/Program Files (x86)/Steam/steamapps/common/mirrors edge/Binaries/PhysXLocal`.

This way, I'm having no more frame rate drops with shattered glass and GTX 1070.

**Comment by Bitwolfies** [comment]
> I've tested this with wine-staging, but should work similarly for Proton.
> 
> To fix GPU PhysX performance, install a more recent PhysX version via winetricks/protontricks and copy and replace the dlls from
> 
> `drive_c/Program Files (x86)/NVIDIA Corporation/PhysX/Common` to `/drive_c/Program Files (x86)/Steam/steamapps/common/mirrors edge/Binaries"` and `"/drive_c/Program Files (x86)/Steam/steamapps/common/mirrors edge/Binaries/PhysXLocal`.
> 
> This way, I'm having no more frame rate drops with shattered glass and GTX 1070.

How exactly did you get this to work? I installed physx with protontricks into the prefix, then tried deleting all the folders in game, which crashes on launch, I then replaced all the files in game with the ones from the protontricks download, crash. I even tried moving the nvcuda.dll from staging since valves is still stubbed, and it still crashed.

DXVK_ENABLE_NVAPI=1 and PROTON_HIDE_NVIDAGPU=0 are toggled.

Edit: removing the files and ONLY having the included physx runtime installed allows the game to work with the files deleted, albeit at the same awful fps. I guess some sorta regression happened.

This issue also somehow copies itself to my clipboard, is that a steam feature? 

General protection fault!

History: Address = 0x7b011297 (filename not found) [in C:\windows\system32\kernelbase.dll]
Address = 0x18ade3c  (filename not found) [in Z:\home\bitwolf\.local\share\Steam\steamapps\common\mirrors edge\Binaries\MirrorsEdge.exe]
Address = 0x145b6ae  (filename not found) [in Z:\home\bitwolf\.local\share\Steam\steamapps\common\mirrors edge\Binaries\MirrorsEdge.exe]
Address = 0x401378   (filename not found) [in Z:\home\bitwolf\.local\share\Steam\steamapps\common\mirrors edge\Binaries\MirrorsEdge.exe]
Address = 0x40170c   (filename not found) [in Z:\home\bitwolf\.local\share\Steam\steamapps\common\mirrors edge\Binaries\MirrorsEdge.exe]
Address = 0x13113ae  (filename not found) [in Z:\home\bitwolf\.local\share\Steam\steamapps\common\mirrors edge\Binaries\MirrorsEdge.exe]
Address = 0x7b62ebd0 (filename not found) [in C:\windows\system32\kernel32.dll]
Address = 0x7bc5dc77 (filename not found) [in C:\windows\system32\ntdll.dll]
RtlCreateUserThread() Address = 0x7bc5e420 (filename not found) [in C:\windows\system32\ntdll.dll]

**Comment by Tobe95** [comment]
There's something very strange going on with performance on the Jackknife level. The first time you enter the sewer passage, FPS and frametime will be much better than on subsequent visits. 

This seems to be related to the shadercache, so I'm not sure if the issue is with Proton, DXVK or rather Mesa though...

If you delete/rename the ME shadercache folder in `$HOME/.steam/steam/steamapps/shadercache/17410`, performance will be fine:

![20230708215302_1](https://github.com/ValveSoftware/Proton/assets/70862046/ea8c6e8c-b787-43d8-ba49-a92fbd8a0f81)

But if you return to the main menu and reload the Checkpoint again, performance is significantly worse from then on without any obvious reasons:

![20230708215330_1](https://github.com/ValveSoftware/Proton/assets/70862046/c28777b9-4ad5-4424-b73e-369e98eef17a)

I suppose there's a problem with shader compilation or how they are being loaded once compiled, restarting the game does not fix the issue. This has been the case with Proton 7.0/8.0/Experimental (I haven't tested older versions).

Steam OS 3.4.8 (Steam Deck)
Proton Experimental 8.0-20230705b

Not sure if the log is of any use to be honest...

[steam-17410.log](https://github.com/ValveSoftware/Proton/files/11992369/steam-17410.log)

**Comment by ahydronous** [comment]
Game doesn't detect Xbox controller running on NixOS 23.05, with xone driver on Xbox Wireless dongle.

Proton Experimental, 8.0-4 and 7.0-6 all do not enable the controller.

Controller works fine in other games.

Aside from that (and the PhysX framedrops), the game works swimmingly.

**Comment by TheSainEyereg** [comment]
In case someone want to play this game with PhysX, here are the steps to make it use GPU:

1. Download [nvidia-libs](https://github.com/SveSop/nvidia-libs/releases/latest)
2. Unpack it and run `PROTON_LIBS=/path/to/proton ./proton_setup.sh`  
    i.e. `PROTON_LIBS=/home/oleg/.local/share/Steam/compatibilitytools.d/GE-Proton10-25 ./proton_setup.sh`
3. **Re-create game's prefix (delete `steamfolder/steamapps/compatdata/17410`)**
4. Launch the game, so new prefix is created
5. Download [PhysX System Software](https://www.nvidia.com/en-us/drivers/physx/physx-9-23-1019-driver/)
6. Install it via `protontricks-launch --appid 17410 ./PhysX_9.23.1019_SystemSoftware.exe`
7. Open game's files location, navigate to `Binaries` folder and **REMOVE** `PhysXLocal` directory, `PhysXCore.dll` and `PhysXDevice.dll`  

Done! Now you should have PhysX hardware acceleration enabled and functioning.

[I uploaded these instructions to GitHub Gist in case I update them](https://gist.github.com/TheSainEyereg/1f79686b337e3fc7bde915def141e06a)

**Comment by ahydronous** [comment]
> In case someone want to play this game with PhysX, here are the steps to make it use GPU:

Note that PhysX is never accelerated on AMD GPUs, and that the Nvidia RTX 5000 series and beyond will not accelerate PhysX32 (technically Cuda32).

**Comment by gordan-ramsey** [comment]
I'm having an issue with the mouse movement, the mouse is on steroids.
A slight mouse movement, and the screen spazes out.

This is on proton 10.0-4.

it happens on random game launches.

Is anyone else seeing this?

I'm including a recording below.

https://github.com/user-attachments/assets/f6800435-dbc4-4a0f-a44e-eb0416e6fbe4

**Comment by wisplite** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/355#issuecomment-3522281570

This unfortunately doesn't work, the game still drops to single-digit framerates, particularly when glass shatters (i7-14700HX, RTX 4050)

**Comment by kisak-valve** [comment]
Mirrors Edge 17410

Issue transferred from https://github.com/ValveSoftware/Proton/issues/10022.
@legomind posted on 2026-07-31T16:39:25:

# Compatibility Report
- Name of the game with compatibility issues: Mirrors Edge
- Steam AppID of the game: 17410

## System Information
- GPU: NVIDIA GeForce RTX 5070
- Video driver version: nvidia 610.43.03
- Kernel version: 7.1.5-1-cachyos
- Proton version: 11
- [Full System Info](https://gist.github.com/legomind/72a0f264c5731a51aaba9a7a56d9462c)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.



[steam-17410.log](https://github.com/user-attachments/files/30596626/steam-17410.log)

## Symptoms 
Game does not launch.

## Reproduction
Click play button.

***
@legomind commented on 2026-07-31T16:41:01:

Possibly not a regression as older proton versions do not worth either tested 11-8

**Comment by kisak-valve** [comment]
Hello @legomind, please copy the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

`err:   DxvkInstance::createInstance: Failed to create Vulkan instance` in your Proton log hints that there's an issue with a Vulkan render path.

**Comment by legomind** [comment]
Here you go: https://gist.github.com/legomind/904b4d2907ac324937d29b070b59abee

**Comment by kisak-valve** [comment]
https://gist.github.com/legomind/904b4d2907ac324937d29b070b59abee#file-systeminfo-json-L403-L416 is the section to focus on. I'd check if the `lib32-nvidia-utils` package is installed.

**Comment by legomind** [comment]
Wow, installing that package fixed it immediately. I suppose this is the first 32 bit game I have tried running. Thanks!

**Comment by gordan-ramsey** [comment]
For those who are interested in fixing the mouse spazing out, it's the force mouse lock flag (--force-grab-cursor).

gamescope -f -W 3440 -H 1440 -r 60 --force-grab-cursor -- %command%

<img width="1729" height="760" alt="Image" src="https://github.com/user-attachments/assets/82602a57-47e8-4474-9bb7-10efb5711859" />


The game now works perfectly fine for me.

Tested with Proton 11.0

Hardware:
3 Monitors (Samung S34E790C, Samsung S32D850T, ASUS VE278) all connected through displayport
CPU: AMD Ryzen 7 3700x
MB: ASUS X570-l
Storage: 2x 2TB M.2 SSDs Sk hynix Platinum P41 SSD PCI-e 4.0.
RAM: 64GB DDR4 @ 3000Mhz
GPU: Nvidia RTX 3060 (Driver Version: 580.173.02 CUDA Version: 13.0)
Mouse: wireless LogiTech M170
OS: Pop! 24.04
Kernel: 7.0.11-76070011-generic

<img width="1935" height="793" alt="Image" src="https://github.com/user-attachments/assets/a0a5b663-2bd3-4496-beff-5b33bceff3b0" />
