### ISSUE TITLE
Proton 5.0-7 RC Testing

### ISSUE THREAD

**Issue by aeikum** [ValveSoftware/Proton#3814]
Hey all,

Back again with another set of Release Candidate builds which you can opt into. In the Steam client, the Proton 5.0 app should have a "next" beta branch which you can choose to start testing the 5.0-7 release candidates (note that the name of the build in the Steam Settings dialog will not be updated). I will post changes here when we push new builds. The source for the latest RC build is available on the `proton_5.0-next` branch in these repositories. This branch may receive forced updates.

In this issue, we are interested only in problems that are new to the 5.0-7 RC builds. If you find **new** problems in the "next" branch, please confirm that the problem does **not** occur in on the "default" branch before reporting it here.

Here is the tentative changelog. Again, this can change before the final release as we add or remove features during RC testing.

-Street Fighter 5 is now playable.

-Update DXVK to v1.6.1. 
 
_-Update wine-mono to 5.0.0. Among other things, this fixes Fight'N Rage and Woolfe - The Red Hood Diaries. - Removed in RC3._ 
 
-Improve dsound performance, which especially helps Zusi 3 Aerosoft and TrackMania Nations Forever. 
 
-Fix crashes in Halo: Spartan Strike, _TOXIKK - Removed in RC3_, Mount & Blade 2: Bannerlord, and Plebby Quest: The Crusades. 
 
-Fix connecting to Gearbox SHiFT in Borderlands 3. 
 
-Grand Theft Auto 4 is now playable. 

-Updates to vkd3d to improve Direct3D 12 compatibility and performance in The Division, The Talos Principle, and Monster Hunter World.
 
-Improve developer debugging experience.

**Comment by kattjevfel** [comment]
> -Grand Theft Auto 4 is now playable.

Wait what, wasn't this addressed in a previous RC already? It was what made me try RCs in the first place and I've since played through the whole game..

**Comment by aeikum** [comment]
> > -Grand Theft Auto 4 is now playable.
> 
> Wait what, wasn't this addressed in a previous RC already? It was what made me try RCs in the first place and I've since played through the whole game..

Issues fixed include: rendering issues on Nvidia; gamepads and keyboards have conflicting input; and the VRAM reported to the game was incorrect. See #350 and related DXVK issues.

**Comment by lucifertdark** [comment]
Street Fighter 5 you say? Fingers crossed cause I've been dying to give this one a whirl for months.

**Comment by Brunfunstudios** [comment]
I don't know if this should also be commented here but TrackMania United Forever now has ingame vehicle sound. Very happy about this :D

**Comment by doitsujin** [comment]
For the record, Monster Hunter World currently requires users to set `VKD3D_FEATURE_LEVEL=12_0` in order to run with D3D12, since the game asks for features that are not yet implemented (but doesn't seem to use them).

**Comment by leillo1975** [comment]
> > -Grand Theft Auto 4 is now playable.
> 
> Wait what, wasn't this addressed in a previous RC already? It was what made me try RCs in the first place and I've since played through the whole game..

It don't work for me. Game Launcher takes 100% CPU and nothing happens

**Comment by nutta-git** [comment]
@doitsujin as a steam launch command right? 
`VKD3D_FEATURE_LEVEL=12_0 %command%`

edit
it works

**Comment by doitsujin** [comment]
Yes, that should work.

**Comment by douggle** [comment]
So street fighter V launches however i cannot get either my ds4 or my mayflash universal fight stick to recognize controls keyboard controls work fine  Using arch linux  system specs 
MSI B450 Tomahawk
GTX 1060 6GB
Arch Linux 
5.6.3 kernel

**Comment by Plagman** [comment]
If you have other controller devices plugged in, try unplugging them and restarting the game with only one controller. You'll also want to make sure Steam Input is correctly set up, with /dev/uinput permissions/etc.

**Comment by Supreeeme** [comment]
Street Fighter V refuses to launch for me. I get this set of errors:
`2535.938:00d8:00dc:err:module:import_dll Library api-ms-win-core-apiquery-l1-1-1.dll (which is needed by L"Z:\\home\\supreme\\.local\\share\\Steam\\steamapps\\common\\StreetFighterV\\kernelbase.dll") not found`
`2535.938:00d8:00dc:err:module:import_dll Library kernelbase.dll (which is needed by L"C:\\windows\\system32\\kernel32.dll") not found`
`wine: could not load kernel32.dll, status c0000135`
`2535.942:0020:0024:err:steam:run_process Failed to create process L"\"Z:\\home\\supreme\\.local\\share\\Steam\\steamapps\\common\\StreetFighterV\\StreetFighterV.exe\"": 1359`
Deleting the prefix or reinstalling the game doesn't help. I'm on Arch Linux.

**Comment by douggle** [comment]
So I ve tried disconnecting all the other controllers, Using just the ds4, just the fightstick and just my xbox 360 controller, with the xbox 360 controller at least the dpad works but the buttons aren't mapped properly at all i ve tried several configs and don't seem to have success.

**Comment by GuzTech** [comment]
I just plugged my 360 controller, launched SF5 and everything works just fine. Also on Arch with the latest updates.

You could try to reboot (in case you installed a newer kernel but didn't reboot).

**Comment by HughJass** [comment]
@leillo1975 I always had a weird problem with GTA4 on steam. When I press play I wait for a little bit, then open a terminal, do ps -x and look for a Windows Live process and I kill it, then the rockstart launcher pops up and I can continue.

**Comment by douggle** [comment]
@HughJass Windows Live has been removed from GTA 4 .

**Comment by douggle** [comment]
also I m still having the issues with inputs on street fighter v. I'm a bit stumped really i ve even tried deleted my controller info from config.vdf and and the games input2.ini in an attempt to get it to redetect, no dice.

**Comment by qwertychouskie** [comment]
`- Improve dsound performance, which especially helps Zusi 3 Aerosoft and TrackMania Nations Forever.`

Feels a bit misleading, at least in TMNF's case it's not like sound was choppy and now it's not, it's that sound was totally non-functional before, and now it's fixed.  Although the first patch could be argued to be a performance fix (ref https://github.com/ValveSoftware/Proton/issues/3387), the second patch is definitely a bug fix ([fixing the 128 character limit](https://github.com/ValveSoftware/wine/commit/3cf224182e23ac0e9f3f028df2eb8235786fa8e7)).

Maybe something like this?:

`- Fixed 2 bugs in dsound that could cause lockups and/or missing sound in games such as "Zusi 3 Aerosoft" and "TrackMania Nations Forever`

Anyways, definitely happy to see these patches in a Proton release!  Now I don't have to run Windows Steam in Wine Staging. :)

**Comment by lucifertdark** [comment]
So far I've had no noticeable issues with any of the games I've fired up with the 5.0-7 RC, Street Fighter V is working perfectly, Steam Controller support is spot on, x360 controller to be tested later.

**Comment by nutta-git** [comment]
The Division crashes with DX12 render enabled on Proton.5.0-7 RC and with Proton.5.0-6 
Logs: 
[proton-5-0-6-short.txt](https://github.com/ValveSoftware/Proton/files/4550134/proton-5-0-6-short.txt)  grep "fixme"
[proton-5-0-6-shorte.txt](https://github.com/ValveSoftware/Proton/files/4550135/proton-5-0-6-shorte.txt)  grep "err"
[proton-5-0-7-rc-short.txt](https://github.com/ValveSoftware/Proton/files/4550136/proton-5-0-7-rc-short.txt)   grep "fixme"
[proton-5-0-7-rc-shorte.txt](https://github.com/ValveSoftware/Proton/files/4550137/proton-5-0-7-rc-shorte.txt)  grep "err"
[Proton5-0-6.log](https://github.com/ValveSoftware/Proton/files/4550138/Proton5-0-6.log)   default
[Proton5-0-7-rc.log](https://github.com/ValveSoftware/Proton/files/4550139/Proton5-0-7-rc.log)  default

**Comment by soredake** [comment]
With proton 5.0-7 rc launcher in fallout 2 does not show up.

[steam-38410.log](https://github.com/ValveSoftware/Proton/files/4550793/steam-38410.log)

**Comment by yuiiio** [comment]
@aeikum Maybe you should include this raw-input patch update.
https://github.com/wine-staging/wine-staging/commit/8d4d0a840e6ce434483edd81acb3be90fd734e44

**Comment by r3k4** [comment]
just tried street fighter V (with proton_5.0-next enabled), and its still not playable on my machine...
my steam app says the game is running, but the game is not displayed. 

OS : Ubuntu 18.04
Kernel: 5.6.7-050607-generic
CPU: Intel i7-8700K (12) @ 4.700GHz
GPU: NVIDIA GeForce GTX 1660 SUPER

**Comment by aeikum** [comment]
> With proton 5.0-7 rc launcher in fallout 2 does not show up.

@soredake Thanks for reporting. I can reproduce this problem. We'll look into it.

**Comment by Shin-Aska** [comment]
Even though this is an RC, the fact that we have finally managed to make street fighter 5 work is worth a celebration! 🎉🥳

**Comment by PQuintela** [comment]
> So street fighter V launches however i cannot get either my ds4 or my mayflash universal fight stick to recognize controls keyboard controls work fine Using arch linux system specs
> MSI B450 Tomahawk
> GTX 1060 6GB
> Arch Linux
> 5.6.3 kernel

This is normal behavior for SFV. It doesn't recognize non-Xinput controllers without some sort of wrapper.

**Comment by Supreeeme** [comment]
Ah, I figured out how to get SFV working for me. I set kernelbase.dll to builtin via winecfg, although you can achieve the same thing by renaming/deleting the kernelbase.dll that's inside the SFV folder. Appears to run flawlessly now.

**Comment by aeikum** [comment]
@YungDaVinci As far as I can tell, SFV does not ship a kernelbase.dll. Any idea how that got there?

**Comment by Supreeeme** [comment]
No clue, it was definitely a fresh install.

**Comment by cybik** [comment]
Somehow I can't seem to be getting 5.0-7 even switching Proton 5.0 to the `next` branch.

**Comment by skibyte** [comment]
<details><summary>Street Fighter V works fine for me without any modification.</summary><p>

```
 Processor Information:
     CPU Vendor:  GenuineIntel
     CPU Brand:  Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz
     CPU Family:  0x6
     CPU Model:  0x3f
     CPU Stepping:  0x2
     CPU Type:  0x0
     Speed:  3700 Mhz
     12 logical processors
     6 physical processors
     HyperThreading:  Supported

Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.6.7-arch1-1
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12008000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime_0.20200417.0

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 970/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 440.82
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 144 Hz

Sound card:
    Audio device: USB Mixer

Memory:
    RAM:  15923 Mb
```

</p></details>

**Comment by dpanter** [comment]
Movies do not play from the Gallery->Movies menu. Nothing happens when you try to play it. Example file:
`...../StreetFighterV/StreetFighterV/Content/Movies/OpeningTrPC.wmv`
It plays fine with VLC, codec info: Windows Media Video VC1 (WVC1)

Logitech F710 gamepad detail:
Steam client controller settings, nothing checked, Steam Overlay enabled: **works**
Steam client controller settings, nothing checked, Steam Overlay disabled: **doesn't work**
Steam client controller settings, Generic Gamepad Support checked, Steam Overlay enabled: **works**
Steam client controller settings, Generic Gamepad Support checked, Steam Overlay disabled: **works**

Thought this was worth mentioning since I never have generic gamepad support enabled and the gamepad normally works in all titles, regardless of Proton version and overlay usage.

**Comment by Probotector** [comment]
TOXIKK freezes when try load Castello map, rest of maps load correctly.

Please check it out

My OS is Manjaro 20.0

AMD Ryzen 2700

NVIDIA GTX 1070 // 440.82 drivers

**Comment by kisak-valve** [comment]
Friendly reminder that we only want new regressions from between Proton 5.0-6 and Proton 5.0-7 RC to be discussed here. Everything else is considered off-topic for this issue report and should be reported on the individual compatibility reports.

Additionally, if you find a regression, please make it clear how it's regressed, which game(s) are involved, that you confirmed the healthier behavior with Proton 5.0-6, and attach a Proton log of the regression.

**Comment by douggle** [comment]
So enabling the steam overlay I was able to get my xbox 360 controller to work with street fighter v but my ds4 and my arcade fightstick (mayflash f300 which has dinput xinput and a console mode) doesnt but it works in other games, but at least i can use 1 controller so there is that lol

**Comment by aeikum** [comment]
Hello. I've just pushed a new RC3 build live on the "next" branch. This build fixes an error launching GTA5. It also rolls back the wine-mono update, which caused the Fallout 2 regression (thanks @soredake), and also rolls back the fix for TOXIKK, which was causing issues in other games.

**Comment by dinhokusanagi** [comment]
fedora 32 silverblue. The game works well, but does not recognize the generic control on the keyboard

**Comment by edoantonioco** [comment]
Halo: spartan strike still crashes at the start, same behavior than other proton releases

**Comment by soredake** [comment]
fallout 1/2 now work as intended using 640x480 resolution https://github.com/ValveSoftware/Proton/issues/3651
![Screenshot_20200501_115646](https://user-images.githubusercontent.com/5204968/80794741-59c16c80-8ba3-11ea-8b71-fb0176b9ab6a.png)

**Comment by dinhokusanagi** [comment]
generic control is not recognized in Street Fighter V

**Comment by aeikum** [comment]
Proton 5.0-7 was release. Thanks all for your testing and feedback.

**Comment by dinhokusanagi** [comment]
proton 5.0.7 was released but not to play sfv because the generic control is not recognized by the game

**Comment by Huluti** [comment]
@aeikum you said "Fix crashes in Mount & Blade 2: Bannerlord" but the game still won't start for me with proton 5.0.7. Have I miss something? Thank's!

**Comment by kisak-valve** [comment]
Hello @Huluti, the Proton 5.0-7 RC testing has concluded. Please use #3706 to discuss that game.

**Comment by metadune** [comment]
Awesome for Street Fighter V support. Hope it improves over time!
