### ISSUE TITLE
Proton 5.0-8 taskbar on KDE visible in fullscreen games

### ISSUE THREAD

**Issue by Zorrototo** [ValveSoftware/Proton#3945]
In recent Proton 5.0-8 update here is what got me exited:

> -On KDE, games being fullscreen should no longer prevent alt-tabbing out of the game.

It actually seems to work good, but it introduced a new 'problem', the taskbar stays on top of the fullscreen game when it starts. However, you can have the taskbar to disappear by alt-tabbing out of the game, and then click on the game icon to have fullscreen game without taskbar.

So far I have confirmed this behavior with the following games:
- Killing Floor 2 (UE 3 game)
- Rocket League (UE 3 game)
- Rising Storm / Red Orchestra 2 (UE 3 game)
- Depth (UE 3 game)

Following games seem to NOT have the issue of taskbar on top of the fullscreen game on launch:
- Deep Rock Galactic (UE 4 game)
- Stick Fight: The Game
- Wreckfest

I'm using Manjaro KDE with Nvidia 440.xx drivers, nothing out of the ordinary. Let me know if you want more system information but the behavior seems the same on other machines around me.

**Comment by deathxxx123** [comment]
Can you make task bar inteligent hide? Or maybe the game window is not focused and for that you still see task bar.
I have similar issue with Streets Of Rage 4. When i start the game, sometimes it start minimized and have to click on icon or Alt-Tab to maximize game. Sometime game start focused with full screen.
I'm with Ubuntu Budgie 20.04. (that is with every Proton i tryed)
In comparsion, Dark Souls 3 or Skyrim always start with focused fullscreen.

**Comment by Zorrototo** [comment]
The issue is exactly as described, because of the new fix regarding alt-tabbing on **KDE**.

**Comment by Zorrototo** [comment]
hello? @kisak-valve 

I found another way of having the taskbar to disappear, press the windows/super/meta/whatever key it is called, then click the game icon or 'window' and the taskbar disappears. Basically, lose focus on game and get focus back.

**Comment by zzag** [comment]
Are you able to reproduce this issue after disabling focus stealing prevention? In order to disable focus stealing prevention, go to System Settings > Window Management > Window Behavior and select "None" focus stealing prevention level.

It will be very helpful to have the xprop output for one of the affected games and kwin support information as well. Getting xprop output is going to be a bit tricky. Run "sleep 30 && xprop" from terminal and launch a game. When the cursor shape changes to a cross, click any area in the game.

As for the kwin support information, just run "qdbus org.kde.KWin /KWin supportInformation". Also ensure that the xprop output and the support info don't contain any confidential or highly sensitive information.

**Comment by Zorrototo** [comment]
I'll try to gather more information then with these commands and settings, thanks for reply.

EDIT: So far with the 'focus stealing prevention' setting set to NONE (was previously on LOW) it seems to have fixed the issue and game do not have the taskbar over them at launch. However what is weird is that before the game was actually focused too, and fullscreen, I could interact with the menus and all but just the taskbar was on top. 
Not sure if I shall investigate further if changing this setting is enough to fix the situation.

**Comment by alasky17** [comment]
@zzag I was seeing the same problem, and also had the Focus stealing prevention level set to "low".  Here is the full range of behavior I saw by changing that setting:
 
(All tested with Hat in Time, Proton 5.0-9)
None: Like Zorrototo reported, the taskbar is not visible on launch.
Low & Medium: Taskbar visible until focus is lost and regained
High & Extreme: Taskbar is visible on launch, but disappears as soon as game window is clicked on.

Also attaching KWin info output.
[kwin-info-alasky.txt](https://github.com/ValveSoftware/Proton/files/4773019/kwin-info-alasky.txt)

**Comment by zzag** [comment]
Hmm, so it looks like a focus-related issue after all... I wonder whether the way how games are launched matters. How do you folks launch games?

**Comment by alasky17** [comment]
@zzag I just launch games by hitting "Play" in the Steam client.  I am running the Steam client out of a terminal, but I don't imagine that making a difference.

**Comment by Zorrototo** [comment]
Same I click play in Steam.

**Comment by aeikum** [comment]
I have heard from KDE devs that this is fixed in the upcoming KDE Plasma 5.18.6 and Plasma 5.19.3 releases.

Commit: https://invent.kde.org/plasma/kwin/-/commit/a0c4a8e766a2160213838daf6f71c7ae6c3705df

Release schedule: https://community.kde.org/Schedules/Plasma_5

**Comment by Zorrototo** [comment]
OK great! thanks for the heads up. I'll close the issue when the update comes to my distro stable repo and that it is confirmed that KDE does not act weird anymore.

**Comment by Zorrototo** [comment]
The issue is back on all Unreal Engine 3 games. To hide the taskbar you can't click in your game, you need for example to open the "start menu" twice then the taskbar disappears.

**Comment by alasky17** [comment]
The last time, this was fixed with a KDE update.  Is it possible that you got a recent KDE update and there is a KDE regression?  Is this happening on all Proton versions?  Also, could you give an example game?

**Comment by Zorrototo** [comment]
Pick one I already mentioned previously.  I only use Proton 7. About KDE I can't find shit on their bug tracker it is such a mess. 

//EDIT: it is the same issue as before. Setting focus stealing prevention to NONE seem to fix the issue.

**Comment by alasky17** [comment]
@Zorrototo Ok - we are looking into it.  In the meantime, for any game that runs with 6.3-8, you can switch the Proton version for just that game and hopefully avoid the issue :)  I tested Killing Floor 2 and that one at least seemed to work with 6.3-8.   Or just set focus stealing prevention to none ... lots of options :)

**Comment by Zorrototo** [comment]
Yes I did that, for now, I opened an issue on KDE tracker too https://bugs.kde.org/show_bug.cgi?id=466160 but from experience you get no response there (or it is not easy to get to the point), I really don't like the interactions there.. I guess it is a too big machinery with too much issues opened per second.. and not enough people. I'm just getting the information in the thread here so the information is available.

PS: KDE 5.27.1 will come soon on Manjaro I'm still on 5.26.5, I'll see if it is fixed on this new release, maybe it is not really worth to fix it in 5.26 as this one will be scrapped at some point, 5.27 will be their last LTS for maybe a year.
