### ISSUE TITLE
Teardown (1167630)

### ISSUE THREAD

**Issue by JonathanBrouwer** [ValveSoftware/Proton#4332]
# Compatibility Report
- Name of the game with compatibility issues: Teardown
- Steam AppID of the game: 1167630

## System Information
- GPU: GTX 970
- Driver/LLVM version: nvidia 455.28
- Kernel version: 5.8.16-2-MANJARO
- Link to full system information report as [Gist](https://gist.github.com/JonathanBrouwer/70ad4f8f7aaacf318c4b46caa8f97155):
- Proton version: 5.13-1

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

Proton log:
[steam-1167630.log](https://github.com/ValveSoftware/Proton/files/5466786/steam-1167630.log)
Std error:
[Std error](https://gist.github.com/JonathanBrouwer/d216cb2fb89a5149a29e902c3a43f386)

## Symptoms 
The game works perfectly (better performance than on windows btw), except when I load a level there is about a 10% chance the game will crash. The log file above contains the crash report.
Reproduces on proton 5.13-1 and proton 5.0-9. Does not reproduce on Windows 10.

## Reproduction
- Start the game, and load into a mission (was not able to reproduce it when quickloading in the lobby world)
- Make a quicksave
- Repeatedly quickload, the crash usually happens within 10-20 quickloads.

**Comment by Moire9** [comment]
This happens to me as well, except it's not on loading a level. It seems to be either random, or happening within a time frame. I spent a lot of time checking out the Löckelle compound, and crashed before I was even able to get to the first level. The second time I went as fast as I could, and was able to play the first level for about 30 seconds before crashing.

**Comment by JonathanBrouwer** [comment]
I played for about an hour, and crashes definitely only happened during loading for me. Could you create a proton log so we can compare and see if the Backtraces are similar? @SirNapkin1334

**Comment by domve** [comment]
i've only had one crash so far, but sometimes the audio completely stops working until i restart the game. anyone else experience this?

**Comment by ashirviskas** [comment]
@JonathanBrouwer Same crashing on level loading happens on my laptop, which has RTX 2070, but it doesn't happen on my desktop with a GTX 1060.

Both are running Arch.

**Comment by Solitary** [comment]
@ashirviskas Crashing is probably not related to GPUs. What is the rest of the specs? CPU, RAM? I also have desktop with GTX 1060, 28GB RAM and slightly overclocked i5 2500K. Running Fedora 32.

So far from what I can gather, it is sorta coin flip on whether the loading screen crashes or not. Because I don't think the crashing gets worse the longer you play (like a leak), but it is just game of chance that you eventually lose and your "winning" (not crashing) streak is over. From what I have seen it is just as likely to crash on 1st one as is on 10th loading screen. Obviously, the chance you get to see 10 loading screens in a row is quite low. 

But given your success with the desktop, maybe it is possible to get better chances with specific setup?

**Comment by ashirviskas** [comment]
@Solitary I've played like 5+ hours on my desktop with 0 crashes.

My specs on non-crashing machine are:

```
CPU: 3900X
GPU: GTX 1060 6GB
RAM: 32GB
Kernel: 5.8.12-arch1-1
Nvidia: 455.23.04-3
```


Crashing laptop:

```
CPU: 9750h
GPU: RTX 2700
RAM: 16GB
Kernel: 5.8.14-arch1-1
Nvidia: 455.28-4
```

Any idea what could it be?

**Comment by Solitary** [comment]
@ashirviskas I can point out similarities, CPU vendor and gfx driver version. Also possibly kernel, mine and your laptop are both newer than your desktop. My game is running from SSD.

My specs are:
```
CPU: i5 2500K
GPU: GTX 1060 6GB
RAM: 28GB
Kernel: 5.8.15-201.fc32.x86_64
Nvidia: 455.28
```

**Comment by ashirviskas** [comment]
@Solitary 
Huh, that's interesting. It could also be the `nvidia` driver. Could you try downgrading that? (I can't test it on my laptop rn)

**Comment by Solitary** [comment]
@ashirviskas 
No, I can't. Not without having to do extra work and installing it from different source. Probably not worth the effort. Repo I use only has the current version.

**Comment by JonathanBrouwer** [comment]
On protondb, someone suggested to add this launch command:
`WINEDLLOVERRIDES=winedbg.exe=d %command%`
I couldn't reproduce the crash with this enabled, can other people confirm?

**Comment by Brainzman** [comment]
I personally have played ~2 hours, with no crash either.
I would like to point out that the main problem, for me at least, is the **complete absence of particles effects**. The game thus lacks fire particles, which are really hard to play without since you need to guess where the fire is, and other particles like extinguisher gas.

Anyways here are my specs so you guys can compare:
```
RAM:16 GB
GPU Driver:4.6 Mesa 20.1.9
GPU:Radeon RX Vega
CPU:Intel Core i5-7600K @ 3.80GHz
```

**Comment by 0x4C4A** [comment]
I encounter crashes on level loads and sometimes in levels, when playing.

Adding the `WINEDLLOVERRIDES=winedbg.exe=d %command%` string made it not crash that much, but resulted in a loss of sound (presumably when the game would have normally crashed) - nothing would get the sound back on that session. It still did crash on a load later though.

```
Distro: Linux Mint 20
Kernel: 5.4.0-51-generic
RAM: 16 GB
GPU Driver: NVIDIA 450.80.02
GPU: NVIDIA GeForce GTX 1070
CPU: Intel Core i5-6500 @ 3.20GHz```

**Comment by ruabmbua** [comment]
For me it crashes the entire system in the third level (Marina) after a while.

I am running 20.2.1-1 on kernel 5.9.3-arch1-1 using a radeon rx5700xt.

I already reported kernel crashes on mesa and amdgpu bugtrackers. Looks lile the radeonsi opengl driver is messing something up.

Tried a couple of different kernels 4.19, 5.4, 5.8 all crash with similar issues.

**Comment by ruabmbua** [comment]
Is anyone aware, how I can capture e.g. an apitrace, to help the radeonsi developers reproduce the issue?

**Comment by Solitary** [comment]
> I encounter crashes on level loads and sometimes in levels, when playing.
> 
> Adding the `WINEDLLOVERRIDES=winedbg.exe=d %command%` string made it not crash that much, but resulted in a loss of sound (presumably when the game would have normally crashed) - nothing would get the sound back on that session. It still did crash on a load later though.
> ```

I can confirm that it does help with constant crashing. Did multiple reloads during a long mission without crashing, but I also did end up losing sound on the last reload (luckily it was actually the last one before I finished a long level), but I can't confirm whether the loss of sound would otherwise result in a crash. I did successfully reload more times than ever before, which maybe means it is different issue? Hard to tell, needs more testing.

Adding log from the play session, I exited the game cleanly through main menu.
[steam-1167630.log](https://github.com/ValveSoftware/Proton/files/5484265/steam-1167630.log)

**Comment by JonathanBrouwer** [comment]
Yep, can confirm the loss of sound with `WINEDLLOVERRIDES=winedbg.exe=d %command%`

**Comment by ruabmbua** [comment]
To make particle effects like fire work on amd GPU driver: https://gitlab.freedesktop.org/mesa/mesa/-/issues/3714#note_682885

**Comment by Brainzman** [comment]
> To make particle effects like fire work on amd GPU driver: https://gitlab.freedesktop.org/mesa/mesa/-/issues/3714#note_682885

Thanks, works great !

**Comment by Zed-GH** [comment]
I've also been game crashes, but much more catastrophic. Instead of just the game crashing, it seems to crash the X server as well. This crash mainly happens during general gameplay. I haven't experienced any of these crashes that happen during loadfing that others are reporting. I'm no Linux wizard, and am certainly not a troubleshooting genius, but figured I should say that its an issue I'm having.
Specs:
`Ubuntu 20.04.1 LTS`
`Kernel: 5.4.0-52-generic`
`Ram: 8 GB, 3000MHZ`
`Cpu: Ryzen 3 2300X, not overclocked`
`Gpu: RX 570 4GB, Driver: 4.6 Mesa 20.0.8`

**Comment by ruabmbua** [comment]
> I've also been game crashes, but much more catastrophic. Instead of just the game crashing, it seems to crash the X server as well. This crash mainly happens during general gameplay. I haven't experienced any of these crashes that happen during loadfing that others are reporting. I'm no Linux wizard, and am certainly not a troubleshooting genius, but figured I should say that its an issue I'm having.
> Specs:
> `Ubuntu 20.04.1 LTS`
> `Kernel: 5.4.0-52-generic`
> `Ram: 8 GB, 3000MHZ`
> `Cpu: Ryzen 3 2300X, not overclocked`
> `Gpu: RX 570 4GB, Driver: 4.6 Mesa 20.0.8`

This is probably a bug in the radeonsi driver: https://gitlab.freedesktop.org/mesa/mesa/-/issues/3714

As a workaround, launch the game with `AMD_DEBUG=zerovram,nodcc radeonsi_clamp_div_by_zero=true radeonsi_no_infinite_interp=true`.

Additionally set `allow_glsl_extension_directive_midshader=true force_glsl_version=420` to fix missing particle affects on radeonsi driver.

**Comment by Zed-GH** [comment]
> > I've also been game crashes, but much more catastrophic. Instead of just the game crashing, it seems to crash the X server as well. This crash mainly happens during general gameplay. I haven't experienced any of these crashes that happen during loadfing that others are reporting. I'm no Linux wizard, and am certainly not a troubleshooting genius, but figured I should say that its an issue I'm having.
> > Specs:
> > `Ubuntu 20.04.1 LTS`
> > `Kernel: 5.4.0-52-generic`
> > `Ram: 8 GB, 3000MHZ`
> > `Cpu: Ryzen 3 2300X, not overclocked`
> > `Gpu: RX 570 4GB, Driver: 4.6 Mesa 20.0.8`
> 
> This is probably a bug in the radeonsi driver: https://gitlab.freedesktop.org/mesa/mesa/-/issues/3714
> 
> As a workaround, launch the game with `AMD_DEBUG=zerovram,nodcc radeonsi_clamp_div_by_zero=true radeonsi_no_infinite_interp=true`.
> 
> Additionally set `allow_glsl_extension_directive_midshader=true force_glsl_version=420` to fix missing particle affects on radeonsi driver.

Regarding the fix for missing particles, that has worked, thanks.
However, the workaround for the crashing X server has been unsuccessful for me, Teardown still takes down my GPU with it in the event of a crash.
It also seems other people haven't gotten the workaround to work( https://steamcommunity.com/app/1167630/discussions/0/3001047413717024275/ )

**EDIT:** I have found a workaround that works for me:
Setting these launch options seems to have fixed the game crashing my RX 570:
`allow_glsl_extension_directive_midshader=true force_glsl_version=420 force_integer_tex_nearest=true MESA_NO_ERROR=1 %command%`
With these launch options, the game does still sometimes decide to crash the GPU, however its so infrequent that I was able to spend a good 2 hours in a single session before the GPU crashed on me.

**Comment by sklawik** [comment]
Morning/evening. The issue aswell affects computers with AMD graphics card and a processor. We both have SSD so that may be the issue somehow.

- Proton latest experience version, 
- Steam Beta, 
- Pop-OS, Ryzen 5 2600,
- 16GB RAM DDR5 
- and RX 590 8GB

**Comment by Friz64** [comment]
The game is crashing after the "Warning / Press any key to continue" splash screen since version 0.6 (Steam Workshop Update).

proton-5.13-6
[steam-1167630.log](https://github.com/ValveSoftware/Proton/files/6095612/steam-1167630.log)
Used launch options: `PROTON_LOG=1 allow_glsl_extension_directive_midshader=true force_glsl_version=420 AMD_DEBUG=zerovram,nodcc radeonsi_clamp_div_by_zero=true radeonsi_no_infinite_interp=true %command%`
Arch Linux 5.10.20-1-lts; RX 580 8 GB; Mesa 20.3.4

I also found [this Steam Community discussion](https://steamcommunity.com/app/1167630/discussions/0/3108018684251343316/) of a Nvidia GTX 1650 SUPER user having the same issue.

I tried other Proton versions and Launch options to no success.

**Comment by kisak-valve** [comment]
Hello @Friz64, these look like lines of interest from the log:
```
err:steamclient:create_win_interface Don't recognize interface name: SteamController008
err:steamclient:create_win_interface Don't recognize interface name: SteamInput002
err:steamclient:create_win_interface Don't recognize interface name: STEAMUGC_INTERFACE_VERSION015
```
Looks like https://github.com/ValveSoftware/Proton/commit/302e5d985e2abbd008f3ca2afebf20fca7c9cc08 https://github.com/ValveSoftware/Proton/commit/2f6395407f59b269c53542719fb9cba4af8ee070 in Proton experimental-5.13-20210302 can help with that. Please test the game with the current Proton Experimental build.

**Comment by Friz64** [comment]
That fixed it, thank you so much!

**Comment by zaggynl** [comment]
Game works well up until it crashes, which can take 30m or pretty short after loading a level.
Steam System Information:
http://paste.debian.net/plainh/a1e4e6d8
dmesg output: http://paste.debian.net/plainh/01654921
proton log: http://paste.debian.net/plain/1203498

Edit:
Launch option: radeonsi_no_infinite_interp=true allow_glsl_extension_directive_midshader=true %command%
seems to not cause any crashes anymore, via: https://gitlab.freedesktop.org/mesa/mesa/-/issues/3714#note_691556

**Comment by mathew2214** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/4332#issuecomment-874288536

even with those arguments, i still get frequent crashes. it make s significant improvement though.

**Comment by ruabmbua** [comment]
Had the game running successfully for a long time with all the environment variables from here. Unfortunately it stopped working, now it crashes every time, when something in the game should explode (gas tanks etc...). This started with a game update.

Here is a log of the crash: https://gist.github.com/ruabmbua/bc988e72310aa922e95bc72fb2f7e87b

Nothing suspicious in dmesg, seems like a straightforward segmentation fault from the game binary itself.

**Comment by Liamolucko** [comment]
I think I've figured out the source of this issue, but I'm not quite sure how to fix it.

The crash is happening on a thread which seems to be handling Teardown's audio, and is happening when the callback passed to `winmm.waveOutOpen` gets called reentrantly. (The callback calls `winmm.waveOutWrite`, which then calls the callback again.) I think the crash is caused by then attempting to acquire a lock which is still locked from the outer invocation; it doesn't actually make the syscall to acquire it, but presumably it's finding out through some other avenue that it's already locked.

The part I'm not sure about is whether or not it's valid for that callback to be called reentrantly; evidently, Teardown assumes it isn't, but it might just be a coincidence that it never does on Windows. I don't really know anything about `winmm`.

(Also, this explains the report of audio cutting out, if this is the thread which crashes.)

Here's the relay trace of the end of the run (with added indentation and comments):

<pre>
<b>// This is what a normal invocation of the callback looks like; acquires some locks, does some stuff, and releases them.</b>
    0128:trace:driver:DriverCallback (40256DA0, 32bit function 0003, 000000000000FF00, 03BD, 00000000, 005E0148, 00000000)
    0128:Call ntdll.RtlAcquireSRWLockExclusive(005e0068) ret=140270d41
    0128:Ret  ntdll.RtlAcquireSRWLockExclusive() retval=00000001 ret=140270d41
    0128:Call ntdll.RtlAcquireSRWLockExclusive(003b03d0) ret=140270d41
    0128:Ret  ntdll.RtlAcquireSRWLockExclusive() retval=00000001 ret=140270d41
    0128:Call ntdll.RtlReleaseSRWLockExclusive(003b03d0) ret=1402710a0
    0128:Ret  ntdll.RtlReleaseSRWLockExclusive() retval=ffffffff ret=1402710a0
    0128:Call winmm.waveOutWrite(0000ff00,005e0148,00000030) ret=140256d79
        0128:trace:winmm:waveOutWrite (000000000000FF00, 00000000005E0148, 48)
        0128:trace:winmm:waveOutWrite dwBufferLength: 4096
        0128:trace:winmm:WINMM_BeginPlaying (000000000000FF00)
        0128:trace:winmm:WOD_PushData (000000000000FF00)
        0128:Call ucrtbase.memcpy(02c829f0,005e3178,00001000) ret=3b8f16e5d
        0128:Ret  ucrtbase.memcpy() retval=02c829f0 ret=3b8f16e5d
    0128:Ret  winmm.waveOutWrite() retval=00000000 ret=140256d79
    0128:Call ntdll.RtlReleaseSRWLockExclusive(005e0068) ret=1402710a0
    0128:Ret  ntdll.RtlReleaseSRWLockExclusive() retval=ffffffff ret=1402710a0
<b>// End of normal invocation.</b>
    0128:trace:driver:DriverCallback Done
    0128:Call user32.MsgWaitForMultipleObjects(00000001,02b70690,00000000,ffffffff,3000004ff) ret=3b8f172f3
        0128:Call ntdll.NtWaitForMultipleObjects(00000002,02b2f480,00000001,00000000,00000000) ret=7b06de8a
        0128:Ret  ntdll.NtWaitForMultipleObjects() retval=00000000 ret=7b06de8a
    0128:Ret  user32.MsgWaitForMultipleObjects() retval=00000000 ret=3b8f172f3
    0128:trace:winmm:WOD_PushData (000000000000FF00)
    0128:Call user32.MsgWaitForMultipleObjects(00000001,02b70690,00000000,ffffffff,3000004ff) ret=3b8f172f3
        0128:Call ntdll.NtWaitForMultipleObjects(00000002,02b2f480,00000001,00000000,00000000) ret=7b06de8a
        0128:Ret  ntdll.NtWaitForMultipleObjects() retval=00000000 ret=7b06de8a
    0128:Ret  user32.MsgWaitForMultipleObjects() retval=00000000 ret=3b8f172f3
    0128:trace:winmm:WOD_PushData (000000000000FF00)
<b>// Start of invocation which causes crash.</b>
    0128:trace:driver:DriverCallback (40256DA0, 32bit function 0003, 000000000000FF00, 03BD, 00000000, 005E00B8, 00000000)
    0128:Call ntdll.RtlAcquireSRWLockExclusive(005e0068) ret=140270d41
    0128:Ret  ntdll.RtlAcquireSRWLockExclusive() retval=00000001 ret=140270d41
    0128:Call ntdll.RtlAcquireSRWLockExclusive(003b03d0) ret=140270d41
    0128:Ret  ntdll.RtlAcquireSRWLockExclusive() retval=00000001 ret=140270d41
    0128:Call ntdll.RtlReleaseSRWLockExclusive(003b03d0) ret=1402710a0
    0128:Ret  ntdll.RtlReleaseSRWLockExclusive() retval=ffffffff ret=1402710a0
    0128:Call winmm.waveOutWrite(0000ff00,005e00b8,00000030) ret=140256d79
        0128:trace:winmm:waveOutWrite (000000000000FF00, 00000000005E00B8, 48)
        0128:trace:winmm:waveOutWrite dwBufferLength: 4096
        0128:trace:winmm:WINMM_BeginPlaying (000000000000FF00)
        0128:trace:winmm:WOD_PushData (000000000000FF00)
        0128:Call ucrtbase.memcpy(02c839f0,005e0178,00001000) ret=3b8f16e5d
        0128:Ret  ucrtbase.memcpy() retval=02c839f0 ret=3b8f16e5d
<b>// Start of reentrant callback.</b>
        0128:trace:driver:DriverCallback (40256DA0, 32bit function 0003, 000000000000FF00, 03BD, 00000000, 005E00E8, 00000000)
<b>// This is immediately different; literally every other invocation of the callback starts by calling ntdll.RtlAcquireSRWLockExclusive.</b>
        0128:Call ntdll.RtlAllocateHeap(00140000,00000000,00000020) ret=1402cceb4
        0128:Ret  ntdll.RtlAllocateHeap() retval=02b70710 ret=1402cceb4
        0128:Call ntdll.RtlAllocateHeap(00140000,00000000,00000020) ret=1402cceb4
        0128:Ret  ntdll.RtlAllocateHeap() retval=02b70750 ret=1402cceb4
        0128:Call ntdll.RtlAllocateHeap(00140000,00000000,00000020) ret=1402cceb4
        0128:Ret  ntdll.RtlAllocateHeap() retval=02b70790 ret=1402cceb4
        0128:Call ntdll.RtlAllocateHeap(00140000,00000000,00000040) ret=1402cceb4
        0128:Ret  ntdll.RtlAllocateHeap() retval=02bd07d0 ret=1402cceb4
        0128:Call KERNEL32.HeapFree(00140000,00000000,02b70750) ret=1402cc7a8
        0128:Ret  KERNEL32.HeapFree() retval=00000001 ret=1402cc7a8
        0128:Call KERNEL32.HeapFree(00140000,00000000,02b70790) ret=1402cc7a8
        0128:Ret  KERNEL32.HeapFree() retval=00000001 ret=1402cc7a8
        0128:Call ntdll.RtlAllocateHeap(00140000,00000000,00000031) ret=1402cceb4
        0128:Ret  ntdll.RtlAllocateHeap() retval=02bd0830 ret=1402cceb4
        0128:Call KERNEL32.HeapFree(00140000,00000000,02bd07d0) ret=1402cc7a8
        0128:Ret  KERNEL32.HeapFree() retval=00000001 ret=1402cc7a8
        0128:Call KERNEL32.HeapFree(00140000,00000000,02b70710) ret=1402cc7a8
        0128:Ret  KERNEL32.HeapFree() retval=00000001 ret=1402cc7a8
        0128:Call ntdll.RtlPcToFileHeader(140428b30,02b2f790) ret=1402776bb
        0128:Ret  ntdll.RtlPcToFileHeader() retval=140000000 ret=1402776bb
<b>// And then it throws an exception, causing the crash.</b>
        0128:Call KERNEL32.RaiseException(e06d7363,00000001,00000004,02b2f750) ret=1402776fa
</pre>

I captured the log with `PROTON_LOG=1 WINEDEBUG=+relay,+seh,+tid,+winmm,+driver %command%`

**Comment by Liamolucko** [comment]
I don't know whether this applies to @ruabmbua's issue, I haven't been experiencing it.

**Comment by Liamolucko** [comment]
I think I've managed to solve this on https://github.com/Liamolucko/wine/tree/winmm-no-reentrancy.

**Comment by kisak-valve** [comment]
Hello @Liamolucko, when you're happy with your patches, please send them to wine's mailing list for review and integration into upstream wine, then make a merge request for them to be cherry picked into Proton's variant of wine.

**Comment by Liamolucko** [comment]
The fix is included in Wine 7.1, so this should be fixed once Proton updates to it.

In the meantime, [Proton-GE](https://github.com/GloriousEggroll/proton-ge-custom) has already updated, so it's fixed there.

**Comment by ruabmbua** [comment]
Still crashing for me with Proton-GE updated. Probably a different issue then? I have to get into proton debugging, I have no experience with it.

**Comment by ruabmbua** [comment]
When looking at my logs, its rather weird, that the crashing instruction is at 0x00007fa510fc9878, which is apparently not even inside the memory map, according to the crash dump. The closest module is winepulse, but at a slightly higher address...

**Comment by kisak-valve** [comment]
Teardown (1167630) Intermittent Failure to Start After Weeks of Normal Behavior

Issue transferred from https://github.com/ValveSoftware/Proton/issues/8521.
@tybird13 posted on 2025-03-13T23:54:35:

# Compatibility Report
- Name of the game with compatibility issues: **Teardown: (1167630)**
- Steam AppID of the game: 1167630

## System Information
### Generic Information
![Image](https://github.com/user-attachments/assets/453ccd9f-84fd-4b8d-8adf-542bdbc51d9e)
- GPU: AMD Radeon RX 7900 XTX [Discrete]
- Video driver version: Navi 31 (Mesa 24.3.4)
- Kernel version: Kernel: Linux 6.13.5-102.bazzite.fc41.x86_64
- Proton version: Proton: 1741116382 experimental-9.0-20250304

### GPU Information
```
tyler@bazzite:~$ glxinfo | grep OpenGL
OpenGL vendor string: AMD
OpenGL renderer string: AMD Radeon RX 7900 XTX (radeonsi, navi31, LLVM 19.1.7, DRM 3.61, 6.13.5-102.bazzite.fc41.x86_64)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 24.3.4
```

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

## Log File
### ⚠️ NOTE ⚠️: THIS IS A 13GB FILE! 
This log file was 13GB before I finally just killed Teardown. The fact that this thing compresses to 103MB is astonishing. 
[Log File @ Google Drive](https://drive.google.com/file/d/1k0v-4PM7z4P6616hJ7z2BYpE-sMkyM4p/view?usp=sharing)
It's worth noting that after adding `PROTON_LOG=1 %command%` to the comand line args in Steam, the program just hung for a few minutes, never getting to the splash screen. I finally killed the process after a minute or two. After removing the `PROTON_LOG=1 %command%` from the args, it started fine! And then proceeded to crash on startup the second time, as shown in the video. 

## Symptoms 
Teardown has started exhibiting this behavior where it will fail to start, and will throw a dialog error. 
I have been playing Teardown for weeks now. I love this game, and I will just hop on randomly to mess around. I have sunk hours into this game, so the fact that it won't start really bothers me. 
This just started happening this morning. 
### Video File
[Video of Issue](https://drive.google.com/file/d/1wBSuCOpKXnCTpxWVtiAt1AUFU-TOwvlV/view?usp=sharing) 
- To my surprise, the first time I started Teardown it booted right up! I was so happy!!
- Then my happiness was completely shattered when I tried to load it again. I guess this issue is intermittent...
- This is the first time today that Teardown had booted up for me.

![Image](https://github.com/user-attachments/assets/e4e52b59-b4c2-49a9-ae0b-1baafac43cdf)

I keep getting this error dialog. 

## Steam Runtime Info
[Steam Runtime Diagnostics.txt](https://github.com/user-attachments/files/19238334/Steam.Runtime.Diagnostics.txt)

**Comment by tybird13** [comment]
Any help on the above would be greatly appreciated. 
Thanks all!

**Comment by simifor** [comment]
@tybird13 couldn't reproduce the issue on my end with my rx6600, could you try to launch the game with this option to see if it works as expected?
`DRI_PRIME=1 %command%`
and
`DRI_PRIME=0 %command%`

**Comment by tybird13** [comment]
@simifor Those launch arguments didn't seem to have an affect.

**Comment by alek3y** [comment]
@tybird13 I have the same issue.
Using `PROTON_USE_WINED3D=1 %command%` seems to work around the issue for me, but it forces the "Graphics API" to "OpenGL" in the settings and I think it also disables Vulkan.

**Comment by simifor** [comment]
@tybird13 from your video, the game doesn't instantly crash for you. Could you try running the game with mangohud to verify what card is being used by the game? after installing mangohud you can make your launch parameter this `mangohud %command%`, but you might need to add this to your mangohud configuration file first: `gpu_name`. The file is in `/home/youruser/.config/MangoHud/MangoHud.conf`

@alek3y The game offers opengl and d3d12 as renderers, the latter leads to proton to translate it to vulkan through vkd3d-proton. If there is some sort of issue in the vulkan driver or vkd3d-protont hen switching to opengl can workaround the problem

**Comment by tybird13** [comment]
@simifor @alex3y

Thank you so much for your replies!! I really appreciate it!!

This worked for me: PROTON_USE_WINED3D=1 %command%

The game starts up every time now!
I'm still not sure what the issue is though. MangoHud seems to indicate that I'm using my discrete AMD GPU 7900XTX, but I can't get it to print that to the screen. It just shows that GPU0 is 90%, and GPU1 is 0%.

Regardless, Thanks so much guys for your help!!

**Comment by tybird13** [comment]
A quick google shows that `PROTON_USE_WINED3D=1 %command%` forces Wine to use Direct3D rather than Vulkan? Maybe there's a problem with Vulkan?

**Comment by GyomeiHimejima9906** [comment]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game:

## System Information
- GPU: RTX3060
- Video driver version: Mesa NV176

- Kernel version: 6.14.8-300.fc42.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/GyomeiHimejima9906/498352ffe977f16de318c026b07a4ba9
- Proton version: experimental-10.0-20250522b

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.





## Symptoms 
anything visible

![Image](https://github.com/user-attachments/assets/5b581c68-6639-4a3b-97dc-b9998a990717)
![Image](https://github.com/user-attachments/assets/d95ec1b0-6ff1-4cb8-a307-3ea8d32daee1)



using teeardown cause system freezze

[kernel.log](https://github.com/user-attachments/files/20540129/kernel.log)
see this:
```
[  204.435866] wlp0s20f0u4: Limiting TX power to 20 (20 - 0) dBm as advertised by XX:XX:XX:XX:XX:XX
[  642.700127] nouveau 0000:01:00.0: Xwayland[2198]: nv50cal_space: -16
[  642.771255] nouveau 0000:01:00.0: Xwayland[2198]: nv50cal_space: -16
[  647.462286] nouveau 0000:01:00.0: Xwayland[2198]: nv50cal_space: -16
[  674.098117] nouveau 0000:01:00.0: Xwayland[2198]: nv50cal_space: -16
[  675.619238] nouveau 0000:01:00.0: Xwayland[2198]: nv50cal_space: -16
[  680.979410] nouveau 0000:01:00.0: Xwayland[2198]: nv50cal_space: -16
[  688.053567] nouveau 0000:01:00.0: Xwayland[2198]: nv50cal_space: -16
[  688.548068] nouveau 0000:01:00.0: Xwayland[2198]: nv50cal_space: -16
[  754.769887] nouveau 0000:01:00.0: Xwayland[2198]: nv50cal_space: -16
[  754.833180] nouveau 0000:01:00.0: Xwayland[2198]: nv50cal_space: -16
[  763.247204] nouveau 0000:01:00.0: Xwayland[2198]: nv50cal_space: -16
[  864.327487] nouveau 0000:01:00.0: Xwayland[2198]: nv50cal_space: -16
[  890.098833] nouveau 0000:01:00.0: Xwayland[2198]: nv50cal_space: -16
[  892.802630] nouveau 0000:01:00.0: Xwayland[2198]: nv50cal_space: -16

```

## Reproduction
open game start to play a map

**Comment by kisak-valve** [comment]
Hello @GyomeiHimejima9906, that rendering issue should be reported to and evaluated by your video driver vendor.

**Comment by GyomeiHimejima9906** [comment]
But I suing the fedora default Mesa video driver

> Hello [@GyomeiHimejima9906](https://github.com/GyomeiHimejima9906), that rendering issue should be reported to and evaluated by your video driver vendor.

**Comment by simifor** [comment]
@GyomeiHimejima9906 You should use nvidia's proprietary drivers instead of mesa

**Comment by GyomeiHimejima9906** [comment]
i report a lot of micro stuttering (with the expected lag) when were a lot of fire/physics elements
the micro stutter there are simultanely wirh
```
30697.198:0124:0128:fixme:steamclient:Steam_BGetCallback HACK: Steam overlay activated, disabling all input events.
30745.090:0108:011c:fixme:oleacc:find_class_data unhandled window class: L"#32769"
30745.092:0108:011c:fixme:uiautomation:msaa_provider_GetPatternProvider Unimplemented patternId 10002
30745.092:0108:011c:fixme:uiautomation:base_hwnd_provider_GetPatternProvider 0000000000AD62B0, 10002, 000000000193F8A0: stub
30745.093:0108:011c:fixme:oleacc:find_class_data unhandled window class: L"#32769"
30745.095:0108:011c:fixme:oleacc:find_class_data unhandled window class: L"#32769"
30745.097:0108:011c:fixme:uiautomation:msaa_provider_GetPatternProvider Unimplemented patternId 10002
30745.097:0108:011c:fixme:uiautomation:base_hwnd_provider_GetPatternProvider 0000000000B1C020, 10002, 000000000193F8A0: stub
30745.098:0108:011c:fixme:oleacc:find_class_data unhandled window class: L"#32769"
30747.550:0108:011c:fixme:uiautomation:msaa_provider_GetPatternProvider Unimplemented patternId 10002
30747.550:0108:011c:fixme:uiautomation:base_hwnd_provider_GetPatternProvider 0000000000ADF590, 10002, 000000000193F8A0: stub
```

you can search `base_hwnd_provider_GetPatternProvider` in the log

[steam-1167630.log](https://github.com/user-attachments/files/20598050/steam-1167630.log)

**Comment by GyomeiHimejima9906** [comment]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game:

## System Information
- GPU: 3060
- Video driver version: 4.6.0 NVIDIA 575.64
- Kernel version: 6.15.3-zen1-1-zen
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/GyomeiHimejima9906/ec7c479ae1315aa0360a8c3f49f61147
- Proton version: 1749849620 experimental-10.0-20250612c / 1748829653 GE-Proton10-4


WARMING: the log can reach 3+GB

[steam-1167630- 10.0-1f.tar.gz](https://github.com/user-attachments/files/20962067/steam-1167630-.10.0-1f.tar.gz)
[steam-1167630-experimental.tar.gz](https://github.com/user-attachments/files/20962068/steam-1167630-experimental.tar.gz)
[steam-1167630-GE.tar.gz](https://github.com/user-attachments/files/20962069/steam-1167630-GE.tar.gz)

## Symptoms 
unable to upload mod to steam workshop

## Reproduction
1. open game
2. create your mod to upload
3. upload them
4. the game will NOT upload and freeze it self (must terminated with task manager)

P.S.:
in the log there are a lot oof
```
22698.443:01d0:01d4:warn:debugstr:OutputDebugStringA "0000 00:00:02.617124 INFO 58d6 [Init|Render] Vendor: Nvidia\nRenderer: NVIDIA GeForce RTX 3060\nTotal VRAM: 12256 Mb\nAvailable VRAM: 10539 Mb\n\n"
22698.443:01d0:01d4:warn:seh:dispatch_exception "0000 00:00:02.617124 INFO 58d6 [Init|Render] Vendor: Nvidia\nRenderer: NVIDIA GeForce RTX 3060\nTotal VRAM: 12256 Mb\nAvailable VRAM: 10539 Mb\n\n"
``` 

<details><summary>and</summary>

```
22319.697:0160:0164:trace:unwind:dwarf_virtual_unwind next function rip=00007fc084549fbc
22319.697:0160:0164:trace:unwind:dwarf_virtual_unwind   rax=000055556a7e0000 rbx=000000000011f1d0 rcx=000000000023e470 rdx=000000000002cb80
22319.697:0160:0164:trace:unwind:dwarf_virtual_unwind   rsi=000000000011f230 rdi=00007fc087959ac0 rbp=00000001000ff4f0 rsp=00000001000ff4e0
22319.697:0160:0164:trace:unwind:dwarf_virtual_unwind    r8=000000000011f230  r9=00007fc087959ac0 r10=000000000011f240 r11=0000000000000000
22319.697:0160:0164:trace:unwind:dwarf_virtual_unwind   r12=00000001000ff500 r13=00006ffffdc442a0 r14=0000000000000003 r15=0000000000000040
22319.697:0160:0164:trace:unwind:dwarf_virtual_unwind function 7fc084549fbc base 0x7fc084549fa4 cie 0x7fc08458b6d0 len 14 id 0 version 1 aug 'zR' code_align 1 data_align -8 retaddr %rip
22319.697:0160:0164:warn:seh:dwarf_virtual_unwind backtrace: 0x7fc084549fbc: /home/giacomobc/.local/share/Steam/steamapps/common/Proton - Experimental/files/lib/wine/x86_64-unix/lsteamclient.so + 0x115fbc (_ZdaPv + 0x18).
22319.697:0160:0164:trace:unwind:execute_cfa_instructions 7fc084549fa4: DW_CFA_def_cfa %rsp, 8
22319.697:0160:0164:trace:unwind:execute_cfa_instructions 7fc084549fa4: DW_CFA_offset %rip, -8
22319.697:0160:0164:trace:unwind:dwarf_virtual_unwind fde 0x7fc0845f5e38 len 1c personality (nil) lsda (nil) code 7fc084549fa4-7fc084549fbf
22319.697:0160:0164:trace:unwind:execute_cfa_instructions 7fc084549fa4: DW_CFA_advance_loc 1
22319.697:0160:0164:trace:unwind:execute_cfa_instructions 7fc084549fa5: DW_CFA_def_cfa_offset 16
22319.697:0160:0164:trace:unwind:execute_cfa_instructions 7fc084549fa5: DW_CFA_offset %rbp, -16
22319.697:0160:0164:trace:unwind:execute_cfa_instructions 7fc084549fa5: DW_CFA_advance_loc 3
22319.697:0160:0164:trace:unwind:execute_cfa_instructions 7fc084549fa8: DW_CFA_def_cfa_register %rbp
22319.697:0160:0164:trace:unwind:execute_cfa_instructions 7fc084549fa8: DW_CFA_advance_loc 22
22319.697:0160:0164:trace:unwind:dwarf_virtual_unwind next function rip=00007fc08450ca2e
24351.409:0194:0198:warn:seh:dwarf_virtual_unwind backtrace: 0x7fd868fce09e: /home/giacomobc/.local/share/Steam/steamapps/common/Proton 10.0/files/bin/../lib/wine/x86_64-unix/ntdll.so + 0x4909e (__wine_unix_call_dispatcher + 0xda).
24351.409:0194:0198:trace:unwind:execute_cfa_instructions 7fd868fcdfc4: DW_CFA_def_cfa %rsp, 8
24351.409:0194:0198:trace:unwind:execute_cfa_instructions 7fd868fcdfc4: DW_CFA_offset %rip, -8
24351.409:0194:0198:trace:unwind:dwarf_virtual_unwind fde 0x7fd86901c45c len 70 personality (nil) lsda (nil) code 7fd868fcdfc4-7fd868fce131
24351.409:0194:0198:trace:unwind:execute_cfa_instructions 7fd868fcdfc4: DW_CFA_advance_loc 15
24351.409:0194:0198:trace:unwind:execute_cfa_instructions 7fd868fcdfd3: DW_CFA_def_cfa_offset 0
24351.409:0194:0198:trace:unwind:execute_cfa_instructions 7fd868fcdfd3: DW_CFA_expression %rip 7fd86901c472-7fd86901c475
24351.409:0194:0198:trace:unwind:execute_cfa_instructions 7fd868fcdfd3: DW_CFA_advance_loc 14
24351.409:0194:0198:trace:unwind:execute_cfa_instructions 7fd868fcdfe1: DW_CFA_expression %rbx 7fd86901c479-7fd86901c47b
24351.409:0194:0198:trace:unwind:execute_cfa_instructions 7fd868fcdfe1: DW_CFA_advance_loc 4
24351.409:0194:0198:trace:unwind:execute_cfa_instructions 7fd868fcdfe5: DW_CFA_expression %rsi 7fd86901c47f-7fd86901c481
24351.409:0194:0198:trace:unwind:execute_cfa_instructions 7fd868fcdfe5: DW_CFA_advance_loc 4
24351.409:0194:0198:trace:unwind:execute_cfa_instructions 7fd868fcdfe9: DW_CFA_expression %rdi 7fd86901c485-7fd86901c487
24351.409:0194:0198:trace:unwind:execute_cfa_instructions 7fd868fcdfe9: DW_CFA_advance_loc 4
24351.409:0194:0198:trace:unwind:execute_cfa_instructions 7fd868fcdfed: DW_CFA_expression %r12 7fd86901c48b-7fd86901c48e
24351.409:0194:0198:trace:unwind:execute_cfa_instructions 7fd868fcdfed: DW_CFA_advance_loc 4
24351.409:0194:0198:trace:unwind:execute_cfa_instructions 7fd868fcdff1: DW_CFA_expression %r13 7fd86901c492-7fd86901c495
24351.409:0194:0198:trace:unwind:execute_cfa_instructions 7fd868fcdff1: DW_CFA_advance_loc 4
24351.409:0194:0198:trace:unwind:execute_cfa_instructions 7fd868fcdff5: DW_CFA_expression %r14 7fd86901c499-7fd86901c49c
24351.409:0194:0198:trace:unwind:execute_cfa_instructions 7fd868fcdff5: DW_CFA_advance_loc 4
24351.409:0194:0198:trace:unwind:execute_cfa_instructions 7fd868fcdff9: DW_CFA_expression %r15 7fd86901c4a0-7fd86901c4a3
24351.409:0194:0198:trace:unwind:execute_cfa_instructions 7fd868fcdff9: DW_CFA_advance_loc 7
24351.409:0194:0198:trace:unwind:execute_cfa_instructions 7fd868fce000: DW_CFA_def_cfa_expression 7fd86901c4a6-7fd86901c4aa
24351.409:0194:0198:trace:unwind:execute_cfa_instructions 7fd868fce000: DW_CFA_advance_loc 7
24351.409:0194:0198:trace:unwind:execute_cfa_instructions 7fd868fce007: DW_CFA_expression %rbp 7fd86901c4ae-7fd86901c4b1
24351.409:0194:0198:trace:unwind:execute_cfa_instructions 7fd868fce007: DW_CFA_advance_loc1 98
24351.409:0194:0198:trace:unwind:execute_cfa_instructions 7fd868fce069: DW_CFA_remember_state
24351.409:0194:0198:trace:unwind:execute_cfa_instructions 7fd868fce069: DW_CFA_def_cfa_expression 7fd86901c4b6-7fd86901c4ba
24351.409:0194:0198:trace:unwind:execute_cfa_instructions 7fd868fce069: DW_CFA_offset %rip, -8
24351.409:0194:0198:trace:unwind:execute_cfa_instructions 7fd868fce069: DW_CFA_offset %rbp, -16
24351.409:0194:0198:trace:unwind:execute_cfa_instructions 7fd868fce069: DW_CFA_offset %rbx, -24
24351.409:0194:0198:trace:unwind:execute_cfa_instructions 7fd868fce069: DW_CFA_offset %r12, -32
24351.409:0194:0198:trace:unwind:execute_cfa_instructions 7fd868fce069: DW_CFA_offset %r13, -40
24351.409:0194:0198:trace:unwind:execute_cfa_instructions 7fd868fce069: DW_CFA_offset %r14, -48
24351.409:0194:0198:trace:unwind:execute_cfa_instructions 7fd868fce069: DW_CFA_offset %r15, -56
24351.409:0194:0198:trace:unwind:execute_cfa_instructions 7fd868fce069: DW_CFA_undefined %rdi
24351.409:0194:0198:trace:unwind:execute_cfa_instructions 7fd868fce069: DW_CFA_undefined %rsi
24351.409:0194:0198:trace:unwind:execute_cfa_instructions 7fd868fce069: DW_CFA_advance_loc1 167
24351.409:0194:0198:trace:unwind:dwarf_virtual_unwind next function rip=00007fd868fcc346
```

</details><details><summary>when terminating (forced with task manager) after the end fo the loop
there is:</summary>

```
22868.835:01d0:01d4:trace:unwind:dwarf_virtual_unwind fde 0x7fed494a21b0 len 14 personality (nil) lsda (nil) code 7fed494a14e0-7fed494a150b
22868.835:01d0:01d4:trace:unwind:dwarf_virtual_unwind next function rip=00007fed494a150a
22868.835:01d0:01d4:trace:unwind:dwarf_virtual_unwind   rax=00005555972ca000 rbx=0000000000000000 rcx=000000000023eb50 rdx=00000000000151a0
22868.835:01d0:01d4:trace:unwind:dwarf_virtual_unwind   rsi=000000000011f5a0 rdi=00007fed4938aac0 rbp=0000000000000000 rsp=00007ffeb6db9730
22868.835:01d0:01d4:trace:unwind:dwarf_virtual_unwind    r8=000000000011f5a0  r9=00007fed4938aac0 r10=000000000011f5b0 r11=0000000000000000
22868.835:01d0:01d4:trace:unwind:dwarf_virtual_unwind   r12=00007fed494a14e0 r13=00007ffeb672a0e0 r14=0000000000000000 r15=0000000000000000
22868.835:01d0:01d4:trace:unwind:dwarf_virtual_unwind function 7fed494a150a base 0x7fed494a14e0 cie 0x7fed494a2198 len 14 id 0 version 1 aug 'zR' code_align 1 data_align -8 retaddr %rip
22868.835:01d0:01d4:warn:seh:dwarf_virtual_unwind backtrace: 0x7fed494a150a: Z:\home\giacomobc\.local\share\Steam\steamapps\common\Teardown\teardown.exe + 0x150a (_start + 0x2a).
22868.835:01d0:01d4:trace:unwind:execute_cfa_instructions 7fed494a14e0: DW_CFA_def_cfa %rsp, 8
22868.835:01d0:01d4:trace:unwind:execute_cfa_instructions 7fed494a14e0: DW_CFA_offset %rip, -8
22868.835:01d0:01d4:trace:unwind:execute_cfa_instructions 7fed494a14e0: DW_CFA_undefined %rip
22868.835:01d0:01d4:trace:unwind:dwarf_virtual_unwind fde 0x7fed494a21b0 len 14 personality (nil) lsda (nil) code 7fed494a14e0-7fed494a150b
22868.835:01d0:01d4:trace:unwind:dwarf_virtual_unwind next function rip=00007fed494a150a
22868.835:01d0:01d4:trace:unwind:dwarf_virtual_unwind   rax=00005555972ca000 rbx=0000000000000000 rcx=000000000023eb50 rdx=00000000000151a0
22868.835:01d0:01d4:trace:unwind:dwarf_virtual_unwind   rsi=000000000011f5a0 rdi=00007fed4938aac0 rbp=0000000000000000 rsp=00007ffeb6db9738
22868.835:01d0:01d4:trace:unwind:dwarf_virtual_unwind    r8=000000000011f5a0  r9=00007fed4938aac0 r10=000000000011f5b0 r11=0000000000000000
22868.835:01d0:01d4:trace:unwind:dwarf_virtual_unwind   r12=00007fed494a14e0 r13=00007ffeb672a0e0 r14=0000000000000000 r15=0000000000000000
22868.835:01d0:01d4:trace:unwind:dwarf_virtual_unwind function 7fed494a150a base 0x7fed494a14e0 cie 0x7fed494a2198 len 14 id 0 version 1 aug 'zR' code_align 1 data_align -8 retaddr %rip
22868.835:01d0:01d4:warn:seh:dwarf_virtual_unwind backtrace: 0x7fed494a150a: Z:\home\giacomobc\.local\share\Steam\steamapps\common\Teardown\teardown.exe + 0x150a (_start + 0x2a).
22868.835:01d0:01d4:trace:unwind:execute_cfa_instructions 7fed494a14e0: DW_CFA_def_cfa %rsp, 8
22868.835:01d0:01d4:trace:unwind:execute_cfa_instructions 7fed494a14e0: DW_CFA_offset %rip, -8
22868.835:01d0:01d4:trace:unwind:execute_cfa_instructions 7fed494a14e0: DW_CFA_undefined %rip
22868.835:01d0:01d4:trace:unwind:dwarf_virtual_unwind fde 0x7fed494a21b0 len 14 personality (nil) lsda (nil) code 7fed494a14e0-7fed494a150b
22868.835:01d0:01d4:trace:unwind:dwarf_virtual_unwind next function rip=00007fed494a150a
22868.835:01d0:01d4:trace:unwind:dwarf_virtual_unwind   rax=00005555972ca000 rbx=0000000000000000 rcx=000000000023eb50 rdx=00000000000151a0
22868.835:01d0:01d4:trace:unwind:dwarf_virtual_unwind   rsi=000000000011f5a0 rdi=00007fed4938aac0 rbp=0000000000000000 rsp=00007ffeb6db9740
22868.835:01d0:01d4:trace:unwind:dwarf_virtual_unwind    r8=000000000011f5a0  r9=00007fed4938aac0 r10=000000000011f5b0 r11=0000000000000000
22868.835:01d0:01d4:trace:unwind:dwarf_virtual_unwind   r12=00007fed494a14e0 r13=00007ffeb672a0e0 r14=0000000000000000 r15=0000000000000000
22868.835:01d0:01d4:trace:unwind:dwarf_virtual_unwind function 7fed494a150a base 0x7fed494a14e0 cie 0x7fed494a2198 len 14 id 0 version 1 aug 'zR' code_align 1 data_align -8 retaddr %rip
22868.835:01d0:01d4:warn:seh:dwarf_virtual_unwind backtrace: 0x7fed494a150a: Z:\home\giacomobc\.local\share\Steam\steamapps\common\Teardown\teardown.exe + 0x150a (_start + 0x2a).
22868.835:01d0:01d4:trace:unwind:execute_cfa_instructions 7fed494a14e0: DW_CFA_def_cfa %rsp, 8
22868.933:01b0:01b4:trace:unwind:RtlGrowFunctionTable 00000000048D36A0, 41
22868.933:01b0:01b4:trace:unwind:RtlGrowFunctionTable 00000000048D36A0, 42
22868.933:01b0:01b4:trace:unwind:RtlGrowFunctionTable 00000000048D36A0, 43
22868.933:01b0:01b4:trace:unwind:RtlGrowFunctionTable 00000000048D36A0, 44
22868.933:01b0:01b4:trace:unwind:RtlGrowFunctionTable 00000000048D36A0, 45
22868.933:01b0:01b4:trace:unwind:RtlGrowFunctionTable 00000000048D36A0, 46
22868.933:01b0:01b4:trace:unwind:RtlGrowFunctionTable 00000000048D36A0, 47
22868.933:01b0:01b4:trace:unwind:RtlGrowFunctionTable 00000000048D36A0, 48
22868.933:01b0:01b4:trace:unwind:RtlGrowFunctionTable 00000000048D36A0, 49
22868.933:01b0:01b4:trace:unwind:RtlGrowFunctionTable 00000000048D36A0, 50
22868.933:01b0:01b4:trace:unwind:RtlGrowFunctionTable 00000000048D36A0, 51
22869.285:01b0:01b4:trace:unwind:RtlGrowFunctionTable 00000000048D36A0, 52
22869.286:00f8:02a8:warn:threadname:NtSetInformationThread Thread renamed to L"wine_threadpool_worker"
22869.417:0128:0168:trace:unwind:RtlGrowFunctionTable 00000000048EF1C0, 78
22869.417:01b0:01f8:trace:unwind:RtlGrowFunctionTable 00000000048D36A0, 53
22869.417:01b0:02b0:trace:mscoree:DllMain (00006FFFFE460000, 2, 0000000000000000)
22869.417:0128:02ac:trace:mscoree:DllMain (00006FFFFE460000, 2, 0000000000000000)
22869.418:01b0:01e0:warn:seh:dispatch_exception backtrace: --- Exception 0x6be.
22869.418:01b0:01e0:trace:seh:dispatch_exception code=6be (unknown) flags=0 addr=00006FFFFFC0D0C7
22869.418:01b0:01e0:trace:seh:dispatch_exception rip=00006fffffc0d0c7 rsp=000000000379e440 rbp=000000000379e530 eflags=00000202
22869.418:01b0:01e0:trace:seh:dispatch_exception rax=000000000379e460 rbx=000000000379f2d0 rcx=000000000379e460 rdx=0000000000000000
22869.418:01b0:01e0:trace:seh:dispatch_exception rsi=0000000000000014 rdi=000000000379e5d8  r8=0000000000000000  r9=0000000000000000
22869.418:01b0:01e0:trace:seh:dispatch_exception r10=00000000005a9b10 r11=000000000000001b r12=000000000379f2d0 r13=0000000000000005
22869.418:01b0:01e0:trace:seh:dispatch_exception r14=00006fffffad2e82 r15=00000000034d0e40 mxcsr=00001f80
22869.418:01b0:01e0:trace:seh:call_vectored_handlers calling handler at 00006FFFFDCF0600 code=6be flags=0
22869.418:01b0:01e0:trace:seh:call_vectored_handlers handler at 00006FFFFDCF0600 returned 0
22869.418:01b0:01e0:warn:seh:virtual_unwind backtrace: 00006FFFFFC0D0C7: L"kernelbase.dll" + 000000000000D0C7.
22869.418:01b0:01e0:trace:unwind:RtlVirtualUnwind2 type 1 base 6fffffc00000 rip 6fffffc0d0c7 rva d0c7 rsp 379e440
22869.418:0128:0154:warn:seh:dispatch_exception backtrace: --- Exception 0x6be.
22869.418:01b0:02c0:trace:mscoree:DllMain (00006FFFFE460000, 2, 0000000000000000)
22869.418:0030:02b8:warn:threadname:NtSetInformationThread Thread renamed to L"wine_threadpool_worker"
22869.418:0128:0154:trace:seh:dispatch_exception code=6be (unknown) flags=0 addr=00006FFFFFC0D0C7
22869.418:0128:0154:trace:seh:dispatch_exception rip=00006fffffc0d0c7 rsp=000000000379e440 rbp=000000000379e530 eflags=00000202
22869.418:0128:0154:trace:seh:dispatch_exception rax=000000000379e460 rbx=000000000379f2d0 rcx=000000000379e460 rdx=0000000000000000
22869.418:0128:0154:trace:seh:dispatch_exception rsi=0000000000000014 rdi=000000000379e5d8  r8=0000000000000000  r9=0000000000000000
22869.418:0128:0154:trace:seh:dispatch_exception r10=00000000005a9b10 r11=000000000000001b r12=000000000379f2d0 r13=0000000000000005
22869.418:01b0:01e0:trace:unwind:dump_unwind_info **** func d058-d0cf
22869.418:0128:0154:trace:seh:dispatch_exception r14=00006fffffad2e82 r15=00000000034d0e40 mxcsr=00001f80
22869.418:01b0:01e0:trace:unwind:dump_unwind_info unwind info at 00006FFFFFCC1CD8 flags 0 prolog 0xf bytes function 00006FFFFFC0D058-00006FFFFFC0D0CF
22869.418:0128:0154:trace:seh:call_vectored_handlers calling handler at 00006FFFFDCF0600 code=6be flags=0
22869.418:01b0:01e0:trace:unwind:dump_unwind_info     0xf: subq $0xc8,%rsp
22869.418:0128:0154:trace:seh:call_vectored_handlers handler at 00006FFFFDCF0600 returned 0
22869.418:01b0:01e0:trace:unwind:RtlVirtualUnwind2 inside epilog.
22869.418:0030:02b4:warn:threadname:NtSetInformationThread Thread renamed to L"wine_threadpool_worker"
22869.418:01b0:01e0:warn:seh:virtual_unwind backtrace: 00006FFFFF930E56: L"rpcrt4.dll" + 0000000000030E56.
22869.418:01b0:01e0:trace:unwind:RtlVirtualUnwind2 type 1 base 6fffff900000 rip 6fffff930e56 rva 30e56 rsp 379e510
22869.418:01b0:01e0:trace:unwind:dump_unwind_info **** func 30e40-30e8b
22869.418:01b0:01e0:trace:unwind:dump_unwind_info unwind info at 00006FFFFF97981C flags 0 prolog 0x8 bytes function 00006FFFFF930E40-00006FFFFF930E8B
22869.418:01b0:01e0:trace:unwind:dump_unwind_info     frame register rbp offset 0x0(%rsp)
22869.418:01b0:01e0:trace:unwind:dump_unwind_info     0x8: subq $0x20,%rsp
22869.418:01b0:01e0:trace:unwind:dump_unwind_info     0x4: leaq 0x0(%rsp),rbp
22869.418:01b0:01e0:trace:unwind:dump_unwind_info     0x1: pushq %rbp
22869.418:01b0:01e0:warn:seh:virtual_unwind backtrace: 00006FFFFF920414: L"rpcrt4.dll" + 0000000000020414.
22869.418:01b0:01e0:trace:unwind:RtlVirtualUnwind2 type 1 base 6fffff900000 rip 6fffff920414 rva 20414 rsp 379e540
22869.418:01b0:01e0:trace:unwind:dump_unwind_info **** func 20310-20415
22869.418:01b0:01e0:trace:unwind:dump_unwind_info unwind info at 00006FFFFF976FA0 flags 0 prolog 0xc bytes function 00006FFFFF920310-00006FFFFF920415
22869.418:01b0:01e0:trace:unwind:dump_unwind_info     frame register rbp offset 0x30(%rsp)
22869.418:01b0:01e0:trace:unwind:dump_unwind_info     0xc: leaq 0x30(%rsp),rbp
22869.418:0128:0154:warn:seh:virtual_unwind backtrace: 00006FFFFFC0D0C7: L"kernelbase.dll" + 000000000000D0C7.
22869.418:01b0:01e0:trace:unwind:dump_unwind_info     0x7: subq $0x30,%rsp
22869.418:0128:0154:trace:unwind:RtlVirtualUnwind2 type 1 base 6fffffc00000 rip 6fffffc0d0c7 rva d0c7 rsp 379e440
22869.418:01b0:01e0:trace:unwind:dump_unwind_info     0x3: pushq %rbx
22869.419:0128:0154:trace:unwind:dump_unwind_info **** func d058-d0cf
22869.419:01b0:01e0:trace:unwind:dump_unwind_info     0x2: pushq %rsi
22869.419:0128:0154:trace:unwind:dump_unwind_info unwind info at 00006FFFFFCC1CD8 flags 0 prolog 0xf bytes function 00006FFFFFC0D058-00006FFFFFC0D0CF
22869.419:01b0:01e0:trace:unwind:dump_unwind_info     0x1: pushq %rbp
22869.419:0128:0154:trace:unwind:dump_unwind_info     0xf: subq $0xc8,%rsp
22869.419:01b0:01e0:warn:seh:virtual_unwind backtrace: 00006FFFFF93F465: L"rpcrt4.dll" + 000000000003F465.
```

</details><details><summary>at the same time in log journalCTL there is</summary>

```
giu 28 19:19:00 GAMING steam[37946]: chdir "/home/giacomobc/.local/share/Steam/steamapps/common/Teardown"
giu 28 19:19:00 GAMING steam[37946]: Game Recording - would start recording game 1167630, but recording for this game is disabled
giu 28 19:19:00 GAMING steam[37946]: Adding process 43645 for gameID 1167630
giu 28 19:19:00 GAMING steam[37946]: WARNING: discarding _NET_WM_PID 2 as invalid for X11 window - use specialized XCB_X11_TO_PID function!
giu 28 19:19:00 GAMING steam[37946]: ERROR: ld.so: object '/home/giacomobc/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
giu 28 19:19:00 GAMING steam[37946]: ERROR: ld.so: object '/home/giacomobc/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
giu 28 19:19:00 GAMING steam[37946]: ERROR: ld.so: object '/home/giacomobc/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
giu 28 19:19:00 GAMING steam[37946]: ERROR: ld.so: object '/home/giacomobc/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
giu 28 19:19:00 GAMING steam[37946]: ERROR: ld.so: object '/home/giacomobc/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
giu 28 19:19:00 GAMING steam[37946]: Adding process 43646 for gameID 1167630
giu 28 19:19:00 GAMING steam[37946]: Adding process 43647 for gameID 1167630
giu 28 19:19:01 GAMING steam[37946]: pressure-vessel-wrap[43646]: W: Not sharing path STEAM_COMPAT_TOOL_PATHS="...:/usr/share/steam/compatibilitytools.d/proton-ge-custom:..." with container because "/usr" is reserved by the container framework
giu 28 19:19:01 GAMING steam[37946]: Adding process 43745 for gameID 1167630
giu 28 19:19:01 GAMING steam[37946]: Proton: Upgrading prefix from None to GE-Proton10-4 (/home/giacomobc/.local/share/Steam/steamapps/compatdata/1167630/)
giu 28 19:19:03 GAMING steam[37946]: ProtonFixes[43745] WARN: [CONFIG]: Parent directory "/home/giacomobc/.config/protonfixes" does not exist. Abort.
giu 28 19:19:03 GAMING steam[37946]: ProtonFixes[43745] INFO: Running protonfixes on "GE-Proton10-4", build at 2025-06-02 02:00:53+00:00.
giu 28 19:19:03 GAMING steam[37946]: ProtonFixes[43745] INFO: Running checks
giu 28 19:19:03 GAMING steam[37946]: ProtonFixes[43745] INFO: All checks successful
giu 28 19:19:03 GAMING steam[37946]: ProtonFixes[43745] INFO: Using global defaults for "Teardown" (1167630)
giu 28 19:19:03 GAMING steam[37946]: ProtonFixes[43745] INFO: No global protonfix found for "Teardown" (1167630)
giu 28 19:19:03 GAMING steam[37946]: Adding process 43757 for gameID 1167630
giu 28 19:19:03 GAMING steam[37946]: Adding process 43758 for gameID 1167630
giu 28 19:19:03 GAMING steam[37946]: Adding process 43759 for gameID 1167630
giu 28 19:19:03 GAMING steam[37946]: Adding process 43762 for gameID 1167630
giu 28 19:19:03 GAMING steam[37946]: Adding process 43764 for gameID 1167630
giu 28 19:19:03 GAMING steam[37946]: Adding process 43767 for gameID 1167630
giu 28 19:19:03 GAMING steam[37946]: Adding process 43777 for gameID 1167630
giu 28 19:19:03 GAMING steam[37946]: Adding process 43782 for gameID 1167630
giu 28 19:19:03 GAMING steam[37946]: Adding process 43790 for gameID 1167630
giu 28 19:19:04 GAMING systemd[1]: Bluetooth service was skipped because of an unmet condition check (ConditionPathIsDirectory=/sys/class/bluetooth).
giu 28 19:19:04 GAMING steam[37946]: Adding process 43814 for gameID 1167630
giu 28 19:19:04 GAMING steam[37946]: Adding process 43833 for gameID 1167630
giu 28 19:19:07 GAMING kwin_wayland[37549]: kf.windowsystem: static bool KX11Extras::mapViewport() may only be used on X11
giu 28 19:19:07 GAMING kwin_wayland[37549]: kwin_scene_opengl: 0x501: GL_INVALID_VALUE error generated. <levels>, <width> and <height> must be 1 or greater.
giu 28 19:19:07 GAMING kwin_wayland[37549]: kwin_scene_opengl: Invalid framebuffer status:  "GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT"
giu 28 19:19:07 GAMING kwin_wayland[37549]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated. Framebuffer name must be generated before being bound.
giu 28 19:19:07 GAMING kwin_wayland[37549]: kwin_scene_opengl: 0x506: GL_INVALID_FRAMEBUFFER_OPERATION error generated. Operation is not valid because a bound framebuffer is not framebuffer complete.
giu 28 19:19:09 GAMING kded6[37650]: Registering ":1.767/StatusNotifierItem" to system tray
giu 28 19:19:09 GAMING kded6[37650]: Service  ":1.767" unregistered
giu 28 19:19:09 GAMING kded6[37650]: Registering ":1.768/StatusNotifierItem" to system tray
giu 28 19:19:09 GAMING kded6[37650]: Service  ":1.768" unregistered
giu 28 19:19:09 GAMING kded6[37650]: Registering ":1.769/StatusNotifierItem" to system tray
giu 28 19:19:09 GAMING kded6[37650]: Service  ":1.769" unregistered
giu 28 19:19:09 GAMING kded6[37650]: Registering ":1.770/StatusNotifierItem" to system tray
giu 28 19:19:09 GAMING kded6[37650]: Service  ":1.770" unregistered
giu 28 19:19:11 GAMING steam[37946]: 06/28 19:19:11 minidumps folder is set to /tmp/dumps
giu 28 19:19:11 GAMING steam[37946]: 06/28 19:19:11 Init: Installing breakpad exception handler for appid(gameoverlayui)/version(20250519195100)/tid(44022)
giu 28 19:19:11 GAMING steam[37946]: 06/28 19:19:11 Init: Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)/tid(44022)
giu 28 19:19:30 GAMING steam[37946]: Game Recording - game stopped [gameid=1167630]
giu 28 19:19:30 GAMING steam[37946]: Removing process 43833 for gameID 1167630
giu 28 19:19:30 GAMING steam[37946]: Removing process 43814 for gameID 1167630
giu 28 19:19:30 GAMING steam[37946]: Removing process 43790 for gameID 1167630
giu 28 19:19:30 GAMING steam[37946]: Removing process 43782 for gameID 1167630
giu 28 19:19:30 GAMING steam[37946]: Removing process 43777 for gameID 1167630
giu 28 19:19:30 GAMING steam[37946]: Removing process 43767 for gameID 1167630
giu 28 19:19:30 GAMING steam[37946]: Removing process 43764 for gameID 1167630
giu 28 19:19:30 GAMING steam[37946]: Removing process 43762 for gameID 1167630
giu 28 19:19:30 GAMING steam[37946]: Removing process 43759 for gameID 1167630
giu 28 19:19:30 GAMING steam[37946]: Removing process 43758 for gameID 1167630
giu 28 19:19:30 GAMING steam[37946]: Removing process 43757 for gameID 1167630
giu 28 19:19:30 GAMING steam[37946]: Removing process 43745 for gameID 1167630
giu 28 19:19:30 GAMING steam[37946]: Removing process 43647 for gameID 1167630
giu 28 19:19:30 GAMING steam[37946]: Removing process 43646 for gameID 1167630
giu 28 19:19:30 GAMING steam[37946]: Removing process 43645 for gameID 1167630
giu 28 19:19:32 GAMING steam[37946]: (process:44022): GLib-GObject-CRITICAL **: 19:19:32.983: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```

</details>

**Comment by simifor** [comment]
@GyomeiHimejima9906 the issue should now be solved on proton experimental bleeding edge, you can switch to that branch following these instructions https://github.com/ValveSoftware/Proton/wiki/Proton-Versions#proton-bleeding-edge

**Comment by GyomeiHimejima9906** [comment]
> [@GyomeiHimejima9906](https://github.com/GyomeiHimejima9906) the issue should now be solved on proton experimental bleeding edge, you can switch to that branch following these instructions https://github.com/ValveSoftware/Proton/wiki/Proton-Versions#proton-bleeding-edge

sorry, but I still unable to upload to steam workshop, tested: experimental bleeding edge and proton GE 10-7

[steam-1167630.log](https://github.com/user-attachments/files/20993255/steam-1167630.log)

**Comment by simifor** [comment]
@GyomeiHimejima9906 proton GE isn't related to valve, can you upload a log when using bleeding edge?
