### ISSUE TITLE
Titanfall (1454890)

### ISSUE THREAD

**Issue by serebit** [ValveSoftware/Proton#4410]
# Compatibility Report
- Name of the game with compatibility issues: Titanfall
- Steam AppID of the game: 1454890

## System Information
- GPU: AMD RX 580 8GB
- Driver/LLVM version: Mesa 20.2.2/LLVM 10.0.1
- Kernel version: 5.16.19
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/serebit/e229a728e236c18b1ac68dc65b6b5f90
- Proton version: 5.13-2

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms
- Changing the VSync setting from the Double Buffered default causes the framerate to drop to 1 FPS. Also occurs in Titanfall 2, though in that case the default is None. **No known fix.**

**Comment by Plarpoon** [comment]
# Compatibility Report
- Name of the game with compatibility issues: Titanfall
- Steam AppID of the game: 1454890

## System Information
- GPU: Radeon RX 7900 XTX Gaming OC 24GB GDDR6
- Driver/LLVM version: Mesa 23.1.1
- Kernel version: Linux 6.3.6-200.fc38.x86_64
- Link to full system information report as [Gist](https://gist.github.com/Plarpoon/948dc14a5a1054a0bfda68bd0ed83b15):
- Proton version: Experimental and 8.0-2

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[001-steam-1454890.log.tar.gz](https://github.com/ValveSoftware/Proton/files/11716224/001-steam-1454890.log.tar.gz)
[002-steam-1454890.log.tar.gz](https://github.com/ValveSoftware/Proton/files/11716225/002-steam-1454890.log.tar.gz)
(To extract these archives move the split numbered component [001 and 002] to the end of the file, as this is a split archive.)

The game starts the boot-up sequence, executes the EA App, logs into it and once it executes the actual game nothing happens.


## Reproduction
Just press the play button and wait.

##Extra-Notes
I have tried the game with and without extra launch options and it doesn't change the end result. Launch options being: "PROTON_LOG=1 gamemoderun mangohud %command%".

I managed to log in into the EA App during the first execution of the game successfully, and since then the EA App (strangely) works very well, loading up first and then booting up into the main screen of it. I can see it once completed that process that it's trying to launch the game which then crashes immediately.

During the first installation I managed to reach the "configuring audio" part of the first game launch, it's the phase immediately after that fails.

---

Different evaluation on Titanfall

Issue transferred from https://github.com/ValveSoftware/Proton/issues/6847.
@Plarpoon posted on 2023-06-14T19:25:48:

Hello, I have currently downloaded and installed "Titanfall" (Steam ID: 1454890). I have noticed that when launching the game the EA App launches successfully, it does the login and even shows me the game library on it. Unfortunately at the moment it boots the game nothing appears on screen and shorty after it closes down on me.

I have written an issue already for this but then I realized that I don't know really for a fact if this is an issue present only with my configuration or it's more common. Would anyone that still has it downloaded please be able to tell me if the game boots up fine after the new EA App came to on Steam or if you also can't even launch the game?

Thank you in advance for your time, if the error is only mine I will be able to more accurately describe the issue when updating it, but if it's more generalized I would like to pinpoint which part of the process did it all go to fail.

**Comment by Plarpoon** [comment]
Can anyone comment if they managed to successfully launch the game after EA App became the default on Steam? I literally can't see anything happen after the EA App loads, the game gets never launched. I would like to know if it's my issue alone or others share it too.

**Comment by Plarpoon** [comment]
I have just discovered that the game runs fine on my Steam Deck, the error seems to be only with my desktop Fedora 38 Linux. Anyone has ideas on why and how could that be fixed? The distro has just been installed so it's with all defaults.

**Comment by Plarpoon** [comment]
On further exam I have realized that the error spam in my log is given by "RtlVirtualUnwind". Considering the nature of Fedora with SELinux always loaded on enforcing I presume I might have found a more generic Proton bug with SELinux instead of a specific bug with Proton itself.

**Comment by Plarpoon** [comment]
Update, my issue is actually related to this one:
https://github.com/ValveSoftware/Proton/issues/6859#issue-1762053811

**Comment by ivyl** [comment]
Leaving aside the Nvidia driver crash on prefix creation, Titanfall not starting on Proton 8 has been fixed in DXVK. It's already included in Proton Experimental's bleeding-edge branch and should be part of the next release.

**Comment by Plarpoon** [comment]
I presume the bleeding-edge branch is not the one I have in the standard Steam Client out of the box, just tested it and it doesn't work yet. But I am happy it was fixed, thank you a lot @ivyl!

I really appreciate all the work that is going in Proton, DXVK, vkd3d and all the other projects that made me possible enjoying gaming on Linux!

**Comment by braiam** [comment]
The launcher is still broken. For some reason, DirectX and VCredist are installed after the launcher, when I believe it has to be before, since the launcher may need VisualC.
