### ISSUE TITLE
Grim Dawn (219990)

### ISSUE THREAD

**Issue by PadreAdamo** [ValveSoftware/Proton#466]
No issues with Grim Dawn across AMD hardware. Launches perfectly.

**Comment by kisak-valve** [comment]
Hello @PadreAdamo, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by PadreAdamo** [comment]
https://gist.github.com/PadreAdamo/dda0c289bcca5ed60279f041bf8a4ea1

**Comment by arzardk** [comment]
This game have poor performance on Nvidia video card even on lowest settings.
[My system specs](https://gist.github.com/arzardk/6f020699814adc78c0b9c8c1e1ee2764)
"Poor prefomance" is about 30-40 FPS against 60+ with same settings on Windows 10.

**Comment by Twinsonian** [comment]
- Missing Shaman class from list of class choices. Also, unable to select any classes on new characters. Have not tested on established characters with only one class selected.
-     Grim Dawn does not allow accessing skills menu a second time after leveling a new character

**Comment by kisak-valve** [comment]
Grim Dawn Class Selection Broken

Issue transferred from https://github.com/ValveSoftware/Proton/issues/535.
@twinsonian posted on 2018-08-25T13:02:57:

i5-4460 / RX 460
Proton 3.7 - Proton 3.7.4
Ubuntu 18.04 / Mesa 18.3.0-devel - padoka PPA

- Missing Shaman class from list of class choices. Also, unable to select any classes on new characters. Have not tested on established characters with only one class selected.
- Grim Dawn does not allow accessing skills menu a second time after leveling a new character.

_This affects Grim Dawn with or without ashes expansion._

***
@kungtotte commented on 2018-08-25T17:30:15

CPU Brand: Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz
Kernel Version: 4.14.65-1-MANJARO
Driver Version:  4.6.0 NVIDIA 396.51, Proton 3.7

I'm having the same issue. I mounted my Windows games partition and compared the files between the Windows install and this one, and everything matches up. Going to investigate some more.

**Comment by nelsam** [comment]
To add to this, bosses don't seem to spawn.  See [here](https://steamcommunity.com/app/219990/discussions/0/1733210552681205001/) for an additional report (it's also mentioned several times in the [unofficial compatibility list spreadsheet](https://docs.google.com/spreadsheets/d/1DcZZQ4HL_Ol969UbXJmFG8TzOHNnHoj8Q1f8DIFe8-8/htmlview?sle=true#gid=2086525177)).  I've tried a number of things and haven't found anything that solves either this or the inability to select masteries (at both level 2 and level 10).

**Comment by kungtotte** [comment]
Aside from my previously mentioned issue of not being able to select a class, I am experiencing flickering of character models. They will intermittently disappear and reappear rapidly.

System Information: https://gist.github.com/kungtotte/c2a8a74134971703bec4635b14853362

**Comment by BLaDZer** [comment]
Can't apply/save any game option. This mean also unable to change language for me :(
It seems not created any files in /steamapps/compatdata/219990/pfx/drive_c/users/steamuser/Documents/My Games/Grim Dawn/. Creating empty paths or copying from windows version has no effect...

P.S. removed prefix, reinstall game several times - everytime same bug

**Comment by garpu** [comment]
CPU: Intel(R) Core(TM) i7-2700K CPU @ 3.50GHz
NVIDIA: 1050ti,   4.6.0 NVIDIA 396.54
Proton: default

Same here with the missing classes, except it's missing shaman, Inquisitor, and Necromancer for me.  I can play my Conjurer/shaman and Necromancer/nightblade just fine, though. (Existing characters made on WINE.) No problems with wine-staging 3.13. 

Other than that, dx11 (default without /d3d9 flag) works awesome.

**Comment by nelsam** [comment]
@garpu do boss monsters spawn for you? i switched to normal wine to choose masteries, then got stuck in proton again because named boss monsters wouldn't spawn, so i couldn't finish quests requiring me to kill them. I had to switch to normal wine for that too.

**Comment by garpu** [comment]
I just tried with my new character and the first boss in Burial Hill, and it didn't spawn for me using Proton.  The boss spawned fine in non-Proton wine.

**Comment by tkossak** [comment]
Similar problems on Manjaro, nvidia 396.54, default Proton 3.7:

- The first time I create new character in main menu it doesn't work: I press the "Create Character" button in lower right corner, enter name, press "Create" and nothing happens. I repeat these steps and second time it works.
- Some objects of main menu (trees, character) flicker. Once I enter single player game, the graphics seem to be perfect (I played for 1 hour). UPDATE: today also during the game some objects flicker all the time. It started to flicker after I created default user_settings.py
- When I lvl up (2 and next levels) I cannot choose any class for my character (started the game twice, and had the same problem) [All the class buttons are greyed out (screenshot)](https://imgur.com/GiWdaWk)
- I cannot access skills menu (default button doesn't work, remapped button doesn't work either)

[Steam Information](https://gist.github.com/tkossak/7917b1b1a506f04a8511449134ccff7a)
[steam-219990.log](https://gist.github.com/070c0aab49a2b7116bf1dfdcb56ed942)
[Steam stdout](https://gist.github.com/tkossak/a0406c6b80123dee9b742cf5dc0ea6a9) (from start of the game to quitting)

**Comment by garpu** [comment]
Another weird issue for me?  It's not loading dxvk, and I know it works well with dxvk with regular WINE. (I can upload that log, too, if anyone needs it.)

https://gist.github.com/garpu/c54d1dcf7b11c6eef68ba794369b35f4

**Comment by stshow** [comment]
#### Nvidia // DirectX 11 - Flickering textures when shadows enabled.

DirectX 11 via Proton results in flickering of all textures. I have tried all video configurations from low to high, but the only change that consistently resolves the issue is to disable shadows completely and then restart the game. The other solution is to set launch option `/d3d9` under _**Properties > General > SET LAUNCH OPTIONS...**_ ; shadows work fine with DirectX 9 it seems. 

Performance is otherwise excellent on max settings (all), if not slightly improved by adding `+fullproc` to the launch options (though this is likely placebo). What probably enhances performance the most is the optimizations I list at the end.

#### Two minor, _unrelated_, issues I have seen are:

1. Progress doesn't seem to be saved as indicated by all achievements being displayed each time a game is started.
2. The Homestead rift will not open because the boss appears and then disappears. This does not seem to be the same issue as seen [here](https://steamcommunity.com/app/219990/discussions/0/611702631224473373/), as I have tried to run through that area on multiple occasions. 

<details>
  <summary>CPU Governor // Nvidia Xorg optimizations</summary>

##### CPU performance
```
echo performance | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
```
##### Xorg settings // Force Powermizer to full performance level 3

```
Section "Device"
    Identifier     "Device0"
    Driver         "nvidia"
    ## Powersaver mode
    #Option  "RegistryDwords"   "PowerMizerEnable=0x1; PerfLevelSrc=0x3333; PowerMizerLevel=0x3; PowerMizerDefault=0x3; PowerMizerDefaultAC=0x3"
    ## Performance mode
    Option  "RegistryDwords"   "PowerMizerEnable=0x1; PerfLevelSrc=0x3322; PowerMizerLevel=0x1; PowerMizerDefault=0x1; PowerMizerDefaultAC=0x1"
    VendorName     "NVIDIA Corporation"
    BoardName      "GeForce GTX 980 Ti"
EndSection
```
</details>

<details>
 <summary>Steam - System Information</summary>

```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
    CPU Family:  0x6
    CPU Model:  0x3f
    CPU Stepping:  0x2
    CPU Type:  0x0
    Speed:  3600 Mhz
    12 logical processors
    6 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Ubuntu 18.04.1 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.15.0-33-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11906000
    X Window Manager:  i3
    Steam Runtime Version:  steam-runtime-beta-release_2018-06-14

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 980 Ti/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 396.54
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x17c8
    Revision Not Detected
    Number of Monitors:  3
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 4890 x 1680
    Primary Display Size: 20.08" x 11.30" (23.03" diag)
                                            51.0cm x 28.7cm (58.5cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 6144 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC1150

Memory:
    RAM:  48191 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Total Hard Disk Space Available:  243791 Mb
    Largest Free Hard Disk Block:  5237 Mb
    VR Headset: None detected

Recent Failure Reports:

```
</details>

**Comment by garpu** [comment]
https://steamcommunity.com/app/219990/discussions/0/3338745825889250571/?ctp=2 So there's some speculation that the missing boss and class issue is Proton triggering the anti-piracy measure.  What does proton do that regular WINE doesn't?

**Comment by garpu** [comment]
With proton 3.16-1, there's absolutely no flickering, whatsoever.  But classes and bosses are still missing.

**Comment by garpu** [comment]
And now regular WINE with dxvk 0.91 and Nvidia drivers 396.54.09 is flickering. /d3d9 doesn't have this issue. Regression?

Out of curiosity, has there been any movement on fixing proton tripping the anti-piracy measures? Anything we can help test?

**Comment by stshow** [comment]
@garpu I can confirm that `wine-3.20 (Staging)` and `dxvk 0.92` also produces flickering. Sysinfo: 

```
Ubuntu 18.04.1
Driver: Nvidia 410.73
Wine: wine-3.20 (Staging)
Dxvk: 0.92
```

<details>
    <summary>Recreate steps</summary>

#### Ubuntu 18.04.1
```
$ sudo dpkg --add-architecture i386 
$ sudo add-apt-repository ppa:graphics-drivers/ppa
$ wget -nc https://dl.winehq.org/wine-builds/Release.key
$ sudo apt-key add Release.key
$ sudo apt-add-repository https://dl.winehq.org/wine-builds/ubuntu/
$ sudo apt-get update
$ sudo apt-get install --install-recommends winehq-staging nvidia-driver-410 winetricks
$ reboot
$ wget https://github.com/doitsujin/dxvk/releases/download/v0.92/dxvk-0.92.tar.gz
$ tar xvzf dxvk-0.92.tar.gz
$ cd dxvk-0.92
$ export WINEPREFIX=~/.grimdawn
$ export WINEARCH=win32
$ winetricks --force setup_dxvk.verb
### Following borrowed from: http://www.grimdawn.com/forums/showthread.php?t=34333
$ WINEARCH=win32 WINEPREFIX=~/.grimdawn winecfg
### Set Windows version to `Windows 7`
$ WINEARCH=win32 WINEPREFIX=~/.grimdawn winetricks vcrun2010 vcrun2012 xact xinput d3dx9
$ wget https://steamcdn-a.akamaihd.net/client/installer/SteamSetup.exe
$ cd /path/to/downloaded/steam/installer
$ WINEARCH=win32 WINEPREFIX=~/.grimdawn wine SteamSetup.exe
### Sign into Steam, install Grim Dawn, start Grim Dawn. 
```
#### Result: Flickering in the UI
#### Workaround: Enable `/d3d9` under `Properties > General > SET LAUNCH OPTIONS` in Steam
</details>

**Comment by garpu** [comment]
Should this go on dxvk's issues? I think it may have started around 0.90.

**Comment by stshow** [comment]
@garpu I was thinking the same thing. An issue should be opened here **after** we have confirmed that this happens in the `master` branch: https://github.com/doitsujin/dxvk/issues

Per the project's guidelines:
```
If you run into a problem with a binary release, make sure to test with latest `master` as well.
```

**Comment by stshow** [comment]
I have successfully built the master branch, but have only been able to test for a few minutes. The flickering was worse on the character screen. So far, no flickering observed in game, but I am not confident that will last. Further, I am not sure if the latest `dxvk` libraries will trigger the anti-piracy measures of the software. 

---
To accomplish this, I forked a github project that I found for building the latest master branch of `dxvk`:
https://github.com/stshow/dxvk-docker

<details> 
     <summary>Instructions (building on above `Recreate steps` // follow those first)</summary>

```
$ git clone https://github.com/stshow/dxvk-docker.git
$ cd dxvk-docker
$ ./make-dxvk
# Follow the prompts. 
# What branch/tag/gitref do you want to build? [master]: <Enter>
# Install dxvk-master to Lutris? [Y/n]: n
$ cd dxvk/DXVK-MASTER/dxvk-master
$ export WINEPREFIX=~/.grimdawn
$ export WINEARCH=win32
$ winetricks --force setup_dxvk.verb
```
</details>

--- 
Feel free to run the above container and try it for yourself. If you feel inclined to open the PR on https://github.com/doitsujin/dxvk/issues, be my guest. Only prerequisite is to use the above instructions to install the latest Docker CE. If you have never done that, try this (if you trust pulling down a bash script and running it as such): 

```
$ curl -fsSL https://get.docker.com | bash
$ git clone https://github.com/stshow/dxvk-docker.git
$ docker build -t stshow/dxvk-docker:latest .
```

**Update:** My PR was merged in the upstream dxvk-docker image. You may want to use that one moving forward as it is more actively maintained. https://github.com/cheald/dxvk-docker

**Update:** New nvidia 415.18 drivers are available with improvements to Vulkan. This may be worth testing as well. https://www.phoronix.com/scan.php?page=news_item&px=NVIDIA-415.18.02-Linux-Released

**Comment by stshow** [comment]
I just did a couple of short tests on Ubuntu 18.04 with Nvidia 415.18 drivers, https://github.com/doitsujin/dxvk/commit/cf21111401db1ba301fe013132746030130aa67d (latest master), and Wine Staging 3.21. No flickering observed.

**Comment by stshow** [comment]
Still seeing flickering, but only on the title screen prior to starting the game and **only** when playing fullscreen. In borderless windowed mode, there is ~~zero~~ flickering.  **Update:** When talking to Barnabas in Devil's Crossing, there is some small amount of flickering in the character portrait (windowed borderless). Otherwise, gameplay seems fine.

**Comment by thamenato** [comment]
@stshow I used to have the flickering problem on title screen but now that I updated my nvidia to the latest driver it's working fine. I am getting same fps with same config on both Windows and Linux and no problems at all when it comes to graphics. 

For me what makes the game unplayable is the progression, I started a new character and I already could not pick one of the Masteries at level 2, I kept playing until level 10 to see if I could find any other issue but that seems to be the only thing. 

> OS: Manjaro 18
> Kernel: 4.19.6-1-MANJARO
> Driver: 415.18
> Proton 3.16-4 Beta (using the latest one available on Steam)
> Resolution: Windows (Borderless) 2560x1080

**Comment by beaverusiv** [comment]
@thamenato that is the anti-piracy protection. Unfortunately Crate are not looking to do anything with Linux and Steam are not going to change how Proton works for this one game unless it shows as a more widespread problem :/

I believe Grim Dawn will forever be 'unplayable' on Proton.

**Comment by stshow** [comment]
@thamenato I concur with @beaverusiv. Hence, I provided the details for running the game with wine-staging. Best case scenario: if we can find the wine patch that triggers the anti-piracy in the game ( _esync etc_ ) using wine, we can make suggestions for improvements/changes to Proton. In the end, it is possible that our findings here may require changes to Proton that are undesirable to Valve et al. I will gladly continue to post findings that help our cause nevertheless.

**Comment by garpu** [comment]
And if we can figure out what's causing it, and if it's a problem with WINE, it might be something that can be fixed upstream from Proton.

**Comment by thamenato** [comment]
I would love to help you guys somehow, though I'm not sure if my lack of knowledge on how WINE works under the hood would be useful.

**Comment by GloriousEggroll** [comment]
I'm on AMD and don't have the flickering issue, just the supposed anti-piracy issue with missing classes + boss spawns + class choice etc. For Nvidia users if /d3d9 works fine then the flickering issue is with DXVK. I would say try older versions of DXVK (you can manually copy them into proton/dist/lib(and lib64)/wine/dxvk to see if any older version gets rid of the flicker. if it does, then dxvk needs to be bisected

**Comment by beaverusiv** [comment]
The theory I have seen put forth is that Proton puts files in the directory of the game it is running under wine whereas other methods (PlayOnLinux, etc) do not and Grim Dawn is checking that only its files are in the directory. If this is the case then it is definitely not something Proton would likely change.

**Comment by GloriousEggroll** [comment]
@beaverusiv not sure if this is correct/true, as I have my entire prefix folder inside of grim dawn's steam folder for lutris, and it runs the game without issue. If this is the case it might be helpful to figure out what files proton is placing in the grim dawn folder

**Comment by beaverusiv** [comment]
@GloriousEggroll I am referring [to this thread](https://steamcommunity.com/app/219990/discussions/0/3338745825889250571/). I have not confirmed myself.

**Comment by stshow** [comment]
I confirmed that using the latest `dxvk` master https://github.com/doitsujin/dxvk/commit/9572425912c2ee07ee112d8fe75a817c0f82b85c along with [wine-tkg-protonified](https://github.com/lutris/wine/tree/tkg-protonified) allows the game to progress. I leveled a a new necromancer to 5, opened the Burial Hill rift gate, and completed the first quest (kill boss beneath Burial Hill) without issue. 

I have not reviewed the "protonified" source to find out which Proton patches are incorporated, but perhaps this can serve as a diff against Proton and help us to get to the bottom of the mystery. You can try it by downloading this pre-built binary (from Lutris' servers) and running it:

```
$ wget https://lutris.nyc3.digitaloceanspaces.com/runners/wine/wine-tkg-protonified-3.21-x86_64.tar.gz
$ tar xvzf wine-tkg-protonified-3.21-x86_64.tar.gz -C ~
$ WINEESYNC=1 WINEARCH=win32 WINEPREFIX=~/.grimdawn ~/tkg-protonified-3.21-x86_64/bin/wine C:\\\\windows\\\\command\\\\start.exe steam://rungameid/219990
```
---
We may also want to consider testing a standalone build of the latest `Proton` master too. Perhaps, if @beaverusiv 's theory is correct, the Steam client is triggering the anti-piracy, and not the engine itself.

**Comment by GloriousEggroll** [comment]
I fired up both the lutris/winesteam version and the proton version and looked into the libraries in-use in the task manager, then compared them to see if there was anything extra the lutris version had in use, here's what's missing from the proton version in relation to wine:

```
668 KB	/home/gloriouseggroll/.local/share/lutris/runners/wine/3.21-x86_64/lib/wine/msvcr120.dll.so
220 KB	/home/gloriouseggroll/.local/share/lutris/runners/wine/3.21-x86_64/lib/wine/dbghelp.dll.so
80 KB	/home/gloriouseggroll/.local/share/lutris/runners/wine/3.21-x86_64/lib/wine/shcore.dll.so
76 KB	/home/gloriouseggroll/.local/share/lutris/runners/wine/3.21-x86_64/lib/wine/concrt140.dll.so
60 KB	/home/gloriouseggroll/.local/share/lutris/runners/wine/3.21-x86_64/lib/wine/netapi32.dll.so
44 KB	/home/gloriouseggroll/.local/share/lutris/runners/wine/3.21-x86_64/lib/wine/crypt32.dll.so
20 KB	/home/gloriouseggroll/.local/share/lutris/runners/wine/3.21-x86_64/lib/wine/secur32.dll.so
16 KB	/home/gloriouseggroll/.local/share/lutris/runners/wine/3.21-x86_64/lib/wine/imagehlp.dll.so
12 KB	/home/gloriouseggroll/.local/share/lutris/runners/wine/3.21-x86_64/lib/wine/kerberos.dll.so
12 KB	/home/gloriouseggroll/.local/share/lutris/runners/wine/3.21-x86_64/lib/wine/mswsock.dll.so
8 KB	/home/gloriouseggroll/.local/share/lutris/runners/wine/3.21-x86_64/lib/wine/bcrypt.dll.so
```

my hunch is that maybe it needs bcrypt/crypt32. 
Interestingly enough - using runner 3.16-x86_64 in lutris - which is the vanilla version of wine 3.16, with dxvk, the game doesn't render, just shows a black screen. It does work with 3.21.

**Comment by stshow** [comment]
@GloriousEggroll Just to be clear, you are comparing Wine `3.21` (vanilla) to [Proton](https://github.com/ValveSoftware/Proton/tree/proton-3.16beta-20181031#Building) and not Wine `tkg-protonified`, correct? Just wanted to clarify:
> here's what's missing from the proton version in relation to wine

Appreciate the cycles on this!

**Comment by GloriousEggroll** [comment]
Correct.

**Comment by ryanmusante** [comment]
Flickering for me was corrected by setting antialiasing to 4x. Exited game and restarted, flickering present again, meh. 

Wine-tkg-staging 4.0rc3, Dxvk 0.94, nvidia 415.25

**Comment by stshow** [comment]
```
Proton Beta Release: 3.16-6
Support for gnutls >= 3.0, which should fix many networking issues with games. Note the Steam runtime doesn’t ship this yet, so your distribution will need to provide it. 
```

Have not had a chance to test, but might address crypto lib issues mentioned in https://github.com/ValveSoftware/Proton/issues/466#issuecomment-446109963 and help overcome anti-piracy issues seen thus far. If that does not work, a custom compile of proton with aforementioned dependencies (https://github.com/ValveSoftware/Proton/issues/466#issuecomment-446109963) may be in order. 

---

 @ryanmusante did you note whether quest progress is possible (https://github.com/ValveSoftware/Proton/issues/466#issuecomment-423186921)? Anti-piracy has been kicking in on versions prior to 3.16-6 so far.

**Comment by GloriousEggroll** [comment]
sadly it did not fix it. the only other thing I can think of is maybe proton's version of the steam dlls needed for DRM is not enough

**Comment by greydmiyu** [comment]
Still cannot pick a class with 3.16-7.  Didn't expect it to work, just putting it here as I tested and know others will want to know.

**Comment by bendooru** [comment]
The new x64 binary added in v1.1.0.0 does not seem to exhibit the problems reported here: I was able to pick a mastery upon reaching level 2 and Kyzogg did spawn, so I was able to complete the first quest. I was also able to kill Warden Krieg with another character.

The x32 version still has the same problems, even on Proton 3.16-8.

E: As @scottc points out, version 1.1.0.1 also fixes the problems for the x32 executable.

**Comment by kungtotte** [comment]
I can confirm, @bendooru None of the fixes described previously have worked for me for the class/progression issue but now running with x64 I am able to pick a class just fine. No HW changes for me and I've only updated Proton and the proprietary nVidia driver continuously as updates have been made available.

**Comment by scottc** [comment]
Grim Dawn 1.0.1.1
Proton 3.16-8 Beta

Both x86 and x86_64 builds are working flawlessly on my setup.

Kyzogg spawns and character progression is working.

Prior to Grim Dawn 1.1.0.0 I had issues with Kyzogg.

**Comment by lieff** [comment]
With V1.1.0.0 I have no issues, but I have to re-create already bugged character.

**Comment by mvdstam** [comment]
@scottc @lieff With Proton 4.2.1 and the x64 binary of V1.1.0.0, I'm experiencing flickering textures. Do you have this issue as well? Disabling D3D11 fixes this, but seems to have an very large impact on performance (going from native-like-smooth to barely playable when lots of stuff is happening on screen). What are you experiences in this?

I'm using nvidia-418.56 and linux 5.0.4.

According to [this comment on Reddit](https://old.reddit.com/r/SteamPlay/comments/b0plxz/grim_dawn_has_been_potentially_fixed_with_release/eio09ei/), this issue seems to be related to the texture flickering: https://github.com/doitsujin/dxvk/issues/405. Running example with the fix [here](https://www.youtube.com/watch?v=fJrxBgM74zk). Looks like one would need to provide a custom-built Proton version just for Grim Dawn with a specific patch that fixes the texture flickering, but breaks other games. :disappointed:

**Comment by lieff** [comment]
I'm already using dx9. With dx11 there flickering textures on previous versions of the game too.

**Comment by garpu** [comment]
It's just the patched version of dxvk that's needed.  I pulled the dxvk files (dist/lib/wine/dxvk and dist/lib64/wine/dxvk) out of the version provided and put them into a copy of proton 4.2 pasted into Steam/compatibilityltools.d.  (And compatibilitytool.vdf copied into the new proton directory and edited to reflect the new version.)

**Comment by mvdstam** [comment]
@garpu Thanks, I did just that and it seems to work fine. I couldn't get the game to work when compiling the dxvk dll's myself when cherry-picking the patch to DXVK 1.0, but with the patched DXVK 0.96 as described in the description of the aforementioned [Youtube video](https://www.youtube.com/watch?v=fJrxBgM74zk), it works perfectly. No need to disable D3D11, no flickering textures.

## How to install and use the patched DXVK version with Proton.

#### Disclaimer: undertake these steps at your own risk. Always check the contents of archives you download from the internet. Furthermore, the patched DXVK DLL's will likely not work with games other than Grim Dawn. Finally, take note of the following warning as stated by the maintainers of DXVK themselves:

> Manipulation of Direct3D libraries in multi-player games may be considered cheating and can get your account banned. This may also apply to single-player games with an embedded or dedicated multiplayer portion. Use at your own risk.

Without further ado, these are the steps I took to get this to work:

- `mkdir ~/.local/share/Steam/compatibilitytools.d/`
- `cp -r ~/.steam/steam/steamapps/common/Proton\ 4.2 ~/.local/share/Steam/compatibilitytools.d/`
- Download the patched DXVK DLL's as provided by said [Youtube video](https://www.youtube.com/watch?v=fJrxBgM74zk) and `cd` to the directory where `dxvk-dsr-0.96.tar.gz` was downloaded, or compile the DLL's yourself.
- `tar xzvf dxvk-dsr-0.96.tar.gz`
- `mv dxvk-dsr-0.96/x32/*.dll ~/.local/share/Steam/compatibilitytools.d/Proton\ 4.2/dist/lib/wine/dxvk`
- `mv dxvk-dsr-0.96/x64/*.dll ~/.local/share/Steam/compatibilitytools.d/Proton\ 4.2/dist/lib64/wine/dxvk`
- Finally, `touch ~/.local/share/Steam/compatibilitytools.d/Proton\ 4.2/compatibilitytool.vdf` and fill with the following content:

```"compatibilitytools"
{
  "compat_tools"
  {
    "Proton 4.2-GrimDawn" // Internal name of this tool
    {
      // Can register this tool with Steam in two ways:
      //
      // - The tool can be placed as a subdirectory in compatibilitytools.d, in which case this
      //   should be '.'
      //
      // - This manifest can be placed directly in compatibilitytools.d, in which case this should
      //   be the relative or absolute path to the tool's dist directory.
      "install_path" "."

      // For this template, we're going to substitute the display_name key in here, e.g.:
      "display_name" "Proton 4.2-GrimDawn"

      "from_oslist"  "windows"
      "to_oslist"    "linux"
    }
  }
}
```

After restarting `steam`, you should be able to select the patched `proton` version specifically for Grim Dawn:

![image](https://user-images.githubusercontent.com/7629384/55089966-940e2f80-50ae-11e9-87a5-ae0529c65adb.png)
![image](https://user-images.githubusercontent.com/7629384/55090754-f1ef4700-50af-11e9-9f0e-436964e41c1b.png)

And that's it!

**Comment by garpu** [comment]
It would be nifty, if there could be a release of the patched version of dxvk built specifically for Proton, like an optional tool release. (Seeing as though it's a fix for Grim Dawn and Dark Souls.)  Are there any other games that are affected by this?

**Comment by mvdstam** [comment]
@garpu Unfortunately, this seems to be a bug that's not easily fixed without breaking other games according to https://github.com/doitsujin/dxvk/issues/405#issuecomment-458900682.

I wish I could fix it myself, but I have zero experience in C++ let alone DirectX or Vulkan programming. :smiley:  Perhaps @doitsujin is willing to take a fresh look at it once more if we ask them nicely. Perhaps the codebase has evolved over the last couple of months so that the changes in https://github.com/doitsujin/dxvk/commit/621aed5fdbaf92764944be7b3a27cbb3df63ba94 can be incorporated more easily without breaking other stuff, who knows. :wink:

I'm not sure about other games being affected by this by the way. I haven't seen the flickering problem in any games other than Grim Dawn and Dark Souls Remastered.

**Comment by garpu** [comment]
That's why I thought the patched dxvk as an optional tool download would make sense--it would be compiled for proton and distributed through Valve.  Compiling dxvk involves a dependency hell that not everyone would (or could) resolve.  Although if it only affects two games, would it be worth the extra trouble?

**Comment by Desidiosus** [comment]
@mvdstam My follow-up comments on reddit have a link to a Proton version with the flickering patch applied to DXVK 1.0.1, which has a bit better performance than the 0.96 version, so there's no need to use the old version. 

The patched 1.0.1 is available [here](https://github.com/Desidiosus/dxvk/tree/constant-bounds-option). If you actually look at the commits, [K0bin](https://github.com/K0bin/dxvk/tree/constant-bounds-option) is the real MVP for making the flicker fix work with 1.0. The only thing I did was add Grim Dawn support.

**Comment by rosshadden** [comment]
I can't launch Grim Dawn. I get the dialog for 32bit vs 64bit, but when choosing either nothing happens.
Launching Steam from a terminal does give some (hopefully helpful) output when it crashes (included below). I have tried on every version of Proton from 3.7 to 4.2, including the betas.

It's hard to tell which of the errors are specific to this and which may be safely ignored, but these stick out:

```
[S_API FAIL] SteamAPI_Init() failed; no appID found.
Either launch the game from Steam, or put the file steam_appid.txt containing the correct appID in your game folder.
Proton: Missing or invalid openvrpaths.vrpath file! [Errno 2] No such file or directory: '/home/ross/.config/openvr/openvrpaths.vrpath'
shadercachemanager/shadercacheimplsteamdepot.cpp (75) : Assertion Failed: Platform disambiguator mismatch!
ERROR: ld.so: object '/home/ross/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/ross/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
```

The full error given: https://gist.github.com/rosshadden/66d20b2b5823068a5bb1f8a838bea57c
My system information: https://gist.github.com/rosshadden/fba3b2e3378b01835af987f8d84672a0

Update: Tried with steam-native as well, and I get similar errors (added to gist above). The only difference I found was that steam-runtime had this error and native did not: `wine: cannot find '/home/ross/.local/share/Steam/legacycompat/iscriptevaluator.exe'` (and sure enough, that file exists and is readable by everyone).

**Comment by rosshadden** [comment]
Apparently I skipped a proton version. Based on [this comment](https://github.com/ValveSoftware/Proton/issues/1676#issuecomment-450701845) I tried proton `3.16-4` and it launched. After running it with this version of proton, I tried with 4.2 and it worked as well... Nothing other than trying 3.16-4 was done since when it did not work, so either something random is happening or there are some artifacting side-effects going on that bleed across proton versions.

**Comment by garpu** [comment]
I've had it crash a couple times with me, as well, but I had the /x64 flag set.  If I don't set it, it seems to launch OK. Perhaps coincidence?

**Comment by greydmiyu** [comment]
> I'm already using dx9. With dx11 there flickering textures on previous versions of the game too.

Are you also putting +fullproc on the command line?  Here's the Launch Options I use for Grim Dawn.  No flickering, no noticable issues with FPS.

/d3d9 +fullproc

**Comment by lieff** [comment]
@greydmiyu Nope, I do not have +fullproc, and quick googling says there no such option for Grim Gawn:
https://steamcommunity.com/app/219990/discussions/0/535152276590715701/#c535152276591233289
But I'll check it soon.

**Comment by jesusredondo** [comment]
I have been messing with the dxvk modified versions posted above. Unfortunately I don't have Proton 4.2 yet (I still don't know how to manage/update Proton versions, if possible through steam). So all test has been performed in 3.16 Beta

The updated dxvk version (1.0) [in reddit](https://old.reddit.com/r/SteamPlay/comments/b0plxz/grim_dawn_has_been_potentially_fixed_with_release/eio09ei/) works as fine as is the 0.96 posted in the video above.

FPS is great, no more Flickering,everything looks fine except... there is a small stutter every 2-3 seconds which is very annoying, such a pity.

As other mentioned before, disabling dx11 halves performance (even at lowest resolutions, and considerind I am using a 1080ti, something must be wrong) so I have discarded that option. 

Using the dxvk modified version is not 100% playable without the stutter every 3-4 seconds. If anyone has been able to make it run smooth... could you please share Proton folder? Thanks

**Comment by kisak-valve** [comment]
Hello @jesusredondo, Proton versions managed by Steam are listed in the Tools section (Steam -> Library dropdown -> Tools).

**Comment by jesusredondo** [comment]
@kisak-valve Thanks a ton! Downloading proton 4.2... I will update with the outcome.

**Comment by jesusredondo** [comment]
Ok, proton 4.2 fixed everything. No need to include the modified dxvk dlls.

Thanks!

**Comment by garpu** [comment]
With 4.2, you're not getting the flickering on dx11? I just tried 4.2-1 without the modified dxvk, and it's still flickering for me. It comes and goes.  It almost seems to be similar to the old Titan Quest missing texture bug in that sometimes when you restart, the bug is gone.

**Comment by jesusredondo** [comment]
Yes, I have just installed the 4.2.1. and it made the trick. No flickering at all. And the 3 second stutter is almost gone (almost). Very playable now. I have latest nvidia drivers (1080ti), I also updated the kernel to latest version ( [somebody in protonDB fixed the flickering doing so](https://www.protondb.com/app/219990)).

Maybe I fixed the flickering by doing both things: Kernel upgrade and proton 4.2.

**Comment by lieff** [comment]
@greydmiyu no noticeable difference with +fullproc

For dx11, Proton 4.2 with unpatched dxvk do not works for me too.

**Comment by garpu** [comment]
https://github.com/doitsujin/dxvk/issues/405 Apparently with dxvk 1.1 the flickering is fixed?

**Comment by tr37ion** [comment]
It looks like #864 has a similar issue.

**Comment by scottc** [comment]
Popular unofficial Grim Dawn community mods. (Not steam workshop)

DISCLAIMER: I am not the author of these mods. Use at your own risk, no warranty provided, may destroy your save games, may cause data loss, get your steam account stolen, permanently banned, damage to hardware or personal injury.

At time of writing this post:

## GrimInternals

0) Download [GrimInternals](http://www.grimdawn.com/forums/showthread.php?t=53629).

1) Extract GrimInternals, as per the windows instructions.
(Typically; `"/home/__YOUR_USER__/.local/share/Steam/steamapps/common/Grim Dawn"`)

~**Note:** I extracted griminternals inside the `/Grim Dawn/x64/` folder instead, because it cannot find the dlls inside the `/x64/` folder otherwise.~ Note: this is no longer the case.

> OK, I got it working tonight. For me, I had to make sure GrimInternals64.exe and GrimInternalsDll64.exe were located directly in my Grim Dawn folder. Having them in the x64 folder simply would not work.

@SherrifsNear https://github.com/ValveSoftware/Proton/issues/466#issuecomment-503800017


2) Can dump the proton run command via adding launch options to Grim Dawn:
Properties > SET LAUNCH OPTIONS...
`PROTON_DUMP_DEBUG_COMMANDS=1 %command%`

3) Run and then exit Grim Dawn.

4) Make a copy of the dumped run command, to home directory:
`cp "/tmp/proton_$USER/run" "$HOME/run_grim_dawn.sh"`

5) Edit `$HOME/run_grim_dawn.sh` with text editor, and modify the `DEF_CMD` var file path to point at GrimInternals. And any other customizations as you see fit.
```
cd "/home/__YOUR_USER__/.local/share/Steam/steamapps/common/Grim Dawn"
DEF_CMD=("/home/__YOUR_USER__/.local/share/Steam/steamapps/common/Grim Dawn/GrimInternals64.exe")
```
**Note:** I also explicitly have the version of proton installed, under Library > Tools. Which appears under `$HOME/.local/share/Steam/steamapps/common/Proton __VERSION__/`

6) Make it executable:
`chmod +x ~/run_grim_dawn.sh`

6) Run it:
```
cd ~
./run_grim_dawn.sh
```

If it fails to run, you can remove this line from the run command, to get errors printed to the console. To help troubleshoot. But comes with a small performance penalty.
```
WINEDEBUG="-all" \
```

Should also be able to add it as a Non-Steam game shortcut.

## Item Color Filter

0) Download [Item Color Filter](http://www.grimdawn.com/forums/showthread.php?t=63773&page=15#post718407) and check that you have the latest version.
(outdated versions may break in-game text descriptions)
1) Extract the Item Color Filter, as per the windows instructions.
(Typically; `"/home/__YOUR_USER__/.local/share/Steam/steamapps/common/Grim Dawn"`)
2) Play Grim Dawn.
3) Manually update after each Grim Dawn release.

## GDItemAssistant

I haven't had any luck with [GDItemAssistant](http://www.grimdawn.com/forums/showthread.php?t=35240) which depends on dll injection.

## GDStash

As per @lieff 's comments below:
https://github.com/ValveSoftware/Proton/issues/466#issuecomment-483631990

> `java -Xms1024m -Xmx1024m -jar GDStash.jar`

You can also put this in a shell script (`.sh`) file with executable permissions `chmod +x`, and then add to steam library for convenience.

```
#!/bin/sh
java -Xms1024m -Xmx1024m -jar GDStash.jar
```

**Comment by lieff** [comment]
GDStash works for me. Both variants: installed inside wine prefix or linux native.
Native runs like this: java -Xms1024m -Xmx1024m -jar GDStash.jar

**Comment by Pardlerum** [comment]
@scottc thanks for taking the time to post that in such detail - I miss auto-pickup! Will try and implement when I get back from work...

**Comment by Pardlerum** [comment]
Just can't get GrimInternals working on my setup. A few changes from @scottc description above:
(1) Needed to chmod +x the files after expanding; and
(2) Rather than manually editing the path details in Steam use the 'Change...' button to locate the GrimInternals64.exe file. This populates the "Target" and "Start In" elements with your details...

..but although GrimInternals obviously runs it always gives a "Can't find Grim Dawn!" error for me. I presume there is some Windows path it's looking for beyond the launch folder. Any assistance greatly appreciated...

**Comment by scottc** [comment]
@Pardlerum 

> ..but although GrimInternals obviously runs it always gives a "Can't find Grim Dawn!" error for me. I presume there is some Windows path it's looking for beyond the launch folder. Any assistance greatly appreciated...

It would be looking relative to the current "working directory".

New instructions https://github.com/ValveSoftware/Proton/issues/466#issuecomment-483628753

**Comment by Pardlerum** [comment]
Thanks for the update @scottc. Working! I am very happy. :)

**Comment by lieff** [comment]
Latest proton 4.2-3 and Nvidia 418.56 now works with dx11 without glitches.

**Comment by beaverusiv** [comment]
Hmm, using @scottc's instructions I can get GD to load from the GrimInternals bash script but Ctrl+F5 does nothing.

**Comment by scottc** [comment]
> Hmm, using @scottc's instructions I can get GD to load from the GrimInternals bash script but Ctrl+F5 does nothing.

Have you edited the shell script to use GrimInternals?

> DEF_CMD=("/home/**YOUR_USER**/.local/share/Steam/steamapps/common/Grim Dawn/x64/**GrimInternals64.exe**")

Does it mention GI version in the bottom right hand corner of character select?

> v1.1.1.2 (x64) **(GI v1.77)**

If GI is working, but the configuration UI is not. As a workaround, you can edit the `GrimInternals.ini` file for configuration changes before launching the game.

I believe most of the run-time dependencies are similar between grim dawn and grim internals. Can try turn on WINEDEBUG console messages by removing `WINEDEBUG="-all" \`. For additional information.

**Comment by beaverusiv** [comment]
Yes, the proper .exe is set in DEF_CMD.
No, the GI version does not show up :/

I have tried without suppressing debug output but I see nothing that indicates an error. If I misspell GrimInternals64.exe it throws an error so it is definitely looking for that file.

It does have these lines when starting:
```
info:  Game: Grim Dawn.exe
info:  DXVK: v1.0.3-4-g46908d47
info:  Found built-in config: Grim Dawn.exe
```

The same thing happens for steam-native and steam-runtime.

**Comment by beaverusiv** [comment]
Update: commenting out `SteamGameId="219990" \` seemed to fix it for me. Note `SteamGameId`, *not* `SteamAppId`.

Hopefully this helps if someone else has problems.

**Comment by AndyHoang** [comment]
@scottc Thanks you I follow and its work for me with latest grim internal v1.1.2.2  
Event better I try to improve it so that we can run it inside the steam instead running the script
[https://i.imgur.com/ZkukHuW.jpg](me playing)

- Go on Steam and press Game : Add a Non-Steam game.
- Press on Browse and search for the `run_grim_dawn.sh`  in the folder and after clicking on it press on "Add selected Programs"
- In the steam Library below the Grim Dawn game launcher there will be the new games too. Right click on this and press on properties to check:
- `target: "/home/{user_name}/.local/share/Steam/steamapps/common/Grim Dawn/x64/run_grim_dawn.sh"`
- `call start in: "/home/{user_name}/.local/share/Steam/steamapps/common/Grim Dawn/"`
- `set launch option`: None (can edit params later)

And now we can play it on steam

**Comment by blutigJK** [comment]
I'm having issues getting GrimInternals to run. Followed the steps above from @scottc and it doesn't want work even though GrimInternals64.exe process is running. It seems to spit out this error when loading to the main menu.

```
Timed out waiting for game mapping!
002d:fixme:system:SystemParametersInfoW Unimplemented action: 59 (SPI_SETSTICKYKEYS)
002d:fixme:system:SystemParametersInfoW Unimplemented action: 53 (SPI_SETTOGGLEKEYS)
002d:fixme:system:SystemParametersInfoW Unimplemented action: 51 (SPI_SETFILTERKEYS)
info:  Presenter: Actual swap chain properties:
  Format:       VK_FORMAT_B8G8R8A8_UNORM
  Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
  Buffer size:  1920x1080
  Image count:  3
```

[Here's the full log from the terminal.
](https://pastebin.com/PGkqzuW3)

Taking out `SteamGameId="219990" \` doesn't seem to change anything either.

**Comment by blutigJK** [comment]
I thought maybe this could be an issue due to the newest version of Grim Internals, so I was looking to download some of the older versions of GI to test, but it seems the author deleted all the older versions from his MEGA.
So if anyone has an older version I can try or perhaps help me figure out how to get the newest version (1.784 - May 17, 2019) to work, I'd be very grateful!

**Comment by beaverusiv** [comment]
@blutigJK http://www.mediafire.com/file/ub1m9364649g2s5/GrimInternals1.77_%28x64%29.zip

**Comment by kisak-valve** [comment]
Hello @blutigJK, @beaverusiv, your comments were removed due to the request and link of copyrighted content. This is legally problematic.

**Comment by SherrifsNear** [comment]
blutigJK, did you ever solve this problem?  I am having the same issue.  GrimInternals64.exe runs no problem, but it isn't actually enabled in-game.

**Comment by blutigJK** [comment]
@SherrifsNear Unfortunately not. Older versions also straight up don't work as they need older versions of the game to work. I'm currently waiting for the Steam Summer sale myself to buy the DLCs before I pick up Grim Dawn again as the two builds I want to play with require the DLC classes. Hopefully someone can chime in by then with a potential fix or I eventually figure it out.

**Comment by SherrifsNear** [comment]
OK, I got it working tonight.  For me, I had to make sure GrimInternals64.exe and GrimInternalsDll64.exe were located directly in my Grim Dawn folder.  Having them in the x64 folder simply would not work.

**Comment by lucifertdark** [comment]
I copied what AndyHoang & SherrifsNear posted & it's working for me too, thanks guys. :D

**Comment by scottc** [comment]
Thanks @SherrifsNear for fix.

**Comment by GloriousEggroll** [comment]
Hi all, for those using Grim Internals, feel free to try my proton build. It has detection for grim internals and will ask you if you'd like to run it before running the game, and will run it ootb without hassle.

https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/4.11-GE-1

*Also, I recommend copying the Grim Internals files into just the game's main folder. 

Grim Internals launches the 64 bit version of the game regardless of which folder it's in, so there is no point in using the Play Grim Dawn (x64) option that steam gives.

If you wish to use Grim Internals and have both options work, you will need to copy the Grim Internals files to both the game's main folder and the x64 folder. 
![griminternals0](https://user-images.githubusercontent.com/11287837/59990698-6e3aed00-9601-11e9-83d5-9faf82f2e704.png)

![griminternals](https://user-images.githubusercontent.com/11287837/59990610-fb317680-9600-11e9-97b1-e1355bfac4b1.png)

![griminternals1](https://user-images.githubusercontent.com/11287837/59990742-988caa80-9601-11e9-934b-a9ad67f8a62a.png)

**Comment by cryzed** [comment]
I run this on Arch Linux using Steam with the latest Proton. I have a recent Intel i7-7770k CPU and a NVIDIA GTX 1060. Outside of fights, even with graphical settings all maxed, the game runs at a stable 60 FPS -- in most cases even during the fights. However as soon as I use the Demolitionist's skill "Blackwater Cocktail" and hit a group of enemies, the frames drop to around 1 FPS for several seconds initially. This keeps happening and doesn't get better.

Just to test, I also set the lowest graphical settings possible and tried again: even there the game freezes up for several seconds. This is specifically happening in the Sewers during the early-game mission for Barnaby. Anyone else had this experience?

**Comment by cryzed** [comment]
I found the issue: it was the sound SFX. After muting it, the stutters disappeared entirely when using the skill. I suspect this happened in combination with my specific Pulseaudio configuration (`/etc/pulse/daemon.conf`) which had some non-standard high-quality values:

```
resample-method = soxr-vhq
flat-volumes = no
default-sample-format = s24le
default-sample-rate = 192000
alternate-sample-rate = 192000
```

I assume this caused Pulseaudio to have to resample a bunch of sound effects that all occurred at once during an explosion, causing the game to stutter. When I revert this configuration to its much less demanding defaults, the stutters are gone even with the sound SFX slider enabled.

What's strange is that even setting the `resample-method` to `speex-float-1`, to my understanding a very cheap resampler, doesn't fix the issue -- so I suspect it has something to do with the target sample format. Anyways, my workaround for now will be to change these settings before playing -- however, maybe it's worth looking at how these sound effects are forwarded to Pulseaudio, maybe there's a way to optimize this: but I am not well-versed in audio at all.

**Comment by cryzed** [comment]
I did some more experiments and simply setting: `default-sample-rate` and `alternate-sample-rate` to their defaults was enough.

**Comment by AndyHoang** [comment]
Not sure how its ended up, but to use GrimInternals on proton, I have to use GloriousEggroll custom proton build, the old way from @scottc make the game constantly crash (try latest griminternals and proton (4.11.8). Hope someone can double check with me
Normal grimdawn worked like usual (v 4.1.5.1)

**Comment by ruvaldak** [comment]
Heavy microstuttering/stuttering when using Linux 5.4rc7 kernel on Manjaro. Switching back to 5.3 solves most of the stuttering, though changing anything including proton version seems to bring it back until a reboot. May just be my machine though.

**Comment by jazztickets** [comment]
So the game has an in-game clock that you can click or hover over to see the real world time (the button is right above your character level). However, the time is being displayed in UTC instead of localtime. The hardware clock in BIOS is set to UTC (as it should be), and the timezone is correct in linux as shown by timedatectl. The timezone in regedit is also correct (HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\TimeZoneInformation)

Anyone else experiencing this?

**Comment by lucifertdark** [comment]
Just checked & everything is the same for me in the way of settings but I'm getting the correct time on the in-game clock.

**Comment by shoober420** [comment]
# Whitelist Request
- Name of the game to be whitelisted: Grim Dawn
- Steam AppID of the game: https://steamdb.info/app/219990/

## System Information
- GPU: GTX 760
- Driver/LLVM version: NVIDIA 440.44
- Distro version: Arch
- https://github.com/shoober420/linux-scripts/blob/main/home/shoober420/sysinfonvidia
- Proton version: 4.11-12

Works great out of the box using the x64 exe!

**Comment by ziabice** [comment]
Tested the game with Proton 5.0-2 and 5.0-3, it seems to works well (I haven't played too much).

Important: when started, the game has long loading times during which it shows only a black screen. Don't be fooled like me believing it crashed, it (maybe) is just compiling shaders.

Launched the game selecting "Play Grim Dawn" from the menu that appears when you press the "Play" button into the Steam Client game library.

My specs:
GPU: AMD RX 580 4GB
Driver: Mesa 19.3.4
Distro: Manjaro
CPU: Ryzen 2600, 16GB RAM

**Comment by wfstuff** [comment]
# Whitelist Request
- Name of the game to be whitelisted: Grim Dawn
- Steam AppID of the game: 219990

## System Information
- GPU: GTX 960
- Driver/LLVM version: nvidia 418.56
- Distro version: Ubuntu 19.04
- Link to full system information report as [Gist]: https://gist.github.com/wfstuff/3d17c51305709a46c984e1e348714a95
- Proton version: 4.11-13

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [ ] that no workarounds other than PROTON_* env variables are necessary.

## Issues
- [x] I haven't experienced any issues.
- [ ] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are remaining issues:

**Comment by wfstuff** [comment]
P.S. I played about 65 hours through the whole base game. I did almost all quests I found and explored all areas I found. Had no problems at all. (I had installed all expansions, but did not play the expansions, yet.)

**Comment by kisak-valve** [comment]
Hello, is anyone seeing an issue with this game and Proton 4.11 that would block it from being whitelisted?

**Comment by garpu** [comment]
For what it's worth, I've been playing it on the 5.0 tree, and it's just fine.  I didn't have a problem with 4.11 when I was using it.

**Comment by wfstuff** [comment]
After updating to 5.x I had the feeling that some mouse clicks did not register when moving. After downgrading to 4.11 it did not occur. Not really sure about it though, could also be the area I was in or just clicking on the wrong area etc.
Checking on protondb.com it seems at least another person had the same problem, quote: "I would click somewhere and sometimes it wouldn't register. Was annoying, but not gamebreaking."

I'm still playing on 4.11 (because it just works) and almost finished the Malmouth expansion. Still no problems at all. Not a single crash or glitch in over 80h of play time.
The only minor issue I have with the game is that sometimes square areas of the map are revealed. But it seems to be a general game bug:
https://steamcommunity.com/app/219990/discussions/0/405693392915991830/
https://steamcommunity.com/app/219990/discussions/0/1483232961039531181/

**Comment by ziabice** [comment]
@wfstuff  I played nearly 5 hours last weekend using Proton 5.0-4 and everything worked perfectly, never had the feeling that mouse clicks were not registered.

**Comment by jazztickets** [comment]
When proton 5.0 was first released, I experienced the same mouse problems as @wfstuff. 5.0-3 fixed it for me. Tested on Arch with rx570, using a 1000hz polling rate.

**Comment by greydmiyu** [comment]
> Hello, is anyone seeing an issue with this game and Proton 4.11 that would block it from being whitelisted?

I have not checked recently, but AFAIK the above only applies to the 64-bit client.  The 32-bit version of the game had several issues which were surmised to be triggered by Crate's anti-piracy code.  I believe the 32-bit version is still the default.

So, 64-bit version I've had no problems and I've finished the base game, Ashes of Malmouth and half of Forgotten Gods.  32-bit as of a few months ago, game breaking issues.

**Comment by wfstuff** [comment]
I have played the 32-bit (default) Version without problems. Finished the base game and Ashes of Malmouth without problems.

**Comment by kisak-valve** [comment]
Grim Dawn with no launcher yields VR error

Issue transferred from https://github.com/ValveSoftware/Proton/issues/3696.
@alex-gunning posted on 2020-03-28T12:06:35:

Whilst trying to run Grim Dawn through Steam with ProtonDB, I'm coming across the following error

```
Unable to read VR Path Registry from C:\users\\steamuser\\Local Settings\\Application Data\\openvr\\openvrpaths.vrpath
terminate called after throwing an instance of 'dxvk::DxvkError'
```
Not sure why it's asking for VR paths.

Running with `PROTON_USE_WINED3D=1 %command%` the game runs fine.

**Comment by kisak-valve** [comment]
Hello @alex-gunning, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by alex-gunning** [comment]
Hi @kisak-valve 

Sure thing. Thanks for being active :)

https://gist.github.com/alex-gunning/237be15ab1a63a7bd2481b21f09f91b1

**Comment by kisak-valve** [comment]
Looks like your Hainan chipset is part of AMD's Southern Island (SI) generation. By default the linux kernel uses the `radeon` kernel module with this video card generation, which is also incompatible with vulkan.

Please give https://github.com/ValveSoftware/Proton/wiki/For-AMD-users-having-issues-with-non-OpenGL-games a read.

**Comment by alex-gunning** [comment]
@kisak-valve 

Aah, thank you. Yes. I did not know that. 

Some follow up: I installed the AMDGPU driver and the game starts up fine with no launch parameters but performance is poor. Reverting to my old launch parameters `PROTON_USE_WINED3D=1 %command%` yielded pretty much the same results as without them.

I reverted to the old Radeon driver without Vulcan support (with launch parameters) and performance is much better.

So the radeon driver seems to outperform the AMDGPU driver in this case - weird.

Thanks for the input.

**Comment by wfstuff** [comment]
Another update:
- I finished the whole game (including expansions) and have done almost all quests I could find and explored all areas I could find. Having played played about 100 hours (although a lot of this time a was reading lore texts) I only had 2 crashes. Those 2 crashes were both in Forgotten Gods content but most likely bad luck. From my end I still think it could be whitelisted - at least the Single Player
- One minor issue (but probaly relevant to proton overall): I just recognized about 100h in: When bringing up the steam overlay, the game still seems to react mouse clicks and the character moves.
- Now we come to the Multiplayer. The last days I was playing with some friends and we were 4 players. We had a lot of lag issues and often crashed. But that also happend to the Windows guys. One of them already clocks about 2000 hours and only experienced one crash or so. So it seems the Multiplayer issues are issues of the game and not proton issues. Though it might be worth to add though.

**Comment by Inveli** [comment]
I just tried to play the game on current Steam Version (Proton 7.0-2), as well as GE version 7-15, and I'm having a horrible audio balancing issue. The ambient noises and sound effects are extremely loud, so much it hurts my ears. It also seems the audio settings don't really work, they are all or nothing. If they are set completely to the left they are muted, but even one pixel to the right and it seems to go to the maximum volume for those sounds. Everything else in the game works correctly, and I'm not having this audio issue with any other game. I'm running on Manjaro Linux with KDE, and I'm using some USB headphones for audio.

**Comment by Inveli** [comment]
I found out what the issue was and a solution, so I'd like to share in case anyone else has the issue.

For my headphones I have the profile in my audio options set to "Analog Surround 7.1 Output + Mono Input). This is because I have headphones have a 7.1 surround sound mode. This work well for every other game I've tried, but it seems it causes an issue with Grim Dawn. If I change to simply "Analog Stereo Output + Mono Input" the sound level goes back to normal, like I am used to from my old Windows Desktop. Not sure why that is an issue only in this game.

**Comment by johnpicasso** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/466#issuecomment-483628753

Anyone trying to get Grim Internals working on Steamdeck? This works to get GI launched, but I can't get any controller support working to actually play the game.

EDIT: To add some details here, I'm launching GI in Steam via non-Steam Game shortcut as outlined in that post. Some of the things I've tried:

- With the default/suggested controller layout and a customized one
- Launching in "normal" steam deck mode (instead of Desktop mode)
- Enabling Generic Controller Support as well as Xbox controller support (separately)
- Ticking (and un-ticking) the "Enable Non-Steam Gamepad" in game.

The only actions I can perform in-game are using the touch screen to move the cursor over menu items, and then clicking the right track pad to send a click. 

Base Grim Dawn (without GI) otherwise works correctly on SteamDeck and I also play with a controller regularly on my Windows PC so I'm at a loss for how to fix this.

EDIT 2: Solved by installing GEProton (7-32) and launching GI and GD in GEProton compatibility mode.

**Comment by ruineka** [comment]
Hosting a lan session causes serious lag for the host when playing this with Proton experimental. The client players and single player don't experience this lag. 

It can even freese the host for up to 15 seconds and then run at 2-10fps for a majority of the time after.

This is on the Steam Deck btw.

**Comment by kisak-valve** [comment]
Can't gather game logs.

Issue transferred from https://github.com/ValveSoftware/steam-for-linux/issues/10100.
@jakubby2 posted on 2023-09-30T12:42:45:

#### Your system information

* Steam client version (build number or date): 169019606
* Distribution (e.g. Ubuntu): Debian Testing
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: AMD

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Game launch options:
``DXVK_ASYNC=1 gamescope -w 1280 -h 720 -F fsr --sharpness 0 %command% &>~/log.log``
``DXVK_ASYNC=1 %command% &>~/log.log``

#### Steps for reproducing this issue:

1. Launch grim dawn with Proton 6/7, also tried non-valve affiliated Proton-GE.
2. The game crashes, want to investigate/provide logs of what happend.
3. Log file is 0Bytes.
4. Launch gamescope --prefer-output --help &> ~/log.log in terminal.
5. Stdout/stderr log gets logged. 

How can I redirect/find logs now?

**Comment by kisak-valve** [comment]
Hello @jakubby2, you're more likely to generate a log worth pondering by adding [`PROTON_LOG=1`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options, which tells Proton to log itself to $HOME/steam-$APPID.log.

**Comment by ghost** [comment]
Alright, I was trying to figure out/gather bug report logs.
Original proton fails to start the game past the main menu screen.
And proton-GE sometimes fails to start the game at all.

**Comment by Logge1002** [comment]
Have a problem with the game micro stuttering. Any way to fix it? Deckyloader is currently bugged on preview channel. So can't reduce cores atm.

**Comment by holyfight6** [comment]
My game stutters terribly during combats with sfx enabled. It is solved by reduce sfx volume to 0. Any way to fix it?
Edit: I tried proton-ge and it fixed the issue

**Comment by garpu** [comment]
Apparently today's hotfix breaks Grim Dawn, saying that it must be run through Steam. It seems to largely affect linux/proton users, although there are some reports of Windows users encountering it as well: https://steamcommunity.com/app/219990/discussions/0/583929583674458934/

As noted in the thread that Glorious Eggroll's 11-03 is a workaround. (And I can verify that this does enable the game to start.) 

I'm on Slackware current, plasma 6.7, wayland, system profile: https://gist.github.com/garpu/b9de146ec53d60fb0cfb5b1066c67f50 

But there are reports from people on all distros not being able to launch grim dawn. The Grim Dawn devs say that they don't support Linux, but this doesn't seem isolated to linux/proton/SteamOS.

**Comment by alasky17** [comment]
Thank you for the report! This is fixed on Proton Experimental bleeding-edge (beta branch) and it will be fixed in the next Proton version updates (should be within the next 24h).

**Comment by garpu** [comment]
Awesome! I tried Grim Dawn hotfix 3 with Proton Hotfix from today, and it worked as expected, thanks! (No need for the 'legacy' mode they added with 1.3.0.3)
