### ISSUE TITLE
Splitgate (677620)

### ISSUE THREAD

**Issue by Dryadxon** [ValveSoftware/Proton#4736]
# Compatibility Report
- Name of the game with compatibility issues: Splitgate ~: Arena Warfare~
- Steam AppID of the game: 677620

## System Information
- GPU: AMD Vega 8 (iGPU of Ryzen 7 4800u)
- Driver/LLVM version: Mesa 20.3.5/LLVM 11.0.0
- Kernel version: 5.11.11-200.fc33.x86_64
- Link to full system information report as Gist: [link](https://gist.github.com/Dryadxon/526ac6fb449113cca697cd051bedaa3e)
- Proton version: 5.13, 5.13-Experimental, 6.3-1

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Here there are two logs using `PROTON_LOG=1 %command%` as game's launch options:
- [less-stutters.log.zip](https://github.com/ValveSoftware/Proton/files/6253751/less-stutters.log.zip)
- [more-stutter.log.zip](https://github.com/ValveSoftware/Proton/files/6253752/more-stutter.log.zip)

## Symptoms 
This game has always worked correctly with Steam Proton, however the latest versions cause severe stutter in online matches.
If you try the “Training” and “Race” modes the problem does not arise, so I think it is not related to the weak hardware.
Also, up to Proton 5.0-10 the game does not have this issue.

## Reproduction
Install the game and play online matches, even with bots, using either Proton 5.13-x or 6.3-1.

**Comment by Dryadxon** [comment]
- Another regression: the game crashes on login with the latest version of Proton Experimental.
- Small improvement: the game stutters a little less often with Proton 6.3-2, but it's still very difficult to play online. Here a log [steam-677620.zip](https://github.com/ValveSoftware/Proton/files/6401515/steam-677620.zip) and an updated [system information](https://gist.github.com/Dryadxon/c0d95d04841ec8048967720c7f8cb7fd) file.

Also, looking at [ProtonDB](https://www.protondb.com/app/677620) some players have trouble logging in, a workaround is to create a file called "steam_appid.txt" with just the APPID number inside, which is "677620"
The file must be placed in the "_STEAM LIBRARY DIRECTORY_/steamapps/common/Splitgate Arena Warfare/PortalWars/Binaries/Win64" directory.

**Comment by kisak-valve** [comment]
Hello @Dryadxon, can you also share a Proton log of the crash with Proton Experimental?

**Comment by Dryadxon** [comment]
Sorry if I forgot to send it, I created a new one right now: [steam-677620.zip](https://github.com/ValveSoftware/Proton/files/6408257/steam-677620.zip)
The game freeze on login, after a while the system says the process is unresponsive and kills it.

**Comment by Dryadxon** [comment]
There is a new issue with the latest Proton Experimental, an assertion failed when the game starts:
![Schermata da 2021-06-03 15-42-15](https://user-images.githubusercontent.com/81884588/120656379-18b91d00-c473-11eb-8725-de9b10cc132f.png)
[New system information](https://gist.github.com/Dryadxon/1ba30f084a6c711e9d6ba8d43da3c5a2) after checking for upgrades.
And a new log file [CET-2021-06-03-677620.zip](https://github.com/ValveSoftware/Proton/files/6592094/CET-2021-06-03-677620.zip).

I've tried the following to fix it:
- Delete the directory "677620" in "~/.local/share/Steam/steamapps/compatdata"
- Reinstalling the game
- Reinstalling Steam (and deleting both "\~/.steam" and "\~/.local/share/Steam" for a clean reinstallation)

What I didn't try (yet):
- Reinstalling Fedora 34 (seams a bit extreme, and I doubt this will solve the issue)

The user doesn't need to install anything other than their (i)GPU drivers to get this version of Proton Experimental to work, right?
Or do I need to install Wine or other dependencies that aren't shipped with Steam?

**Comment by kisak-valve** [comment]
Tracking note: Marking the last comment as resolved because it should be fixed in Proton Experimental. If you're still seeing an issue with winegstreamer in Proton Experimental, then please add a new note for the Proton devs to ponder.

**Comment by Dryadxon** [comment]
Everything has been fixed with the latest update, now there are no regressions or issues with the game, even with low-end devices. Thanks for your amazing work!

**Comment by user1-github** [comment]
According to [this](https://www.reddit.com/r/linux_gaming/comments/nx37yb/splitgate_got_a_bugfix_in_valves_proton_the/?sort=confidence) reddit post, some still have an issue with the game tutorial freezeing. I think it's worth taking a look at that issue.

**Comment by Dryadxon** [comment]
Proton Experimental (1623850434 experimental-6.3-20210616) broke compatibility again - the game silently crashes on startup, nothing is displayed on the screen.
Reinstalling the game or Steam didn't help, even deleting any leftovers from the previous installation.
[steam-677620.log](https://github.com/ValveSoftware/Proton/files/6664399/steam-677620.log)

**Comment by Dryadxon** [comment]
> Everything has been fixed with the latest update, now there are no regressions or issues with the game, even with low-end devices. Thanks for your amazing work!

As before the 6.3-20210616 update, Proton Experimental (6.3-20210625) works perfectly and now media works too* which is awesome! Currently, the game works almost as if it were native to GNU/Linux systems.

*Sometimes errors occur in the tutorial and show placeholder videos or nothing, the last option is a bad sign as completing a tutorial with playing black videos causes the game to hangs, forcing the user to terminate its process. Since winegstream still doesn't work at its best, I wouldn't consider this a major issue at the moment, when the whole media thing is going to work in most games, it will most likely work in this one too.

**Comment by PL4y3r98** [comment]
Hello, I have problem to even start this game, currently game has native but when I luck at ProtonDB not only I have problem, that is sad because game has native, I will sent report to 1047 Game but Steam Support tell me `,,Please note that the game is not currently whitelisted''` `,,Please submit all issues or bugs occurring when using this new feature, to the Valve - Proton Github bug database''`,
With Proton experimental, proton 7.0-4, 6.3-8 and with game mode run ,,gamescope -f -W 1920 -H 1080 -r 144 -o 60 -- mangohud %command%'' I find it in commend on ProtonDB by guy report reporting that it works, I change 1920 to ,,-W 2560'' ,,-r 75'' and delete ,,mangohud''  and everything work that same:
Installing without problems but when I try run only to menu, then game has freezing in loading screen (after some 15-20 seconds), fans make high noise, screen make weird artifacts and I cant close it (and alt+tab too not work), I must hold power button to shut dawn my PC
Yet I try `,,Changed bHasRunAutoCalibration=True to bHasRunAutoCalibration=False in /home/lonnon/.config/Epic/PortalWars/Saved/Config/LinuxNoEditor/GameUserSettings.ini''`, I will tell how it works but currently I downloading this game again

**Comment by PL4y3r98** [comment]
So I don't fined it in game files so I search `GameUserSettings.ini` on disc and find but when I try to open, it was just copied... I uninstall game

**Comment by colemickens** [comment]
I have 18 games installed, but as far as I can tell, Splitgate is the only one not working for me. I'm attaching the PROTON_LOG output file from trying to launch it with current Proton Experimental.

When you hit Play, the log fills with stuff, but nothing ever appears on screen, doesn't appear to be eating CPU, and Steam continues to think its running for ... well I gave up after 5 minutes or so.

[steam-677620.log](https://github.com/ValveSoftware/Proton/files/12271082/steam-677620.log)

nixos, mesa `23.2.0-rc2`

**Comment by Naitrate** [comment]
So I recently tried running Splitgate with 6.3-8, and I noticed that attempting to have the game in focus causes it to rapidly flash black, and there's a crash handler window that appears alongside my system becoming slow when I'm alt-tabbing.

**Comment by sleepingroxas** [comment]
I noticed that it doesn't even seem to use Native by default anymore:
```
wine: using kernel write watches, use_kernel_writewatch 1.
. . .
/home/USERNAME/.local/share/Steam/steamapps/common/Splitgate/PortalWars.exe: 1: /home/USERNAME/.local/share/Steam/steamapps/common/Splitgate/PortalWars.exe: MZ������: not found
/home/USERNAME/.local/share/Steam/steamapps/common/Splitgate/PortalWars.exe: 1: /home/USERNAME/.local/share/Steam/steamapps/common/Splitgate/PortalWars.exe: Syntax error: word unexpected (expecting ")")
```
It forces Proton and tries to launch a Windows executable...
After checking the game folder, it seems the native Linux binary doesn't exist anymore either.
I've never published a game to Steam before, so I don't know if what happened was that the update got pushed to both branches or if Linux support was removed and it automatically switched to the Windows build when the last update came out.
Either way, Proton shouldn't be crashing on launch, and this particular error is pretty strange.

**Comment by simifor** [comment]
@sleepingroxas it's working fine on my end. Just in case, have you specifically set the game to use proton? Games that previously had native versions might mess things up. If the game is still crashing after manually setting a proton version (9,10 and experimental all worked for me, at least for launching), then add this to the game's launch parameters `PROTON_LOG=1 %command%`, launch the game again and upload the resulting `steam-677620.log` that will appear in your home folder.
