### ISSUE TITLE
F1 2021 (1134570)

### ISSUE THREAD

**Issue by AbnocChinwads** [ValveSoftware/Proton#4966]
# Compatibility Report
- Name of the game with compatibility issues: F1 2021
- Steam AppID of the game: 1134570

## System Information
- GPU: RX 5700 XT
- Driver/LLVM version: Mesa 21.2.0-devel (git-9d225c4 2021-07-13 focal-oibaf-ppa)
- Kernel version: 4.6
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/AbnocChinwads/efbe2d15da13e20922df97ac08682669
- Proton version: 6.3-5

## I confirm:
- [ X] that I haven't found an existing compatibility report for this game.
- [ X] that I have checked whether there are updates for my system available.

[steam-1134570.log](https://github.com/ValveSoftware/Proton/files/6807907/steam-1134570.log)

## Symptoms 
It begins to open and then immediately shuts down. It's a brand new game I didn't expect it to run straight away, I just want to help people who don't buy the deluxe edition and have to wait until 16th to play it.

## Reproduction
Install the game, run it. I added PROTON_USE_SECCOMP=1 %command% to the launch options as that works for F1 2020, but it doesn't seem to help 2021 launch

**Comment by kisak-valve** [comment]
Hello @AbnocChinwads, your log hints that there might a D3D12 / VKD3D-Proton related issue going on with this game.

**Comment by AbnocChinwads** [comment]
Hello @kisak-valve I'm glad it could help in some way, is there anything I could try to help narrow down the issue?

**Comment by davidjmemmett** [comment]
Same as above, except I also get a "DirectX 12 is incompatible with this version of Windows" alert: [
![Screenshot from 2021-07-20 19-10-15](https://user-images.githubusercontent.com/213197/126374213-0077b3ca-dd56-4cae-98ab-aabf1ea46456.png)
](url)

**Comment by Arsconyl** [comment]
## System Information
- GPU: RX 5700 XT
- Driver/LLVM version: Mesa 21.3.0-devel (git-2138d1b9e6) build with LLVM 12.0.1
- Kernel version: 5.13.1-178-tkg-pds
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/SmileEdge/e439c10a5a09e326220f11e1066791ca
- Proton version: 6.3-5

[steam-1134570.log](https://github.com/ValveSoftware/Proton/files/6880338/steam-1134570.log)

## Symptoms

Black fullscreen then closes.

## Reproduction

Install the game and run it. (Just with `PROTON_LOG=1 %command%`)

I have a similar setup as OP but maybe it can help.

**Comment by davidjmemmett** [comment]
I got further using Proton Experimental and passing `-force-d3d11` as launch options, this starts to play an introduction video and then crashes.

**Comment by davidjmemmett** [comment]
Ignoring my last comment - I upgraded `vkd3d-proton` and got slightly further, latest failure in attached log:

```
20568.822:010c:01ac:trace:seh:raise (22)
Assertion failed: std::find(succ.begin(), succ.end(), to_next) == succ.end(), file ../src-vkd3d-proton/subprojects/dxil-spirv/node.cpp, line 354
```
[steam-1134570.log](https://github.com/ValveSoftware/Proton/files/6910481/steam-1134570.log)

**Comment by der-eismann** [comment]
Just chiming in with the same problem. Hopefully it gets fixed soon, I was getting used to playing F1 2020 on Linux.

## System Information
- GPU: Radeon VII
- Driver/LLVM version: Mesa 21.1.7 / LLVM 12.0.1
- Kernel version: 5.13.9
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/der-eismann/074f66080e6f556ea25689bff5f652c3
- Proton version: proton-6.3-6

[steam-1134570.log](https://github.com/ValveSoftware/Proton/files/7031117/steam-1134570.log) (Proton 6.3)
[steam-1134570.log](https://github.com/ValveSoftware/Proton/files/7031135/steam-1134570.log) (Proton experimental)


## Symptoms 

Black fullscreen then closes.

**Comment by nizos** [comment]
@HansKristian-Work Can you have a look at this? Thanks. :)

**Comment by davidjmemmett** [comment]
I have verified the fix from @HansKristian-Work in [dxil-spirv](https://github.com/HansKristian-Work/dxil-spirv/issues/78) fixes the crash. Now the game runs until the main menu, where I reliably experience a full system lock-up and have to REISUB.

**Comment by nizos** [comment]
> I have verified the fix from @HansKristian-Work in [dxil-spirv](https://github.com/HansKristian-Work/dxil-spirv/issues/78) fixes the crash. Now the game runs until the main menu, where I reliably experience a full system lock-up and have to REISUB.

Do you have any new logs you can share?

**Comment by davidjmemmett** [comment]
Yup, please find attached:
[steam-1134570.log](https://github.com/ValveSoftware/Proton/files/7040478/steam-1134570.log)

**Comment by Raboebie** [comment]
Interesting that you note that @davidjmemmett. I can navigate the menu just fine using this fix. The game did crash upon trying the benchmark or a track.

**Comment by nizos** [comment]
> Interesting that you note that @davidjmemmett. I can navigate the menu just fine using this fix. The game did crash upon trying the benchmark or a track.

Interesting, I feel optimistic enough to get the game now. Do you have any logs you can share? How do I apply the mentioned fix? I will post my logs once I have tried it.

**Comment by Raboebie** [comment]
Yup, here you go![
[steam-1134570.log](https://github.com/ValveSoftware/Proton/files/7041049/steam-1134570.log)

I can navigate the menu, sounds works, changing graphics settings work. Mapping my controller works. I tried running a benchmark on Silverstone in this example log.

Using proton experimental here.

**Comment by davidjmemmett** [comment]
@nizos you'll have to do it yourself for now - go into vk3d-proton/subprojects/dxil-spirv, pull the latest from `master`, build, set up F1 2021 to run from your own build (in Properties -> Compatibility -> Force the use of a specific Steam Play compatibility tool). Also, don't forget to set Launch Options to `PROTON_LOG=1 %command%`.

**Comment by Raboebie** [comment]
I have done a bunch of additional tests. All tests crash with the same result. As soon as a track is loaded it crashes.

1. Changed proton version and updated to latest vkd3d with the same result.
2. Used external versions of proton like GE with the same result.
3. Changed various graphics settings to see if that might be causing the issue.
4. Changed resolutions, windowed, fullscreen etc.
5. Adjusted audio settings in-game

The showroom works correctly when choosing a car. It's all rendered correctly and I'm able to connect to online services and view multiplayer lobbies.

Attached is my latest log with vkd3d tracing enabled with Proton experimental.
[steam-1134570.log](https://github.com/ValveSoftware/Proton/files/7060709/steam-1134570.log)

DXGI log if useful:
[F1_2021_dx12_dxgi.log](https://github.com/ValveSoftware/Proton/files/7060721/F1_2021_dx12_dxgi.log)

**Comment by Raboebie** [comment]
Another update.

I updated vkd3d to the latest git and now I have some mixed results.

1. Game no longer crashes at the loading screen but instead loads forever when using an F1 car and any track
2. Game loads correctly when using an F2 car in the rain in France.

As soon as I select a dry track it crashes the display driver, so this could be a amdgpu issue or vkd3d. 

I actually did quite a few laps with an F2 car in the wet around Paul Ricard without any issues. No stutter on missing textures.

Latest log: 
[steam-1134570.log](https://github.com/ValveSoftware/Proton/files/7105131/steam-1134570.log)

`warn:select_vk_format: Failed to find Vulkan swapchain format for DXGI_FORMAT_R8G8B8A8_UNORM.`

**Comment by Raboebie** [comment]
Update 2

The game now works for the most part. I managed to complete the benchmark with acceptable performance and loaded up a few track and car combos and they all worked fine except for one occurrence where the display driver crashed but I haven't been able to reproduce that.

On to the next issue for me then!

My wheel is not detected as it was in F1 2020. Nothing shows up to configure it at all. Perhaps someone else can test as well just in case the problem is on my side? Launching 2020 confirms the wheel still works so the game must be detecting it differently.

I built vkd3d from the latest git master again this morning and this allowed me to run the game. The game seems to work fine
with proton 6.3.x and up.

Am I allowed to share the build dll's for others that don't have a build environment?

**Comment by davidjmemmett** [comment]
There's nothing stopping you, however, it is at others' risk if they use any binaries that you distribute.

**Comment by Raboebie** [comment]
> There's nothing stopping you, however, it is at others' risk if they use any binaries that you distribute.

Naturally thanks! 

@nizos I see you are following the thread like a hawk. Interested in doing some testing? I can share the built libs with you if you can update us on your findings perhaps?

**Comment by nizos** [comment]
> > There's nothing stopping you, however, it is at others' risk if they use any binaries that you distribute.
> 
> Naturally thanks! 
> 
> @nizos I see you are following the thread like a hawk. Interested in doing some testing? I can share the built libs with you if you can update us on your findings perhaps? 

I'm in! I'll just get the game and start downloading it now. I also have a steering wheel that I can use to test the input issue that you mentioned.

**Comment by der-eismann** [comment]
I'd be in as well, I just didn't want to build it myself. Got an AMD graphics card w/ G29 steering wheel and Xbox controller.

**Comment by Raboebie** [comment]
Perfect, thanks. Any suggestions on what platform we can use to collaborate so we don't flood this thread?

**Comment by WantedFreak** [comment]
Hi I would also be interested in testing if needed. I have a Nvidia gpu and g920 wheel

**Comment by Raboebie** [comment]
Cool, I think discord would work nicely. Join here then we can all discuss over there and post our findings here:

https://discord.gg/7eQY5BVj

**Comment by nizos** [comment]
> Perfect, thanks. Any suggestions on what platform we can use to collaborate so we don't flood this thread?

We can move to Discord, but we can also stay here to keep the information accessible to others.

**Comment by davidjmemmett** [comment]
I got as far as loading a track, then it crashed. Though this time "ego dumper" caught the fault and allowed the game to exit without me having to force a REISUB. Log attached.
[steam-1134570.log](https://github.com/ValveSoftware/Proton/files/7121501/steam-1134570.log)

**Comment by Raboebie** [comment]
Thanks David. I actually just did a bunch of laps on various laps and really does run very well for me now. Even my wheel works now. I have no idea what I did but after a reboot it just worked.

For me, the game crashes on the first load of a track for whatever reason. If I go again it works just fine. Played about an hour or breaking point now without issues.

The only notable problem is some flashing of shadows here and there.

**Comment by Raboebie** [comment]
> I got as far as loading a track, then it crashed. Though this time "ego dumper" caught the fault and allowed the game to exit without me having to force a REISUB. Log attached.
> [steam-1134570.log](https://github.com/ValveSoftware/Proton/files/7121501/steam-1134570.log)

Just noting, when I used the stock amd drivers I also had ego dumper pop up. Perhaps update to the latest git version if you don't already have that. Not sure if you have green or red power you machine.

**Comment by Raboebie** [comment]
Update 3

I can reliably launch the game and play breaking point, no issues on that front. 

I also found a way to reliably crash the game. Launch game, select time trial with any car and select Canada as the track. Game loads and flashes the F1 into skip then the screen goes blank and display driver crashes. I've only managed to get this result in time trial so not really sure how loading time trial is different from other game modes.

In any case, see my latest log attached. This was the run that crashes. Notable log entries are

`warn:seh:dispatch_exception EXCEPTION_WINE_NAME_THREAD exception (code=406d1388) raised`
`err:ntdll:RtlpWaitForCriticalSection section 0000000425003178 "?" wait timed out in thread 0184, blocked by 0188, retrying (60 sec)`

[steam-1134570.log](https://github.com/ValveSoftware/Proton/files/7126444/steam-1134570.log)

**Comment by Raboebie** [comment]
Update 4

Based on some discussion I had with a few people on Discord I think I can safely say the game is now playable for AMD users running the latest git drivers. The game still crashes for Nvidia users after loading a track. So this must be related to the Nvidia drivers in some way.

**Comment by LorenzKa** [comment]
Any update on this?

**Comment by dmolin93** [comment]
### System Information
GPU: NVIDIA GeForce GTX 1070
Driver: NVIDIA 470.63.01
Kernel version: 5.10.70-1-MANJARO
Link to full system information report as Gist: https://gist.github.com/dmolin93/f52b35b2d5115e3218551577c1092b6c
Proton version: Proton-6.20-GE-1

[steam-1134570.log](https://github.com/ValveSoftware/Proton/files/7419354/steam-1134570.log)

Tested both Proton Experimental and Proton-6.20-GE-1.
Main menu loads fine, when trying to load into the track the game just hangs after a seconds and I have to kill the process.

Tested with "PROTON_HIDE_NVIDIA_GPU=1 %command%" and then it won't even load the main menu.

**Comment by smt923** [comment]
unrelated to most of the issues here but I just want to note that proton experimental lets me launch the game, but my wheel (T150 via [scarburato/t150_driver](https://github.com/scarburato/t150_driver)) isn't detected at all, using 6.20-GE-1 actually detects the wheel, but has no ffb - is adding in ffb support something planned for future proton versions? for me on AMD it's very close to working 'as it should', the ffb is really the last thing (and of course fixes for the nvidia users)

**Comment by ReazerDev** [comment]
> unrelated to most of the issues here but I just want to note that proton experimental lets me launch the game, but my wheel (T150 via [scarburato/t150_driver](https://github.com/scarburato/t150_driver)) isn't detected at all, using 6.20-GE-1 actually detects the wheel, but has no ffb - is adding in ffb support something planned for future proton versions? for me on AMD it's very close to working 'as it should', the ffb is really the last thing (and of course fixes for the nvidia users)

You'd need to install hid-tminit for FFB support. There's a GitHub page for it.

The current kernel module for Thrustmaster devices doesn't support FFB

**Comment by ReazerDev** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/4966#issuecomment-952046091

What about F2? It works for me.

Oh and btw. the Problems are probably not related to Proton but the Nvidia Driver

**Comment by smt923** [comment]
> You'd need to install hid-tminit for FFB support. There's a GitHub page for it.
> 
> The current kernel module for Thrustmaster devices doesn't support FFB

the t150 driver I mentioned in my comment uses tminit, I have FFB in other games, it's specific to f1 2021 for whatever reason

**Comment by ReazerDev** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/4966#issuecomment-952148426

Oh yeah, I must've missed that you are using another driver :)

It's weird that it's not working in F1 2021. I haven't used my Wheel with F1 2021 yet, I'll try later to see if FFB works on my T300rs and comment wether or not it works.

**Comment by ReazerDev** [comment]
@Raboebie Do you think that this could be causing the issues on nvidia graphics cards?

`1332.428:0118:0418:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.`

**Comment by Raboebie** [comment]
@ReazerDev No this is not something to worry about. NTLM is not required for most software to function. I have the same log message when I boot the game and it runs just fine :)

**Comment by klllr** [comment]
Has anyone found a way to deal with flashing shadows? @Raboebie seems like you've had a similar issue

For me, the only way to successfully launch the game was to select Proton 6.3-7 instead of Experimental. Otherwise it would either hang on "connection to online services" loading screen, crash on car selection in Time Trial, or just endlessly load any selected track.
I'm using Artix Linux / RX 5700XT / Proton 6.3-7 / mesa 21.2.4-1.

@ReazerDev if you're on an Arch-based system, try to install `samba`, it contains ntlm_auth. On Debian-based systems you need to, as per instruction, install (or reinstall) `winbind`. Though I would agree with @Raboebie, most applications that produced this error on my system, weren't really affected by it.

**Comment by Hydranet** [comment]
I recently stared having the following problem, whenever I continue my career, then it autosaves before loading the track then my graphics card hangs and then resets. I can delete delete my career and start a new one and then it works for one Grand Prix and when I try to continue then the same thing happens. I bought the game 29-10-2021 and it was working fine then, mesa hasn't been update since then. I tried downgrading to Mesa 21.1.x ,  downgrading Xorg to  1.20.x and downgrading the previous kernel which I was running when the game was working. It happens with all Proton version(Stable, Experimental and GE). The strange thing is when I play a Solo game I am able to load the track and just play as normal, the hanging of the gpu causing it then to reset only happens when I continue my career when it autosaves before it loads the track. I'm not having any issues when loading my career when playing F1 2021.

GPU: RX 6700 XT
Mesa: 21.2.5
Kernel version: 5.15.5
Proton: Stable/Experimental/GE

I'm getting the idea it's because of a recent game update but I can't be sure.  I ran the game with the following launch options for creating some log files for debugging information: PROTON_LOG=1 RADV_DEBUG=hang, I attached those files here.
[radv_dumps.tar.gz](https://github.com/ValveSoftware/Proton/files/7613840/radv_dumps.tar.gz)
[steam-1134570.log](https://github.com/ValveSoftware/Proton/files/7613841/steam-1134570.log)

**Comment by ReazerDev** [comment]
@Raboebie Hi, do you happen to know, how I can disable the NvAPI workaround in Proton?
Or maybe link me to a cheatsheet for the available proton launch arguments, if you have one? I can't find any

**Comment by kisak-valve** [comment]
Hello @ReazerDev, sounds like you're looking for https://github.com/ValveSoftware/Proton#runtime-config-options.

**Comment by dmolin93** [comment]
According to protondb people have started to get it to work on Nvidia cards, but I'm still facing issues.
https://www.protondb.com/app/1134570

GPU: NVIDIA GeForce GTX 1070
Driver: NVIDIA 495.46
Kernel version: 5.15.7-1-MANJARO
Proton: 6.21-GE-2/6.3-8/6-20-GE-1/Experimental
System info: https://gist.github.com/dmolin93/413a680c1f6c38f8b213f420175571df

[steam-1134570.log](https://github.com/ValveSoftware/Proton/files/7713716/steam-1134570.log)

F2 2020 Time trial works, trying to run F1 2021 time trial/grand prix hangs on loading.

Any ideas what to try next?
It do seem like those who got it working on protondb have 2070s or newer cards, so maybe I'm just out of luck unless I upgrade?

**Comment by lehleh** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/4966#issuecomment-981107226

Can confirm this, same GPU as well, also happens to Braking Point EP12.
[System Info](https://gist.github.com/lehleh/245a6af46a87b041f724675c8c61da63)


[relevant journalctl](https://github.com/ValveSoftware/Proton/files/7784497/f1crash.log)

Likely vkd3d/-proton or f1 dx12 issue

**Comment by hakzsam** [comment]
It seems RADV_DEBUG=nohiz "fixes" the shadows flickering. I will look into a fix.

**Comment by hakzsam** [comment]
Just pushed a workaround for RADV https://gitlab.freedesktop.org/mesa/mesa/-/commit/90994e4db7000951be058a956813e4a828f862c9

**Comment by kisak-valve** [comment]
F1 2021 Missing FFB Proton7.0

Issue transferred from https://github.com/ValveSoftware/Proton/issues/5582.
@hodasemi posted on 2022-02-16T19:14:02:

# Compatibility Report
- Name of the game with compatibility issues: F1 2021
- Steam AppID of the game: 1134570

## System Information
- GPU: RTX 2060
- Driver/LLVM version: nvidia 510.47
- Kernel version: 5.15
- Link to full system information: https://gist.github.com/hodasemi/2b886b2a48722d1646608d9d6908466f
- Proton version: 7.0-1

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms
Using Proton 6.3-8 force feedback works as intended with F1 2021, changing to Proton 7.0-1 it doesn't work at all. I'm using Thrustmaster T300.

## Reproduction
Force specific Proton version to 7.0-1. Start the game and go into a race (or time trial). The wheel has no force feedback.

**Comment by rbernon** [comment]
Hi @hodasemi,

I don't have the device to try with, so it would be very helpful if you could run the game with `PROTON_LOG=1 WINEDEBUG=+timestamp,+pid,+tid,+seh,+unwind,+loaddll,+dinput,+xinput,+hid,+plugplay %command%` set in the game launch options, and attach the resulting steam-1134570.log file there. Both with Proton 7.0 and 6.3 if you can (or 7.0 only at least), copying the file between each run, as it gets overwritten.

Thanks!

**Comment by hodasemi** [comment]
Hi,

here they are:
[steam-1134570_Proton6.3.zip](https://github.com/ValveSoftware/Proton/files/8087888/steam-1134570_Proton6.3.zip)
[steam-1134570_Proton7.0.zip](https://github.com/ValveSoftware/Proton/files/8087889/steam-1134570_Proton7.0.zip)

I had to compress them, otherwise the upload didn't work.

**Comment by rbernon** [comment]
That's fine, thanks!

**Comment by rbernon** [comment]
@hodasemi I have pushed some changes to Proton Experimental "bleeding-edge" beta branch, would you mind trying if it solves your force feedback issues? You can select the branch in Proton Experimental properties, under the Betas tab. Please note that this branch is only meant for testing purposes and should not be used by default, we do not do any QA on it and it may break any time.

**Comment by hodasemi** [comment]
Sadly, force feedback is still missing using the bleeding-edge branch.

**Comment by rbernon** [comment]
Thanks for testing, though I'm dumb and I found the reason it probably didn't change anything. I pushed another fix to bleeding edge and it should hopefully be better now.

**Comment by hodasemi** [comment]
I believe for the short moment I could drive, there was actually some feedback. But now, throttle and break are both at 100% input all the time. Rebinding keys and recalibration didn't work. The throttle axis was recognized, but the input was 100% no matter what. The break pedal was completely unrecognized, when trying to bind it.

**Comment by rbernon** [comment]
Thanks for testing it, this is actually something we kind of expected could happen with the fix, I'll try to find something better.

**Comment by rbernon** [comment]
I pushed another version of the fix, would you mind checking if it's better?

**Comment by hodasemi** [comment]
Hi, everything does seem to work again. Thanks for your effort.

**Comment by rbernon** [comment]
Awesome, thanks for your patience and testing! I'll make sure this ships in next proper Experimental release.

**Comment by alasky17** [comment]
@hodasemi rbernon's fixes were shipped in experimental-7.0-20220225, so you should be able to leave the bleeding-edge branch and still have the regresssion fixed :)

**Comment by davidjmemmett** [comment]
Has anyone managed to get this working yet? I've just tried Experimental (+ Bleeding Edge) & 7.0, but it still crashes when loading the race.

[steam-1134570.log](https://github.com/ValveSoftware/Proton/files/8154105/steam-1134570.log)

**Comment by hodasemi** [comment]
The game does run perfectly fine on my RX 470. On my RTX 2060 the game still crashes on full wet conditions.

**Comment by kisak-valve** [comment]
Tracking note: Dropping mesa/radv labels because the driver workaround mentioned above has been in mesa since 21.3.4.

**Comment by tphaster** [comment]
I've tried yesterday running it using the newest stable Proton, Experimental and newest GE-Proton on the current Ubuntu 20.04 LTS with GTX 1060 6GB - the game starts fine, but crashes with EXCEPTION_ACCESS_VIOLATION when loading any F1 race/time trial. This happens on both 470 and 510 Nvidia drivers. Surprisingly I managed to run F2 time trial and it worked fine, until the end screen where it crashed as previously.

Seems that's the same issue as in https://github.com/ValveSoftware/Proton/issues/4966#issuecomment-1054324149 or https://github.com/ValveSoftware/Proton/issues/4966#issuecomment-993831279 .

**Comment by ReazerDev** [comment]
Hi, so the game used to run perfectly for me until it recently started to memory leak pretty badly.
It takes up ~2 GB every second until I run out of RAM and the game crashes.
Also, all of my CPU cores go up to ~90%.

I tried it with multiple Proto versions and the same happens every time. I also tried to use `-force-d3d11`, but it still happens.

GPU: RX 6900 XT
CPU: Ryzen 7 2700
Driver: mesa 22.0.0-1
Kernel: 5.16.16-arch1-1

[steam-1134570.log](https://github.com/ValveSoftware/Proton/files/8383538/steam-1134570.log)

**Comment by kisak-valve** [comment]
Hello @ReazerDev, `info:    Driver: 2.0.216` in your Proton log hints that the game is running with AMDVLK or AMDGPU-Pro. Please test how it behaves with mesa/RADV.

**Comment by ReazerDev** [comment]
@kisak-valve I don't even have any proprietary driver installed.
Is there a way I can force the use of mesa? I couldn't find anything in the proton config options

**Comment by ReazerDev** [comment]
Thank you so much, I figured it out. For some reason I was missing the `vulkan-radeon` package and I only had `radeon_icd.i686.json` on my system. Installing the package and disabling `amd_icd64.json` (renaming it to `amd_icd64.json.disabled`) fixed the problem!

**Comment by NikPoliakov** [comment]
2080 Ti
Driver 510.60.02
The game freezes (On loading screen) on full wet conditions. This can be reliably reproduced by going to benchmark mode and selecting a wet track. If you wait long enough the window will close itself and pop out the EGO bug reporting tool.

System:
OS: Fedora Linux 35 (Workstation Edition)
KERNEL: 5.16.17-201.fsync.fc35.x86_64
CPU: AMD Ryzen 7 3700X 8-Core
GPU: NVIDIA GeForce RTX 2080 Ti
GPU DRIVER: NVIDIA 510.60.02
RAM: 32 GB

**Comment by ReazerDev** [comment]
Hi, @rbernon do you happen to have a link to the commit for your FFB fixes from the 22nd and 23rd of February?
Or do you know what exactly you changed? FFB is not working for me in Proton 7, but in previous versions and I'm trying to investigate what the cause is :)

Thanks in advance!

**Comment by rbernon** [comment]
The fixes aren't in Proton 7 yet, and they're a bit spread out into several commits as multiple things needed to be fixed. You should maybe try with Proton Experimental.

**Comment by davidjmemmett** [comment]
> Has anyone managed to get this working yet? I've just tried Experimental (+ Bleeding Edge) & 7.0, but it still crashes when loading the race.
> 
> [steam-1134570.log](https://github.com/ValveSoftware/Proton/files/8154105/steam-1134570.log)

I can confirm that upgrading graphics card from GTX1060 to RTX3060 allows the game to run.

**Comment by Nandru86** [comment]
> > Has anyone managed to get this working yet? I've just tried Experimental (+ Bleeding Edge) & 7.0, but it still crashes when loading the race.
> > [steam-1134570.log](https://github.com/ValveSoftware/Proton/files/8154105/steam-1134570.log)
> 
> I can confirm that upgrading graphics card from GTX1060 to RTX3060 allows the game to run.

Same drivers/kernel/proton version?

**Comment by davidjmemmett** [comment]
That is correct, tested before and after replacing my card.

Beforehand the game hung in the loading screen and made my entire machine unresponsive until the “EGO dumper” appeared. After replacing the card with its modern counterpart I’ve not had any issues whatsoever.

Maybe it’s worth noting that my old card had 6GB graphics memory compared to 12GB on the newer card?

Cheers,
David

**Comment by CataDev0** [comment]
I am currently crashing in a wet weather race. Hoping there will be a fix soon.

The race is in Portugal, I'm on the last lap, and I always crash near the 150m mark on the pit straight.

System:
OS: openSUSE Tumbleweed
KERNEL: 5.17.3-1-default
CPU: AMD Ryzen 7 5800X 8-Core
GPU: AMD Radeon RX 6700 XT (navy_flounder, LLVM 14.0.0, DRM 3.44, 5.17.3-1-default)
GPU DRIVER: 4.6 Mesa 22.0.1
RAM: 16 GB

**Comment by opale95** [comment]
It always crash when i start a Solo GP in Azerbaijan in Wet Conditions (when it rains). Does not crash in the Qualifications but when the Race starts. 

Depending on the Proton version i try or my kernel version, it will either just crash and i have to kill the game process, or will make the whole system crash and reboot.

Tested Proton versions: from Proton6.3 to Experimental

journactl output:
```
avril 26 21:02:30 antoine-fixe kernel: amdgpu 0000:0a:00.0: amdgpu: [gfxhub0] no-retry page fault (src_id:0 ring:221 vmid:6 pasid:32769, for process Xorg pid 814 thread Xorg:cs0 pid 853)
avril 26 21:02:30 antoine-fixe kernel: amdgpu 0000:0a:00.0: amdgpu:   in page starting at address 0x0000800000029000 from IH client 0x1b (UTCL2)
avril 26 21:02:30 antoine-fixe kernel: amdgpu 0000:0a:00.0: amdgpu: VM_L2_PROTECTION_FAULT_STATUS:0x006009BA
avril 26 21:02:30 antoine-fixe kernel: amdgpu 0000:0a:00.0: amdgpu:          Faulty UTCL2 client ID: CPF (0x4)
avril 26 21:02:30 antoine-fixe kernel: amdgpu 0000:0a:00.0: amdgpu:          MORE_FAULTS: 0x0
avril 26 21:02:30 antoine-fixe kernel: amdgpu 0000:0a:00.0: amdgpu:          WALKER_ERROR: 0x5
avril 26 21:02:30 antoine-fixe kernel: amdgpu 0000:0a:00.0: amdgpu:          PERMISSION_FAULTS: 0xb
avril 26 21:02:30 antoine-fixe kernel: amdgpu 0000:0a:00.0: amdgpu:          MAPPING_ERROR: 0x1
avril 26 21:02:30 antoine-fixe kernel: amdgpu 0000:0a:00.0: amdgpu:          RW: 0x0
avril 26 21:02:30 antoine-fixe kernel: amdgpu 0000:0a:00.0: amdgpu: [gfxhub0] no-retry page fault (src_id:0 ring:221 vmid:7 pasid:0, for process  pid 0 thread  pid 0)
avril 26 21:02:30 antoine-fixe kernel: amdgpu 0000:0a:00.0: amdgpu:   in page starting at address 0x0000800105394000 from IH client 0x1b (UTCL2)
avril 26 21:02:30 antoine-fixe kernel: amdgpu 0000:0a:00.0: amdgpu: VM_L2_PROTECTION_FAULT_STATUS:0x007009BA
avril 26 21:02:30 antoine-fixe kernel: amdgpu 0000:0a:00.0: amdgpu:          Faulty UTCL2 client ID: CPF (0x4)
avril 26 21:02:30 antoine-fixe kernel: amdgpu 0000:0a:00.0: amdgpu:          MORE_FAULTS: 0x0
avril 26 21:02:30 antoine-fixe kernel: amdgpu 0000:0a:00.0: amdgpu:          WALKER_ERROR: 0x5
avril 26 21:02:30 antoine-fixe kernel: amdgpu 0000:0a:00.0: amdgpu:          PERMISSION_FAULTS: 0xb
avril 26 21:02:30 antoine-fixe kernel: amdgpu 0000:0a:00.0: amdgpu:          MAPPING_ERROR: 0x1
avril 26 21:02:30 antoine-fixe kernel: amdgpu 0000:0a:00.0: amdgpu:          RW: 0x0
avril 26 21:02:30 antoine-fixe kernel: umip_printk: 7 callbacks suppressed
avril 26 21:02:30 antoine-fixe kernel: umip: F1_2021_dx12.ex[20004] ip:14e8ec3c4 sp:2ff7fbc0: SGDT instruction cannot be used by applications.
avril 26 21:02:30 antoine-fixe kernel: umip: F1_2021_dx12.ex[20004] ip:14e8ec3c4 sp:2ff7fbc0: For now, expensive software emulation returns the result.
```

System:
```
OS: Manjaro Linux x86_64
Kernel: 5.17.1-3-MANJARO
DE: Xfce 4.16
WM: i3
CPU: AMD Ryzen 5 3600 (12) @ 3.600GHz
GPU: AMD ATI Radeon RX Vega 56/64
Memory: 2948MiB / 15968MiB
```

**Comment by Nandru86** [comment]
Oh, ok. I ihave an 1660 super with 6gb as well, I guess some sort of memory leak or missreport is the issue.

I could try mangohud to see if it report memory usage

------- Original message -------
> From: David JM Emmett ***@***.***>
> To: ***@***.***
> Cc: ***@***.***, ***@***.***
> Sent: 25.4.'22,  2:24
> 
> That is correct, tested before and after replacing my card.
> 
> Beforehand the game hung in the loading screen and made my entire machine unresponsive until the “EGO dumper” appeared. After replacing the card with its modern counterpart I've not had any issues whatsoever.
> 
> Maybe it's worth noting that my old card had 6GB graphics memory compared to 12GB on the newer card?
> 
> Cheers,
> David
>

**Comment by kisak-valve** [comment]
F1 2021 license verification pop-up window issue

Issue transferred from https://github.com/ValveSoftware/Proton/issues/6746.
@shinjitumala posted on 2023-05-06T01:07:59:

# Compatibility Report
- Name of the game with compatibility issues: F1 2021
- Steam AppID of the game: 1134570

## System Information
- GPU: NVIDIA GeForce RTX 3080
- Driver/LLVM version: Nvidia 530.41.03
- Kernel version: 6.3.1-arch1-1
- Proton version: Proton 8.0-2

## I confirm:
- [x] that I have checked whether there are updates for my system available.
- [x] that I haven't found an existing compatibility report for this game.

## Symptoms 
The game is unable to reach the license server, so it is asking me to manually enter some activation code.
However, none of the buttons on the pop up menu are properly rendered, preventing me from activating and playing the game.

## Reproduction
Attempt to start the game after a fresh install. I assume the license servers  are currently down (probably for good).
