### ISSUE TITLE
The Great Ace Attorney Chronicles (1158850)

### ISSUE THREAD

**Issue by Cyborger** [ValveSoftware/Proton#5016]
# Compatibility Report
- Name of the game with compatibility issues: The Great Ace Attorney Chronicles
- Steam AppID of the game: 1158850

## System Information
- GPU: NVIDIA GeForce GTX 1660 SUPER
- Driver/LLVM version: nvidia 470.57.02
- Kernel version: 5.13.4-arch2-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Cyborger/bf111afaae7c981edcc2eb0e1bf83757
- Proton version: Experimental / 4.11 / 5.0

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1158850.zip](https://github.com/ValveSoftware/Proton/files/6884921/steam-1158850.zip)

## Symptoms 

Multiple in-game videos are not playing. Freezing the game to a black screen in certain cases.

## Reproduction

From the main menu: 
1. "Select Adventure"
2. "New Game"
3. Game freezes to a black screen, requiring a restart

Alternatively, still from the main menu (requires the [The Great Ace Attorney Chronicles - Additional Art & Music from the Vaults](https://store.steampowered.com/app/1487540/The_Great_Ace_Attorney_Chronicles__Additional_Art__Music_from_the_Vaults/) DLC):
1. "Special Contents"
2. "Gallery"
3. "Moving Pictures"
4. Select any
5. The video won't play but the player is still able to exit the screen by pressing the pause button

**Comment by gwemmie** [comment]
Experiencing the same issue on AMD graphics (R9 Fury) w/ radeon ICD loaded.

**Comment by FM1337** [comment]
Experiencing the same issue with the RTX 2060.

**Comment by ghost** [comment]
```
2109.439:0038:0075:fixme:wmvcore:WMSyncReader_OpenStream (0x375bbbd0)->(0x28e34980): stub!
2109.439:0038:0075:fixme:wmvcore:WMSyncReader_GetOutputCount (0x375bbbd0)->(0x361afd18): stub!
```
It seems to be the same problem with the Resident Evil franchise (before 7), installing wmp11 would probably work around that.

**Comment by FM1337** [comment]
> ```
> 2109.439:0038:0075:fixme:wmvcore:WMSyncReader_OpenStream (0x375bbbd0)->(0x28e34980): stub!
> 2109.439:0038:0075:fixme:wmvcore:WMSyncReader_GetOutputCount (0x375bbbd0)->(0x361afd18): stub!
> ```
> 
> It seems to be the same problem with the Resident Evil franchise (before 7), installing wmp11 would probably work around that.

I tried installing it (wmp11) using protontricks (not sure if that was the right approach) it resulted in the game not starting at all. And it also broke my proton and caused a huge memory leak to the point where I had to reinstall proton and wipe out my wine configuration to fix games not launching at all after it.

**Comment by 4n0nct** [comment]
(integrated intel gpu)
CPU usage 100%, graphical glitch, memory leak, the only way to free memory is not only to quit the game, it's TO KILL the terminal which was used for launching the game. And while in game memory use will grow up, never stopping, until it freeze everything.
Here the graphical glitch which keeps me to play the game, it's embarrassing:

![image](https://user-images.githubusercontent.com/50212348/130648931-a8361895-ae6f-4fb2-9919-6f3015103cd3.png)

![image](https://user-images.githubusercontent.com/50212348/130648871-05b2da92-b289-4986-be70-c6dfa849ec3a.png)

![image](https://user-images.githubusercontent.com/50212348/130684230-a721dee8-727d-4523-8365-35786cfeda23.png)

**Comment by XRaTiX** [comment]
In case anyone is interested,in reddit someone post a solution for the videos,now the videos works
`<Link removed by moderator>`

**Comment by kisak-valve** [comment]
Hello @XRaTiX, the workaround you linked is legally problematic and has been removed.

**Comment by kisak-valve** [comment]
The Great Ace Attorney Chronicles 

Issue transferred from https://github.com/ValveSoftware/Proton/issues/5226.
@ioletsgo posted on 2021-10-17T06:15:33:

When running The Great Ace Attorney Chronicles with Proton, the entire system crashes.

When running it through Wine, i get this error message.
[backtrace.txt](https://github.com/ValveSoftware/Proton/files/7358913/backtrace.txt)

**Comment by MininuxDev** [comment]
On Intel UHD Graphics 620 I also have the graphical glitch that makes characters disappear. I tried disabling dxvk but it didn't help

**Comment by aldelaro5** [comment]
Hey it seems the video now plays properly as of proton 7.0-1 was it fixed in the same way p4g was?

Not only it seems the video cutscenes works perfectly on my end without issues (I can get to the game afterwards no problem), but I also seen someone making it work on the steam deck with vanilla proton 7.

Really curious since no one seems to have publicly shared this with proton 7.

**Comment by ArclightMat** [comment]
It seems to have been fixed by re-encoding the video and sending it as shader data. It seems to be working out OK for the main cutscenes but the additional videos (AKA the ones under "Moving Pictures" don't have sound here). This leaves the main game fully playable at least.

**Comment by strawberrycupid** [comment]
still having this issue even with Proton 7.0-3 and using PROTON_USE_WINED3D=1 %command% as a launch command. Also having the model issue 4nonct showed. my pc was able to run it just fine back when it had windows so i don't think it's a specs issue

**Comment by Martchus** [comment]
I've tested it with experimental Proton which fixes the video. However, on my system with Intel HD graphics (Haswell) the 3d models don't work similarly to what 4nonct showed. Since I have dual boot I tested it on Windows where it works without issues.

I've also tested on a PC with NVIDIA card and the proprietary driver. There everything works just fine under Proton. So maybe these issues are rather caused by the Intel driver (since Proton generally seems to work)?

By the way, this test outcome (Intel/Proton vs. Intel/Windows vs. NVIDIA/Proton) is actually the same for Disco Elysium. (There I never get passed the main menu in the negative Intel/Proton case.) Maybe using Intel graphics is just not the best idea on Linux for newer games.

**Comment by kisak-valve** [comment]
Hello @Martchus, it should be noted that the Vulkan drivers for the Haswell generation does not provide a spec-compliant implementation and rendering artifacts and/or crashes are expected regardless of the game. That said, this particular render artifact was noted with a newer Intel generation and it might be worthwhile to mention it to your video driver vendor.

**Comment by Martchus** [comment]
> it should be noted that the Vulkan drivers for the Haswell generation does not provide a spec-compliant implementation

I know. Mesa never relents telling me that (via https://gitlab.freedesktop.org/mesa/mesa/-/blob/242c7a651308f43d5f6f2590717fd72f44eba3ca/src/intel/vulkan/anv_device.c#L769-771). Therefore I'm pretty sure my driver vendor already knows :-)

And yes, considering https://github.com/ValveSoftware/Proton/issues/5016#issuecomment-1005008056= newer Intel generations seem not be much better off.

(And to be fair, I also get graphical glitches on that Haswell Intel GPU on Windows in certain games. It is just not made for gaming and Proton cannot fix that. With "simple" games like Ace Attorney one might just hopes it works nevertheless.)

**Comment by 4n0nct** [comment]
I can confirm about intel haswell (yes it was what I used in the pic), I've played it on my other computer which has a nvidia gtx970, and this glitch wasn't there anymore. And even if it worked finally fine, it was eating all cpu and gpu power, the game has poor optimization and poor compatibility. So it's a render/shader thing (I don't know exactly) that isn't supported on intel (maybe it is on the newest gen). Nothing to do to fix that, older intels gens have been forgotten by most of devs who don't don't make shmups or iso/2d games...

**Comment by kj** [comment]
I'm also missing character textures with Iris Plus 640 (Core i5 7260U). Sits around 70 to 75% CPU though, which seems okay.

**Comment by AlleyDismay** [comment]
Testing with the various "Force Use of a specific Steam Play Compatibility Tool", and 7.0-5 seems work for me, videos play and characters are more than just eyes, while Experimental gets:

> ERR03 : Failed to initialize DirectX11. err : 0x000000cb

**Comment by kisak-valve** [comment]
Hello @AlleyDismay, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by AlleyDismay** [comment]
> Hello @AlleyDismay, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

Like, in this comment?

https://gist.github.com/AlleyDismay/37f37f8613267d042d38cbbac09f2098

**Comment by kisak-valve** [comment]
Thanks, `"driver-version" : "Mesa 21.2.6"` is the detail I wanted to ponder. The build of DXVK in Proton Experimental requires mesa 22.0 or newer, which isn't new enough and led to the DirectX initialization failure.

**Comment by AlleyDismay** [comment]
> Thanks, `"driver-version" : "Mesa 21.2.6"` is the detail I wanted to ponder. The build of DXVK in Proton Experimental requires mesa 22.0 or newer, which isn't new enough and led to the DirectX initialization failure.

Yep, followed https://itsfoss.com/install-mesa-ubuntu/ and it fixed it.

**Comment by cartoonnerie** [comment]
If I should post somewhere else tell me I am not very sure.
I also have the characters showing just eyes
My system is Ubuntu **23.04**. 
I launch the game with **proton 8** installed through Steam. 
The graphic card is **Intel Mesa Intel(R) HD Graphics 5500 (BDW GT2)** with the driver **Mesa 23.0.2**.

If I should give any more information tell me, I am not sure what would be useful.

**Edit** : same problem with proton 7 and proton experimental

**Comment by cartoonnerie** [comment]
I activated logs and the lines that seem relevant are
```log
14719.716:0128:0194:err:ole:com_get_class_object apartment not initialised
14719.716:0104:0114:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
```
those lines are repeated a huge number of times, most of the log is this

and [here](https://gist.github.com/cartoonnerie/ead2c299952f40bb6a51c741d7e48218) is a gist extract for the `fixme` lines

**Comment by cartoonnerie** [comment]
Tried newer mesa  23.1.2 and Proton release candidate 8.0-3 without anything changed

**Comment by cartoonnerie** [comment]
Sorry to just up:
is there any more useful information I could bring to the discussion? And/or is there any ongoing or incoming work that could help with my issue?

**Comment by eagleflo** [comment]
I have a reliable crash to desktop when trying to access any bonus video content from main menu -> Special Contents -> Gallery -> Moving Pictures, similar to original reporter.

This happens both on my gaming desktop (Nvidia) and Steam Deck, two widely different system configurations.

Somehow related to `xaudio2_7`? Codec trouble?

[steam-1158850.zip](https://github.com/ValveSoftware/Proton/files/13403466/steam-1158850.zip)

**Comment by kisak-valve** [comment]
Hello @eagleflo, skimming through your Proton log, these might be some lines of interest:
`17561.142:012c:027c:warn:debugstr:OutputDebugStringA "SimpList: non-growable list ran out of room for new elements"`
This is almost immediately followed by
`17561.143:012c:027c:warn:seh:dispatch_exception EXCEPTION_BREAKPOINT exception (code=80000003) raised`.
The breakpoint wasn't handled by the game
`wine: Unhandled exception 0x80000003 in thread 27c at address 00000000385EB72C (thread 027c), starting debugger...`
and the game falls over there.

There's also an extreme amount of `err:ole:com_get_class_object apartment not initialised` in the log.
```
grep "err:ole:com_get_class_object apartment not initialised" steam-1158850.log | wc -l
839060
```

**Comment by eagleflo** [comment]
Another attempt where I did `tail -f` on the accumulating logfile while clicking through the menus. That `apartment not initialised` spam starts right away when the game boots and is quite excessive as you noted, but possibly restricted to just menus (I had a successful 40 minute play session in the game proper with Steam Deck).

Ignoring those lines, the salient bits start right after clicking on the first video in the gallery. It looks like some additional DLLs are being loaded and the game starts to play a WMV file. It actually successfully plays the first ~8 seconds or so before crashing.

What might be notable is that these first seconds were completely silent, and it's only right before where audio would begin where the game crashes. (It looks like the actual WMV files are stored under the game files, `$STEAM_HOME/steamapps/common/TGAAC/nativeDX11x64/movie/MP/SP_Court.wmv` in this instance.)

```
3877.158:0134:0290:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\msdmo.dll" at 0000000218320000: builtin
3877.158:0134:0290:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\winegstreamer.dll" at 000000039B8D0000: builtin
3877.335:0134:0290:fixme:wmvcore:reader_SetOutputSetting Ignoring EnableDiscreteOutput setting.
3877.335:0134:0290:fixme:wmvcore:reader_SetOutputSetting Ignoring SpeakerConfig setting.
3877.335:0134:0290:fixme:wmvcore:reader_SetOutputSetting Ignoring VideoSampleDurations setting.
3877.686:0110:0120:fixme:oleacc:find_class_data unhandled window class: L"#32769"
3877.686:0110:0120:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
3877.686:0110:0120:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
3877.688:0110:0120:fixme:uiautomation:uia_element_GetCurrentPropertyValueEx Default property values currently unimplemented
3877.688:0110:0120:fixme:uiautomation:uia_element_GetCurrentPropertyValueEx Default property values currently unimplemented
3877.688:0110:0120:fixme:uiautomation:msaa_provider_GetPatternProvider Unimplemented patternId 10002
3877.688:0110:0120:fixme:uiautomation:nc_provider_GetPatternProvider 00000000008FB460, 10002, 0000000001B2EC90: stub
3877.688:0110:0120:fixme:uiautomation:base_hwnd_provider_GetPatternProvider 00000000008FB3D0, 10002, 0000000001B2EC90: stub
3888.176:0134:0290:warn:debugstr:OutputDebugStringA "SimpList: non-growable list ran out of room for new elements"
3888.176:0134:0290:trace:seh:dispatch_exception code=40010006 flags=0 addr=000000007B00CD97 ip=7b00cd97
3888.176:0134:0290:trace:seh:dispatch_exception  info[0]=000000000000003d
3888.176:0134:0290:trace:seh:dispatch_exception  info[1]=00000000388e19c8
3888.176:0134:0290:warn:seh:dispatch_exception "SimpList: non-growable list ran out of room for new elements"
```

and then some additional lines about the exception:

```
3888.177:0134:0290:warn:seh:dispatch_exception EXCEPTION_BREAKPOINT exception (code=80000003) raised
3888.177:0134:0290:trace:seh:dispatch_exception  rax=0000000000000000 rbx=0000000038a1d4d8 rcx=00000000c0000034 rdx=0000000000000133
3888.177:0134:0290:trace:seh:dispatch_exception  rsi=000000003d32fde0 rdi=0000000000000000 rbp=000000003d32fdb0 rsp=000000003d32fd30
3888.177:0134:0290:trace:seh:dispatch_exception   r8=0000000000000002  r9=0000000170085fbc r10=0000000170085ec0 r11=0000000000000202
3888.177:0134:0290:trace:seh:dispatch_exception  r12=00000000008fe3f4 r13=0000000000000000 r14=0000000000000200 r15=0000000000000000
3888.177:0134:0290:trace:seh:call_vectored_handlers calling handler at 0000000270F7C760 code=80000003 flags=0
3888.177:0134:0290:trace:seh:call_vectored_handlers handler at 0000000270F7C760 returned 0
3888.177:0134:0290:trace:seh:call_vectored_handlers calling handler at 000000035906B320 code=80000003 flags=0
3888.177:0134:0290:trace:seh:call_vectored_handlers handler at 000000035906B320 returned 0
3888.177:0134:0290:trace:seh:call_vectored_handlers calling handler at 00000002EDF1C050 code=80000003 flags=0
3888.177:0134:0290:trace:seh:call_vectored_handlers handler at 00000002EDF1C050 returned 0
3888.177:0134:0290:warn:seh:virtual_unwind backtrace: 00000000388EB72C: L"XAudio2_7.dll" + 000000000002B72C.
```

Edit: I've now confirmed this is related to Windows Media Foundation being used as the codec for these files. Switching to GE-Proton8-24 made the crash go away, but sound would still not work -- so I researched a bit, found a fix and submitted it to https://github.com/GloriousEggroll/protonfixes/pull/156.

If all goes well this will start working out of the box for Proton-GE soon -- and hopefully one day for everyone as Proton improves its transcoding capability and / or Wine improves its WMA implementation.

(While investigating, I made cleaned up crash logs with `GST_DEBUG=4` for [Proton 8.0-4](https://gist.githubusercontent.com/eagleflo/9e6fd99acef586b3c68e2e1005cec8a5/raw/3e15a8d08a3131989542fcff52a49d4c17535033/proton-8.0.4.log) and [Proton Experimental 8.0-2023114c](https://gist.githubusercontent.com/eagleflo/9e6fd99acef586b3c68e2e1005cec8a5/raw/3e15a8d08a3131989542fcff52a49d4c17535033/proton-experimental-8.0-20231114c.log).)

**Comment by matte-schwartz** [comment]
Immediately after the first animated intro video for Episode 3 - The Adventure of the Runaway Room, there is a second video that is not transcoded properly on Steam Deck despite Steam Deck Verified status:

![Image](https://github.com/user-attachments/assets/010a0a60-6d78-4ebe-b931-b9b82ac6fce2)

I tested this on two separate devices, a Steam Deck and an MSI Claw 8 (Intel Lunar Lake) and both have the same issue. You can reproduce the issue by launching the game -> press any key -> select adventure -> select adventure again -> scroll to episode 3 -> select Opening -> pause + skip the first video

Log from Deck: 

[steam-1158850.log.zip](https://github.com/user-attachments/files/19216596/steam-1158850.log.zip)
