### ISSUE TITLE
Sid Meier's Civilization: Beyond Earth (65980)

### ISSUE THREAD

**Issue by libcg** [ValveSoftware/Proton#5043]
# Compatibility Report
- Name of the game with compatibility issues: Sid Meyer's Civilization: Beyond Earth
- Steam AppID of the game: 65980

## System Information
- GPU: R9 Fury
- Driver/LLVM version: Mesa 21.1.5
- Kernel version: 5.13.5
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/libcg/f4cbe321c1958333a07ee683b089ecf3
- Proton version: 4.11, 5.0, 5.13, 6.3, experimental

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms
The game doesn't launch. This seems to be caused by CEG (#753).

## Reproduction
- Start the game

**Comment by Newbytee** [comment]
Game now works, but dragging around the map and research tree with the mouse doesn't work. Not a big deal for the map, but it seems to be the sole way to navigate the research tree which isn't very nice.

**Comment by Zlopez** [comment]
With the recent Proton Experimental the dragging works for both the research tree and map.

**Comment by simifor** [comment]
I noticed that the game crashes before startup in proton 8.0-4, this is a regression as the game works in 7.0-6. That said, the game works again on proton experimental, currently.

[steam-65980-proton8.log](https://github.com/ValveSoftware/Proton/files/13260608/steam-65980-proton8.log)
[steam-65980-protonexp.log](https://github.com/ValveSoftware/Proton/files/13260609/steam-65980-protonexp.log)
[steam-65980-proton7.log](https://github.com/ValveSoftware/Proton/files/13260610/steam-65980-proton7.log)

system info: https://gist.github.com/simifor/4cb5b3852884dec2519323cfb55eaeb8

**Comment by kisak-valve** [comment]
Hello @simifor, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put them in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by simifor** [comment]
For a sanity check, I booted into the stock 6.5.9 kernel and used stable mesa (23) and the behavior was the same: proton 7 worked, proton 8 crashed, proton experimental worked

**Comment by simifor** [comment]
I've done more testing, I tried a few things like lts releases for linux, multiple wipes of prefix, verifying proton 8 file, and now I have a bit more info. If you run steam from the terminal, the following will be printed when using proton 8:
`[S_API FAIL] SteamAPI_Init() failed; no appID found.
Either launch the game from Steam, or put the file steam_appid.txt containing the correct appID in your game folder.
`

If you then change proton version to 7 after creating the prefix with 8, the same error will appear again and the game won't work. But if you verify game files, 1 or 2 will fail and be reacquired and it will work with proton 7, this breakage sees to happen consistently, so it appears that proton 8 is somehow breaking things with this game. I'm seeing something similar with **dirt showdown, dirt 3, and bionic commando**.

I think this might be CEG related but I couldn't find a comprehensive list of games that use it.

**Comment by simifor** [comment]
The crash was related to the multiple audio devices bug that's fixed in experimental
Edit: the crash is also fixed in the release candidate of 8.0.5

**Comment by RedPhoenix1208** [comment]
I get a OS Crash and restart after a few minutes of playing, roughly around 15 or less on Proton 8.0-4. I’m attempting to test 8.0-5(Does Not Fix), Experimental(Fixes) and will update this post if one of them fixes it. I’m using a 64 GB Steam Deck running Stable branch Edit 1: Going into the options from the main menu crashes the game but not the OS immediately.

**Comment by simifor** [comment]
@RedPhoenix1208 could you specify what was fixed by experimental? I'm guessing just the 15 minutes crash.
I tested the options menu with proton 7, 8 and experimental on my desktop, and they all caused the game to crash.

**Comment by RedPhoenix1208** [comment]
I was wrong, I thought it was fixed, only for it to crash a few minutes later than expected. I thought I’d updated my post. Sorry.

**Comment by simifor** [comment]
@RedPhoenix1208 I'm currently 15 minutes into a new game and it hasn't crashed for me yet. Were your attempts on a new game, or maybe an existing game from windows? I ask because the longer this sort of game tends to go on, the more complex and resource intensive they tend to become as well, and that might be a factor

**Comment by RedPhoenix1208** [comment]
I haven’t tested it in the last two weeks, so they may have fixed it, but I also recently factory reset my Deck, so I will test sometime today and respond later.

**Comment by simifor** [comment]
well, I was testing with proton 8 specifically to try and get it to crash, played for 44 minutes before closing the game myself, so I wasn't able to reproduce that crash on my desktop.

**Comment by simifor** [comment]
@RedPhoenix1208 did you get around testing this already? If you haven't, I recommend adding `PROTON_LOG=1` to the start of your launch parameter for the game, this will create a steam-65980.log file in your home folder that you should upload here if it's still crashing.

You should also mention what steamos version you're using (whether it still crashes or not).

**Comment by RedPhoenix1208** [comment]
I haven’t been getting any crashes since I factory reset my Steam Deck, but I also have only played this game for a little while recently.
