### ISSUE TITLE
Enable "Automatically capture the mouse in full-screen windows" by default

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#53]
This is a setting in winecfg under Graphics. Most games require this to function properly. It should probably be checked by default.

In the mean time, this seems to work, however I'm not sure if it may break anything:

```
WINEPREFIX=~/.steam/steam/steamapps/compatdata/APPID/pfx/ winecfg
```

Perhaps a Proton winecfg would also be beneficial to this #24

**Comment by linkjay** [comment]
I agree with this. I don't see any feasible problem with this shouldn't be enabled by default.

**Comment by John-Gee** [comment]
Wouldn't this be better to ask the Wine guys?

**Comment by cjwijtmans** [comment]
Not really,. Proton should ensure to enable this. +1

**Comment by mat8913** [comment]
Looks like this has been fixed by ValveSoftware/wine@2ae5df5246290f68ccd66b4ccaa0a4067fdd178b, which is included in 59b018c19de4062d529678176583d85fea9ed7ac.

**Comment by njdattler** [comment]
> Looks like this has been fixed by [ValveSoftware/wine@2ae5df5](https://github.com/ValveSoftware/wine/commit/2ae5df5246290f68ccd66b4ccaa0a4067fdd178b), which is included in [59b018c](https://github.com/ValveSoftware/Proton/commit/59b018c19de4062d529678176583d85fea9ed7ac).

I still have this issue with the latest version of Proton on a vanilla SteamOS install. I've tried Quake 3 and DeadSpace. With both games, I have to press the mouse button before it will capture the mouse movement input. Maybe they undid this change between Sep 26, 2018 and today?

**Comment by Semperverus** [comment]
Is there a way to disable this? On KDE I have never needed this feature, and it's actually quite annoying when I have my game open on my main monitor and I have to ALT TAB just to get my mouse control back to go to a side monitor (I play most games in borderless fullscreen mode, due to multimonitor).

**Comment by bailtree** [comment]
please revert this. I have 2 monitors, and run games in windowed-fullscreen, but with this option in winecfg set means that I have to alt-tab or otherwise unfocus the window to move the cursor to my other monitor :(

**Comment by nerzhul** [comment]
i clearly agree with @bailtree , cannot we have at least a env var for it ?

**Comment by aeikum** [comment]
Can someone please list a specific game and describe the problem you are having?

**Comment by Semperverus** [comment]
> Can someone please list a specific game and describe the problem you are having?

In the following games:

* Guild Wars 2
* Warframe
* Maneater
* Phasmophobia
* Dark Souls 1 through 3
* Star Citizen
* The Sims 3
* Undertale
* NieR: Automata
* NieR: Replicant
And so on (honestly I'm being facetious: the answer is "all games, all the every games ever made")

The issue: I cannot drag my mouse off of the screen to click on things on my side monitor. This involves: messing with the game's wiki, changing the YouTube video currently playing, changing the music currently playing, responding to someone in a chat of some kind (XMPP, Discord, etc.) and general basic multitasking. This is a hugely annoying problem that you have to go digging to fix. Launching winecfg for a proton game's prefix is an adventure unto itself.

**Comment by nerzhul** [comment]
i have the issue with World of Warcraft on my side

**Comment by aeikum** [comment]
@Semperverus Thanks for the detailed info. I'll ask our QA to take a look and scope the problem and see what we can do about it.

**Comment by aeikum** [comment]
Hi everyone.  The upcoming Proton 6.3-6 release will include a revert of the commit that caused this problem. You can test it out now if you like, see #5065.

**Comment by Semperverus** [comment]
> Hi everyone. The upcoming Proton 6.3-6 release will include a revert of the commit that caused this problem. You can test it out now if you like, see #5065.

This is excellent news! Thank you very much.

While this benefits myself and many multimonitor users, is there a planned proton launch flag or env var that would allow users who want this to easily re-enable it?

**Comment by aeikum** [comment]
No. We will let them complain first to see if anyone actually wants it :) We should be replicating Windows's behavior now, which is the goal.

**Comment by Semperverus** [comment]
That makes sense. Thank you all for your effort, it is incredibly appreciated.

**Comment by aeikum** [comment]
Proton 6.3-6 is released, so this issue should be fixed. Thanks, all, for your feedback.

**Comment by AstralPhnx** [comment]
Ah so this is what's been making my life a pain as a multi monitor user.

Yes I know, bumping an old issue but undoing this has been the source of a lot of issues as a multi monitor user myself with my cursor going wandering off onto my secondary screen even when set to fullscreen. 

Turns out, cursor grabbing behaviour is extremely game dependent, some games grab my cursor better than others (EG Deep Rock Galactic can grab it just fine but HellDivers 2 completely falls over unless I enable "Automatically capture the mouse in full-screen windows"

Now I'm not saying that this change gets undone again but it would be nice to do as was suggested earlier in this issue report and put it behind an env switch that's easier to get it because as of right now if I want to switch it on I have to use protontricks to get into the specific prefix to fire up winecfg to flip one toggle and that's just kinda clunky to be honest.

If there was a command switch we could pass to the game via a launch option or something I feel that would be a lot less clunky and would be a good overall middleground to solving this once and for all.

**Comment by Sorrydough** [comment]
Can we get an environment variable? It's clear that some users want on to be default and others want off to be default. I want it on.

**Comment by mercster** [comment]
Why did this option go away?  Was it hurting anyone?  I went to do this on a game today, and the option has magically disappeared from winecfg for no good reason.  Good lord.

**Comment by ghost** [comment]
> Why did this option go away? 

It didnt. The default just reverted to off by default. The option is clearly and obviously still there.

**Comment by mercster** [comment]
> > Why did this option go away?
> 
> It didnt. The default just reverted to off by default. The option is clearly and obviously still there.

No, no it is not.  What winever are you looking at?

**Comment by mercster** [comment]
It used to be in the "Graphics" tab of `winecfg`.  It is no longer there.

![Image](https://github.com/user-attachments/assets/806d233e-9913-4a86-a983-669718d7a69c)

Old winecfg:

![Image](https://github.com/user-attachments/assets/e4585442-8c27-403f-b5db-d1df4133b3fb)
