### ISSUE TITLE
Renegade Ops (99300)

### ISSUE THREAD

**Issue by lennie420** [ValveSoftware/Proton#5550]
# Compatibility Report
- Name of the game with compatibility issues: Renegade Ops
- Steam AppID of the game: 99300

## System Information
- GPU: AMD RX 6800M
- Driver/LLVM version: Mesa 21.2.2/ LLVM 12.0.1
- Kernel version: 5.15.15
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/lennie420/5d00ac101ecc8516fc0f21a71c1d7da3
- Proton version: Experimental

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

[steam-99300.log](https://github.com/ValveSoftware/Proton/files/8014430/steam-99300.log)

## Symptoms 
Opens to black screen and nothing happens.

## Reproduction
Install game. Open game.

**Comment by Kuratius** [comment]
Installing d3dcompiler_43 and d3dcompiler_47 via protontricks seems to make it run. Note that I have not verified whether both are required for successful operation.
I was able to play through the entire campaign, except for a crash in mission 9 in the elevator, which I fixed by disabling vsync and changing from fullscreen to windowed.

**Comment by waspennator** [comment]
Game still seems to get stuck on a black screen on launch on steam deck using proton Experimental unless you use protontricks to install d3dcompiler_43 and d3dcompiler_47
[steam-99300.log](https://github.com/ValveSoftware/Proton/files/11854285/steam-99300.log)

**Comment by kisak-valve** [comment]
Hello @waspennator, these look like some lines of interest from your log:
```
err:d3dcompiler:D3DCompile2 Failed to compile shader, vkd3d result -4.
err:d3dcompiler:D3DCompile2 Shader log:
err:d3dcompiler:D3DCompile2     <anonymous>:4:1: E5000: syntax error, unexpected KW_TEXTURE2DMS
err:d3dcompiler:D3DCompile2
```

https://gitlab.winehq.org/wine/vkd3d/-/merge_requests/115 might help with that.

**Comment by Root-Core** [comment]
> https://gitlab.winehq.org/wine/vkd3d/-/merge_requests/115 might help with that.

No proton version tested works out of the box.
As this fix is merged for quite some time, I don't think it helped with this issue.

The only fix is still to install `d3dcompiler_47`. I tested it with success, even without `d3dcompiler_43`.
It runs perfectly fine on my Steam Deck.

**Comment by waspennator** [comment]
> Hello @waspennator, these look like some lines of interest from your log:
> 
> ```
> err:d3dcompiler:D3DCompile2 Failed to compile shader, vkd3d result -4.
> err:d3dcompiler:D3DCompile2 Shader log:
> err:d3dcompiler:D3DCompile2     <anonymous>:4:1: E5000: syntax error, unexpected KW_TEXTURE2DMS
> err:d3dcompiler:D3DCompile2
> ```
> 
> https://gitlab.winehq.org/wine/vkd3d/-/merge_requests/115 might help with that.

PR has been merged for quite awhile, I don't think that changed anything, still get a blackscreen like mentioned above on my oled deck using experimental unless you use the protonfix.

Should I provide another log file?

**Comment by Root-Core** [comment]
Current Proton Experimental:
```
err:d3dcompiler:D3DCompile2 Failed to compile shader, vkd3d result -4.
err:d3dcompiler:D3DCompile2 Shader log:
err:d3dcompiler:D3DCompile2     <anonymous>:6:121: W5300: Implicit truncation of vector type.
err:d3dcompiler:D3DCompile2     <anonymous>:6:225: W5300: Implicit truncation of vector type.
err:d3dcompiler:D3DCompile2     <anonymous>:6:160: W5017: Loop unrolling is not implemented.
err:d3dcompiler:D3DCompile2     <anonymous>:6:243: E5002: Expected literal sample index.
err:d3dcompiler:D3DCompile2 
```

The related bug report in Wine: https://bugs.winehq.org/show_bug.cgi?id=54973

**Comment by waspennator** [comment]
Still gets stuck with proton Experimental with wine 9.0

**Comment by ranplayer** [comment]
There is an open bug for this one on the Wine tracker: https://bugs.winehq.org/show_bug.cgi?id=54973

**Comment by Root-Core** [comment]
The issue should be fixed: https://gitlab.winehq.org/wine/vkd3d/-/commit/2034a8bab9acbf3e80d35d597d1565ade3f68077

**Comment by waspennator** [comment]
> The issue should be fixed: https://gitlab.winehq.org/wine/vkd3d/-/commit/2034a8bab9acbf3e80d35d597d1565ade3f68077

~~Is this build of vkd3d in proton yet?~~

Edit: Nevermind, accidentally thought this was merged in earlier, but it seems like it was pretty recent.

**Comment by waspennator** [comment]
Build seems to have finally hit proton Experimental and i can finally play through the game on my oled deck.

**Comment by lennie420** [comment]
I have tested a few times since @waspennator posted last comment and can confirm that the game launches and plays without issue.

**Comment by ranplayer** [comment]
I confirm this game is now playable with **Proton 10.0** without workarounds
