### ISSUE TITLE
HROT (824600)

### ISSUE THREAD

**Issue by RockafellaJaz** [ValveSoftware/Proton#5654]
# Compatibility Report
- Name of the game with compatibility issues: HROT
- Steam AppID of the game: 824600

## System Information
- GPU: GTX 970
- Driver/LLVM version: nvidia 510.54
- Kernel version: 5.15.25-1-MANJARO
- Link to full system information report as Gist: [Steam - System Information](https://gist.github.com/RockafellaJaz/14dfc667e5602e45d938fc1c2f503873)
- Proton version: 7.0-100

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[Proton-5.0-10_steam-824600.log](https://github.com/ValveSoftware/Proton/files/8193299/Proton-5.0-10_steam-824600.log)
[Proton-7.0-1_steam-824600.log](https://github.com/ValveSoftware/Proton/files/8193300/Proton-7.0-1_steam-824600.log)

## Symptoms 
Low frame rate.
Frame rate of 7-18fps when using Proton above version 5.0-10.
Frame rate of 47-55fps when using Proton 5.0-10.

## Reproduction
Run game using Proton version above 5.0-10.

## Note
Proton version 5.0-10 requires the following launch options to get sound working
`WINEDLLOVERRIDES="openal32=b" %command%`

**Comment by zzhiyi** [comment]
Fixed pushed to experimental_7.0. Will be released soon. This is caused by wine 7161dcd removing the timezone bias cache.

**Comment by RockafellaJaz** [comment]
Just tested it with the latest experimental and it seems to have fixed the issue.
I am still getting extreme frame drops when there are explosion particles on the screen but that was also happening with 5.0-10.

**Comment by terrestrian** [comment]
Don't remember exact proton version but I used to set `PROTON_USE_WINED3D=1` env variable and it had resulted in playable frame rates. It doesn't work anymore. I get around 4 fps. I've tried stable proton and experimental.

**Comment by Sterophonick** [comment]
Performance ingame gets about 5-6 FPS. Nothing I ever tried fixed it on Proton Experimental. Audio works out of the box though.

Forcing Zink does improve performance to about 10-14 FPS, but thats still not really playable.

**Comment by Sterophonick** [comment]
Re-testing with current Experimental on Plasma 6.5.3.

On XWayland the game performs horribly. You must set Zink to get better performance. On my setup I got around 58 frames per second, but that still feels low. 

Using a Wayland-patched Proton such as Proton-GE with `PROTON_ENABLE_WAYLAND=1` also greatly improves performance, but the problem is that `winewayland` is not even remotely ready for use in games and causes this game to not respond to camera movement unless you turn off Raw Input, and it also doesn't play nicely with multi-monitor setups.

**Comment by Baegus** [comment]
I published and documented a patch for this game, which improves the performance, adding ~18 FPS ingame (with no launch params). Maybe it could reveal what's being hit on Proton's side so bad:

https://github.com/Baegus/HROT-Proton-Fix
