### ISSUE TITLE
FIFA 22 (1506830)

### ISSUE THREAD

**Issue by NRG-R9T** [ValveSoftware/Proton#5673]
# Compatibility Report
- Name of the game with compatibility issues: FIFA 22 (1506830)
- Steam AppID of the game: 1506830

## System Information
- GPU: AMD RENOIR (Vega 8 / Ryzen 7 5700G)
- Driver/LLVM version: 4.6 Mesa 21.3.7 - LLVM 13.0.1
- Kernel version: 5.16.14-zen1-1-zen
- Link to full system information report: [Gist](https://gist.github.com/NRG-R9T/cf799c3927b349cd2fefc23bb86eff28)
- Proton version: proton-7.0-1b

## I confirm:
- [*] that I haven't found an existing compatibility report for this game.
- [*] that I have checked whether there are updates for my system available.

LOG-File: [steam-1506830.tar.gz](https://github.com/ValveSoftware/Proton/files/8238374/steam-1506830.tar.gz)

## Symptoms 
specific matches crash the game with a directx-error everytime, others run seamless. the error freezes the loading screen of the match and crashs the game.
Screenshot: ![Screenshot_54](https://user-images.githubusercontent.com/1843978/158033948-57893256-0262-4c79-b0ae-e01791468025.png)

## Reproduction
Start the game in FIFA Ultimate Team (FUT), go to Squad Battles or Rival, choose a match. It might work or might produce the error. The Error is always appearing in the loading screen of the match, when the opponent's team overview is displayed for about a second (if the match works).

I had those crashes in different matches all over the game modes offline or online with others. It seems random to me. I reproduced it in Ultimate Team / Squad Battles in 2 of 6 matches, always the same matches. 

![Screenshot_56](https://user-images.githubusercontent.com/1843978/161248477-0ba2cbf6-dc2a-400b-806e-a6a8f7c248e5.png)
Loading Screen

**Comment by H34dl3ss** [comment]
@NRG-R9T 
Hi, sorry for the off-topic, but would you please share some information on your overlay in the top left corner? Thanks a lot!

**Comment by Blisto91** [comment]
@H34dl3ss It's [mangohud](https://github.com/flightlessmango/MangoHud) 🙂 Hope that is enough info hehe.

**Comment by NRG-R9T** [comment]
Additionally to the absolutely annoying problem with unpredictable Game crashes, that still exists, there is also a Steam Cloud Error happening since about a week.  This is the Steam Log-File to download: https://mega.nz/file/ZEAAyTgI#b4LltDAb25VV9xnej8lQGg19dtt0EJGmGJUUpTzpTv8 (56MB is apparently too big for Github or Gist)
![Screenshot_Steam_4-Fifa22-Steamclouderror](https://user-images.githubusercontent.com/1843978/175549710-795dc92d-4d28-413d-a2dd-25b14f7e7bb8.png)

Another Problem: EA Origin does not recognise, that I bought the game and starts more often than not with a browser window to EA Origin's Platform and a prompt "Trial Version ended" and shows "Buy Game", which I click (having bought it already), then Origin recognises, that it was at fault and shows a "start game" button. All this happens inside the Launcher Window, which normaly just shows the 3 buttons to play, settings and exit.
![Screenshot_80_fifa22-origin fault](https://user-images.githubusercontent.com/1843978/175556577-20b1607d-364e-438c-b50e-268bf9824440.png)

**Comment by NRG-R9T** [comment]
I've played the Game for over 300 hours by now, and while it can be played well, it is impossible for me to play it seriously competitive, as the game crashes the competitive matches in about 1 in 3 cases. So in FUT Champions I've often got 19 of 20 points needed to qualify for Play-offs (Weekend League), with about 3-4 games effectively played out of 8 possible ones. The rest crashed me out before it started. 
![20220504180924_1](https://user-images.githubusercontent.com/1843978/175557161-758677c9-fcd7-4a50-a5ec-0d62ab227b0d.jpg)

**Comment by mirashif** [comment]
I have faced the same issue.
![image](https://user-images.githubusercontent.com/34467318/180921569-11def168-59b4-47a1-911e-27dac440a768.png)

**Comment by kisak-valve** [comment]
Fifa 22 Origin after update not works (Other apps already running)

Issue transferred from https://github.com/ValveSoftware/Proton/issues/6083.
@senpl posted on 2022-08-09T17:23:04:

# Compatibility Report
- Name of the game with compatibility issues: Fifa 22
- Steam AppID of the game: 1506830
- BuildID 9186369

## System Information
- GPU: RTX 2060
- Driver/LLVM version: nvidia 515.65.01-2
- Kernel version: 5.18.16-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 7.0.3

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Games lunch today before update. 
After fifa update no longer starts (complains about other process or not starts at all).
system update not helps.

## Reproduction
1. Install Fifa 22
2. Install origin
3. start game( not possible in current version.


[steam-1506830.log](https://github.com/ValveSoftware/Proton/files/9293209/steam-1506830.log)

**Comment by senpl** [comment]
Huge ea servers problems was present today. Officialy it's fixed now according to official Twitter ea direct communication account.

**Comment by NRG-R9T** [comment]
The connection problems where temporary for all players and solved. The original issue of FIFA22 (running with Proton) with FUT Games that are crashing at random (in the match loading screen) is still present.

**Comment by tegaidogun** [comment]
I seem to have an issue whenever I start the game I get a black screen, and I've tried multiple things but I still can't seem to get it to work. No custom launch options, and using latest Proton, my system specifications should be listed in the given text file.

Whenever I click Play on the Game Screen I get a Black Screen Window before it crashes later.

![image](https://github.com/ValveSoftware/Proton/assets/63559796/3d0b85d8-e6af-41fe-b039-83486243c663)

Black Screen:

![image](https://github.com/ValveSoftware/Proton/assets/63559796/85ec02f1-fa2f-4728-8145-b6aa795845fe)

This is what I got when I ran Steam in the terminal:

[steam.log](https://github.com/ValveSoftware/Proton/files/14538392/steam.log)

**Comment by kisak-valve** [comment]
EA-Launcher stopped working with Proton 7 & FIFA 22

Issue transferred from https://github.com/ValveSoftware/Proton/issues/8249.
@puxplaying posted on 2024-11-16T08:29:58:

# Compatibility Report
- Name of the game with compatibility issues: FIFA 22
- Steam AppID of the game: 1506830

## System Information
- GPU:  RX 6750 XT
- Video driver version:  Mesa 24.2.7-arch1.1
- Kernel version:  6.11.8-1-MANJARO
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/puxplaying/d0fa4a0f6a7f767a3d7a2624d50316a5
- Proton version: 7.0-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.



## Symptoms 
The EA launcher does not start anymore with Proton 7 - and hence the game FIFA 22 can not be launched.
- The reason to use Proton 7 is, it is the only version which is able to run this game at 60 FPS on AMD GPU's in cut-scenes, pro-cam and the menu. Any other (newer) Proton version is capped at 30 FPS in DX11 and DX12 mode.

## Reproduction
Run FIFA 22 via Proton 7

[PROTON_LOG](https://gist.github.com/puxplaying/9e05b69a27e31a039c83ddd6e429ba40)
[Steam Runtime Diagnostics](https://gist.github.com/puxplaying/a96f05df446f9059160643bc9dca458f)

**Comment by puxplaying** [comment]
Hello @kisak-valve, are there any plans by Valve to stop allowing third party launchers like this one in the future, which break perfectly playable offline games that require a older Proton version?

The only thing that invasive third party launchers like this achieve, is that people will start pirating those games when they get screwed by shady companies that break their games on purpose. These self-updating always online launchers make game preservation basically impossible without pirating.

**Comment by alasky17** [comment]
@puxplaying Have you checked the "game settings" in the launcher to see if you have it set to be capped to 30fps or 60fps?  Due to the specific situation you described, I wonder if somehow it is set to 30fps for you right now?  

Also - how have you been checking the FPS?  It looks like the steam overlay fps counter doesn't work for this one :(  And what part of the game are you playing?  I keep getting warnings that the servers have been turned off, so I'm not able to test any cutscenes etc.

**Comment by puxplaying** [comment]
Hello @alasky17!
> Have you checked the "game settings" in the launcher to see if you have it set to be capped to 30fps or 60fps? Due to the specific situation you described, I wonder if somehow it is set to 30fps for you right now?

I made sure to set it to 60fps in the settings app and also confirmed it by checking the `fifasetup.ini` in `/compatdata/1506830/pfx/drive_c/users/steamuser/My Documents/FIFA 22` - `WAITFORVSYNC = 1`



> Also - how have you been checking the FPS? It looks like the steam overlay fps counter doesn't work for this one :( And what part of the game are you playing? I keep getting warnings that the servers have been turned off, so I'm not able to test any cutscenes etc.

The best way to check this without any FPS counter is in the career mode on a 60Hz monitor. Simply start a match with your player and make sure the Pro Cam is used. It will immediately start stuttering with this cam and set the frame rate to half of the screen refresh rate, while the traditional cams work fine on 60 fps. (This issue is also affecting Windows with AMD GPU's, maybe because it's a console port)

Here a reddit post about it: https://www.reddit.com/r/FIFA22/comments/pw0ep7/fifa_22_30fps_lock_also_pro_camera_issue_solved/?rdt=45957

My guess is, that proton 7 is either spoofing the actual refresh rate, or somehow forcing 60fps, while newer versions don't do that. Which makes Proton 7 the only option in my case. I've tested that also on a RX580 with the same result. So it seems to be a AMD GPU issue, I don't think that Nvidia GPU's are affected.

I could work around this issue with newer Proton versions by using a 120Hz monitor, which then will be internally set to 60fps in Pro Cam - career mode.

**Comment by alasky17** [comment]
@puxplaying Ah I see - so it looks like the FPS getting set to 1/2 of the refresh rate is a game bug?  I'm assuming the refresh rate of your monitor is 60fps and Proton versions newer than 7.0 are reporting that correctly? (just making sure I'm understanding this correctly).  

If the issue is with AMD GPUs, you could try using WINE_HIDE_AMD_GPU=1 or PROTON_FORCE_NVAPI=1.  You could also potentially try adding a file called "dxvk.conf" in the game directory with the following content: 
dxgi.customDeviceId = 10DE
dxgi.customVendorId = 1C02

I'm not 100% confident in these options to hide your AMD GPU, maybe someone else has better advice in that regard :)

**Comment by puxplaying** [comment]
@alasky17 
> Ah I see - so it looks like the FPS getting set to 1/2 of the refresh rate is a game bug? I'm assuming the refresh rate of your monitor is 60fps and Proton versions newer than 7.0 are reporting that correctly? (just making sure I'm understanding this correctly).

Absolutely right!



> If the issue is with AMD GPUs, you could try using WINE_HIDE_AMD_GPU=1 or PROTON_FORCE_NVAPI=1. You could also potentially try adding a file called "dxvk.conf" in the game directory with the following content:
> dxgi.customDeviceId = 10DE
> dxgi.customVendorId = 1C02

The "dxvk.conf" file with the content you posted seems to solve it completely. The launch options when tried one by one, don't seem to have any effect without the "dxvk.conf".

You my friend just solved years of mystery (for me) in a single post. Thank you very much for that!
