### ISSUE TITLE
Ghostwire Tokyo (1475810)

### ISSUE THREAD

**Issue by asaokej** [ValveSoftware/Proton#5720]
# Compatibility Report
- Name of the game with compatibility issues: Ghostwire Tokyo
- Steam AppID of the game: 1475810

## System Information
- RTX 3070
- Driver/LLVM version: nvidia 510.54
- Kernel version: 5.4.0-105
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/asaokej/8651fed192124745555f67ad7690df36
- Proton version: Proton experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

 

Proton log: 
https://gist.github.com/asaokej/0c9723f623441fab314e6001e847dad4 

## Symptoms 
Blackscreens  and freezes in certain cutscenes. First cutscene in the start you can skip before freezing/black screen but then after ca 20 minutes there comes a cutscene that you cant skip. Tried installing mfplat but it still does not work 

## Reproduction

Every time you try to progress story

**Comment by Mar0xy** [comment]
I have the exact same issue you can skip the first cutscene right after clicking play and selecting difficulty but at the cutscene where akito enters mari's room it fades to black and then just stays black not doing anything.

I have tried it with Proton Experimental aswell as Proton GE both resulting in the same issue.

**Comment by TamsenSpelchak** [comment]
I'm encountering this issue as well. I can skip the first cutscene to get around the black screen there, but skipping the cutscene of entering Mari's room doesn't help.

Interestingly, the program isn't completely frozen. If you use something like mangohud you can see that the game is still rendering frames and the CPU/GPU have substantial usage. I'm not sure what the game thinks it's doing, but whatever it is it never seems to finish it.

EDIT: I've attached the output from `PROTON_LOG=1`. I can see that the game continually repeats the following line when the game is stuck at the black screen, but I have no idea if it's of any use.
> ```0278:warn:d3d12_device_SetResidencyPriority: iface 000000002d3f0030, object_count 2, objects 000000003b9ff738, priorities 000000003b9ff730 stub!```

[steam-1475810.log](https://github.com/ValveSoftware/Proton/files/8354577/steam-1475810.log)

**Comment by TamsenSpelchak** [comment]
As per a related discussion on the Linux Gaming Dev Discord, it seems this issue is caused by  Ghostwire's prerendered cutscenes being encoded as VP9:
```
winegstreamer error: decodebin6: ../src-gst_base/gst/playback/gstdecodebin2.c(4719): gst_decode_bin_expose (): /GstBin:bin6/GstDecodeBin:decodebin6:
no suitable plugins found:
Missing decoder: VP9 (video/x-vp9, width=(int)3840, height=(int)2160, framerate=(fraction)30/1)
```

As per [this](https://www.reddit.com/r/SteamDeck/comments/tnddlv/ghostwire_tokyo_black_screens/) Reddit thread, it seems that using an older version of Proton GE fixes the issue. I have been using [Proton GE 7.2 GE 3 test 2](https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/7.2-GE-3-test-2) and it's been working well for displaying cutscenes that otherwise cause black screens. I'm not sure why only this older version of GE has VP9 support when the newer ones don't, but presumably having VP9 decode support through GStreamer in Proton is the fix for this issue.

Also of note is that this game stutters quite a bit when traversing the open world. This seems more related to asset streaming than shader compilation stuttering.

**Comment by Billli11** [comment]
Maybe because proton now use steamdeck soldier runtime to build?
Seems like soldier do not have libvpx installed and ~~gstreamer won't build with vp9 support if libvpx is not exist.~~

./gst-plugins-good/meson_options.txt

    option('vpx', type : 'feature', value : 'auto', description : 'VP8 and VP9 video codec plugin')

./gst-plugins-good/meson_options.txt

    vpx_features = [`
        [ 'vpx/vp8cx.h', 'vpx_codec_vp8_cx_algo', '-DHAVE_VP8_ENCODER', 'VP8 encoder' ],
        [ 'vpx/vp8dx.h', 'vpx_codec_vp8_dx_algo', '-DHAVE_VP8_DECODER', 'VP8 decoder' ],
        [ 'vpx/vp8cx.h', 'vpx_codec_vp9_cx_algo', '-DHAVE_VP9_ENCODER', 'VP9 encoder' ],
        [ 'vpx/vp8dx.h', 'vpx_codec_vp9_dx_algo', '-DHAVE_VP9_DECODER', 'VP9 decoder' ],
    ]

The only header file in soldier SDK image that is vp9 related is

    /usr/include/va/va_enc_vp9.h
    /usr/include/va/va_dec_vp9.h

EDIT(2022-03-30 19:00:00+00:00):The soldier runtime is updated in client beta to included libvpx.so

    SteamLinuxRuntime_soldier/soldier_platform_0.20220329.0/files/lib/i386-linux-gnu/libvpx.so.5.0.0
    SteamLinuxRuntime_soldier/soldier_platform_0.20220329.0/files/lib/steamrt/expectations/i386-linux-gnu/libvpx5.symbols
    SteamLinuxRuntime_soldier/soldier_platform_0.20220329.0/files/lib/steamrt/expectations/x86_64-linux-gnu/libvpx5.symbols
    SteamLinuxRuntime_soldier/soldier_platform_0.20220329.0/files/lib/x86_64-linux-gnu/libvpx.so.5.0.0
    SteamLinuxRuntime_soldier/soldier_platform_0.20220329.0/files/share/doc/libvpx5

soldier SDK is not yet updated.

EDIT2:meson auto feature is disabled in Makefile.in

    GST_GOOD_MESON_ARGS := \
    -Dauto_features=disabled \

**Comment by ThisNekoGuy** [comment]
I was playing the game for a few hours and came across a mandatory loading screen for progressing the game (the first underground area of the game) where the loading screen stalled and became infinite.
The log says that:
`(null) wait timed out in thread 025c, blocked by 0148`
[(Proton Log)](https://github.com/ValveSoftware/Proton/files/13654965/steam-1475810.zip)
<details><summary>Screenshot:</summary>

![Screenshot_20231212_134234](https://github.com/ValveSoftware/Proton/assets/28468662/55d7a8bd-aa61-49c2-b169-7ce8ee6ae217)
</details>

Re-launching the game and loading an autosave to try again worked, so it appears that the issue might be associated with the length of time the game was running? I'm not sure.

The game also exhibits intermittent audio crackling and mutes, and they get significantly worse in cutscenes.

**Comment by yuiiio** [comment]
only on raytracing mode, game has a lot of memory leak.
(proton experimental breeding edge + mesa-git)
[steam-1475810.log](https://github.com/ValveSoftware/Proton/files/13788577/steam-1475810.log)

**Comment by yuiiio** [comment]
```
vkd3d_view_map_create_view: Intense view map pressure! Got 1024 views in hash map 000000003ceccfc8. This may lead to out-of-memory errors in the extreme case.
```
only get when enabled raytracing mode.


UPDATE:
It was a mesa bug. 
and fixed in https://gitlab.freedesktop.org/mesa/mesa/-/commit/34cc76517286b88c8191a3e10dda0a3293c09127
(thanks pixelcluster !)

**Comment by hyperstown** [comment]
Hello, does anyone also experience extremely high CPU usage when loading textures with raytracing on? It only happens when settings `Ray-Traced Reflection Quality` and/or `Ray-Traced Shadow Quality` is ON. (Low-High).

I'm not sure if it's a texture fault or shaders are compiling but I said textures because the CPU (R5 2600 6c12t) hovers around 40% (around 50 fps) when I don't move around but the second I change location I see textures loading, CPU spikes to 100% and framerate drops to 15 fps. If you try to run ahead ignoring low framerate game will freeze for a few seconds.\
It can also freeze when character move around small, already loader area, CPU usage is normal but game still freezes for a few seconds.  

System Information:
```
CPU: AMD Ryzen 5 2600 (12) @ 3.40 GHz
GPU: AMD Radeon RX 6700 XT [Discrete]
Memory: 31.27 GiB
Mesa: 24.2.8
Kernel: 6.11
Proton: Experimental
```

I also did some additional testing running game on the steamdeck and there game won't even launch (Message that says starting engine time-outed) with ray tracing which could be a problem since settings were synced with my PC and the game could not start. 

To exclude issue with hardware or game itself I also tried Windows 10 and there game run without issues with the same settings. 

In proton log I see a lot of:
```log
7314.062:0130:01e0:warn:vkd3d-proton:vkd3d_get_image_allocation_info: Padding allocation requirements. Requested alignment 4096 < 65536 (dim 3, 256 x 256 x 1, 9 levels, 1 samples, fmt #3d, flags #0).
7314.531:0130:0134:warn:vkd3d-proton:vkd3d_get_image_allocation_info: Padding allocation requirements. Requested alignment 4096 < 65536 (dim 3, 256 x 256 x 1, 9 levels, 1 samples, fmt #3d, flags #0).
```

But I'm not sure if it's related since I also saw similar warning with rt disabled.

Full log: [steam-1475810.log](https://github.com/user-attachments/files/18260802/steam-1475810.log)

**Comment by alosslessdev** [comment]
Still present in the latest proton experimental version, ray tracing disabled I think. Can't progress past entering Mari's room, it fades into a black screen, I have not tried using older versions of proton-ge

**Comment by alosslessdev** [comment]
I was able to work around the issue by installing https://gstreamer.freedesktop.org/documentation/installing/on-linux.html?gi-language=c but I have not played the game for over 30 minutes

**Comment by ejrydhfs** [comment]
I was able to work around the cutscene issue by installing https://gstreamer.freedesktop.org/documentation/installing/on-linux.html?gi-language=c

**Comment by simifor** [comment]
Assuming the cutscene talk is about mari's hospital room, I got there, and its video, without issue. This was on 9.0-4 (which is the default for this game) and also proton experimental
