### ISSUE TITLE
Resident Evil 0 HD Remaster + Resident Evil 1 HD Remaster (339340 304240)

### ISSUE THREAD

**Issue by naterz1204** [ValveSoftware/Proton#576]
The black screen / cinematic fix needs implementing to be able to pass the initial CAPCOM logo after running the game. Dependencies "winetricks wmp10 d3dcompiler_43 d3dx9 xact_jun2010" needed as well as the installation of "windowsmedia-kb942423-x86-intl.exe". 

System Info gist -
https://gist.github.com/naterz1204/40ee88dd24160117d3ed62524f9145e6

**Comment by naterz1204** [comment]
System Info gist - 
https://gist.github.com/naterz1204/40ee88dd24160117d3ed62524f9145e6

**Comment by pcfirebeats** [comment]
Same thing happens to me.

https://gist.github.com/pcfirebeats/1c35f9c01e57312d7d154f1351c9b6f6

**Comment by rafaelgomesxyz** [comment]
I was able to get it to work in Arch Linux.

First I created a 32-bit prefix following this guide: https://www.reddit.com/r/linux_gaming/comments/99e0kc/steam_playguide_create_custom_32bit_prefix_to/

Then I followed the Wine instructions for fixing the black screen (in the additional comments): https://appdb.winehq.org/objectManager.php?sClass=version&iId=33247

The game ran fine, but I'm not sure if this is the correct way. Since I created a 32-bit prefix, I'm not really using Proton, I'm just using Wine, right?

**Comment by HonkingGoose** [comment]
Hi, 

I'm doing some research for my issue at number 1464. That issue deals with cinematic/video playback. Most of the listed games already have a proton log attached to their issue, but this game does not.

Could somebody be so kind as to upload a proton log from a clean install?

I need to search in the proton log for mentions of MF or quartz, so that I can categorize the game.

Thanks for the help!

HonkingGoose

**Comment by unit73e** [comment]
@HonkingGoose here you go:
[steam-304240.log](https://github.com/ValveSoftware/Proton/files/2809477/steam-304240.log)

I also have Resident Evil 0 HD Remaster but I'll have to install it first.

**Comment by unit73e** [comment]
While I'm at it:

```
General
Complete name                            : ./nativePC/movie/01/20_b.wmv
Format                                   : Windows Media
File size                                : 10.3 MiB
Duration                                 : 10 s 933 ms
Overall bit rate mode                    : Constant
Overall bit rate                         : 7 883 kb/s
Maximum Overall bit rate                 : 8 050 kb/s
Encoded date                             : UTC 2014-10-30 14:16:33.150

Video
ID                                       : 2
Format                                   : VC-1
Format profile                           : Advanced@L3
Codec ID                                 : WVC1
Codec ID/Hint                            : Microsoft
Description of the codec                 : VC-1 - VC-1 Advanced Profile
Duration                                 : 10 s 933 ms
Bit rate mode                            : Constant
Bit rate                                 : 8 000 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 30.000 FPS
Original frame rate                      : 15.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.129
Stream size                              : 10.4 MiB
Language                                 : Japanese (JP)
```

So the video codec is WVC1. Oddly the videos don't seem to have any sound.

EDIT: All videos are in WVC1

**Comment by unit73e** [comment]
@HonkingGoose logs of Resident Evil 0 HD Remaster:
[steam-339340.log](https://github.com/ValveSoftware/Proton/files/2810049/steam-339340.log)

Some videos are in WMV3 and others in WVC1.

**Comment by HonkingGoose** [comment]
Seems WMvcore.dll is the troublemaker:
```
10931.686:0008:0055:fixme:wmvcore:WMCreateSyncReader ((nil), 1, 0x8411e08): stub
```

**Comment by shoober420** [comment]
# Compatibility Report
- Name of the game with compatibility issues: Resident Evil 0 / biohazard 0 HD REMASTER
- Steam AppID of the game: https://steamdb.info/app/339340/

## System Information
- GPU: GTX 760
- Driver/LLVM version: NVIDIA 440.44
- Kernel version: 5.4.15
- https://github.com/shoober420/linux-scripts/blob/main/home/shoober420/sysinfonvidia
- Proton version: 4.11-12

LOG:
[steam-339340.log](https://github.com/ValveSoftware/Proton/files/4123108/steam-339340.log)

## Symptoms
Black screen after Capcom logo

**Comment by soredake** [comment]
https://github.com/Winetricks/winetricks/pull/1489

**Comment by frostworx** [comment]
I've overseen the last comment from @soredake and tried to find out what needs to be done to get the games working. Just "found out" that wmp11 is the only dependency missing for both titles... thanks @soredake ;)
*adding both to stl*

**Comment by thaewrapt** [comment]
`protontricks [steamid] -q wmp11` is broken on Proton 5.13 and current Experimental (as it's a same 5.13 but with experimental patches/updates) due to the changes introduced in that version of Proton, namely some of .dll files in `pfx` directory (aka game's wine/Proton prefix) being now symlinked to the main Proton directory. As it seems not to affect `wmp11` winetricks verb directly, it breaks `wsh57` and `gdiplus` verbs which are the prerequisites for the latter.

Workaround for now: switch back to the Proton-5.0 branch.

**Comment by DomiStyle** [comment]
I can confirm what @thaewrapt wrote. I was unable to get Resident Evil 1 to work with Proton 5.13.

Also, instead of the usual WMP11 issue on 5.13 my game wouldn't start at all, didn't even get the Capcom logo. Seems to also be related to gdiplus.dll.

Here's the debug log: [steam-304240_nolaunch.log](https://github.com/ValveSoftware/Proton/files/5880174/steam-304240_nolaunch.log)

Probably the issue:
> 8808.337:00c8:00cc:err:module:import_dll Loading library gdiplus.dll (which is needed by L"Z:\\mnt\\games\\steam\\steamapps\\common\\Resident Evil Biohazard HD REMASTER\\bhd.exe") failed (error c000007b).

On 5.0 everything works perfectly (including cinematics) after installing WMP11 with protontricks, which would previously error out because of a few access denied errors during wsh57 just like @thaewrapt described.

I'm having the same issue with Resident Evil 5 so I'm going to test there next.

**Comment by mmbossoni** [comment]
@thaewrapt 
You may want to try this shell oneliner from inside the proton prefix (steamapps/compatdata/<gameid>/pfx/drive_c

`IFS=$'\n'; for f in $(find -type l); do echo "$f"; cp --remove-destination --no-preserve=mode "$(readlink $f)" "$f"; done;`

What this does is to replace all of proton symlinks with the actual files. This may allow protontricks to run normally after.

**Comment by thaewrapt** [comment]
> What this does is to replace all of proton symlinks with the actual files. This may allow protontricks to run normally after.

I'm ok with 5.0 solution as long as it makes an unplayable game a playable one. There is no clarity in what Proton development team was trying to achieve with that change, in a first place.

**Comment by mmbossoni** [comment]
Probably saving space (one full system copy per games vs one copy per system using symlinks)
Also, probably avoiding us tinkering with stuff and reporting bugs when we mess something LoL

**Comment by kisak-valve** [comment]
Resident evil 0 Color bars

Issue transferred from https://github.com/ValveSoftware/Proton/issues/5770.
@songsofsyx posted on 2022-04-16T11:36:01:

# Compatibility Report
- Name of the game with compatibility issues: Resident Evil 0
- Steam AppID of the game:

There are color bars on Resident Evil 0, playing it on the steam deck.
Proton 7.x has color bars on cutscenes and color bars in-game
Proton experimental has color bars in-game

The in-game color bars do not occur at first glance, one must progress in the game a bit.

By color bars, I mean stripes of colors, with a noisy flickering in the lower right. 

I'm pretty sure this is codec-related, maybe having a look at the game files will identify the offending codec.

I'm sorry, due to technical issues I'm reporting this on my windows machine, and can not offer logs.

**Comment by esmorun** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/576#issuecomment-1100654293

I can confirm. The game looks like this:
![Screenshot from 2022-04-28 20-14-13](https://user-images.githubusercontent.com/59760231/165820068-d4730ab3-d84c-435d-a464-2ed1a4d68f51.png)

**Comment by kisak-valve** [comment]
Resident Evil 0 Remastered  Color bars

Issue transferred from https://github.com/ValveSoftware/Proton/issues/6103.
@liufengxin123 posted on 2022-08-18T15:41:30:

# Compatibility Report
- Name of the game with compatibility issues: Resident Evil 0 Remastered 
- Steam AppID of the game: 339340

## System Information
Steam Deck 
SteamOS
- Proton version: Proton 7.0-4 (default)  and Proton Experimental

## I confirm:
- [yes] that I haven't found an existing compatibility report for this game.
- [yes] that I have checked whether there are updates for my system available.



[steam-339340.log](https://github.com/ValveSoftware/Proton/files/9375245/steam-339340.log)


## Symptoms 
There seems to be a problem with the light rendering of the game, there are various rainbow-like rays, I can confirm that this will not happen in Windows, the bug condition requires a little more time to play along the game flow (about 15 minutes flow).

<details><summary>Screenshots</summary>

![1](https://user-images.githubusercontent.com/31117926/185436916-78db9fec-319d-4765-9cbf-cdbb6745ecf9.jpg)
![2](https://user-images.githubusercontent.com/31117926/185436936-d88a7d19-89df-4cb2-abcf-7d20c95b98de.jpg)
![3](https://user-images.githubusercontent.com/31117926/185436959-acbf4972-67d6-403e-815a-80550ac9f6df.jpg)
![4](https://user-images.githubusercontent.com/31117926/185436977-e86e9137-9e78-46ca-8a6a-bdc20f2b4053.jpg)

</details>

## Reproduction

Operating System: SteamOS 3.3.1
KDE Plasma Version: 5.23.5
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Kernel Version: 5.13.0-valve21.1-1-neptune-02211-gc54cda5a36f3 (64-bit)
Graphics Platform: X11
Processors: 8 × AMD Custom APU 0405
Memory: 14.5 GiB of RAM
Graphics Processor: AMD Custom GPU 0405
***
@liufengxin123 commented on 2022-08-18T15:54:57:

<details><summary>System information</summary>

```
Computer Information:
    Manufacturer:  Valve
    Model:  Jupiter
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Custom APU 0405
    CPU Family:  0x17
    CPU Model:  0x90
    CPU Stepping:  0x2
    CPU Type:  0x0
    Speed:  2800 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Supported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    "SteamOS Holo" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.13.0-valve21.1-1-neptune-02211-gc54cda5a36f3
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12101003
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime_0.20220601.1

Video Card:
    Driver:  AMD AMD Custom GPU 0405 (vangogh, LLVM 13.0.0, DRM 3.45, 5.13.0-valve21.1-1-neptune-02211-gc54cda5a36f3)
    Driver Version:  4.6 (Compatibility Profile) Mesa 22.0.2 (git-71648faf15)
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x1002
    DeviceID:  0x163f
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  800 x 1280
    Desktop Resolution: 1280 x 800
    Primary Display Size: 2.36" x 2.36" (3.31" diag)
                                            6.0cm x 6.0cm (8.4cm diag)
    Primary VRAM: 1024 MB

Sound card:
    Audio device: ATI R6xx HDMI

Memory:
    RAM:  14836 MB

VR Hardware:
    VR Headset: None detected

Miscellaneous:
    UI Language:  English
    LANG:  zh_CN.UTF-8
    Total Hard Disk Space Available:  960940 MB
    Largest Free Hard Disk Block:  909566 MB

Storage:
    Number of SSDs: 0
    Number of HDDs: 0

"LD_* scout runtime" information:
{
  "can-write-uinput" : true,
  "steam-installation" : {
    "path" : "/home/deck/.local/share/Steam",
    "data_path" : "/home/deck/.local/share/Steam",
    "bin32_path" : "/home/deck/.local/share/Steam/ubuntu12_32",
    "steamscript_path" : "/usr/lib/steam/steam",
    "steamscript_version" : "1.0.0.74",
    "issues" : [
      "unexpected-steam-uri-handler"
    ]
  },
  "runtime" : {
    "path" : "/home/deck/.local/share/Steam/ubuntu12_32/steam-runtime",
    "version" : "0.20220601.1",
    "issues" : [
    ],
    "pinned_libs_32" : {
      "list" : [
        "pinned_libs_32/has_pins",
        "pinned_libs_32/libcurl.so.3 -> libcurl.so.4",
        "pinned_libs_32/libcurl.so.4 -> $STEAM_RUNTIME/usr/lib/i386-linux-gnu/libcurl.so.4.2.0",
        "pinned_libs_32/libdbus-1.so.3 -> $STEAM_RUNTIME/lib/i386-linux-gnu/libdbus-1.so.3.5.8",
        "pinned_libs_32/libvulkan.so.1 -> $STEAM_RUNTIME/usr/lib/i386-linux-gnu/libvulkan.so.1.3.211",
        "pinned_libs_32/system_libcurl.so.4",
        "pinned_libs_32/system_libdbus-1.so.3",
        "pinned_libs_32/system_libvulkan.so.1"
      ]
    },
    "pinned_libs_64" : {
      "list" : [
        "pinned_libs_64/has_pins",
        "pinned_libs_64/libGLU.so.1 -> $STEAM_RUNTIME/usr/lib/x86_64-linux-gnu/libGLU.so.1.3.08004",
        "pinned_libs_64/libSDL2-2.0.so.0 -> $STEAM_RUNTIME/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0.22.0",
        "pinned_libs_64/libcurl.so.3 -> libcurl.so.4",
        "pinned_libs_64/libcurl.so.4 -> $STEAM_RUNTIME/usr/lib/x86_64-linux-gnu/libcurl.so.4.2.0",
        "pinned_libs_64/libvulkan.so.1 -> $STEAM_RUNTIME/usr/lib/x86_64-linux-gnu/libvulkan.so.1.3.211",
        "pinned_libs_64/system_libGLU.so.1",
        "pinned_libs_64/system_libSDL2-2.0.so.0",
        "pinned_libs_64/system_libcurl.so.4",
        "pinned_libs_64/system_libvulkan.so.1"
      ]
    }
  },
  "os-release" : {
    "id" : "steamos",
    "id_like" : [
      "arch"
    ],
    "name" : "SteamOS",
    "pretty_name" : "SteamOS",
    "version_id" : "3.3.1",
    "version_codename" : "holo",
    "build_id" : "20220817.1",
    "variant_id" : "steamdeck"
  },
  "virtualization" : {
    "type" : "none"
  },
  "container" : {
    "type" : "none"
  },
  "driver_environment" : [
    "DISPLAY=:0",
    "LD_LIBRARY_PATH=/home/deck/.local/share/Steam/ubuntu12_32:/home/deck/.local/share/Steam/ubuntu12_32/panorama:/home/deck/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_32:/home/deck/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_64:/usr/lib32:/usr/lib/perf:/usr/lib:/home/deck/.local/share/Steam/ubuntu12_32/steam-runtime/lib/i386-linux-gnu:/home/deck/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu:/home/deck/.local/share/Steam/ubuntu12_32/steam-runtime/lib/x86_64-linux-gnu:/home/deck/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu:/home/deck/.local/share/Steam/ubuntu12_32/steam-runtime/lib:/home/deck/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib",
    "SDL_GAMECONTROLLERCONFIG=03000000de280000ff11000001000000,Steam Virtual Gamepad,a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b8,leftshoulder:b4,leftstick:b9,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b10,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,platform:Linux\
03000000de280000fc11000001000000,Steam Controller,a:b0,b:b1,back:b6,dpdown:b14,dpleft:b15,dpright:b13,dpup:b12,guide:b8,leftshoulder:b4,leftstick:b9,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b10,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,platform:Linux",
    "XDG_RUNTIME_DIR=/run/user/1000"
  ],
  "architectures" : {
    "i386-linux-gnu" : {
      "can-run" : true,
      "libdl-LIB" : "lib32",
      "libdl-PLATFORM" : "i686",
      "runtime-linker" : {
        "path" : "/lib/ld-linux.so.2",
        "resolved" : "/usr/lib32/ld-2.33.so"
      },
      "library-issues-summary" : [
      ],
      "graphics-details" : {
        "x11/vulkan" : {
          "renderer" : "AMD RADV VANGOGH",
          "version" : "Mesa 22.2.0-devel (git-6decdc8cf2)",
          "devices" : [
            {
              "name" : "AMD RADV VANGOGH",
              "api-version" : "1.3.211",
              "vulkan-driver-id" : 3,
              "driver-name" : "radv",
              "driver-version" : "Mesa 22.2.0-devel (git-6decdc8cf2)",
              "vendor-id" : "0x1002",
              "device-id" : "0x163f",
              "type" : "integrated-gpu"
            }
          ]
        },
        "x11/vdpau" : {
          "renderer" : "G3DVL VDPAU Driver Shared Library version 1.0\
",
          "version" : null
        },
        "x11/vaapi" : {
          "messages" : [
            "libva info: VA-API version 1.13.0",
            "libva info: Trying to open /usr/lib32/dri/radeonsi_drv_video.so",
            "libva info: Found init function __vaDriverInit_1_13",
            "libva info: va_openDriver() returns 0",
            "Testing H264Main decoding"
          ],
          "renderer" : "Mesa Gallium driver 22.0.2 for AMD Custom GPU 0405 (vangogh, LLVM 13.0.0, DRM 3.45, 5.13.0-valve21.1-1-neptune-02211-gc54cda5a36f3)\
",
          "version" : null
        },
        "glx/gl" : {
          "renderer" : "AMD Custom GPU 0405 (vangogh, LLVM 13.0.0, DRM 3.45, 5.13.0-valve21.1-1-neptune-02211-gc54cda5a36f3)",
          "version" : "4.6 (Compatibility Profile) Mesa 22.0.2 (git-71648faf15)",
          "library-vendor" : "glvnd"
        },
        "egl_x11/gl" : {
          "renderer" : "AMD Custom GPU 0405 (vangogh, LLVM 13.0.0, DRM 3.45, 5.13.0-valve21.1-1-neptune-02211-gc54cda5a36f3)",
          "version" : "4.6 (Compatibility Profile) Mesa 22.0.2 (git-71648faf15)",
          "library-vendor" : "glvnd"
        },
        "egl_x11/glesv2" : {
          "renderer" : "AMD Custom GPU 0405 (vangogh, LLVM 13.0.0, DRM 3.45, 5.13.0-valve21.1-1-neptune-02211-gc54cda5a36f3)",
          "version" : "OpenGL ES 3.2 Mesa 22.0.2 (git-71648faf15)",
          "library-vendor" : "glvnd"
        }
      },
      "dri_drivers" : [
        {
          "library_path" : "/usr/lib32/dri/kms_swrast_dri.so"
        },
        {
          "library_path" : "/usr/lib32/dri/radeonsi_dri.so"
        },
        {
          "library_path" : "/usr/lib32/dri/swrast_dri.so"
        },
        {
          "library_path" : "/usr/lib32/dri/zink_dri.so"
        }
      ],
      "va-api_drivers" : [
        {
          "library_path" : "/usr/lib32/dri/radeonsi_drv_video.so"
        },
        {
          "library_path" : "/home/deck/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/dri/dummy_drv_video.so"
        }
      ],
      "vdpau_drivers" : [
        {
          "library_path" : "/usr/lib32/vdpau/libvdpau_radeonsi.so",
          "library_link" : "libvdpau_radeonsi.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib32/vdpau/libvdpau_radeonsi.so.1",
          "library_link" : "libvdpau_radeonsi.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib32/vdpau/libvdpau_trace.so",
          "library_link" : "libvdpau_trace.so.1"
        },
        {
          "library_path" : "/usr/lib32/vdpau/libvdpau_trace.so.1",
          "library_link" : "libvdpau_trace.so.1.0.0"
        }
      ],
      "glx_drivers" : [
        {
          "library_soname" : "libGLX_indirect.so.0",
          "library_path" : "/usr/lib32/libGLX_mesa.so.0.0.0"
        },
        {
          "library_soname" : "libGLX_mesa.so.0",
          "library_path" : "/usr/lib32/libGLX_mesa.so.0.0.0"
        }
      ]
    },
    "x86_64-linux-gnu" : {
      "can-run" : true,
      "libdl-LIB" : "lib",
      "libdl-PLATFORM" : "x86_64",
      "runtime-linker" : {
        "path" : "/lib64/ld-linux-x86-64.so.2",
        "resolved" : "/usr/lib/ld-2.33.so"
      },
      "library-issues-summary" : [
      ],
      "graphics-details" : {
        "x11/vulkan" : {
          "renderer" : "AMD RADV VANGOGH",
          "version" : "Mesa 22.2.0-devel (git-6decdc8cf2)",
          "devices" : [
            {
              "name" : "AMD RADV VANGOGH",
              "api-version" : "1.3.211",
              "vulkan-driver-id" : 3,
              "driver-name" : "radv",
              "driver-version" : "Mesa 22.2.0-devel (git-6decdc8cf2)",
              "vendor-id" : "0x1002",
              "device-id" : "0x163f",
              "type" : "integrated-gpu"
            }
          ]
        },
        "x11/vdpau" : {
          "renderer" : "G3DVL VDPAU Driver Shared Library version 1.0\
",
          "version" : null
        },
        "x11/vaapi" : {
          "messages" : [
            "Testing H264Main decoding"
          ],
          "renderer" : "Mesa Gallium driver 22.0.2 for AMD Custom GPU 0405 (vangogh, LLVM 13.0.0, DRM 3.45, 5.13.0-valve21.1-1-neptune-02211-gc54cda5a36f3)\
",
          "version" : null
        },
        "glx/gl" : {
          "renderer" : "AMD Custom GPU 0405 (vangogh, LLVM 13.0.0, DRM 3.45, 5.13.0-valve21.1-1-neptune-02211-gc54cda5a36f3)",
          "version" : "4.6 (Compatibility Profile) Mesa 22.0.2 (git-71648faf15)",
          "library-vendor" : "glvnd"
        },
        "egl_x11/gl" : {
          "renderer" : "AMD Custom GPU 0405 (vangogh, LLVM 13.0.0, DRM 3.45, 5.13.0-valve21.1-1-neptune-02211-gc54cda5a36f3)",
          "version" : "4.6 (Compatibility Profile) Mesa 22.0.2 (git-71648faf15)",
          "library-vendor" : "glvnd"
        },
        "egl_x11/glesv2" : {
          "renderer" : "AMD Custom GPU 0405 (vangogh, LLVM 13.0.0, DRM 3.45, 5.13.0-valve21.1-1-neptune-02211-gc54cda5a36f3)",
          "version" : "OpenGL ES 3.2 Mesa 22.0.2 (git-71648faf15)",
          "library-vendor" : "glvnd"
        }
      },
      "dri_drivers" : [
        {
          "library_path" : "/usr/lib/dri/kms_swrast_dri.so"
        },
        {
          "library_path" : "/usr/lib/dri/radeonsi_dri.so"
        },
        {
          "library_path" : "/usr/lib/dri/swrast_dri.so"
        },
        {
          "library_path" : "/usr/lib/dri/zink_dri.so"
        }
      ],
      "va-api_drivers" : [
        {
          "library_path" : "/usr/lib/dri/i965_drv_video.so"
        },
        {
          "library_path" : "/usr/lib/dri/radeonsi_drv_video.so"
        },
        {
          "library_path" : "/home/deck/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/dri/dummy_drv_video.so"
        }
      ],
      "vdpau_drivers" : [
        {
          "library_path" : "/usr/lib/vdpau/libvdpau_radeonsi.so",
          "library_link" : "libvdpau_radeonsi.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib/vdpau/libvdpau_radeonsi.so.1",
          "library_link" : "libvdpau_radeonsi.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib/vdpau/libvdpau_trace.so",
          "library_link" : "libvdpau_trace.so.1"
        },
        {
          "library_path" : "/usr/lib/vdpau/libvdpau_trace.so.1",
          "library_link" : "libvdpau_trace.so.1.0.0"
        }
      ],
      "glx_drivers" : [
        {
          "library_soname" : "libGLX_indirect.so.0",
          "library_path" : "/usr/lib/libGLX_mesa.so.0.0.0"
        },
        {
          "library_soname" : "libGLX_mesa.so.0",
          "library_path" : "/usr/lib/libGLX_mesa.so.0.0.0"
        }
      ]
    }
  },
  "locale-issues" : [
    "default-missing",
    "c-utf8-missing",
    "i18n-supported-missing"
  ],
  "locales" : {
    "<default>" : {
      "error-domain" : "srt-locale-error-quark",
      "error-code" : 0,
      "error" : "No such file or directory"
    },
    "C" : {
      "resulting-name" : "C",
      "charset" : "ANSI_X3.4-1968",
      "is_utf8" : false
    },
    "C.UTF-8" : {
      "error-domain" : "srt-locale-error-quark",
      "error-code" : 0,
      "error" : "No such file or directory"
    },
    "en_US.UTF-8" : {
      "resulting-name" : "en_US.UTF-8",
      "charset" : "UTF-8",
      "is_utf8" : true
    }
  },
  "egl" : {
    "icds" : [
      {
        "json_path" : "/usr/share/glvnd/egl_vendor.d/50_mesa.json",
        "library_path" : "libEGL_mesa.so.0",
        "issues" : [
        ]
      }
    ],
    "external_platforms" : [
    ]
  },
  "vulkan" : {
    "icds" : [
      {
        "json_path" : "/usr/share/vulkan/icd.d/radeon_icd.x86_64.json",
        "library_path" : "/usr/lib/libvulkan_radeon.so",
        "api_version" : "1.3.211",
        "issues" : [
        ]
      },
      {
        "json_path" : "/usr/share/vulkan/icd.d/radeon_icd.i686.json",
        "library_path" : "/usr/lib32/libvulkan_radeon.so",
        "api_version" : "1.3.211",
        "issues" : [
        ]
      }
    ],
    "explicit_layers" : [
    ],
    "implicit_layers" : [
      {
        "json_path" : "/home/deck/.local/share/vulkan/implicit_layer.d/steamfossilize_i386.json",
        "name" : "VK_LAYER_VALVE_steam_fossilize_32",
        "description" : "Steam Pipeline Caching Layer",
        "type" : "GLOBAL",
        "api_version" : "1.2.136",
        "implementation_version" : "1",
        "library_path" : "/home/deck/.local/share/Steam/ubuntu12_32/libVkLayer_steam_fossilize.so",
        "issues" : [
        ]
      },
      {
        "json_path" : "/home/deck/.local/share/vulkan/implicit_layer.d/steamfossilize_x86_64.json",
        "name" : "VK_LAYER_VALVE_steam_fossilize_64",
        "description" : "Steam Pipeline Caching Layer",
        "type" : "GLOBAL",
        "api_version" : "1.2.136",
        "implementation_version" : "1",
        "library_path" : "/home/deck/.local/share/Steam/ubuntu12_64/libVkLayer_steam_fossilize.so",
        "issues" : [
        ]
      },
      {
        "json_path" : "/home/deck/.local/share/vulkan/implicit_layer.d/steamoverlay_i386.json",
        "name" : "VK_LAYER_VALVE_steam_overlay_32",
        "description" : "Steam Overlay Layer",
        "type" : "GLOBAL",
        "api_version" : "1.2.136",
        "implementation_version" : "1",
        "library_path" : "/home/deck/.local/share/Steam/ubuntu12_32/steamoverlayvulkanlayer.so",
        "issues" : [
        ]
      },
      {
        "json_path" : "/home/deck/.local/share/vulkan/implicit_layer.d/steamoverlay_x86_64.json",
        "name" : "VK_LAYER_VALVE_steam_overlay_64",
        "description" : "Steam Overlay Layer",
        "type" : "GLOBAL",
        "api_version" : "1.2.136",
        "implementation_version" : "1",
        "library_path" : "/home/deck/.local/share/Steam/ubuntu12_64/steamoverlayvulkanlayer.so",
        "issues" : [
        ]
      },
      {
        "json_path" : "/usr/share/vulkan/implicit_layer.d/MangoHud.json",
        "name" : "VK_LAYER_MANGOHUD_overlay",
        "description" : "Vulkan Hud Overlay",
        "type" : "GLOBAL",
        "api_version" : "1.2.135",
        "implementation_version" : "1",
        "library_path" : "libMangoHud.so",
        "issues" : [
        ]
      },
      {
        "json_path" : "/usr/share/vulkan/implicit_layer.d/libMangoApp.json",
        "name" : "VK_LAYER_MANGOAPP_overlay",
        "description" : "Mangoapp Layer",
        "type" : "GLOBAL",
        "api_version" : "1.2.135",
        "implementation_version" : "1",
        "library_path" : "libMangoApp.so",
        "issues" : [
        ]
      }
    ]
  },
  "desktop-entries" : [
    {
      "id" : "steam.desktop",
      "commandline" : "/usr/bin/steam %U",
      "filename" : "/usr/share/applications/steam.desktop",
      "default_steam_uri_handler" : true,
      "steam_uri_handler" : true
    }
  ],
  "xdg-portals" : {
    "details" : {
      "interfaces" : {
        "org.freedesktop.portal.OpenURI" : {
          "available" : true,
          "version" : 3
        },
        "org.freedesktop.portal.Email" : {
          "available" : true,
          "version" : 3
        }
      },
      "backends" : {
        "org.freedesktop.impl.portal.desktop.gtk" : {
          "available" : false
        },
        "org.freedesktop.impl.portal.desktop.kde" : {
          "available" : true
        }
      }
    },
    "issues" : [
    ]
  },
  "cpu-features" : {
    "x86-64" : true,
    "sse3" : true,
    "cmpxchg16b" : true
  }
}
```

</details>

**Comment by kaincenteno** [comment]
can confirm this happening on Steam Deck.

Can this game go back from verified to playable? Else it is a bad rap for "verified" games

**Comment by ShadowOne333** [comment]
<s>I just tried running RE0 on Steam Deck, and while it does get to the main menu, it crashed right at the "Loading content" window after pressing Start.

I seem to recall the game being playable before, but right now it doesn't even get past that Loading screen. I tried Proton Experimental and 7.0.</s>

EDIT:
Seems like there was something weird with the save file. I entered the folder with the save and deleted it altogether, then let the game create a new save and that seems to fix the game booting properly now.

Although, I can also reproduce the weird coloured RGB lines after meeting with Billy Coen and controlling both characters.

**Comment by ShadowOne333** [comment]
I finished Resident Evil 0 on the Steam Deck yesterday, and I think I found out when/why the coloured RGB lines precisely show up. They seem to be appearing whenever there's lights affecting the background, or lights appearing and/or changing in the same background.

For example, in the Train section, you don't see the coloured lines until the train starts moving, at this point, the backgrounds start having some light effects on them to showcase the movement of the train, and you can see some lights passing by in most of the windows and backgrounds in this location. The exact moment when the lines start appearing can be seen in this video at 17:20 right when the cutscene ends. You can see the several lights that go by in the windows, which most of the other backgrounds in the train now have due to the train being in movement now, and said lines stop appearing when the train crashes and the player reaches the Training Facility: https://youtu.be/Anm_F89z7ks?t=1040

After the train crashes, the whole Training Facility section doesn't have any weird coloured lines at all that I could tell, and they don't reappear at all until after the Lab section. From what I remember, the lines reappear in two other rooms, these ones being both Elevators in the Lab and Factory. Here you can see the exact elevators where you see the weird coloured lines:

Lab Elevator: As soon as you enter this one, you see the coloured lines: https://youtu.be/Anm_F89z7ks?t=10289
Factory Elevator, in this elevator, the floor and arrow lights change whenever you change floors after selecting either of the 4 levels, since as soon as you select a new floor and the lights begin changing, that's when the lines appear in this room: https://youtu.be/Anm_F89z7ks?t=12859

I think there might be one other place where the coloured lines appear, but I can't recall precisely where, but I do remember it also having some light stuff going on with it, so I think the easiest one to test and debug this issue on would be the Train as it is right at the beginning of the game and can be easily triggered.

----

Additionally, I seem to be getting a really weird bug in which the game crashes or simply stays in a black screen or at a loading screen at random points on the game, and that's keeping me from obtaining the "Save Your Prayers" (Finish the game without saving) achievement in RE0, since it crashed each and every time I attempted this achievement. :/

**Comment by waspennator** [comment]
Seeing reports and people saying setting the texture settings to high in the options for re1 hd breaks certain videos, but I don't have the game to check.

**Comment by ipr** [comment]
Just a heads up, Proton 9.0 beta is stuck with black screen after Capcom logo.

Proton experimental shows test pattern but then proceeds to main menu.
[steam-339340.log](https://github.com/ValveSoftware/Proton/files/14395725/steam-339340.log)

**Comment by simifor** [comment]
The game should be working again with current proton experimental (now based on proton 9)

**Comment by BearsPunch** [comment]
By comment in ProtonDB by Cryptocurrenstein, I can confirm that Proton-GE 7.18 has no issue with graphic artifacts!

**Comment by kisak-valve** [comment]
Resident Evil 0 fails show cutscenes

Issue transferred from https://github.com/ValveSoftware/Proton/issues/7806.
@PNunesDev posted on 2024-06-02T22:15:24:

# Compatibility Report
- Name of the game with compatibility issues: Resident Evil 0
- Steam AppID of the game: 339340

## System Information
- GPU: GTX 1650 Super
- Video driver version: 535.171.04-0ubuntu0.22.04.01
- Kernel version: 5.15.0.107-generic
- Link to full system information report as [Gist](https://gist.github.com/): [gist:887f0d70b9b94f95f0324c1566d8c443](https://gist.github.com/PNunesDev/887f0d70b9b94f95f0324c1566d8c443)
- Proton version: (any) (tried experimental, 9.0-1 and GE-Proton9-5

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-339340.log](https://github.com/user-attachments/files/15527060/steam-339340.log)

## Symptoms 
Visual corruption with green and red pixels everywhere.
![20240602230926_1](https://github.com/ValveSoftware/Proton/assets/11355144/aabf887e-901b-4c58-9949-245d689fe4a7)
![20240602230939_1](https://github.com/ValveSoftware/Proton/assets/11355144/ee2490a8-69a8-4e66-8a36-96779f7505af)

## Reproduction
Start a new game
Play until the Secondary character is playable (Billy Coen), it should be playable after 5-10 minutes after starting a new game.
As soon as we reach that point, visual corruption appears.

Reproducted in proton experimental as well as 9.0-1, tried GE-Proton9-5 but issues continues.

**Comment by PNunesDev** [comment]
@kisak-valve Sorry I have made a mess of a report.
At first I was about to create 2 bugs (1 for the cutscenes, another for the visual corruption that can be seen in the images).

The cutscenes seems to be fixed in the proton-experimental branch.
Although the visual corruption does appear whatever if I do use proton-experimental, proton 9,8,7 or even the GE-Proton9-5.

Probably my "report" can be erased since it might create confusion in this topic, I will report the visual corruption bug as a new one (if there isn't a new already available)
Thanks..

**Comment by kisak-valve** [comment]
Hello again @PNunesDev, we're tracking feedback on a per-game basis. This is the right place for all feedback related to Resident Evil 0 HD Remaster.

**Comment by PNunesDev** [comment]
Just some extra news.
I've also tried the GE-Proton7-18 and it seems to fix the visual artifacts on the train.

Still, I would love to have this fix in the regular proton version.

**Comment by villamizarivan** [comment]
Hi, I confirm using Proton Ge 7-18 the artifacts were fixed, using Opensuse tumbleweed, my problem was color bars on screen in the factory.

**Comment by ranplayer** [comment]
Resident Evil 1 Remaster is missing the video images with Proton Experimental (2024/08/08), 9.0-2, 8.0-5 and 7.0-6. The first campaign video has audio and subtitles, but the image is replaced by colored bars. 

Proton logs: 
[steam-304240-re.tar.gz](https://github.com/user-attachments/files/16582007/steam-304240-re.tar.gz)

Main error logs:
```
(wine:37110): GStreamer-WARNING **: 09:54:40.870: Failed to load plugin '/home/gamer/.local/share/Steam/steamapps/common/Proton - Experimental/files/lib64/gstreamer-1.0/libgstcoretracers.so': /home/gamer/.local/share/Steam/steamapps/common/Proton - Experimental/files/lib64/gstreamer-1.0/libgstcoretracers.so: wrong ELF class: ELFCLASS64
winegstreamer error: decodebin0: Your GStreamer installation is missing a plug-in.
winegstreamer error: decodebin0: ../src-gst_base/gst/playback/gstdecodebin2.c(4704): gst_decode_bin_expose (): /GstBin:bin0/GstDecodeBin:decodebin0:
no suitable plugins found:
Missing decoder: Advanced Streaming Format (ASF) (video/x-ms-asf)
(wine:37110): GStreamer-Video-CRITICAL **: 09:54:41.198: gst_video_info_from_caps: assertion 'gst_caps_is_fixed (caps)' failed
(wine:37110): GStreamer-Audio-CRITICAL **: 09:54:41.214: gst_audio_info_from_caps: assertion 'gst_caps_is_fixed (caps)' failed
```

Specs:
- OS: Arch
- Kernel: 6.6.44
- GPU: RX 6700 XT (Mesa 24.1.5)
- CPU: Ryzen 7 5700G (8c/16t)

**Comment by simifor** [comment]
@ranplayer colored bars are a place holder for videos that can't be played by proton directly and need to be transcoded. After it gets transcoded server side, it gets delivered to users through shader caches.

**Comment by ranplayer** [comment]
@simifor thank you for the explanation. So I suppose there are no cached video shaders for this title yet.

**Comment by Slider-Whistle** [comment]
I don't know whether to expect any developer response, but it seems like there's been some kind of regression past Proton 7.9 causing weird green and red lines to start appearing in certain scenes as soon as the multi-character portion of the game starts. I don't really like to run old versions of programs, so does anyone here know any other possible workarounds?

**Comment by kisak-valve** [comment]
Hello @Slider-Whistle, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options, reproduce the regression and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.) Also, please include a screenshot of the misrendering, and separately, a copy of the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by Slider-Whistle** [comment]
@kisak-valve I made a little mistake there misreading the community "ProtonDB" page, there is no version 7.(4)9 of vanilla Proton, just the GE patchset. https://www.protondb.com/app/339340
I'll do some experimenting using just vanilla Proton 9.0 & 7.0 to see whether it's a shared issue.

**Comment by Slider-Whistle** [comment]
Sorry for the late message. The areas affected by the green line bug in the "GE" patchset of Proton are all additionally affected by the video decoding/test image issue in vanilla Proton, making the area unplayable anyway. There might or might not be a regression in vanilla Proton there, but it's nearly impossible to see the lines over the testing pattern, so it wouldn't really be right to diagnose an issue I'm not 100% positive is actually happening.

**Comment by hhirsch** [comment]
Installing wmp11 with protontricks fixes the colored lines issue.

**Comment by Tathagata-0** [comment]
> Installing wmp11 with protontricks fixes the colored lines issue.

For me, this causes the game to crash when the first video starts, right before the title screen. 

[https://gist.github.com/Tathagata-0/a2236d219ba96fac9c4984bae6e61d82](url)

As a workaround, looks like using the last ProtonGE 9 prevents the crashing.

**Comment by hhirsch** [comment]
For a while it worked just by adding wmp11 through protontricks. For some reason that stopped working and GE-Proton7-49 alone does not fix the glitches either. Only using GE-Proton7-49 AND deleting the wine prefix fixed the issue the last time I tried.

**Comment by AJuujarvi** [comment]
The green lines and related distortions in the pre-rendered backgrounds should be fixed with Resident Evil 0 with the latest Proton Experimental release. The first instance of the failure after the leech zombie at the beginning of the game was where I had checked. If there are later instances of this failure that are still happening, we would like to know.

**Comment by PNunesDev** [comment]
@AJuujarvi I've checked on my save file on the cabin, and with proton 11 the issue persist.
But experimental finally fixed it.

I've already finished the game with proton-GE 7 (or 6) can't remember properly.

But it's good news seeing the game working on the main proton, especially because (not sure) other classic remastered games suffered from the same issue.

**Comment by aboutafter** [comment]
> The green lines and related distortions in the pre-rendered backgrounds should be fixed with Resident Evil 0 with the latest Proton Experimental release. The first instance of the failure after the leech zombie at the beginning of the game was where I had checked. If there are later instances of this failure that are still happening, we would like to know.

<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/8a197849-96b5-423a-a836-236b3fc5dc08" />

I've just tried with Proton Experimental [bleeding-edge] (and not bleeding edge), and these lines and some red ones still appear. This is running on a Steam Deck OLED.

**Comment by AJuujarvi** [comment]
@aboutafter That looks exactly like the issue we fixed. Strange it is not fixed for you.

Have you changed any settings from the default settings of the game and if so what settings? Could you also grab a log file of your issue? 

1. You can do that by clicking on the Gear to the right of the Play button. 
2. From there, scroll down and select Properties. 
3. Once in Properties, press right, and then scroll down to a typing field for Launch options and type in `PROTON_LOG=+quartz,+strmbase,+strmbase_qc,+gstreamer,+amstream,+qcap,+qcap_v4l,+qedit,+mciqtz,+mci,+mfplat,+evr,+dxva2,+wmvcore,+dmo %command%`. I know that can be very annoying to type with an OSK, I would recommend a keyboard for that if you are able.
4. That now created a log file in the home directory of your Steam Deck titled `steam-339340.log`. Can you upload that here please?

**Comment by aboutafter** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/576#issuecomment-4769898932

[steam-339340.log](https://github.com/user-attachments/files/29225017/steam-339340.log)

Sure thing. Here you go. And thank you for taking a look at it!

EDIT: wait a minute. I'm seeing in the log that it's using Proton 10 instead of experimental. I have the default compatibility tool pointing to Proton Experimental, but somehow it doesn't work like that with RE0. I now forced Experimental on the game configuration and it's working correctly.

**Comment by simifor** [comment]
@aboutafter your log shows that the game is loading with proton 10, make sure to also select proton experimental on the game's properties window, look for the compatibility tab and select proton experimental

**Comment by ShadowOne333** [comment]
Does the new Proton Experimental also fix the issues of FMV playback for both REmake and RE0?
