### ISSUE TITLE
Yu-Gi-Oh! Master Duel (1449850)

### ISSUE THREAD

**Issue by huyhoang8398** [ValveSoftware/Proton#5876]
# Compatibility Report
- Name of the game with compatibility issues: Yu-gi-oh Master duel
- Steam AppID of the game: 1449850

## System Information
OS: Ubuntu 22.04 LTS
KERNEL: 5.15.0-33-generic
CPU: Intel Core i5-10210U @ 1.60GHz
GPU: Intel Mesa Intel UHD (CML GT2)
GPU DRIVER: 4.6 Mesa 22.0.1
RAM: 16 GB
- Proton version: Proton Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

Yugioh Master Duel crashs when open activities in Ubuntu 22.04 Wayland

## Reproduction

- Open Steam on Ubuntu 22.04 LTS Wayland
- Install proton experimental
- Install Yu-gi-oh Master duel
- Run Yu-gi-oh Master duel
- Open window activities in Ubuntu
- Game crashed

**Comment by kisak-valve** [comment]
Hello @huyhoang8398, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.) Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by sangoku116** [comment]
This is literally the only game that crashes my pc and it's been doing it since launch no matter the proton version.

**Comment by Tholleman** [comment]
@kisak-valve Couldn't play this game either so I decided to follow your instructions. Here you go: [steam-1449850.log](https://github.com/ValveSoftware/Proton/files/10948412/steam-1449850.log)
https://gist.github.com/Tholleman/49184e74e6d402d95102fa35771528c2

**Comment by kisak-valve** [comment]
Hello @Tholleman, can you test how the game behaves with the game's launch options set to `PROTON_USE_WINED3D=1 %command%`?

**Comment by Tholleman** [comment]
The game launches now! Thank you so much!

**Comment by kisak-valve** [comment]
Master Duels

Issue transferred from https://github.com/ValveSoftware/Proton/issues/6915.
@jonte450 posted on 2023-07-05T07:23:35:

Hi i am running an Ubuntu 23.04 and i have tried to start Master Duels with Proton version 08..03
And i have written in PROTON_USE_WINE3D=1 %command% and the game doesn't start and i have tried in my launch options to write PROTON_LOG=1 %command% and i don't get any debug.log file in my home directory?

**Comment by reDBo0n** [comment]
Newest Update (v1.6.0) crashes (freeze on a black screen) now on my Arch machine.

According to Community Members on Steam Discussions are plugged in (virtual) controllers the culprit and they advice to remove all controllers and uninstall tools like vJoy.

It seems to work for some folks, but on Proton I have no luck, because I don't have controllers plugged in at all. The only virtual controllers (?) are Steam Input for Remote Play and Steam Controller, which can't be turned off.

**Comment by reDBo0n** [comment]
Just found out my Keyboard of all things let Master Duel Crash.

Maybe because it has a mouse Emulation mode, idk

**Comment by reDBo0n** [comment]
Tested on my Windows 11 drive, game just works with keyboard.
May be a Bug on Proton's end.
Tested on 8, Experimental and Experimental [bleeding-edge]; all times game freezes with plugged-in keyboard.

**Comment by reDBo0n** [comment]
Did some experimenting and it seems there is a stack overflow happening with the keyboard plugged in.
[Keyboard already in.log](https://github.com/ValveSoftware/Proton/files/12136043/Keyboard.already.in.log)
[Keyboard Pluggin in.log](https://github.com/ValveSoftware/Proton/files/12136044/Keyboard.Pluggin.in.log)

**Comment by reDBo0n** [comment]
Got hand on a "generic" USB Keyboard.
With it just works, no problem.

Plugging in my real keyboard (Ducky ONE 3) it just crashes instantly again.

**Comment by Heliozoa** [comment]
I've found that although Master Duel is playable the performance on Linux is very poor compared to Windows.

In the main menu I get roughly the following performance (just eyeballing with MangoHud):

#### Windows 10
Stable 165 fps

#### Proton Experimental / Proton 8.0-4
Unstable frame rate, varies greatly depending on the number of displays I have turned on:
- 1 display: 80-110 fps
- 2 displays: 45-65 fps
- 3 displays: 35-45 fps
- 4 displays: 20-30 fps

#### Proton 7.0-6
Unstable 50-70 fps

---

Surprisingly, changing the resolution from 2560x1440 to 1280x720 or other settings did not make even a small difference to the performance with any of the Proton versions I tried.

My system information: https://gist.github.com/Heliozoa/256663f758ee6366a10eddb6fb813a0f

Happy to provide more info if needed.

**Comment by Teddy-Kun** [comment]
On my system (tried both Arch and Nobara) on Proton 8 it does not start correctly. It freezes on a grey screen with no audio or anything. On Proton 7 it at least starts, but when using Wayland (Hyprland or KDE), tabbing out of and into the game freezes it as well but it seems random and does not happen consistently. Performance is also poorer than it should be with it only using about 30% of my GPU and hovering around the 100-120fps mark.

System: https://gist.github.com/Teddy-Kun/d0d16f303b9c27b1cff23ce96a85a0f4
Runtime Diagnostics: https://gist.github.com/Teddy-Kun/871fdc50d8a20392d4c91addafdee3c7

[Proton 8 freeze on start](https://github.com/ValveSoftware/Proton/files/14424870/MasterDuelFreeze.log)
[Proton 9 Beta freeze on start](https://github.com/ValveSoftware/Proton/files/14424877/MasterDuelFreeze9.log)
[MasterDuelFreezeWayland.log](https://github.com/ValveSoftware/Proton/files/14424885/MasterDuelFreezeWayland.log)

EDIT: I also could only reproduce the tabbing out freeze issue with the game in fullscreen mode, but that may just be because of the randomness

**Comment by kisak-valve** [comment]
Hello @Teddy-Kun, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options, reproduce the regression, and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.) Also, please copy the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by reDBo0n** [comment]
I can reproduce @Teddy-Kun problem. On Proton 8 starting the game with my (gaming) keyboard plugged in it just keeps getting stuck on a blackscreen, on Proton 7 it just works fine with it plugged in.

Here is my log and system info
[steam-1449850.log](https://github.com/ValveSoftware/Proton/files/14424858/steam-1449850.log)

[System Info](https://gist.github.com/reDBo0n/8fa56e3b7a294627797f14d5be242478)

**Comment by Teddy-Kun** [comment]
@kisak-valve I updated my previous comment with the requested resources. I hope it helps!

**Comment by kisak-valve** [comment]
Hello @reDBo0n, you're implying that the game works for you with Proton 8 and that keyboard disconnected? Please clarify if that's true and exactly what model of keyboard you're using.

**Comment by reDBo0n** [comment]
Yep, with my "Ducky 3 One" plugged in on Proton 8 the game doesn't work, but with a generic keyboard (according to lsusb "Chicony Electronics Co., Ltd HP USB Keyboard") it works again.

**Comment by simifor** [comment]
The game didn't freeze for me at launch when testing proton stable, tried with mesa 24 and 23.3.5 @Teddy-Kun I'm guessing you have the same keyboard as @reDBo0n ? And were all your tests on wayland? Or was it also freezing at launch on xorg?

**Comment by alasky17** [comment]
@reDBo0n Have you tried Proton 9 yet with your Ducky 3 One keyboard?  There was a bug with certain input hardware that should be fixed with 9.0-beta.

**Comment by reDBo0n** [comment]
Tested the Proton 9 beta, problem still persists with my Ducky connected

**Comment by Heliozoa** [comment]
Just a quick update on https://github.com/ValveSoftware/Proton/issues/5876#issuecomment-1784065864: `Proton 9.0 (Beta)` has fixed these performance issues for me and the game now maintains a steady 165 fps in the main menu as it does on Windows.

**Comment by reDBo0n** [comment]
Update from my side:

Proton 9 Beta now works with my Ducky 3 One keyboard connected

**Comment by alasky17** [comment]
@reDBo0n Thank you for the update! Great to hear :)

**Comment by Cypher5014** [comment]
Hi, reopening the subject cause i have a similar problem, when i try to launch the game i can go up to the screen where you to click to launch the game, and when I do it my computer straight up reboots

I am using Ubuntu Noble Numbat 24.04.2
and as for my hardware i use "Lenovo Lenovo 14w Gen 2"
AMD 3015e with Radeon™ Graphics × 4
AMD Radeon™ Graphics
8 GB of RAM memory

**Comment by simifor** [comment]
@Cypher5014 if it's causing your computer to reboot, there should be kernel logs for it. Something like the following could be used to share them: `journalctl -k -b -1 > kernel.log`. This should create the file kernel.log in your home folder. You may need to change the "-1" to something else, "-b -1" means you're selecting the journal log for the previous boot (if you play the game, and it causes the computer to reboot, the new boot would be 0 and the previous one, where it rebooted, would be -1), -2 is the one previous to that and so on.

Also, if you're attempting to run the game again, you can add this to the game's properties on steam, to its launch parameter: `PROTON_LOG=1 %command%`. This will generate a log file in your home folder called `steam-1449850.log` with proton related information.

**Comment by Cypher5014** [comment]
Thank you for your answer, i ran the command and got the kernel log, but i actually don't understand anything when i open the log.
I'm attaching it to this message in case someone would be interested in checking what it contains.
By the way i didn't find where to put the ```PROTON_LOG=1 &command%```

[kernel.log](https://github.com/user-attachments/files/19485868/kernel.log)

**Comment by reDBo0n** [comment]
> By the way i didn't find where to put the `PROTON_LOG=1 %command%`

In your Steam Library right click Master Duel -> Properties there's a Launch Option field. Paste it in there.
