### ISSUE TITLE
Multiple games crash on launch

### ISSUE THREAD

**Issue by Savoy4574** [ValveSoftware/Proton#5944]
#### Your system information

* Steam client version (build number or date): 1654574690 2022-06-07T03:18:43
* Distribution (e.g. Ubuntu): Ubuntu 18.04
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
Multiple games (Icarus, Green Hell, etc.) crash on launch. I've tried restarting steam, restarting laptop, reinstalling the game, reinstalling steam, nothing has worked. I checked that my graphics drivers are up to date.

<details><summary>The terminal output is</summary>

```
Installing breakpad exception handler for appid(steam)/version(1654574690)
Installing breakpad exception handler for appid(steam)/version(1654574690)
Installing breakpad exception handler for appid(steam)/version(1654574690)
Installing breakpad exception handler for appid(steam)/version(1654574690)
GameAction [AppID 1149460, ActionID 2] : LaunchApp changed task to ShowLaunchOption with ""
GameAction [AppID 1149460, ActionID 2] : LaunchApp waiting for user response to ShowLaunchOption ""
GameAction [AppID 1149460, ActionID 2] : LaunchApp continues with user response "0"
GameAction [AppID 1149460, ActionID 2] : LaunchApp changed task to ProcessingInstallScript with ""
Proton: Upgrading prefix from None to 7.0-100 (/home/savoy457/.local/share/Steam/steamapps/compatdata/1149460/)
esync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
GameAction [AppID 1149460, ActionID 2] : LaunchApp changed task to RunningInstallScript with ""
GameAction [AppID 1149460, ActionID 2] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 1149460, ActionID 2] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 1149460, ActionID 2] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 1149460, ActionID 2] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 1149460, ActionID 2] : LaunchApp continues with user response "CreatingProcess"
/bin/sh\0-c\0/home/savoy457/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1149460 -- '/home/savoy457/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/savoy457/.local/share/Steam/steamapps/common/Proton - Experimental'/proton waitforexitandrun  '/home/savoy457/.local/share/Steam/steamapps/common/Icarus/Icarus.exe'\0
Game process added : AppID 1149460 "/home/savoy457/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1149460 -- '/home/savoy457/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/savoy457/.local/share/Steam/steamapps/common/Proton - Experimental'/proton waitforexitandrun  '/home/savoy457/.local/share/Steam/steamapps/common/Icarus/Icarus.exe'", ProcID 23852, IP 0.0.0.0:0
chdir /home/savoy457/.local/share/Steam/steamapps/common/Icarus
ERROR: ld.so: object '/home/savoy457/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 1149460, ActionID 2] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/savoy457/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/savoy457/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/savoy457/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/savoy457/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 1149460, ActionID 2] : LaunchApp changed task to Completed with ""
pid 23861 != 23858, skipping destruction (fork without exec?)
Installing breakpad exception handler for appid(steam)/version(1654574690)
esync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
ThreadGetProcessExitCode: no such process 24012
ThreadGetProcessExitCode: no such process 24010
ThreadGetProcessExitCode: no such process 24009
ThreadGetProcessExitCode: no such process 24008
ThreadGetProcessExitCode: no such process 23859
ThreadGetProcessExitCode: no such process 24015
Game process updated : AppID 1149460 "/home/savoy457/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1149460 -- '/home/savoy457/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/savoy457/.local/share/Steam/steamapps/common/Proton - Experimental'/proton waitforexitandrun  '/home/savoy457/.local/share/Steam/steamapps/common/Icarus/Icarus.exe'", ProcID 24011, IP 0.0.0.0:0
Setting breakpad minidump AppID = 1149460
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198125152677 [API loaded no]
Game process updated : AppID 1149460 "/home/savoy457/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1149460 -- '/home/savoy457/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/savoy457/.local/share/Steam/steamapps/common/Proton - Experimental'/proton waitforexitandrun  '/home/savoy457/.local/share/Steam/steamapps/common/Icarus/Icarus.exe'", ProcID 24105, IP 0.0.0.0:0
Setting breakpad minidump AppID = 1149460
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198125152677 [API loaded no]
Fossilize INFO: Overriding serialization path: "/home/savoy457/.local/share/Steam/steamapps/shadercache/1149460/fozpipelinesv6/steamapprun_pipeline_cache".
Fossilize INFO: Overriding serialization path: "/home/savoy457/.local/share/Steam/steamapps/shadercache/1149460/fozpipelinesv6/steamapprun_pipeline_cache".
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  149 ()
  Minor opcode of failed request:  4
  Serial number of failed request:  401
  Current serial number in output stream:  407
ThreadGetProcessExitCode: no such process 24101
ThreadGetProcessExitCode: no such process 24081
ThreadGetProcessExitCode: no such process 24055
ThreadGetProcessExitCode: no such process 24049
ThreadGetProcessExitCode: no such process 24043
ThreadGetProcessExitCode: no such process 24020
ThreadGetProcessExitCode: no such process 24017
ThreadGetProcessExitCode: no such process 24011
ThreadGetProcessExitCode: no such process 24007
pid 24013 != 24012, skipping destruction (fork without exec?)
Game process removed: AppID 1149460 "/home/savoy457/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1149460 -- '/home/savoy457/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/savoy457/.local/share/Steam/steamapps/common/Proton - Experimental'/proton waitforexitandrun  '/home/savoy457/.local/share/Steam/steamapps/common/Icarus/Icarus.exe'", ProcID 24105 
ThreadGetProcessExitCode: no such process 24105
ThreadGetProcessExitCode: no such process 24029
ThreadGetProcessExitCode: no such process 23858
ThreadGetProcessExitCode: no such process 23857
Game 1149460 created interface STEAMAPPS_INTERFACE_VERSION008 / 
Game 1149460 created interface STEAMREMOTESTORAGE_INTERFACE_VERSION014 / 
Game 1149460 created interface STEAMUSERSTATS_INTERFACE_VERSION011 / 
Game 1149460 created interface SteamController007 / Controller
Game 1149460 created interface SteamFriends017 / 
Game 1149460 created interface SteamInput001 / Controller
Game 1149460 created interface SteamMatchMaking009 / 
Game 1149460 created interface SteamMatchMakingServers002 / 
Game 1149460 created interface SteamNetworking006 / 
Game 1149460 created interface SteamUser020 / 
Game 1149460 created interface SteamUser020 / User
Game 1149460 created interface SteamUtils009 / 
Game 1149460 created interface SteamUtils009 / Utils
Game 1149460 method call count for IClientNetworking::AllowP2PPacketRelay : 1
Game 1149460 method call count for IClientUserStats::RequestCurrentStats : 1
Game 1149460 method call count for IClientUtils::RecordSteamInterfaceCreation : 14
Game 1149460 method call count for IClientUtils::GetAppID : 17
Game 1149460 method call count for IClientUser::BIsSubscribedApp : 1
Game 1149460 method call count for IClientUser::GetSteamID : 1
Uploaded AppInterfaceStats to Steam
```

</details>

#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by kisak-valve** [comment]
Hello @Savoy4574, we're tracking issues with games run with Proton in the Proton issue tracker, so I've transferred this issue report. 

Please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to a couple affected game's launch options and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.) Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by Savoy4574** [comment]
https://gist.github.com/Savoy4574/39645ed2e605c1a0343dfb47a28bd196
I'm not finding any steam-*.log files and below is the only output from terminal. Let me know if the command I'm running is incorrect and what it should be instead.

PROTON_USE_WINED3D=1 steam steam://rungameid/1149460
steam.sh[15819]: Running Steam on ubuntu 18.04 64-bit
steam.sh[15819]: STEAM_RUNTIME is enabled automatically
setup.sh[15958]: Steam runtime environment up-to-date!
steam.sh[15819]: Steam client's requirements are satisfied

**Comment by kisak-valve** [comment]
You've skipped the extended diagnostics information in the system information, so it's hard to tell for sure, but I suspect that you're using an Optimus laptop and encountered an issue like #5113 / https://github.com/ValveSoftware/steam-for-linux/issues/8179 where the `PrefersNonDefaultGPU` setting on Steam's desktop shortcut is telling games using a Vulkan render path to try to use mesa/ANV while X is running on the NVIDIA proprietary driver and having a hard time.

The quick test for this would be to completely close Steam, then run `steam` from a terminal and see if that has an effect.

`PROTON_USE_WINED3D=1 steam steam://rungameid/1149460` This line is starting Steam, when Steam sees that there's an instance already running, it hands off `steam://rungameid/1149460` to the already running instance and the environment variable is lost.

You can find the per-game launch options in Steam -> Library -> Right click on the game in the sidebar *or* select the game and click the gear icon on the right -> Properties -> Launch Options.

**Comment by Savoy4574** [comment]
[steam-1149460.log](https://github.com/ValveSoftware/Proton/files/9014057/steam-1149460.log)
Ah, sorry, now I see what you mean by adding proton log. Attached is the output. I also went ahead and set PrefersNonDefaultGPU=false in steam.deaktop. Now it takes a little longer to crash, but still a crash without opening the game window at all.

**Comment by kisak-valve** [comment]
The key detail from your Proton log: `info:    Device name:     : Intel(R) UHD Graphics 630 (CFL GT2)`  The game is trying to run on the Intel GPU instead of the NVIDIA GPU.

**Comment by Savoy4574** [comment]
Then sorry for the ignorance, but besides including `__NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=NVIDIA_only __GLX_VENDOR_LIBRARY_NAME=nvidia %command%` in the launch options (didn't help) or setting `PrefersNonDefaultGPU=false` in steam.desktop, what is the solution to get Proton to look for the NVIDIA GPU?

**Comment by kisak-valve** [comment]
This is more guesswork than science without lots of information like what's given by Steam's extended diagnostics information.

I would look at how a simpler applications like `glxinfo -B` (OpenGL) and `vulkaninfo --summary` (Vulkan) respond to those environment variables to reduce the complexity of the test case.

Also, you could test setting `VK_ICD_FILENAMES="/usr/share/vulkan/icd.d/nvidia_icd.json"` or renaming `/usr/share/vulkan/icd.d/intel_icd.*.json` files to end in something other than `.json` (like `.json.disabled`) so that the NVIDIA Vulkan render path is the only option available.

**Comment by Savoy4574** [comment]
I tried renaming the files and also running `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.i686.json:/usr/share/vulkan/icd.d/radeon_icd.x86_64.json steam` but they both run into the error message when running the game `A D3D11-compatible GPU (Feature level 11.0, Shader Model 5.0 is required to run this engine)`. I feel back to where I started with not knowing what else to try. I also don't see how this can be the issue since it was running a few weeks ago and I don't see any nvidia files in `/usr/share/vulkan/icd.d/` Are there other issues going on or known update issues from vulkan shaders deleting previous files?

**Comment by Blisto91** [comment]
@Savoy4574 Are you able to post a new steam system information report? Just do the same as first time but wait at least 15 seconds before copying the text as it will still be collecting information in the background.

**Comment by Savoy4574** [comment]
https://gist.github.com/Savoy4574/4f837727a3cc84e6fb5d601df3927d9a
@Blisto91 Ah, sorry, yes, I see the extra information now.

**Comment by kisak-valve** [comment]
Vulkan is broken in general on your system (https://gist.github.com/Savoy4574/4f837727a3cc84e6fb5d601df3927d9a#file-gistfile1-txt-L173-L185 and https://gist.github.com/Savoy4574/4f837727a3cc84e6fb5d601df3927d9a#file-gistfile1-txt-L332-L343) which goes along with `/usr/share/vulkan/icd.d/nvidia_icd.json` missing. I'd expect this to come from [`libnvidia-gl-510`](https://packages.ubuntu.com/bionic-updates/amd64/libnvidia-gl-510/filelist) on your system. Maybe try re-installing the system package?

**Comment by Savoy4574** [comment]
https://gist.github.com/Savoy4574/898c2d7d61bd03607d3e1523119cc413
I did what I could to update the drivers and make sure vulkan is corrected. I now have `nvidia_icd.json` in `/usr/share/vulkan/icd.d/` and attached a new gist with system information (where it has nvidia for the GPU). I had a lot of issues and had to reinstall the software stack that the manufacturer has and then got stuck in the login loop. I'm not even sure which of the 100 solutions I tried that ended up getting past the login loop. The current driver I have is NVIDIA-SMI 515.49.05    Driver Version: 515.49.05    CUDA Version: 11.7. Now when I try to run any games, it doesn't recognize the GPU with the error message `A D3D11-compatible GPU (Feature level 11.0, Shader Model 5.0 is required to run this engine)`

**Comment by kisak-valve** [comment]
To state the obvious, Vulkan is still broken in general on your system (https://gist.github.com/Savoy4574/898c2d7d61bd03607d3e1523119cc413#file-gistfile1-txt-L172-L186 and https://gist.github.com/Savoy4574/898c2d7d61bd03607d3e1523119cc413#file-gistfile1-txt-L329-L343). You still have a system config issue with your NVIDIA driver install.

Overall, reading your system information, it looks like you're now running a GNOME/Wayland user session on the Intel GPU, and the NVIDIA driver install is inconsistent between 32 bit and 64 bit arches. The NVIDIA proprietary driver requires that that video driver's running kernel module, 64 bit userspace libraries, and 32 bit userspace libraries are all installed and exactly the same version to work properly. It looks like you have mangled 515.49.05 and 510.73.05 drivers installs together.

**Comment by Savoy4574** [comment]
So how do I fix it in a way that won't prevent me from ever logging in again or causing other larger problems than just never using steam again?

**Comment by Savoy4574** [comment]
Finally got it working. Thank you for the support in direction for what was wrong

**Comment by kisak-valve** [comment]
Glad to here it's behaving. Closing because this was a system configuration issue.
