### ISSUE TITLE
Ready or Not (1144200)

### ISSUE THREAD

**Issue by domve** [ValveSoftware/Proton#5985]
# Compatibility Report
- Name of the game with compatibility issues: Ready or Not
- Steam AppID of the game: 1144200

## System Information
- GPU: AMD Radeon RX 6700 XT
- Driver/LLVM version: Mesa 22.1.3
- Kernel version: 5.18.9
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/domve/3a7a356ee552bf6f16882d6d47ab8333
- Proton version: Proton Experimental and Proton 7.0-3

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms
Random long stutters on GNOME 42.3 using Xorg, making the game very choppy and nearly unplayable. They seem to happen much more frequently when focused directly on the game window, so I imagine this is likely something related to X or GNOME.

This issue is completely absent on Wayland.

## Reproduction
Launch the game using either DX11 or DX12 on Xorg, enter a single player session, observe a lot of choppiness and stutters.

[steam-1144200.log](https://github.com/ValveSoftware/Proton/files/9091063/steam-1144200.log)

**Comment by DomiStyle** [comment]
Is there a way to get the mod.io integration for this game working via Proton? I just get a "mod.io SDK was not initialized" message.

**Comment by rKsanu2MMYvypWePtQWM** [comment]
I too get the same message when playing this game.

**Comment by PoorPocketsMcNewHold** [comment]
Can confirm. Had it happen around the Adam update. The strange thing, was that it had worked for a while in the supporter branch.
From the mod.io integration log, and as reported too by `I Love China#6722` on Discord :
```
[TIMESTAMP][Info][File] Overriding RootLocalStoragePath to Z:\mnt\sda1\SteamLibrary\steamapps\common\Ready Or Not\ReadyOrNot\Content\Paks\mod.io\
[TIMESTAMP][Warning][File] Failed to create directory: Z:\mnt\sda1\SteamLibrary\steamapps\common\Ready Or Not\ReadyOrNot\Content\Paks\mod.io\, with code: 50 and message Request not supported.
[TIMESTAMP][Warning][Core] SDK is not initialized. Cannot Enable Mod Management.
```
And such, even if we manually change the RootLocalStoragePath for that folder manually, nor create the mod.io folder ourselves. Could it be just an issue with the path ?

**Comment by kisak-valve** [comment]
Ready or Not Vram Leak

Issue transferred from https://github.com/ValveSoftware/Proton/issues/6639.
@Agreeable-f posted on 2023-03-23T15:09:25:

# Compatibility Report
- Name of the game with compatibility issues: Ready or Not
- Steam AppID of the game: 1144200

## System Information
- GPU: RTX 3060ti OC 8GB
- Driver/LLVM version: nvidia 535.89.02
- Kernel version:  6.2.7-zen1-1-zen
- DE: KDE Plasma 5.27.3
- WM: KWin (X11)
- Link to full system information report as Gist: [System Info Report](https://gist.github.com/Agreeable-f/2375e518fc5ac60faaeb3e3398abf8f4)
- Proton version: 7.0-6, Proton Experimental, GE-Proton7-51

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.



## Symptoms 

when loading into the main menu from startup the game takes up about 4.1GiB of vram. then when loading into the pre-game lobby it goes up to about 6.1GiB. then when loading into a game it will take up 7.8/8 GiB or for larger maps it will outright crash saying it ram out of video memory. the way it fills the Vram is similar to a ram leak however occuring on the video memory. this issue/behaviour does not happen on windows

## Reproduction

1. Start the game in either DX12 or DX11.
2. observe vram usage (i'm using KDE's plasma system monitor with vram usage shown on the gpu's history)
3. load into a pre-game lobby. (i joined a friend's private pre-game lobby as we were playing the game. not sure it matters but noting it for consistency)
4. observe Vram usage
5. load into a map. (the maps that crashed for me that were tested so far were neon clubhouse and valley of the dolls. 4u gas station was a case that used 7.8GiB of ram without crashing)
6. Observe Vram usage
7. if loaded into a map that crashes, observe the error message.

## Final notes

This was also tested in the ProtonGE discord on an amd card. same behaviour occurs where their Vram gets filled, however they had more Vram and did not crash.

The game's minimum spec requirements denote a gpu with 2GB of Vram. 8GiB should be more than enough on a 3060ti however it is still filled. The recommenced spec state 6GB Vram which is still below the 8GiB of my card

**Comment by SoraBytes** [comment]
This method I posted for Garry's Mod, also works for mods in Ready or Not (Will fix the Mod IO SDK initialization issue)

https://github.com/ValveSoftware/Proton/issues/2848#issuecomment-1384818821

You can use any recent version of Proton (I'm on Experimental) and you do not need to opt into a Beta for this game. Simply follow the "outside of steam" symlink instructions and apply it to this game, and its compatdata prefix instead.

**Comment by pspirichev** [comment]
> This method I posted for Garry's Mod, also works for mods in Ready or Not (Will fix the Mod IO SDK initialization issue)
> 
> [#2848 (comment)](https://github.com/ValveSoftware/Proton/issues/2848#issuecomment-1384818821)
> 
> You can use any recent version of Proton (I'm on Experimental) and you do not need to opt into a Beta for this game. Simply follow the "outside of steam" symlink instructions and apply it to this game, and its compatdata prefix instead.

You're living legend, works perfectly for me. Also, Lutris always install games on wine's drive c, it's strange that Valve's proton install games outside of wine directory.

**Comment by SoraBytes** [comment]
As someone else pointed out below my original fix, it can be made even easier with "PROTON_SET_GAME_DRIVE=1 %command%" in the launch parameters, and Valve can easily fix it by applying to the fixes they run per game.

When I originally found that fix I was not aware of the "PROTON_SET_GAME_DRIVE" usefulness or a valid reason to even use it because a lack of documentation.

**Comment by kisak-valve** [comment]
Ready or Not (1144200)

Issue transferred from https://github.com/ValveSoftware/Proton/issues/7345.
@Doomguy1364 posted on 2023-12-14T04:54:59:

Compatibility Report
- Name of the game with compatibility issues: Ready or Not
- Steam AppID of the game: 1144200

System Information
- GPU: GTX 3070
- Video driver version: Nvidia proprietary 545.29.06-5
- Kernel version: 6.6.6-arch1-1
- Link to full system information report: https://gist.github.com/Doomguy1364/748e7b5bfc0d8cd421b788fde5d46a74
- Proton version: 8.0-4 and Experimental

I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-1144200.log](https://github.com/ValveSoftware/Proton/files/13668538/steam-1144200.log)

Symptoms:

Under DX12 the game will experience EXTREME freezing and stuttering with-in a few minutes of playing; I do use shader pre-caching, unfortunately it does not seem to help.
As of the 1.0 update for this game DX12 runs at roughly 60% higher FPS over DX11, however it is far from smooth at time of testing!

Reproduction: Always

Play the game for a few minutes on DX12, Extreme stutter and freezing.

**Comment by kisak-valve** [comment]
Ready or Not 1144200

Issue transferred from https://github.com/ValveSoftware/Proton/issues/7347.
@fortunef posted on 2023-12-14T09:42:14:

# Compatibility Report
- Name of the game with compatibility issues: Ready or Not
- Steam AppID of the game: 1144200

## System Information
- GPU: NVIDIA GTX 1650 Mobile
- Video driver version: NVIDIA 545.29.06
- Kernel version: 6.6.6-zen1-1-zen
- Link to full system information report as [Gist](https://gist.github.com/fortunef/977b409462dc161e2f86d03868ffc013):
- Proton version: Proton Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
 
The game is incredibly slow. And for some reason, Steam didn't pre-process the shaders 

## Reproduction

Launch the game in commander mode. Low and unstable framerate
[steam-1144200.log](https://github.com/ValveSoftware/Proton/files/13671499/steam-1144200.log)

**Comment by LuxLucian** [comment]
Was having perfectly fine performance with about 75fps until I moved my PC (Same hardware, monitor, etc) and no software changes. Now I'm getting about 15fps. Resetting prefix and verifying files has done nothing, alongside multiple proton versions.

Kernel: Linux 6.12.7-arch1-1
CPU: AMD Ryzen 5 3600 (12) @ 3.60 GHz
GPU: AMD Radeon RX 5700 XT [Discrete]

EDIT: Seems to have fixed itself, I'll update if it happens again. I am using Proton Hotfix, hopefully that might help other people.

**Comment by kisak-valve** [comment]
Ready or Not - 1144200 crashes after first logo intro on Linux Mint 22.2 (Kernel 6.8)

Issue transferred from https://github.com/ValveSoftware/Proton/issues/9059.
@b3lz3bu posted on 2025-09-21T16:13:03:

Compatibility Report
Name of the game with compatibility issues: Ready or Not
Steam AppID of the game: 1144200

System Information
GPU: NVIDIA GeForce RTX 3060 Ti Lite Hash Rate
Video driver version: NVIDIA 580.65.06
Kernel version: 6.8.0-83-generic
OS Linux Mint 22.2 Zara - Cinnamon 6.4.8 - X11

Proton version: GE-Proton10-15

I confirm:
[ ] that I haven't found an existing compatibility report for this game.
[ ] that I have checked whether there are updates for my system available.

Symptoms
The game crashes immediately after the splash screen/intro. This problem started occurring after updating the operating system to Linux Mint 22.2. A manual analysis of the Proton log revealed an error related to the winebth driver.

Reproduction
Launch the game from the Steam client.
The game starts, but after the intro screen, it crashes without reaching the main menu.
The issue persists across different Proton versions, including GE-Proton10-15.
The problem seems to be a regression caused by the Linux Mint 22.2 update (Ubuntu 24.04 kernel 6.8).

The specific error from the log file is:
16359.572:0094:00a0:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\\Registry\\\\Machine\\\\System\\\\CurrentControlSet\\\\Services\\\\winebth": c0000142
16359.572:0030:0034:fixme:service:scmdatabase_autostart_services Auto-start service L"winebth" failed to start: 1114

[steam-1144200.log](https://github.com/user-attachments/files/22452850/steam-1144200.log)

**Comment by simifor** [comment]
@b3lz3bu the game is working fineon my nvidia laptop (linux 6.16.7, nvidia 580.82.09) with proton 9/10/exp. GE proton is a third party project, so switch out to stock proton 10, verify the game files, delete the existing prefix folder and then get new logs if the game is still crashing, for both dx11 and dx12.

The create driver error is a red herring and won't prevent the game form reaching the main screen.

**Comment by b3lz3bu** [comment]
Thanks for the response and for your help.

I appreciate the advice, but as I specified in my original report, I have already tried resetting the shader cache, verifying the game files, and testing different Proton versions, including stock Proton 10.0-3, but the problem persists.

Furthermore, the log file I attached is not a "red herring." It clearly shows that the game crashes at the exact moment the `winebth` service driver fails to load, with a fatal error code that halts the process. The cause of the issue is a specific regression due to the Linux Mint 22.2 kernel 6.8 update, which was not present in previous versions.

The purpose of this report is to flag this specific behavior to allow developers to investigate this unique combination of kernel and driver.

Thanks for your understanding.

**Comment by simifor** [comment]
@b3lz3bu those errors are part of a working launch. The game works fine on my amd desktop and nvidia laptop, and those errors are present in logs from both.

[p10-steam-1144200.log](https://github.com/user-attachments/files/22501827/p10-steam-1144200.log)

GE proton is a third party project, you need to bring logs for stock proton because you want them to be as relevant as possible. Deleting the prefix also avoids any issues that may crop up from carrying a "dirty" prefix, while these don't happen often, it's a good idea to rule it out because when they do crop up they cause unexpected issues.

Also attach a log for both the DX11 and DX12 versions of the game to have more information.

It could also help to have kernel logs in case they contain something important, you can get a text file in your home folder with said logs by running this on your terminal: `sudo dmesg > dmesg.log`. Do so in a boot session where you've already attempted to run the game.

**Comment by kisak-valve** [comment]
Ready Or Not mods option not working

Issue transferred from https://github.com/ValveSoftware/steam-for-linux/issues/12370.
@UnknownTsunami posted on 2025-10-09T20:11:21:

#### Your system information

* Steam client version: 1759461205
* Distribution: Kubuntu 24.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: Does not exist
* GPU: AMD

#### Please describe your issue in as much detail as possible:
I want to begin using mods in Ready Or Not on Kubuntu but i can't since the mods option blocks my mouse and keyboard inputs from even pressing the mods button again or any other buttons on the left side of the main menu when the mods option is pressed. This makes me have to restart the game to even be able to do anything else in it since it seems to have "kicked my inputs" of the game window. The only thing i've found that can be some what interacted with is the friends drop down button in the bottom right corner. It's the only one that even lights up when hovering over it and that i am able to press after hitting the mods option. //tnx for reading and hope you have a great day!

#### Steps for reproducing this issue:

1. Launch Ready Or Not and get into the main menu.
2. Press Mods button in main menu and get mostly input locked.

<img width="3439" height="1437" alt="Image" src="https://github.com/user-attachments/assets/9d3240aa-8da5-46f5-aee3-c53f7e44ede7" />

<img width="3439" height="1437" alt="Image" src="https://github.com/user-attachments/assets/c8638f77-4b25-4665-8428-c08ebb55b1f8" />

**Comment by err0r2k** [comment]
I also can not launch the game anymore.

With DirectX12 the game crashes directly and with DirectX11 I can see the game menue for a second and then it will crash.
Tried cachy-os-proton, proton-de, Proton 9, Proton10, Proton experimental.

Hardware is AMD and up2date.

[steam-1144200.log](https://github.com/user-attachments/files/22864010/steam-1144200.log)

**Comment by kisak-valve** [comment]
Hello @err0r2k, can you check how the game behaves with the launch options set to `PROTON_DISABLE_NVAPI=1 %command%`? I suspect there's a DXVK <-> DXVK-NVAPI init loop.

**Comment by err0r2k** [comment]
> Hello [@err0r2k](https://github.com/err0r2k), can you check how the game behaves with the launch options set to `PROTON_DISABLE_NVAPI=1 %command%`? I suspect there's a DXVK <-> DXVK-NVAPI init loop.

It is already solved and it was my mistake. After uninstalling the game, there were some files left in the folder. These files are from [OptiScaler](https://github.com/optiscaler/OptiScaler) which I tested some weeks ago but forgot about it. I deleted the folder and reinstalled the game. It is working now with proton-cachyos and DirectX12.

**Comment by kisak-valve** [comment]
Ready or Not (1144200) crashes ~9s after launch with repeating Exception 0xc0000005 in ReadyOrNotSteam-Win64-Shipping.exe

Issue transferred from https://github.com/ValveSoftware/Proton/issues/10030.
@MXL712 posted on 2026-08-02T15:25:54:

**System info:**
- Distro: CachyOS
- Kernel: 7.1.5-1-cachyos-bore
- GPU: NVIDIA GTX 1050 Ti Mobile
- Driver: 580 series
- Proton version tested: GE-Proton10-34 (also tried Proton Experimental, Proton Hotfix - same result)
- Filesystem: btrfs (also tested on NTFS with identical result, so filesystem is not the cause)

**Steps I've already tried (all failed to fix it):**
- Deleted mod data / verified game files via Steam
- Deleted and recreated the Proton prefix from scratch
- Moved the game from an NTFS library to a fresh btrfs partition, clean install, same crash
- Tested with both -dx11 and default DX12, same crash either way
- Tested with Launch Options set to just %command% (no extra flags)
- Confirmed no leftover .pak mod files in ReadyOrNot/Content/Paks
- Confirmed GPU driver matches kernel (580 series, no mismatch)

**What happens:**
Game launches, runs for about 8-9 seconds, then crashes. Process exits with code 3. The game's own crash reporter dialog appears ("Ready Or Not has encountered a critical error and could not recover"), but its resources.dll fails to load so it can't actually submit a report (FileNotFoundException for CrashReporter.resources.dll).

**Relevant Proton log excerpt:**
The crash is a repeating Access Violation (Exception 0xc0000005), happening ~24 times within under a second right before the game exits:

7257.387:0140:0148:warn:seh:dispatch_exception backtrace: --- Exception 0xc0000005.
7257.387:0140:0148:warn:seh:virtual_unwind backtrace: ntdll.dll + 00000000000389AC.
7257.387:0140:0148:warn:seh:virtual_unwind backtrace: ntdll.dll + 00000000000386C6.
7257.387:0140:0148:warn:seh:virtual_unwind backtrace: ReadyOrNotSteam-Win64-Shipping.exe + 0000000000C0D471.

This exact pattern (same offset, same exception) reproduces identically across different Proton versions, different filesystems, and a completely clean prefix.

Full Proton log attached below.

[steam-1144200.txt](https://github.com/user-attachments/files/30634346/steam-1144200.txt)

**Comment by benkalmus** [comment]
Still reproducible post-v1.5.2 (Mission Editor update, Sep 3 2026) - crash in FAsyncLoadingThread; `-NoAsyncLoadingThread` launch option fixes it.

**System:**
- CachyOS (Arch-based), kernel 7.2.4-3-cachyos, ntsync enabled
- GPU: AMD RX 7900 XT/XTX (Navi 31), Mesa RADV
- Proton versions tested: Proton Hotfix (`hotfix-20260828`), GE-Proton11-6, proton-cachyos-11.0 - crash is identical on all

**Symptoms:** game launches, runs ~10s, get a whitescreen and, then UE fatal error:

```
Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0xffffffffffffffff
Crash in runnable thread FAsyncLoadingThread
0x00006ffff3bdf9e8 ReadyOrNotSteam-Win64-Shipping.exe!UnknownFunction []
```

Proton log excerpt (GE-Proton11-6, DX12):

```
622.387:0150:02f4:dispatch_exception code=c0000005 (EXCEPTION_ACCESS_VIOLATION)
622.387:0150:02f4:dispatch_exception  info[1]=FFFFFFFFFFFFFFFF
622.387:0150:02f4:warn:seh:virtual_unwind backtrace: 00006FFFF3BDF9E8: L"ReadyOrNotSteam-Win64-Shipping.exe" + 0000000000DEF9E8.
```

**Already tried, no effect:**
- Verified game files, fresh Proton prefix
- Mods fully disabled (mod.io paks + ReadyOrRealism difficulty files), no leftover mod.io caches in prefix
- DX11 and DX12, `PROTONFIXES_DISABLE=1`, `PROTON_NO_NTSYNC=1`, `PROTON_DISABLE_NVAPI=1`, `PROTON_USE_XALIA=0`

**Workaround found:** adding `-NoAsyncLoadingThread` to launch options lets the game reach the main menu and run reliably.  

Full Proton log: https://gist.github.com/benkalmus/0e6719a667328fcdabcf190e3639296a
