### ISSUE TITLE
Judgment (2058180)

### ISSUE THREAD

**Issue by PaulcPaul** [ValveSoftware/Proton#6156]
# Compatibility Report
- Name of the game with compatibility issues: Judgment
- Steam AppID of the game: 2058180

## System Information
- GPU: RTX 3060 TI
- Driver/LLVM version: NVIDIA 515.65.01
- Kernel version: 5.19.8-200.fc36.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/PaulcPaul/ca28c65c0491d7efbe45b670577ede7c
- Proton version: Proton Experimental, 7.0-4 and 6.3-8

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Game hangs in the first "Tailing" mission as soon as the game is supposed to show you how to hide from the person you're supposed to be tailing.

I've tried this on Proton Experimental, 7.0-4 and 6.3-8, all giving the same results.

[steam-2058180-6.3-8.log](https://github.com/ValveSoftware/Proton/files/9570615/steam-2058180-6.3-8.log)
[steam-2058180-7.0-4.log](https://github.com/ValveSoftware/Proton/files/9570617/steam-2058180-7.0-4.log)
[steam-2058180-experimental.log](https://github.com/ValveSoftware/Proton/files/9570619/steam-2058180-experimental.log)

## Reproduction
Simply start the game and play through it normally until you reach the first "Tailing" mission (which is right at the start of the game), wait enough time and the game will hang as it seemingly tries to show you a small tutorial on how to hide from your "victim". The moment I'm talking about can be seen in the following video and timestamp: https://youtu.be/GoMF004uALc?t=823

**Comment by RodoMa92** [comment]
Just tried the introduction sequence on Steam Deck with proton GE, no issues detected. It's probably a Nvidia only issue.

**Comment by PaulcPaul** [comment]
> Just tried the introduction sequence on Steam Deck with proton GE, no issues detected. It's probably a Nvidia only issue.

I guess it could be a particular issue with my installation, but it doesn't happen to all NVIDIA users as you can see reports on protondb of the game running just fine under the same drivers and kernel as me.

After a day I tried launching the game again and sadly I'm getting this error screen instead of the game launching at all. The link itself is not helpful as one would expect.

![Untitled](https://user-images.githubusercontent.com/17973063/190422090-b0bad80f-1d91-4cb6-86f9-d84764cf3e9b.png)

And here are the logs, not sure how helpful they are either. Experimental, 6.3, 7.0 and even GE give the same results. There were no OS updates from the time I turned off my PC to the time I tried launching the game again.
[steam-2058180.log](https://github.com/ValveSoftware/Proton/files/9575852/steam-2058180.log)

Edit: I should say, there was a game update but I have no idea what it changed, nor do I know how to look it up.

**Comment by RodoMa92** [comment]
The error you see there is the activation limit trip from Denuvo. It’s not a game error, you have just changed too many Proton version and triggered the typical 5 activation checks from your account on Denuvo’s servers.

After 24 hours you will be able to activate it again.

EDIT: I should say probably, since IIRC the message for the activation trip was far more direct. Checked quickly your hardware, I do not see anything particularly out of line. Sorry :(

**Comment by RodoMa92** [comment]
By the way, I can’t really see errors in your wine log, AFAICS. I hope that someone else will be more useful/experienced than me and maybe fix your issue :)

**Comment by PaulcPaul** [comment]
> The error you see there is the activation limit trip from Denuvo. It’s not a game error, you have just changed too many Proton version and triggered the typical 5 activation checks from your account on Denuvo’s servers.

I did not know about that, thank you! I was going to debug the game more today but looks like I'll have to wait. And thanks for the general help too!

**Comment by PaulcPaul** [comment]
I got the opportunity to test things out again and the same thing happens, i.e the game hangs at the first Tailing mission tutorial. The logs go on like below forever, so I assume some thread deadlocked or something.

> 4575.238:0148:01dc:err:sync:RtlpWaitForCriticalSection section 00007FFFC56D48E0 "?" wait timed out in thread 01dc, blocked by 01cc, retrying (60 sec)
> 4640.236:0148:01dc:err:sync:RtlpWaitForCriticalSection section 00007FFFC56D48E0 "?" wait timed out in thread 01dc, blocked by 01cc, retrying (60 sec)
> 4705.227:0148:01dc:err:sync:RtlpWaitForCriticalSection section 00007FFFC56D48E0 "?" wait timed out in thread 01dc, blocked by 01cc, retrying (60 sec)
> 4770.227:0148:01dc:err:sync:RtlpWaitForCriticalSection section 00007FFFC56D48E0 "?" wait timed out in thread 01dc, blocked by 01cc, retrying (60 sec)
> 4835.232:0148:01dc:err:sync:RtlpWaitForCriticalSection section 00007FFFC56D48E0 "?" wait timed out in thread 01dc, blocked by 01cc, retrying (60 sec)
> 4900.232:0148:01dc:err:sync:RtlpWaitForCriticalSection section 00007FFFC56D48E0 "?" wait timed out in thread 01dc, blocked by 01cc, retrying (60 sec)
> 4965.240:0148:01dc:err:sync:RtlpWaitForCriticalSection section 00007FFFC56D48E0 "?" wait timed out in thread 01dc, blocked by 01cc, retrying (60 sec)
> 5030.241:0148:01dc:err:sync:RtlpWaitForCriticalSection section 00007FFFC56D48E0 "?" wait timed out in thread 01dc, blocked by 01cc, retrying (60 sec)

Full logs: [steam-2058180.log](https://github.com/ValveSoftware/Proton/files/9583759/steam-2058180.log)

Then I decided to, instead of triggering the tutorial of the mission, just run in front of the guy I'm tailing like the dumbest detective in Japan and this happened.

> 7726.966:011c:0130:err:virtual:virtual_setup_exception stack overflow 1808 bytes in thread 0130 addr 0x170046edb stack 0xf208f0 (0xf20000-0xf21000-0x1120000)

Full logs: [steam-2058180.log](https://github.com/ValveSoftware/Proton/files/9584096/steam-2058180.log)

I also tried some flags to no avail, both errors can be reproduced every time in both situations.

**Comment by yoyossef** [comment]
I am getting GPU hangs on my 6900XT when the camera is pointed to the sky [steam-2058180.log](https://github.com/ValveSoftware/Proton/files/10777264/steam-2058180.log)

I have explained the issue in further details there https://gitlab.freedesktop.org/mesa/mesa/-/issues/8274

Is anyone else reproducing this?

**Comment by atahanacar** [comment]
> I am getting GPU hangs on my 6900XT when the camera is pointed to the sky

I can confirm this issue on my 6750XT. Only happens in daytime. Pointing to the night sky is completely fine.

I also have a problem with the tailing mission, where the target won't start walking and instead be stuck in a "fighting stance animation" loop. Pushing the target a little bit seems to trigger the hiding tutorial, but after the target does the "looking back to check" animation, he is stuck back in the fighting stance loop. This essentially makes it impossible to progress.

**Comment by NNxCLUTCHERxRS** [comment]
can confirm this issue on:

Steam: Flatpak
OS: Clear Linux OS; Build-ID: 39610
Kernel: 6.4.3-1333.native (split_lock_detect=off)
DE: Gnome 44.3
CPU: 12th Gen Intel® Core™ i5-12400F
GPU: ASUS DUAL RX 6500 XT
Monitor: acer Predator X25 360 Hz
Proton versions tested: GE-Proton8-6, GE-Proton7-47, Proton Experimental, Proton 8.0-2

doesn't make a difference if capped or uncapped fps

**Comment by ghost** [comment]
> > I am getting GPU hangs on my 6900XT when the camera is pointed to the sky
> 
> I can confirm this issue on my 6750XT. Only happens in daytime. Pointing to the night sky is completely fine.
> 
> I also have a problem with the tailing mission, where the target won't start walking and instead be stuck in a "fighting stance animation" loop. Pushing the target a little bit seems to trigger the hiding tutorial, but after the target does the "looking back to check" animation, he is stuck back in the fighting stance loop. This essentially makes it impossible to progress.

Can confirm this issue on an RX 6700XT, hanging for a minute or so before the gpu stops outputting to the screen. For me, this happens specifically on the south end of the map, facing the invisible wall, or at the north east corner during the day, both times looking towards the sky. This hang also happens during the first chase of the game, when the camera is panned up towards the sky.

**Comment by mbriar** [comment]
For anyone having problems with gpu hangs when looking at the sky at day time on AMD GPUs, this seems to be exclusive to Mesa/RADV and works fine with amdvlk, so using amdvlk for this game for the time being is an option.

For reference, here's the corresponding mesa bug report: https://gitlab.freedesktop.org/mesa/mesa/-/issues/9519

**Comment by mbriar** [comment]
Turns out the hangs were a vkd3d-proton bug and should be fixed in proton experimental bleeding edge now.

**Comment by Even749** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/6156#issue-1373710452

Kinda necroposting, but one full year later, many Proton and drivers update and this is still relevant.
I'm on GTX2080Super. Still can't find a solution, i guess i'm going to give it up and refund

**Comment by oddmechanism** [comment]
> I also have a problem with the tailing mission, where the target won't start walking and instead be stuck in a "fighting stance animation" loop. Pushing the target a little bit seems to trigger the hiding tutorial, but after the target does the "looking back to check" animation, he is stuck back in the fighting stance loop. This essentially makes it impossible to progress.

I had the same problem with the tailing mission. Tried switching to Proton Experimental, 8, and 7, none of them fixed the issue. I got past it by booting into Windows and played through the game for a while before trying again in Proton Experimental, where I encountered a couple other issues: the "friends" that randomly walk around the map (the NPCs with smiley face icons) standing completely still, and a chase sequence in "The Ghost Tenant" side mission that softlocks the game.

**Comment by wired-maya** [comment]
I have a 3070 and am having the exact same freezing issue on the tailing mission. I've had it consistently for about 5 months now preventing me from playing the game. No change in launch options, proton version, or in-game options fixes it.

**Comment by NNxCLUTCHERxRS** [comment]
I changed my distro from Clear Linux to CachyOS and it worked without issues with the native steam client. @wired-maya are you using the  flatpak version of steam?

**Comment by wired-maya** [comment]
> I changed my distro from Clear Linux to CachyOS and it worked without issues with the native steam client. @wired-maya are you using the flatpak version of steam?

I am using pacman version of Steam. Might be a package issue if changing OS fixes it. Are you on Flatpak?

**Comment by NNxCLUTCHERxRS** [comment]
I will test on flatpak now

**Comment by NNxCLUTCHERxRS** [comment]
@wired-maya I switched back to Clear Linux and on the flatpak version it just crashes when starting the tailing mission. Unfortunately I dont have Arch installed right now to test the native steam version. maybe try the steam version from Cachyos https://github.com/CachyOS/linux-cachyos#cachyos-repositories

**Comment by wired-maya** [comment]
I'll try that.

I'll document what I've tried and did not work to hopefully narrow down the issue:
- Tried running with Proton Experimental, 7.0-6, GE 8.32, GE 7.35
- Tried running with the launch options `gamemoderun RADV_PERFEST=ext_ms %command%`
- Tried running with the launch options `DXVK_ASYNC=1 PROTON_HIDE_NVIDIA_GPU=0 PROTON_ENABLE_NVAPI=1 VKD3D_CONFIG=dxr %command%`
- Tried upping `vm.max_map_count` to the maximum amount [as per the Arch Wiki](https://wiki.archlinux.org/title/gaming#Game_compatibility) (this is on max on the Steam Deck)
- Full reinstall of the game including removing compatdata folder and the left behind files in common
- Changed in-game settings to the same as the Steam Deck's pre-defined settings

The game works fine on the Steam Deck for me. Because it worked with CachyOS for you I am assuming either they patched Steam or there is a package installed on the system/with Steam that fixes the issue. Perhaps the CachyOS repos have different dependencies for Steam? I'll try it out.

If it doesn't work whatsoever I will most likely switch to CachyOS, however it would be nice to know what the issue is.

**Comment by wired-maya** [comment]
Switched to CachyOS repos, it did not fix the issue for me. There is no alternate version of Steam on their repos it seems (it's just on multilib repo), so it could be an extra package that comes installed with the OS.

On another note, the repos made Firefox hang and Judgement stutter, so I'm switching back to default repos. Odd.

**Comment by NNxCLUTCHERxRS** [comment]
@wired-maya I will test the first tailing mission on CachyOS in ~30 min. Investigating bad performance in Counterstrike 2 right now xD

**Comment by NNxCLUTCHERxRS** [comment]
@wired-maya WORKS! used proton 8.0-5 (used unpackaged steam I will try now with steam from arch repo)

**Comment by NNxCLUTCHERxRS** [comment]
@wired-maya steam from arch repo also works

**Comment by NNxCLUTCHERxRS** [comment]
I found a bug with Hyprland when using my mouse the sensitivity is extremely high (Gamepad works as expected) could someone test with a different DE?

**Comment by wired-maya** [comment]
mouse works as expected for me on KDE

**Comment by NNxCLUTCHERxRS** [comment]
@wired-maya thank you for testing

**Comment by wired-maya** [comment]
Tried comparing installed packages between a fresh CachyOS install, my steam deck, and my PC, installing packages which were on the steam deck and CachyOS but not my PC. No luck, nothing worked. :(

**Comment by NNxCLUTCHERxRS** [comment]
@wired-maya I suggest to install CachyOS on a spare SSD or if you have enough space dual boot with your existing install of arch.

**Comment by simifor** [comment]
@Zeioth sorry can you be more specific about your issue? your original issue seemed to be about chapter 2 but the are comments there about chapter 1 as well. I'm guessing your case was about the masked guy you have to chase, if so, what proton versions have you tried?

When using proton 9, the chase was interrupted by the guy getting stuck in the mall, but I could complete it normally on proton 10 and experimental.

**Comment by Zeioth** [comment]
@simifor I had no issue where OP reports.

I'm speaking about the first mission of chapter 2, and I can 100% reproduce every time on every proton/wine version. This is the exact point when it happens on my case: https://youtu.be/_zD9axxK46U?t=646

**Comment by simifor** [comment]
@Zeioth in my case, with my desktop, when I tried on proton 9, it soft locked once (second try it worked fine) due to the chasee running in place, but that was only after reaching the mall and it didn't happen on either experimental or proton 10 either. Also tried on deck with proton 9 through exp and it worked fine in all of them. 

Can you give information about your setup? There might be something there causing this issue to appear more on your end.

**Comment by Zeioth** [comment]
@simifor I've tried with proton 9, 10, and experimental, and I still experience it. I'm using just regular steam on arch Linux. Nothing special. amd mesa drivers.

**Comment by simifor** [comment]
@Zeioth you haven't specified what is that happens on your end. I know it happens at the start of the chase but not exactly what. I've retried a bunch of times on my end and it seems there's about a 1/5 chance the guy I'm chasing to run in place but eventually he'll snap back to running. What do you see on your end? 

https://github.com/user-attachments/assets/4acc380a-a6fe-4e17-96b9-ca5c165944d9

For reference, this is what I see

**Comment by cooler1972** [comment]
AMD Radeon RX 7900 XTX (radeonsi, navi31, LLVM 20.1.2, DRM 3.61, 6.14.0-37-generic)
4.6 (Compatibility Profile) Mesa 25.0.7-0ubuntu0.24.04.2
X11, Mint 22.2

Proton: Experimental, 7.0-6, Hotfix, 10.0-3, 7.0-4
GE-Proton: 10-26, 9-27, 10-9, 10-3, 10-18, 10-1

This happens in all tailing missions.
1. The intro cutscene plays.
2. The moment the cutscene ends, the game freezes.
3. NPC is stuck in a fighting stance, very close to protagonist. (Should be walking, way further up ahead)  
4. For myself, I must alt-tab to click close in Steam. Game does not respond with hotkeys like ALT+F4. The game might freeze so completely, I cannot do much except restart PC.

https://youtu.be/pDguSMIfSvk
<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/5247e1ce-17d7-4b90-b26c-9da7728fa3bd" />


> For reference, this is what I see

The chase bug happened to me first try in Linux, exact same spot, except the NPC was running in place the entire chase. 

1 year ago I had Windows 10 on this PC, where I did not encounter any of these issues.
As for right now, it works flawlessly with Steam Deck and Windows 11 (albeit laptop, RX 6800M).

**Comment by atahanacar** [comment]
Setting `PROTON_SET_GAME_DRIVE=1` fixed the tailing mission issue for me. This is caused by Denuvo as the issue doesn't exist when using the cracked exe.

**Comment by boraaydogan** [comment]
> Setting `PROTON_SET_GAME_DRIVE=1` fixed the tailing mission issue for me. This is caused by Denuvo as the issue doesn't exist when using the cracked exe.

Can confirm this works.

**Comment by cooler1972** [comment]
> Setting `PROTON_SET_GAME_DRIVE=1` fixed the tailing mission issue for me. This is caused by Denuvo as the issue doesn't exist when using the cracked exe.

that was the fix???????? omg... thank you so much

**Comment by Zeioth** [comment]
I can confirm this has been fixed in `proton-ge 10-28` on my end.
