### ISSUE TITLE
Marvel Snap (1997040)

### ISSUE THREAD

**Issue by jameshulse** [ValveSoftware/Proton#6243]
# Compatibility Report
- Name of the game with compatibility issues: Marvel Snap
- Steam AppID of the game: 1997040

## System Information
- GPU: AMD AMD Radeon RX 6700 XT
- Driver/LLVM version: LLVM 13.0.1, DRM 3.44, 5.17.5-76051705-generic
- Kernel version: 5.17.5-76051705-generic
- Proton version: 7.0-54 (older versions and GE version attempted too)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1997040.log](https://github.com/ValveSoftware/Proton/files/9816470/steam-1997040.log)

## Symptoms 

Cannot log in. It seems like there is no network connection. The error says that it cannot connect to the login servers. The issue has been confirmed by a number of Linux users in the official Marvel Snap discord.

The games log file mentions:

```
[1019/155526.615:ERROR:network_change_notifier_win.cc(140)] WSALookupServiceBegin failed with: 0
[1019/155526.774:ERROR:dxva_video_decode_accelerator_win.cc(1383)] DXVAVDA fatal error: could not LoadLibrary: msmpeg2vdec.dll: Module not found. (0x7E)
[1019/155526.775:ERROR:dxva_video_decode_accelerator_win.cc(1391)] DXVAVDA fatal error: could not LoadLibrary: msvproc.dll: Module not found. (0x7E)
[1019/155528.485:ERROR:dxva_video_decode_accelerator_win.cc(1349)] DXVAVDA fatal error: Could not load msmpeg2vdec.dll: Module not found. (0x7E)
[1019/155528.669:ERROR:network_change_notifier_win.cc(140)] WSALookupServiceBegin failed with: 0
```

## Reproduction

1. Open game
2. Click either of the login buttons

**Comment by jameshulse** [comment]
LInes of interest in the logs include:

```
5889.440:012c:0130:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
5889.441:012c:0130:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\MSV1_0.dll" at 000000039C380000: builtin
5889.451:012c:0130:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
5889.451:012c:0130:trace:loaddll:free_modref Unloaded module L"C:\\windows\\system32\\MSV1_0.dll" : builtin
5890.723:012c:028c:fixme:combase:RoGetActivationFactory (L"Windows.System.DispatcherQueue", {00000035-0000-0000-c000-000000000046}, 000000016FF5FBA0): semi-stub
5890.723:012c:028c:err:combase:RoGetActivationFactory Failed to find library for L"Windows.System.DispatcherQueue"
```

**Comment by Exellin** [comment]
Marvel Snap is working for me now without a specific proton version.  May have been fixed in the lastest patch, but I didn't see it mentioned in the patch notes.

**Comment by phlawlessDevelopment** [comment]
I can confirm it's working on proton experimental, thanks for all the great work people :)

**Comment by dequb** [comment]
Still not working for me with the exact same error both on Proton experimental and stable release (cannot communicate with the login service). Also I had to tweak the command line options (PROTON_USE_WINED3D11=1) to run with Proton experimental but that shouldn't be related, right?

**Comment by jameshulse** [comment]
Can confirm it is now working for me! I would love if someone could share what change in Proton fixed it, as I would be interested to see what the issue was.

**Comment by jameshulse** [comment]
> Still not working for me with the exact same error both on Proton experimental and stable release (cannot communicate with the login service). Also I had to tweak the command line options (PROTON_USE_WINED3D11=1) to run with Proton experimental but that shouldn't be related, right?

Try removing any command line options. It worked for me without any. I'm not sure how to ensure your Proton Experimental is up to date, but I would try and confirm you have the latest version. By all accounts this is now fixed.

**Comment by dequb** [comment]
> > Still not working for me with the exact same error both on Proton experimental and stable release (cannot communicate with the login service). Also I had to tweak the command line options (PROTON_USE_WINED3D11=1) to run with Proton experimental but that shouldn't be related, right?
> 
> Try removing any command line options. It worked for me without any. I'm not sure how to ensure your Proton Experimental is up to date, but I would try and confirm you have the latest version. By all accounts this is now fixed.

I was using the Flatpak Steam version and I suppose that Proton Experimental release is not as updated as the official one. Switched to the official one and it's working.

**Comment by otuva** [comment]
I'm experiencing the same issue on flatpak using both official versions experimental and 7.0.6. My system is up-to-date

```
1257.574:0130:0288:fixme:winsock:WSALookupServiceBeginW (000000017D9CF710 0xff0 000000017D9CF788) Stub!
1257.574:0130:0288:warn:debugstr:OutputDebugStringA "[0327/103009.304:ERROR:network_change_notifier_win.cc(140)] WSALookupServiceBegin failed with: 0\n"
1257.574:0130:0288:trace:seh:dispatch_exception code=40010006 flags=0 addr=000000007B01260E ip=000000007B01260E tid=0288
1257.574:0130:0288:trace:unwind:dispatch_exception  info[0]=0000000000000062
1257.574:0130:0288:trace:unwind:dispatch_exception  info[1]=000000017dac27b0
1257.574:0130:0288:warn:seh:dispatch_exception "[0327/103009.304:ERROR:network_change_notifier_win.cc(140)] WSALookupServiceBegin failed with: 0\n"
1257.574:0130:0288:trace:seh:call_vectored_handlers calling handler at 000000027104DEA0 code=40010006 flags=0

...

257.758:02d4:02d8:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\mfplat.dll" at 00000003A6D40000: builtin
1257.758:02d4:02d8:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\mf.dll" at 000000020FC60000: builtin
1257.759:02d4:02d8:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\msmpeg2vdec.dll" at 00000003287E0000: builtin
1257.759:02d4:02d8:warn:debugstr:OutputDebugStringA "[0327/103009.490:ERROR:dxva_video_decode_accelerator_win.cc(1391)] DXVAVDA fatal error: could not LoadLibrary: msvproc.dll: Module not found. (0x7E)\n"
1257.759:02d4:02d8:trace:seh:dispatch_exception code=40010006 flags=0 addr=000000007B01260E ip=000000007B01260E tid=02d8
1257.759:02d4:02d8:trace:unwind:dispatch_exception  info[0]=0000000000000096
1257.759:02d4:02d8:trace:unwind:dispatch_exception  info[1]=0000000000328b10
1257.759:02d4:02d8:warn:seh:dispatch_exception "[0327/103009.490:ERROR:dxva_video_decode_accelerator_win.cc(1391)] DXVAVDA fatal error: could not LoadLibrary: msvproc.dll: Module not found. (0x7E)\n"
1257.759:02d4:02d8:trace:seh:call_vectored_handlers calling handler at 000000027104DEA0 code=40010006 flags=0
```

[steam-1997040.zip](https://github.com/ValveSoftware/Proton/files/11075930/steam-1997040.zip)

**Comment by leunamd** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/6243#issuecomment-1484659429

It used to work a few days ago now I am having this same problem, tried both with Proton Experimental and Proton 7.0-6 on arch native steam package aswell as the flatpak one, I get stuck at login page and cannot connect to the servers whatsoever

[steam-1997040.log](https://github.com/ValveSoftware/Proton/files/11087711/steam-1997040.log)

**Comment by leunamd** [comment]
> > Replying to [#6243 (comment)](https://github.com/ValveSoftware/Proton/issues/6243#issuecomment-1484659429)
> 
> It used to work a few days ago now I am having this same problem, tried both with Proton Experimental and Proton 7.0-6 on arch native steam package aswell as the flatpak one, I get stuck at login page and cannot connect to the servers whatsoever
> 
> [steam-1997040.log](https://github.com/ValveSoftware/Proton/files/11087711/steam-1997040.log)

this has been fixed with yesterday's patch. Login is working again

**Comment by otuva** [comment]
> this has been fixed with yesterday's patch. Login is working again

Still experiencing the same issue with proton 8.0-1

**Comment by Klairm** [comment]
> > this has been fixed with yesterday's patch. Login is working again
> 
> Still experiencing the same issue with proton 8.0-1

I'm having same issue, when I try to connect it gets stuck on "Assembling" , I can't log in to google account it doesn't  even open the browser to connect the account
