### ISSUE TITLE
Marvin's Mittens (333260)

### ISSUE THREAD

**Issue by wantija** [ValveSoftware/Proton#6254]
# Compatibility Report
- Name of the game with compatibility issues: Marvin's Mittens
- Steam AppID of the game: 333260

## System Information
- GPU: RX 6800 XT
- Driver/LLVM version: mesa-git 22.3.0_devel.161414.53ab57e8882.d41d8cd98f00b204e9800998ecf8427e-1
- Kernel version: 6.0.2-zen
- Link to full system information report as [Gist](https://gist.github.com/wantija/346f819eb5b18014dcb6b91f638b9218):
- Proton version: Experimental

## I confirm:
- [ x ] that I haven't found an existing compatibility report for this game.
- [ x ] that I have checked whether there are updates for my system available.

[steam-333260.log.gz](https://github.com/ValveSoftware/Proton/files/9831985/steam-333260.log.gz)
Log was 30MB, easier to send compressed.

## Symptoms 
Crashes at launch

## Reproduction
Launch the game with Steam Play enabled for all other titles

**Comment by kisak-valve** [comment]
Hello @wantija, these look like some lines of interest from your log:
```
Unhandled Exception:
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
  at System.Collections.Generic.List`1[T].ForEach (System.Action`1[T] action) [0x00046] in <e70d6e9587d64cb3abb4b3f99bbf5a0d>:0 
  at Jumpman.ParticleGroupCustom.update (System.Single deltaTime, System.Collections.Generic.List`1[T] layerEntities) [0x003a5] in <ba1af77bd073493b8eb2939e5b3f288f>:0 
  at Jumpman.Layer.Update (System.Single deltaTime, System.Collections.Generic.List`1[T] layerEntities) [0x00010] in <ba1af77bd073493b8eb2939e5b3f288f>:0 
  at Jumpman.World.Update (System.Single deltaTime, System.Single totalTime) [0x001fd] in <ba1af77bd073493b8eb2939e5b3f288f>:0 
  at Jumpman.MarvinsMittens.Update (Microsoft.Xna.Framework.GameTime gameTime) [0x003b3] in <ba1af77bd073493b8eb2939e5b3f288f>:0 
  at Microsoft.Xna.Framework.Game.Tick () [0x00209] in <e4bd910e73ed465ea91e14aaab0ce109>:0 
  at Microsoft.Xna.Framework.Game.HostIdle (System.Object sender, System.EventArgs e) [0x00000] in <e4bd910e73ed465ea91e14aaab0ce109>:0 
  at Microsoft.Xna.Framework.GameHost.OnIdle () [0x00008] in <e4bd910e73ed465ea91e14aaab0ce109>:0 
  at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle (System.Object sender, System.EventArgs e) [0x00022] in <e4bd910e73ed465ea91e14aaab0ce109>:0 
  at System.Windows.Forms.Application+ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle (System.Int32 grfidlef) [0x0001a] in <73d9f63d378d41d89272ffb52da8e131>:0 
  at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop (System.IntPtr dwComponentID, System.Int32 reason, System.Int32 pvLoopData) [0x00243] in <73d9f63d378d41d89272ffb52da8e131>:0 
  at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner (System.Int32 reason, System.Windows.Forms.ApplicationContext context) [0x00282] in <73d9f63d378d41d89272ffb52da8e131>:0 
  at System.Windows.Forms.Application+ThreadContext.RunMessageLoop (System.Int32 reason, System.Windows.Forms.ApplicationContext context) [0x0001a] in <73d9f63d378d41d89272ffb52da8e131>:0 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.Application+ThreadContext.RunMessageLoop(int,System.Windows.Forms.ApplicationContext)
  at System.Windows.Forms.Application.Run (System.Windows.Forms.Form mainForm) [0x0000d] in <73d9f63d378d41d89272ffb52da8e131>:0 
  at Microsoft.Xna.Framework.WindowsGameHost.Run () [0x0002f] in <e4bd910e73ed465ea91e14aaab0ce109>:0 
  at Microsoft.Xna.Framework.Game.Run () [0x000b4] in <e4bd910e73ed465ea91e14aaab0ce109>:0 
  at Jumpman.Program.Main (System.String[] args) [0x0001a] in <ba1af77bd073493b8eb2939e5b3f288f>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
  at System.Collections.Generic.List`1[T].ForEach (System.Action`1[T] action) [0x00046] in <e70d6e9587d64cb3abb4b3f99bbf5a0d>:0 
  at Jumpman.ParticleGroupCustom.update (System.Single deltaTime, System.Collections.Generic.List`1[T] layerEntities) [0x003a5] in <ba1af77bd073493b8eb2939e5b3f288f>:0 
  at Jumpman.Layer.Update (System.Single deltaTime, System.Collections.Generic.List`1[T] layerEntities) [0x00010] in <ba1af77bd073493b8eb2939e5b3f288f>:0 
  at Jumpman.World.Update (System.Single deltaTime, System.Single totalTime) [0x001fd] in <ba1af77bd073493b8eb2939e5b3f288f>:0 
  at Jumpman.MarvinsMittens.Update (Microsoft.Xna.Framework.GameTime gameTime) [0x003b3] in <ba1af77bd073493b8eb2939e5b3f288f>:0 
  at Microsoft.Xna.Framework.Game.Tick () [0x00209] in <e4bd910e73ed465ea91e14aaab0ce109>:0 
  at Microsoft.Xna.Framework.Game.HostIdle (System.Object sender, System.EventArgs e) [0x00000] in <e4bd910e73ed465ea91e14aaab0ce109>:0 
  at Microsoft.Xna.Framework.GameHost.OnIdle () [0x00008] in <e4bd910e73ed465ea91e14aaab0ce109>:0 
  at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle (System.Object sender, System.EventArgs e) [0x00022] in <e4bd910e73ed465ea91e14aaab0ce109>:0 
  at System.Windows.Forms.Application+ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle (System.Int32 grfidlef) [0x0001a] in <73d9f63d378d41d89272ffb52da8e131>:0 
  at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop (System.IntPtr dwComponentID, System.Int32 reason, System.Int32 pvLoopData) [0x00243] in <73d9f63d378d41d89272ffb52da8e131>:0 
  at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner (System.Int32 reason, System.Windows.Forms.ApplicationContext context) [0x00282] in <73d9f63d378d41d89272ffb52da8e131>:0 
  at System.Windows.Forms.Application+ThreadContext.RunMessageLoop (System.Int32 reason, System.Windows.Forms.ApplicationContext context) [0x0001a] in <73d9f63d378d41d89272ffb52da8e131>:0 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.Application+ThreadContext.RunMessageLoop(int,System.Windows.Forms.ApplicationContext)
  at System.Windows.Forms.Application.Run (System.Windows.Forms.Form mainForm) [0x0000d] in <73d9f63d378d41d89272ffb52da8e131>:0 
  at Microsoft.Xna.Framework.WindowsGameHost.Run () [0x0002f] in <e4bd910e73ed465ea91e14aaab0ce109>:0 
  at Microsoft.Xna.Framework.Game.Run () [0x000b4] in <e4bd910e73ed465ea91e14aaab0ce109>:0 
```

**Comment by madewokherd** [comment]
This is worth a retest. The bug affecting Shenzhen I/O that was fixed in https://gitlab.winehq.org/mono/wine-mono/-/releases/wine-mono-9.0.0 may be the same as what's happening here.

**Comment by michaelneverwins** [comment]
I'm getting the same `System.InvalidOperationException` error as of today with Proton 9.0-4 as well as with Proton 10.0-1 (beta).

**Comment by madewokherd** [comment]
Looks like this is the same as https://github.com/ValveSoftware/Proton/issues/6290#issuecomment-3256326597, should be fixed next time there's a Wine Mono release.

In current Proton, this game is also affected by https://bugs.winehq.org/show_bug.cgi?id=58577 which prevents XNA3 from installing properly.

**Comment by michaelneverwins** [comment]
The game works (perfectly as far as I can tell) with the current version of Proton Experimental (identified as `1761241153 experimental-10.0-20251023` by the `version` file).

It still crashes on start of gameplay with Proton 10.0-2 (beta), so switching to Experimental is required.
