### ISSUE TITLE
Guild Wars 2 (1284210)

### ISSUE THREAD

**Issue by nyannyankas** [ValveSoftware/Proton#6547]
# Compatibility Report
- Name of the game with compatibility issues: Guild Wars 2
- Steam AppID of the game: 1284210

## System Information
I've been able to reproduce the problem on two separate systems:

1.
- GPU: RTX 3090
- Driver/LLVM version: Nvidia 525.60.11
- Kernel version: 5.19.0
- Link to full system information report as [Gist](https://gist.github.com/nyannyankas/bfc8579e89d624c5675843cfb5ce9494):
- Proton version: Proton Experimental

2.
- Steam Deck running both the Client- and System-Beta
- Proton version: Proton Experimental

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
  - There is an [existing compatibility report](https://github.com/ValveSoftware/Proton/issues/6233), but it's closed
- [x] that I have checked whether there are updates for my system available.

Proton Log with the issue: [steam-1284210.log](https://github.com/ValveSoftware/Proton/files/10769480/steam-1284210.log)
Proton Log from a few days ago, when the game was working fine: [steam-1284210.log](https://github.com/ValveSoftware/Proton/files/10769482/steam-1284210.log)

## Symptoms

The game doesn't launch anymore. It's shown as running in Steam, but the launcher never appears. This issue has only appeared in the *bleeding edge*-branch a few days ago, but is now also occuring in the regular *Proton Experimental*-branch.

The line `00c0:00c4:err:sync:RtlLeaveCriticalSection section 00007FF941E4CA60 is not acquired` is repeating in the logs, so I guess that has something to do with it.

## Reproduction

1. Launch the game
2. Nothing happens

**Comment by rjchaves** [comment]
I can confirm, the game appears as running on steam but the launcher never appears. It was introduced in a recent update of proton experimental.
The problem does not occur in proton 7.0-6 nor in proton hotfix

Here is the [system info](https://gist.github.com/rjchaves/5015924951ec692f751fc8077d978332)

**Comment by Iglu47** [comment]
I confirm, but it should by fixed on
https://github.com/ValveSoftware/wine/releases/tag/experimental-wine-7.0-20230220b
please try with this version

**Comment by LingMan** [comment]
Can confirm, the launcher starts again with the latest Proton experimental (which is presumably the version linked above).

There are two other bugs with GW2, which were originally filed against upstream wine before GW2 was on Steam, but deserve a mention here since they also show up on Proton:
- Can't swap weapons with the default controls on a German keyboard (https://bugs.winehq.org/show_bug.cgi?id=52174)
- Mouse cursor turns invisible on the launcher window until it moves over an interactable element (https://bugs.winehq.org/show_bug.cgi?id=40300)

**Comment by nyannyankas** [comment]
Can confirm that the game runs again with the current *bleeding edge* version. Thanks! :)

> * Can't swap weapons with the default controls on a German keyboard (https://bugs.winehq.org/show_bug.cgi?id=52174)

I've come across this issue a few times, but I'm not sure if Proton can fix it. It exists because the `^`-key is handled as a dead key in your keyboard layout. You can work around this issue by choosing `German (no dead keys)` as a keyboard layout in your system settings.

**Comment by LingMan** [comment]
GW2 works just fine with dead keys on Windows, so I don't immediately see why Proton would be unable to fix it. Switching to `German (no dead keys)` is an interesting workaround I wasn't aware of, but unfortunately it breaks, you know... typing. Gonna stick to my current workaround of binding weapon swap to `Q` instead.

**Comment by ahjolinna** [comment]
for me GW2 launcher gets stuck at "Initializing..." -phase, with both version of proton (7.0-6 and experimental-bleeding)

here is the log [steam-1284210.log](https://gist.githubusercontent.com/ahjolinna/aeb213fbbf15a8eba806c8206730b4b6/raw/eab85baba2a5e0c45038b39e70ea122ebbe302bb/steam-1284210.log)

----

my system spec:

```
             .;ldkO0000Okdl;.                
         .;d00xl:^''''''^:ok00d;.            OS: openSUSE MicroOS
       .d00l'                'o00d.          Kernel: x86_64 Linux 6.1.12-1-default
     .d0K^'  Okxoc;:,.          ^O0d.        Uptime: 3h 21m
    .OVVAK0kOKKKKKKKKKKOxo:,      lKO.       Packages: Unknown
   ,0VVAKKKKKKKKKKKKK0P^,,,^dx:    ;00,      Shell: bash 5.2.15
  .OVVAKKKKKKKKKKKKKk'.oOPPb.'0k.   cKO.     Resolution: 3072x1728
  :KVAKKKKKKKKKKKKKK: kKx..dd lKd   'OK:     DE: KDE 5.103.0 / Plasma 5.27.0
  lKlKKKKKKKKKOx0KKKd ^0KKKO' kKKc   lKl     WM: KWin_wayland
  lKlKKKKKKKKKK;.;oOKx,..^..;kKKK0.  lKl     GTK Theme: Breeze [GTK2],  [GTK3]
  :KAlKKKKKKKKK0o;...^cdxxOK0O/^^'  .0K:     Icon Theme: Papirus-Dark
   kKAVKKKKKKKKKKKK0x;,,......,;od  lKP      Disk: 16T / 21T (75%)
   '0KAVKKKKKKKKKKKKKKKKKK00KKOo^  c00'      CPU: AMD Ryzen 7 5700G with Radeon Graphics @ 16x 4.3GHz
    'kKAVOxddxkOO00000Okxoc;''   .dKV'       GPU: NVIDIA GeForce RTX 3060 Ti
      l0Ko.                    .c00l'        RAM: 5594MiB / 15779MiB
       'l0Kk:.              .;xK0l'         
          'lkK0xc;:,,,,:;odO0kl'            
              '^:ldxkkkkxdl:^'

**Comment by rjchaves** [comment]
> * Can't swap weapons with the default controls on a German keyboard (https://bugs.winehq.org/show_bug.cgi?id=52174)

This also happens with an ANSI keyboard on Portuguese (english int layout)  locale, my workaround is to switch to english.

**Comment by LepaBrenaa** [comment]
I have the issue that every time I launch the game, I get the `Processing Vulkan shaders` window:
![image](https://user-images.githubusercontent.com/48409293/227602250-d13599af-8159-49d2-97be-ef1bc71744a1.png)

It happens literally after every start of the game, and lasts for around a min.
I know that that window should pop up after gpu driver update, but it keeps appearing every single time even when I haven't updated my drivers.

I use Proton Experimental Bleeding Edge, Mesa-git

```
                     ./o.                   smokus@smokus-linux
                   ./sssso-                 -------------------
                 `:osssssss+-               OS: EndeavourOS x86_64
               `:+sssssssssso/.             Host: MS-7C91 (2.0)
             `-/ossssssssssssso/.           Kernel: 6.3.0-rc3-273-tkg-cfs
           `-/+sssssssssssssssso+:`         Uptime: 12 hours, 20 mins
         `-:/+sssssssssssssssssso+/.        Packages: 1516 (pacman)
       `.://osssssssssssssssssssso++-       Shell: zsh 5.9
      .://+ssssssssssssssssssssssso++:      Display 1: 1920x1080 @ 144Hz
    .:///ossssssssssssssssssssssssso++:     Display 2: 2560x1440 @ 170Hz
  `:////ssssssssssssssssssssssssssso+++.    DE: KDE Plasma 5.27.3
`-////+ssssssssssssssssssssssssssso++++-    WM: KWin (Wayland)
 `..-+oosssssssssssssssssssssssso+++++/`    WM Theme: Breeze
   ./++++++++++++++++++++++++++++++/:.      Theme: Breeze (Dark) [QT], Breeze [GTK3/4]
    `:::::::::::::::::::::::::------``      Icons: breeze-dark [QT], breeze-dark [GTK2/3/4]
                                            Font: Cantarell (11pt) [QT], Cantarell (11pt) [GTK2/3/4]
                                            Cursor: Bibata-Modern-Ice (24px)
                                            Terminal: konsole 22.12.3
                                            Terminal Font: MesloLGS NF (12pt)
                                            CPU: AMD Ryzen 9 5900X (24) @ 4.950195 GHz
                                            GPU: AMD Radeon RX 6800 XT
                                            Memory: 7.50 GiB / 31.19 GiB (24%)
                                            Disk (/): 916 GiB / 1 TiB (67%)
                                            Disk (/mnt/ExternalHDD): 1 TiB / 4 TiB (30%) [Removable]
                                            Locale: en_US.UTF-8

```

**Comment by LingMan** [comment]
**Edit:** Nevermind, game bug that happens when shadow quality is set to ultra.

-------------------------

Got some misrendering in one specific location. It's a dark room with a light in the middle. Supposed to look like this:
![Screenshot from 2023-04-08 23-36-30](https://user-images.githubusercontent.com/18645382/230744708-d333578a-5e0b-4c92-ba94-267e40c8b319.png)

For me the lighted area is very blocky instead of being a nice circle:
![Screenshot from 2023-04-08 23-48-01](https://user-images.githubusercontent.com/18645382/230744763-034bd301-3621-4b2c-ba31-f1b9fa12b966.png)


Location: Super Adventure Box: World 2 Zone 1: Hidden Room 7 (Associate of Secrets, World 2: Does the log have other secrets?).
Using Proton Experimental (non-BE) with Mesa 23.0.1 on an AMD R9 390.
DX9 renderer: broken with dxvk; broken with wined3d
DX11 renderer: broken with dxvk; game crashes on start with wined3d

My attempts to create an apitrace haven't been fruitful since it's impossible to get there with 6fps. Maybe someone with more powerful hardware has better luck. Can anybody try to reproduce on Windows to rule out a game bug?
A textual guide on how to get there: https://wiki.guildwars2.com/wiki/Rapids#Checkpoint_7_to_Checkpoint_8
Video guide on how to get there: https://youtu.be/UWyjrPp3KN8?t=610

Unfortunately Super Adventure Box is a seasonal festival and will only be available until April 18 this year (10 days from now).

**Comment by kisak-valve** [comment]
Hello @LingMan, you might have better luck getting a renderdoc capture instead of an apitrace and file a bug report with mesa for the video driver devs to ponder.

**Comment by LingMan** [comment]
Thanks for the pointer, @kisak-valve. Had a nice testing session with @Blisto91. Turns out to be a game bug that happens when shadows  are set to ultra. Same behaviour on Windows.

**Comment by ahjolinna** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/6547#issuecomment-1439552278

okay I found the solution for my MicroOS issue or more exact SELinux issue

apparently I need to run this command: `sudo setsebool selinuxuser_execmod 1` to get the game run and other (mmo) games that had the same issue

more about it here: 
https://en.opensuse.org/Portal:MicroOS/Desktop#Steam_Proton,_Bottles,_WINE,_Lutris,_Android_Studio_emulator_not_working_from_flatpaks

**Comment by svin24** [comment]
There is this odd issue were the game client seems to stop downloading randomly 
![image](https://user-images.githubusercontent.com/51864332/235757197-e44dd763-2668-4041-8c15-417c8a311ae8.png)

**Comment by LingMan** [comment]
@SViN24 I've seen that only once and it was shortly after a patch release (just like it is right now), so that's probably a server issue on Anets end.

**Comment by gozes** [comment]
So I think i have come across another small compatibility issue but only on the steam deck . Sometimes an input will get stock and keep repeating over and over again blocking any other aside from movement from taking palace. For example sometimes it will be one of the  skills for example 1 you will see the skill flashing like if you where tapping on the key but not actually being executed in the game. Only way I have found to get back to normal is to return to the chart selection screen and goo back in. I'm running it  on proton 8.1 on the steam deck. I have yet to try experimental. 

Sorry if this not the best place to report this issue.

**Comment by garpu** [comment]
Should Guild Wars 2 be processing vulkan shaders every time it loads? Or is this the processing shaders bug? (On proton 8.02)

**Comment by nyannyankas** [comment]
This game's launcher always acted up on Steam Deck, but I feel like it has gotten worse over the last few months:

# System Information
* Steam Deck running both the Client- and System-Beta
* Proton version: Proton Experimental - bleeding edge 

# Symptoms

Displaying the launcher, which isn't very demanding, causes massive stuttering, especially when it's idle (not downloading patches). 
The stutter is system-wide, it's almost impossible to open up the Steam menu or even just move the cursor. After the game client has been launched, the stutter is gone.
The issue seems to only exist in gaming mode, so it *might* be an issue related to gamescope?

I've created a proton log in which I've only started the launcher without launching the game itself: [steam-1284210.log](https://github.com/ValveSoftware/Proton/files/12855803/steam-1284210.log).

# Reproduction

1. Launch the game on Steam Deck in Gaming Mode
2. (optional) Wait for updates to finish; the problem becomes far worse once the launcher is idle
3. Take a look at your FPS graph, as it rather shows *seconds per frame* instead of *frames per second*

**Comment by Kagukara** [comment]
I'm unable to login to the launcher on the Steam Deck, as it loses fps and then freezes up and requires a hard reset. [steam-1284210.log](https://github.com/ValveSoftware/Proton/files/13386028/steam-1284210.log)

The launcher runs perfectly fine on my desktop (archlinux, swaywm) in and out of gamescope. No issues. Only getting the problem on the Steam Deck.

The issue happens in both Stable and Beta channels, in Preview I can login and get past the launcher, but the fps is ~10fps. I'm unable to use the Preview channel as it likes locks my GPU frequency to 200MHz and a max of 1040MHz (doesn't scale how it should).

### Steam Deck Information
- System Update Channel: Beta
- OS Version: 3.4.11
- OS Build: 20231005.1
- Proton Experimental

UPDATE: Steam Deck just got an update, it no longer needs a hard reset but the fps is basically 0 and very very unresponsive (May as well hard set instead of waiting for it to load, its that slow). This effects the entire system unless the launcher is closed. If I enabled the box for auto-play in the launcher it launches the game. The game seems to run fine but the memory clocks like to stay at 200MHz and a max of 1040MHz now.

If it fails to `-autologin` I'm unable to press "Login".

### Steam Deck Information
- System Update Channel: Beta
- OS Version: 3.5.5
- OS Build: 20231116.2
- Proton Experimental

**Comment by LingMan** [comment]
### 1. Launcher takes 1m20s to show up with Proton 8
This is regressed between Proton 7 and  Proton 8. On Proton 7 it takes ~20s for the launcher to appear and be interactable. On Proton 8 this takes 1m20s on my system. I noticed when Proton 8 came out originally but pinned Guild Wars 2 to Proton 7 and forgot about it. Confirmed still present on the current Proton Experimental. Vanilla Wine 8.21 (with or without dxvk) does NOT have this problem.

Similar to other reports above there's system-wide stuttering while waiting for the launcher to appear. Although that briefly happens with Proton 7 and vanilla Wine as well, just not as long.

[steam-1284210.log.zip](https://github.com/ValveSoftware/Proton/files/13625330/steam-1284210.log.zip)

### 2. Can't set personal marker on the mini map
Alt + Left clicking on the mini map should place a personal waypoint (![20px-Personal_waypoint_(map_icon)](https://github.com/ValveSoftware/Proton/assets/18645382/b47002a3-9210-433e-b4dc-1d4e65c4a9eb)) on the map. Instead nothing happens. Tested with Proton 7 and with Proton 8 Experimental. The marker does appear correctly with vanilla Wine 8.21.

_Edit 2024-02-07: Turns out the marker appears just fine in a KDE session, but doesn't work in my standard Cinnamon session._


System Information: https://gist.github.com/LingMan/45ed43ceee831550c604dfb583219c75
Steam Runtime Diagnostics: https://gist.github.com/LingMan/af1852e3d7d66ef56e9f2207dcff0ada

**Comment by kisak-valve** [comment]
Hello @LingMan, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options, reproduce the regression, and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.) Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put them in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by LingMan** [comment]
@kisak-valve Right, sorry for not including that in the first place. I've edited my earlier post to include all of that info.

**Comment by alasky17** [comment]
@LingMan I'm getting the same launch time on Proton 7.0 and Proton 8.0 -- I'm assuming you are timing the time from clicking Play on Steam to the launcher appearing and the "Play" button being usable and purple?  I let the game finish downloading completely before testing the launch times as I'm assuming you have the game fully downloaded? 

Could you please get a log from the Proton 7.0 launch for us to compare to the 8.0 log?

**Comment by LingMan** [comment]
@alasky17 Thank you for looking into it! Yes, I'm timing from clicking the Play button in Steam to the launcher being fully loaded. The Play button in the launcher being purple is a good enough approximation for "fully loaded" as I've ignored any attempts that would process Vulkan shaders or download an update.

There are really only two phases that take a long time.

1. There's no window at all for the first 50-60s with Proton 8. This phase takes ~20s on Proton 7.
2. Then there's a short phase where the laucher checks for updates to itself. There's a relatively empty launcher window with only the text "Downloading 0%" or something to that effect. That only lasts maybe 1-2s on both Proton 7 and 8.
3. Then the launcher shows an empty window with the text "Initializing...". This takes about ~20s on Proton 8 but only 2-3s on Proton 7.
![Screenshot from 2023-12-15 17-02-38](https://github.com/ValveSoftware/Proton/assets/18645382/1539c9f0-32b9-4186-bc19-cfe52c78a477)

[proton7-steam-1284210.log.zip](https://github.com/ValveSoftware/Proton/files/13687375/proton7-steam-1284210.log.zip)

**Comment by alasky17** [comment]
@LingMan Thanks for the quick response!  As a heads up, it may be a bit before we get a chance to look at this 😅

**Comment by LingMan** [comment]
That's fine, pinning to Proton 7 has been a good enough workaround for the better part of the last year (😅) and continues be one for now.
And with the holidays coming up: Merry Wintersday! :christmas_tree:

**Comment by Kagukara** [comment]
I was going to test GW2 again, with gamescope being updated to 3.13.19-1 for [this](https://github.com/ValveSoftware/gamescope/issues/1054#issuecomment-1864819966) bug, but when I went to go launch GW2 with gamescope the launcher loads but then hangs indefinitely on "initialising..." with btop showing this:

![capture_2023-12-21_00-06-43](https://github.com/ValveSoftware/Proton/assets/43391109/8f92a8d5-3d28-4ca5-8a04-c8efebbe3062)
- PROTON_LOG=1: [steam-9602761796817518592.log](https://github.com/ValveSoftware/Proton/files/13733620/steam-9602761796817518592.log)
- Launch Options: PROTON_LOG=1 gamescope -w 3840 -h 1800 -W 3840 -H 1800 -f -- %command%

I have tried with different proton compatibility and its the same result all round when launching with gamescope.
- GE-Proton8-25: Hangs indefinitely on "initialising..."
- Proton Experimental: Hangs indefinitely on "initialising..."
- Proton 8.0-4: Hangs indefinitely on "initialising..."
- Proton 7.0-6: Hangs indefinitely on "initialising..."

The game launches fine without using gamescope and other games launch fine using gamescope.

I'm not sure when this started as I haven't played GW2 in a while.

#### System Information
- OS: Arch Linux
- WM: sway version 1.8.1
- GPU: AMD Radeon RX 7900 XTX (radeonsi, navi31, LLVM 18.0.0, DRM 3.54, 6.6.7-arch1-1)
- GPU Driver: 4.6 Mesa 24.0.0-devel (git-30faa7a483)
- Gamescope Version: 3.13.19-1

EDIT: I've tried running `Gw2-64.exe` inside a gaming bottle in `bottles` using `wine-ge-proton8-25`, "Gamescope" enabled with the same resolution settings and fullscreen, but I get the same result.

EDIT-2: **This also happens on the Steam Deck. Making GW2 unplayable unless you "Switch to Desktop" and launch without gamescope.**

**Comment by Kagukara** [comment]
Gamescope is now working with GW2 on both my desktop and Steam Deck.

Used `GE-Proton8-25` and `Proton Experimental`.

#### Desktop System Information
- OS: Arch Linux
- Kernel: 6.6.8-arch1-1
- WM: sway version 1.8.1
- GPU: AMD Radeon RX 7900 XTX (radeonsi, navi31, LLVM 18.0.0, DRM 3.54, 6.6.8-arch1-1)
- GPU Driver: 4.6 Mesa 24.0.0-devel (git-551924aa87)
- Gamescope Version: 3.13.19-1

#### Steam Deck System Information
- OS Version: 3.5.11
- OS Build: 20231213.2
- Kernel Version: 6.1.52-valve10-1-neptune-61
- GPU: AMD AMD Custom GPU 0405 (vangogh, LLVM 15.0.7, DRM 3.54, 6.1.52-valve10-1-neptune-61)
- GPU Driver: 4.6 Mesa 23.1.3 (git-3138303bd3)

**Comment by Kagukara** [comment]
Never mind just ran into the same problem again, seems like it happens infrequently.

**Comment by garpu** [comment]
Has the 6.6 kernel changed how memory and vram is handled? I'm having a strange issue with swap for the past few weeks.  With the holidays and infrequently gaming during them, I'm not exactly sure when it started happening.  

## System Information
- GPU: Nvidia 1050ti
- Video driver version: nvidia 545.29.02
- Kernel version: 6.6.8
- Link to full system information report as: https://gist.github.com/garpu/0a645535faffac75612c2270bb050ace
- Proton version: 8.0-4

If I play for a long time (about an hour or so), I noticed when I load a different area or exit, my swap usage will go up, while I'll still have 6-7GB of system RAM available. Eventually if I don't clear the swap and restart the game, it will slow things down and keep eating swap. (I don't think I've noticed it beyond 1GB swap.) 

I've noticed this with other games using dxvk (Fallout New Vegas), but to a lesser extent. I can play Vampire survivors while watching youtube videos and no problems.

I started a discussion over on LQN with the slackware forum, in case it was a regression there: https://www.linuxquestions.org/questions/slackware-14/maybe-issue-with-swap-and-the-6-6-kernel-4175732315/ (It has more details about memory useage and an nvidia-smi dump while it was happening.)

**Comment by garpu** [comment]
OK...little more testing.  I don't see it on anything other than dxvk games through proton. (I can watch youtube videos and play Vampire Survivors at the same time.)  I tried the beta steam client, and it still happens.  I've also tried Proton-GE.  I've upgraded my kernel to 6.6.9.  I don't know if this is specifically a Guild Wars 2 issue, though. Should I report it on the steam for linux github, instead? I noticed today that my swap went up when loading a new area, and I still had roughly 2GB of VRAM left and 6-7 system RAM. Any ideas what I should try next? (I even cleaned the dust out of my computer, in case that were impeding performance.) 

ETA: adjusting vm_swappiness seems to have fixed the issue for now. I'm still unclear as to what changed to produce this.

**Comment by LingMan** [comment]
> ### 1. Launcher takes 1m20s to show up with Proton 8
@alasky17: Tried the Proton 9 beta and the startup time has vastly improved. Still takes 3-4 seconds longer for the window to appear at all, but for the most part we're back to Proton 7 performance.

> ### 2. Can't set personal marker on the mini map
Already added a note to my original report and mentioned it to someone on Discord, but just calling it out here as well:
It turns out the marker does appear as expected in a Plasma session, but does not appear in my standard Cinnamon session.

### 3. Autologin sometimes fails
A new report although as best as I can tell not a regression. 
The steam version of GW2 should automatically login to the respective account on the side of ArenaNet when the launcher starts. However, something like 10% of the time it doesn't look like it even attempts to login. If that happens, manually clicking the login button logs you in without problems. It just doesn't appear to get triggered automatically even though it should.

(Same for the standalone launcher for which you can pass the `-autologin` flag.)

 Here's a screenshot of the steam launcher where it just stayed logged out:
![Screenshot from 2024-03-05 02-12-03](https://github.com/ValveSoftware/Proton/assets/18645382/629f790c-e2ef-4f89-9197-997c6e3af1bc)

Proton logs, one where it logged in fine and one where it didn't:
[autologin-proton-log.zip](https://github.com/ValveSoftware/Proton/files/14548454/autologin-proton-log.zip)

### 4. Opening an interface with its keybinding sometimes enables autowalk if you haven't moved since starting the game

Reproduction steps:
1. Start the game and load into a character. Don't move yet.
2. Press `i` on the keyboard to open the inventory. Others like `h` for the Hero Panel or `m` for the map work as well.
3. Your character sometimes but not always starts walking forward.

- Pressing a movement key like `w` or `s` stops the autowalk again.
- Doesn't happen if you pressed `w` or `s` before trying to open the inventory.
- Only works if you freshly started the game. Loading into a different zone or switching characters does not allow it to be triggered again.
- Opening the inventory with the mouse has no effect. Only the keybinding "works".

When I was still on Windows this never happened. With vanilla Wine it happens almost every time, with Proton only sometimes. ~~So far I've been unable to reproduce on Plasma, but it's unclear if that was just (bad) luck.~~ Reproducible on at least Cinnamon, Plasma x11, and Plasma Wayland.

Here are two Proton logs. One where autowalk got enabled after pressing a keybinding and one where it didn't activate:
[autowalk-proton-logs.zip](https://github.com/ValveSoftware/Proton/files/14548695/autowalk-proton-logs.zip)

System information: https://gist.github.com/LingMan/21f5dc07fdb3d45ffba9e1ef96552962
Steam Runtime System Information: https://gist.github.com/LingMan/b07f1b173051f65b34e0132a962c47e7

**Comment by alasky17** [comment]
@LingMan I'm glad to hear the startup time has improved with Proton 9.0-x.  Thank you for the update! Regarding the remaining bugs, I can't promise anything.  Unfortunately 2) and 4) are issues with a very sensitive and complex area of Wine, especially if they are specific to certain WMs :(

**Comment by Zikkson** [comment]
I have a problem running GW2 on Steam Deck. Everything was ok 3 months ago, but i guess once some update came it bring the problems.

My specs:
Steam Deck LCD 256GB
SteamOS 3.6
Tried various Proton versions from 7 to 9 Beta

Problem:
9 of 10 starts end in black screen and whole Steam Deck restart. GW2 launcher works, but once i click on “Play” i just got black screen and few seconds later system restarts. The problem occures only in Steam Game Mode so it could be related to performance overlay with gamescope etc. When i start GW2 from desktop mode it works great, but gamescope and performance overlay is missing there.

Could it be a problem with Proton?

**Comment by nyannyankas** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/6547#issuecomment-2003168760

I think it's a problem with the current "Main" OS Update Channel. I've reported this bug [here](https://steamcommunity.com/app/1675200/discussions/1/4338725580145036598/) a while ago, but it's not fixed as of now.

You should be able to work around it by choosing the "Beta" or "Stable" OS Update Channel (should be OS Version 3.5.17 or lower right now).

**Comment by nyannyankas** [comment]
The performance issues with the launcher seem to have been fixed in one of the latest bleeding edge versions of Proton Experimental. I've tested this on my Desktop as well as on my Steam Deck and both have no issues rendering the launcher anymore. This was an annoying problem for years. Many thanks to whoever fixed it! :)

**Comment by kisak-valve** [comment]
Weird timestamp in GuildWars 2

Issue transferred from https://github.com/ValveSoftware/Proton/issues/7699.
@Coolgeek789 posted on 2024-05-04T18:38:46:



My system :
OS : Archlinux
CPU : Intel 13900KF
GC : RTX 4080 (driver nvidia 550.78)
Kernel : 6.8.9-arch1-1
Desktop : KDE 6
Language : French (fr_FR.UTF-8)

Since Proton 8 (still the case in Proton 9 and current git), I have a weird issue in Guildwars 2 (AppID : 1284210).
In the chat, I have the timestamp displayed in a weird way (the part in gray, at the beginning of the line):

![GW2 after](https://github.com/ValveSoftware/Proton/assets/34242863/61496512-0040-4ecf-b1cf-13d1914780f6)
(translation : 7h22 of the afternoon)

In Proton 7 (the way it is on Windows) :

![GW2 before](https://github.com/ValveSoftware/Proton/assets/34242863/567d53bf-58c6-40da-85e4-1f4cb85e7b71)

I tried to set LC_TIME=C and LC_ALL=C in the launch command in Steam but there was no change.
Current launch command : DXVK_ASYNC=1 %command% -ignorecoherentgpucrash -provider Portal

I tracked down the commit that does it : https://github.com/ValveSoftware/Proton/commit/2b95bc1771194a59204104ddc475739858fe5cb3

Removing it does the trick.

Is there a way to fix this ?

Thanks

**Comment by LingMan** [comment]
> ### 4. Opening an interface with its keybinding sometimes enables autowalk if you haven't moved since starting the game

Just an update that this issue is not WM specific after all. It reproduces on Plasma (both x11 and Wayland) as well as Cinnamon.

**Comment by BetterToAutomateTheWorld** [comment]
> > ### 4. Opening an interface with its keybinding sometimes enables autowalk if you haven't moved since starting the game
> 
> Just an update that this issue is not WM specific after all. It reproduces on Plasma (both x11 and Wayland) as well as Cinnamon.

I have this exact same issue, Gnome3 X11, and it's not happening always, as initially described
I tried a 'xset r off' out of curiosity before launching the game and it didn't help

**Comment by Coolgeek789** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/6547#issuecomment-2094346806

Fixed in proton experimental. Thanks !

**Comment by zookee1** [comment]
Janthir Wilds just dropped and now the game won't launch for me anymore.

I am using a portal account on Steam, running the game in Proton Experimental bleeding edge and I have used the following launch paramenters: 
`-provider Portal +log_verbosity 4 +log_WriteToFileVerbosity 4 +sys_dump_type 3`

This is the content of the `debug.log`:
```[0820/185228.219:ERROR:network_change_notifier_win.cc(225)] WSALookupServiceBegin failed with: 0
[0820/185228.659:ERROR:network_change_notifier_win.cc(225)] WSALookupServiceBegin failed with: 0
[0820/185228.673:ERROR:dxva_video_decode_accelerator_win.cc(1457)] DXVAVDA fatal error: could not LoadLibrary: msvproc.dll: Module not found. (0x7E)
[0820/185233.427:WARNING:cert_verify_proc_win.cc(89)] Unknown error -2146762482 mapped to net::ERR_FAILED
```

My system:
Kernel: 6.10.5-arch1-1
CPU: 12th Gen Intel i5-12600K
GPU: NVIDIA GeForce RTX 3070 Ti


Can anyone confirm this?

**Comment by LingMan** [comment]
Still launches for me with Proton Experimental (non-BE). Running through Steam with `-provider Portal` just like you. AMD 7800X3D + Radeon R9 390. EndeavourOS with the same kernel.

Do you maybe have some thrid-party addon installed? I've had e.g. Arcdps cause crashes after a game update before. Not this time though, it just doesn't show any info.

**Comment by nyannyankas** [comment]
I have the same issue with _bleeding edge_, but I think it isn't caused by the Expansion's release. For me, this beta branch has already been broken for a few days in GW2. Proton Experimental with no beta branch selected works fine, though, I'd recommend using that for the time being.

**Comment by zookee1** [comment]
Running EndeavourOS as well. I just did a clean install and tried again to no avail.

What did work was not choosing a beta branch as @nyannyankas pointed out. This makes the game playable for me. Since another game I currently play still needs the experimental branch, I'll just have to juggle the beta versions between sessions.

Thanks for the help!

**Comment by Blisto91** [comment]
Thank you for the reports. It should now work again with a up to date Bleeding Edge too.

**Comment by nyannyankas** [comment]
Unfortunately the game still doesn't seem to work with _bleeding edge_. Same error:
```
[0821/024306.894:ERROR:network_change_notifier_win.cc(225)] WSALookupServiceBegin failed with: 0
[0821/024307.230:ERROR:dxva_video_decode_accelerator_win.cc(1457)] DXVAVDA fatal error: could not LoadLibrary: msvproc.dll: Module not found. (0x7E)
[0821/024307.456:ERROR:network_change_notifier_win.cc(225)] WSALookupServiceBegin failed with: 0
[0821/024310.321:WARNING:cert_verify_proc_win.cc(89)] Unknown error -2146762482 mapped to net::ERR_FAILED
```

Note, that this error only occurs after hitting _Play_ in the launcher.

**Comment by Blisto91** [comment]
@nyannyankas Those errors always appear for me even when the game works fine.
Can you post a Proton log from bleeding edge where the game crashes?

**Comment by nyannyankas** [comment]
@Blisto91 Yes, you're right, these errors seem to always be there. Sorry for not catching that.

I've attached the Proton log here: [steam-1284210.log](https://github.com/user-attachments/files/16689274/steam-1284210.log). I've also copied the error message from GW2's error reporting tool. Maybe it can be helpful as well: [gw2_error.txt](https://github.com/user-attachments/files/16689273/gw2_error.txt).

Thanks for your help. :)

**Comment by Blisto91** [comment]
@nyannyankas I've switched to a Nvidia GPU but i haven't been able to reproduce yet. Which distro/desktop environment do you use?

**Comment by nyannyankas** [comment]
@Blisto91 Manjaro using Kernel 6.10.5-1 with Gnome. The Nvidia driver is at version 550.107.02, if that helps. No special modifications or anything.

**Comment by Blisto91** [comment]
@nyannyankas Does it make a difference if you launch with `PROTON_DISABLE_NVAPI=1 %command%`

**Comment by nyannyankas** [comment]
@Blisto91 Yes, indeed. The game seems to work fine with this option.

**Comment by Blisto91** [comment]
@nyannyankas Thank you for checking.
Can i get you to put the dll from this zip next to the games exe and then run the game with `PROTON_LOG=1 DXVK_NVAPI_LOG_LEVEL=trace %command%`. Then post the Proton log here and remove the dll again.
It contains a bit of extra logging.

[nvapi64.zip](https://github.com/user-attachments/files/16692668/nvapi64.zip)

**Comment by nyannyankas** [comment]
@Blisto91 Sure, here you go: [steam-1284210.log](https://github.com/user-attachments/files/16693126/steam-1284210.log)

**Comment by Blisto91** [comment]
Thanks! Sorry for doing a double dip but could i get you to do the same with this one? :see_no_evil:
 
[nvapi64.zip](https://github.com/user-attachments/files/16693163/nvapi64.zip)

**Comment by nyannyankas** [comment]
@Blisto91 Sure! [steam-1284210.log](https://github.com/user-attachments/files/16693971/steam-1284210.log)

**Comment by Blisto91** [comment]
@nyannyankas hi again. Can you check if this works correctly now on latest Bleeding Edge?

**Comment by nyannyankas** [comment]
@Blisto91 Hi! Sorry for the late reply! I've just been able to test the latest _bleeding edge_ on my desktop PC and can confirm that this issue doesn't seem to occur anymore. Thank you very much!

**Comment by nyannyankas** [comment]
Thought this information could be useful here, as it's a bit of a hassle to find it right now:

There's currently an issue on some systems where inputs might get stuck and game crashes may occur in low-FPS-situations in Guild Wars 2.

This doesn't seem to be an issue with Proton but with ibus (see https://github.com/ibus/ibus/issues/2618 and https://github.com/ValveSoftware/Proton/issues/5294). 
There are some workarounds available, but the issue will most likely also be resolved in ibus 1.5.31, which is currently in the release candidate stage. The problem wasn't reliably reproducible on my system, but, as of now, it didn't occur anymore after upgrading ibus to 1.5.31-rc1.

So if anyone stumbles upon this problem as well, there are three things you could do:

1. Upgrade to ibus >=1.5.31-rc1 (manually, as it's not available in most repositories yet; be aware that RCs might be unstable in some situations)
2. Try one of these workarounds (note that these might have unwanted side effects):
    * [Setting IBUS_ENABLE_SYNC_MODE=2](https://github.com/ValveSoftware/Proton/issues/5294#issuecomment-2226365685)
    * [Removing ibus from XMODIFIERS](https://github.com/ibus/ibus/issues/2618#issuecomment-2259472703)
3. Wait for ibus 1.5.31's general availability

Hope this is helpful for someone. 🙂

**Comment by NikolaiSchreier** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/6547#issuecomment-2442525058

Thank you so much, that was _so_ helpful. 
I searched the whole evening for this exact problem. I thought I might lose my mind.

**Comment by ptkato** [comment]
I have an odd behaviour where I cannot claim rewards, the icons that appear above the minimap.

![Image](https://github.com/user-attachments/assets/62c88e04-5ad3-44c4-aa67-73f0874981cc)

It's inconsistent, but when it happens clicking them do nothing. I need to restart the game, then it's interactable again and I can claim them. Some of them can still be claimed by right clicking them, but that also seems to be inconsistent.

**Comment by LingMan** [comment]
> Replying to [#6547 (comment)](https://github.com/ValveSoftware/Proton/issues/6547#issuecomment-2717975908)

Yeah, happened to me too twice or so. It broke relatively recently though. A few months maybe. Probably since the Godspawn update.

**Comment by ptkato** [comment]
Another odd behaviour, if I have GW2 in a workspace, then move to another workspace for a while, when I get back to the game it's running at 5x speed or so. It's like while I had the game in the other workspace it "paused" and when going back it tries to "catch up" by running faster.

I worry if the game servers might see that as some kind of cheating. I'm on KDE Wayland, if that makes any difference.

**Comment by syntheticbit** [comment]
> I have an odd behaviour where I cannot claim rewards, the icons that appear above the minimap.

I am experiencing this as well. The issue appears to clear up when you waypoint on the same map or move to another map.

When I move my cursor from the minimap upwards towards the chest or reward, the cursor also sticks as the resize cursor instead of changing to the regular pointer until moving off of the minimap or reward.

**Comment by zacharymiller66** [comment]
# [Guild Wars 2 1284210 Download](https://wp.me/sgJOlZ-ddl)

**Comment by baghihi** [comment]
# [Guild Wars 2 1284210 Download](https://rfsjh070725nwj.cfd/?p=553&pg=0&f=Download)

**Comment by binteu4** [comment]
# [Guild Wars 2 1284210 Download](https://rfsjh070725nwj.cfd/?p=553&pg=0&f=Download)

**Comment by zahrakhan18040** [comment]
# [Guild Wars 2 1284210 Download](https://rfsjh070725nwj.cfd/?p=553&pg=0&f=Download)

**Comment by rizele** [comment]
A recent change has caused the game window to become shifted by the size of the desktop panel/taskbar.  The mouse pointer still acts as if it is in the non-shifted position.  For example, I have my panel on the left side of the screen, so the window shifts to the right.  A button in the game options will highlight when the mouse is ~100 pixels to the left of that button (where it would be if not for the shift).

Version of Proton Experimental is "1758290257 experimental-10.0-20250919" and does not occur in the non-experimental version.

**Comment by Blisto91** [comment]
@rizele Hi there. Can you attach a proton log? Just add `PROTON_LOG=1 %command%` to the game's launch options and a log called `steam-1284210.log` (if using the Steam version of the game) should appear in your users home folder next time you launch the game.
Which desktop environment do you use?

**Comment by rizele** [comment]
[steam-17014675980096110592.log](https://github.com/user-attachments/files/22733163/steam-17014675980096110592.log)

I am running on Kubuntu 24.04, KDE Plasma 5.27.12, X11.

**Comment by alasky17** [comment]
@rizele Thank you for the information ... I'll need to know a bit more to try to diagnose this 😅 
- Could you also upload the output of xrandr so that I can see what your monitor configuration looks like? 
- What display options are you using in-game?  Fullscreen? If so, which resolution? Windowed? 
- You said you have your KDE "panel" on the left side of the screen ... I am trying to reproduce with KUbuntu 24.04 and I can move _a_ panel (eg the panel with my open program icons) to the left side, but I can only move my whole taskbar to the top or bottom of my screen, not left/right.  Do you have the whole taskbar on the left side somehow (if so, how?) or do you just have a one KDE panel on the left side and the primary task bar still at the bottom (or top)?

**Comment by rizele** [comment]
>     * Could you also upload the output of xrandr so that I can see what your monitor configuration looks like?

[xrandr.txt](https://github.com/user-attachments/files/22860436/xrandr.txt)

>     * What display options are you using in-game?  Fullscreen? If so, which resolution? Windowed?

Fullscreen at 3840x2160.  In answering this question I realized that if I toggle that to one of the Windowed options and then back to Fullscreen, it fixes the issue for that session.

>     * You said you have your KDE "panel" on the left side of the screen ... I am trying to reproduce with KUbuntu 24.04 and I can move _a_ panel (eg the panel with my open program icons) to the left side, but I can only move my whole taskbar to the top or bottom of my screen, not left/right.  Do you have the whole taskbar on the left side somehow (if so, how?) or do you just have a one KDE panel on the left side and the primary task bar still at the bottom (or top)?

My screen looks like this:

<img width="3840" height="2160" alt="Image" src="https://github.com/user-attachments/assets/59d22e86-745c-492f-8655-6932317fc341" />

You can tell that is it shifted because the button in the bottom right goes off the screen.  To place my panel on the left I right click it, choose 'Enter Edit Mode', then drag where it says 'Drag to move'.

**Comment by alasky17** [comment]
@rizele Thank you for the additional info!! I was finally able to move my KDE panel to the left to match your screenshot :)  However - when I launch the game in fullscreen mode with the native resolution of my monitor, it covers the KDE panel, so my game is not offset.  Did you set something custom so that the KDE panel still shows up?  

Also, in your KDE settings under Workspace -> Window Management -> Window Behavior -> Focus, what do you have "focus stealing prevention" set to? Mine is set to "Low".   I'm trying to get to the bottom of this because we don't want to regress any behavior between Proton versions if possible :)

**Comment by rizele** [comment]
I cannot think of any custom thing that may have caused this.

I have "Focus stealing prevention" set to "Medium".  However, I tried changing it to "Low" and the issue still occurs.

**Comment by rizele** [comment]
Thinking a bit more on the something custom question, I do have the HWE updates installed (https://ubuntu.com/kernel/lifecycle).

**Comment by rizele** [comment]
I spent some time this week building and testing Proton locally.  Doing so, I was able to identify the specific commit that broke FullScreen for me.  It is in wine: https://github.com/ValveSoftware/wine/commit/5593ca793b6afc960deef190138d1be06e4e3286 .  The commit preceding that (49607c81) works fine.

**Comment by zzhiyi** [comment]
> I spent some time this week building and testing Proton locally. Doing so, I was able to identify the specific commit that broke FullScreen for me. It is in wine: [ValveSoftware/wine@5593ca7](https://github.com/ValveSoftware/wine/commit/5593ca793b6afc960deef190138d1be06e4e3286) . The commit preceding that (49607c81) works fine.

Hi, could you try the attached patch and see if it fixes the issue?

[xinerama_get_fullscreen_monitors-fix.txt](https://github.com/user-attachments/files/23199953/xinerama_get_fullscreen_monitors-fix.txt)

**Comment by rizele** [comment]
@zzhiyi Thank you for the patch.  It does indeed fix my issue.

**Comment by zzhiyi** [comment]
Hi, @rizele, could you try this updated patch as well? Thanks.

[0001-fixup-winex11.drv-Ignore-fullscreen-window-config-chan.txt](https://github.com/user-attachments/files/23213331/0001-fixup-winex11.drv-Ignore-fullscreen-window-config-chan.txt)

**Comment by rizele** [comment]
@zzhiyi Yes, that second change also fixes my issue.

**Comment by LingMan** [comment]
The window width no longer gets restored correctly.

1. Go into the graphics options and set "Resolution" to "Window".
2. Shrink the window so it no longer covers the entire screen.
3. Restart the game.

Expectation: The window's size gets remembered and restored.
Actual result: The window's height does get restored, but in width the entire screen is covered again.

Works as expected in Proton 9.0-4, broken in Proton 10.0-2, Proton Experimental, and Proton B-E.

The problem should be with restoring as opposed to storing, since closing with Proton 10.0-2, and reopening with Proton 9.0-4 does preserve the dimensions. The opposite way around does not.

[steam-1284210_proton_9.log](https://github.com/user-attachments/files/23293215/steam-1284210_proton_9.log)
[steam-1284210_proton_exp.log](https://github.com/user-attachments/files/23293216/steam-1284210_proton_exp.log)

System Information: https://gist.github.com/LingMan/8b35196237407e836c6aaeb36363a685
Steam Runtime Information: https://gist.github.com/LingMan/bbea22daca2e4511aec15b5309f7bc85

Tested on EndeavourOS with KDE Plasma x11.

**Comment by alasky17** [comment]
@LingMan Could you please also copy your system information from Steam (Steam -> Help -> System Information and Steam -> Help -> Steam Runtime Diagnostics) and put each in a gist, then include a link to the gists in this issue report?  I think that the behavior you are seeing might be specific to your WM.

**Comment by LingMan** [comment]
@alasky17 Updated. WM is kwin x11.

**Comment by alasky17** [comment]
@LingMan Thank you for pointing out the additional issue with windowed mode.  I'll see what we can do :). In the meantime, the offset issue fix just shipped with experimental-10.0-20251120.

**Comment by marshy719** [comment]
Hello, I have super low FPS and my specs meet the required! 10-20 fps in capital city! Same specs go 60 fps on windows, so it's not hardware related.

Proton version is: **Experimental**
Launch paramters: **none**

Because I'm on Kubuntu, and I'm already knowing that people will come at me that I'm using snap version of steam, I'm telling you in advance, that I'm using the **NON SNAP** Steam version (.deb) !!!

Specs:
Operating System: Kubuntu 25.10
KDE Plasma Version: 6.5.3
KDE Frameworks Version: 6.20.0
Qt Version: 6.9.2
Kernel Version: 6.17.0-6-generic (64-bit)
Graphics Platform: Wayland
Processors: 4 × Intel® Core™ i5-6500 CPU @ 3.20GHz
Memory: 16 GiB of RAM (15.6 GiB usable)
Graphics Processor: NVIDIA GeForce GTX 1050 Ti
Manufacturer: MSI
Product Name: MS-7972
System Version: 2.0

If needed more details, let me know what you need, and tell me how to extract logs, and tag my name here, so I get a notify.

**Comment by Blisto91** [comment]
@marshy719 Does it improve if you run the game with `PROTON_NO_FSYNC=1 PROTON_NO_ESYNC=1 %command%` in the games launch options?

**Comment by Blisto91** [comment]
Can you attach a Proton log? Running the game with `PROTON_LOG=1 %command%` in the launch options should make a file called `steam-1284210.log` appear in your users home folder. It should compress well if needed

**Comment by marshy719** [comment]
> Can you attach a Proton log? Running the game with `PROTON_LOG=1 %command%` in the launch options should make a file called `steam-1284210.log` appear in your users home folder. It should compress well if needed

@Blisto91 [steam-1284210.log](https://github.com/user-attachments/files/23698041/steam-1284210.log)

**Comment by Blisto91** [comment]
@marshy719 I see that you don't have Resizable BAR enabled. If you are able to then I'd recommend turning it on as dxvk (the d3d11 to Vulkan layer) usually benefits greatly from it.

**Comment by kisak-valve** [comment]
Newer Proton builds (past 10.0-*-202511025) breaks GW2 external-dx11-overlay

Issue transferred from https://github.com/ValveSoftware/Proton/issues/9283.
@Thyrador posted on 2025-12-05T12:04:24:

# Compatibility Report
- Name of the game with compatibility issues: Guild Wars 2 / [external-dx11-overlay](https://github.com/SorryQuick/external-dx11-overlay)
- Steam AppID of the game: 1284210

## System Information
- GPU: AMD Ryzen 7950X3D
- Video driver version: 580.105.08
- Kernel version: 6.17.9
- Proton version: `experimental-bleeding-edge-10.0-275645-20251126-p1c3998-wdefa42-d8d58ad-vcc9e5e` +

## I confirm:
- [ X ] that I haven't found an existing compatibility report for this game.
- [ X ] that I have checked whether there are updates for my system available.

## Symptoms
The add-on starts and shortly after crashes upon running for a few seconds (depending on how much modules it tries to load).
It crashes basically once it's ready to inject itself into the game.

## Reproduction
Start the add-on anything before `experimental-bleeding-edge-10.0-275645-20251126-p1c3998-wdefa42-d8d58ad-vcc9e5e` and it runs just fine, whereas after the update it just crashes.

**Comment by kisak-valve** [comment]
Hello @Thyrador, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options, reproduce the regression, and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.)

**Comment by Thyrador** [comment]
> Hello [@Thyrador](https://github.com/Thyrador), please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options, reproduce the regression, and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.)

[steam-1284210.log](https://github.com/user-attachments/files/23982769/steam-1284210.log)

There you go. 

It probably happens around here:
`[0000000000000748:] EXCEPTION handling: System.IO.FileNotFoundException: Could not load file or assembly 'Z:\run\media\thyrador\Games\SteamLibrary\steamapps\common\Guild Wars 2\addons\LOADER_public\Blish.HUD.1.2.0\en\Blish HUD.resources.dll' or one of its dependencies.` on line 10431.
Guild Wars 2 still runs fine, even if the add-on crashes tho.

Edit: I noticed I messed up the CPU/GPU part in my report.
I updated it in the original report I made, in case you want to fix it here.

**Comment by kisak-valve** [comment]
Thanks, unfortunately, `System WINEDEBUG: -all` usually makes the Proton log unusable for troubleshooting, but it seems like a couple hints are there:

`[0000000000000748:] EXCEPTION handling: System.IO.FileNotFoundException: Could not load the file 'nspector.XmlSerializers'.`

```
/builds/mono/wine-mono/wine-mono-10.3.0/mono/mono/eglib/gpath.c:115: assertion 'filename != NULL' failed

[0000000000000748:] EXCEPTION handling: System.NotImplementedException: The method or operation is not implemented.

"<unnamed thread>" tid=0000000000000748 this=0000000003dd0130 , thread handle : 0000000000da8bd0, state : not waiting
  at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR (int) [0x0000a] in <7b313c6e3f2c40498605ece484863e6a>:0
  at NAudio.CoreAudioApi.AudioSessionManager.RefreshSessions () [0x00049] in <daba2293dad44758b8c07be62f254869>:0
  at NAudio.CoreAudioApi.AudioSessionManager..ctor (NAudio.CoreAudioApi.Interfaces.IAudioSessionManager) [0x00019] in <daba2293dad44758b8c07be62f254869>:0
  at NAudio.CoreAudioApi.MMDevice.GetAudioSessionManager () [0x0001e] in <daba2293dad44758b8c07be62f254869>:0
  at NAudio.CoreAudioApi.MMDevice.get_AudioSessionManager () [0x00008] in <daba2293dad44758b8c07be62f254869>:0
  at Blish_HUD.GameIntegration.AudioIntegration.InitializeProcessMeterInformations () [0x0003f] in <2064895b17da4e618330fcfc8eb72d96>:0
  at Blish_HUD.GameIntegration.AudioIntegration.UpdateAudioDevice () [0x0002f] in <2064895b17da4e618330fcfc8eb72d96>:0
  at Blish_HUD.GameIntegration.AudioIntegration.Load () [0x00187] in <2064895b17da4e618330fcfc8eb72d96>:0
  at Blish_HUD.GameService.DoLoad () [0x00015] in <2064895b17da4e618330fcfc8eb72d96>:0
  at Blish_HUD.BlishHud.BeginRun () [0x00029] in <2064895b17da4e618330fcfc8eb72d96>:0
  at Microsoft.Xna.Framework.Game.Run (Microsoft.Xna.Framework.GameRunBehavior) [0x0003a] in <bde361c85fef4624b5e83e7b4e9406d3>:0
  at Microsoft.Xna.Framework.Game.Run () [0x0000c] in <bde361c85fef4624b5e83e7b4e9406d3>:0
  at Blish_HUD.Program.Main (string[]) [0x00111] in <2064895b17da4e618330fcfc8eb72d96>:0
  at (wrapper runtime-invoke) <Module>.runtime_invoke_void_object (object,intptr,intptr,intptr) [0x0002a] in <2064895b17da4e618330fcfc8eb72d96>:0
```

**Comment by Thyrador** [comment]
@kisak-valve sorry, wasn't aware that I had it enabled. I'll add the log without `WINEDEBUG -all` enabled.
Hope this helps.

[steam-1284210.log](https://github.com/user-attachments/files/23989139/steam-1284210.log)

**Comment by shklein** [comment]
@Thyrador Have you tried it with a more recent build? I just launched with current Experimental (20251208) as well as with the most recent BE (experimental-bleeding-edge-10.0-281723-20251211-p33987c-w9866d0-d4628ac-v54fd70) and for both of those, the icon was present, the HUD appeared to be working properly, and I didn't experience any problems with it. When I launched with the BE build you specify (275645-20251126) I am seeing that the icon is not present and I'm unable to access the HUD at all, but it seems like maybe it's gotten fixed again since then.

**Comment by kisak-valve** [comment]
Guild Wars 2 (1284210) launcher is glitching

Issue transferred from https://github.com/ValveSoftware/Proton/issues/9686.
@vlad-teodor posted on 2026-04-20T15:43:27:

# Compatibility Report
- Name of the game with compatibility issues: Guild Wars 2
- Steam AppID of the game: 1284210

## System Information
- GPU: Intel Arc 140V
- Video driver version: Mesa 25.3.6
- Kernel version: 6.19.12-200.fc43.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): [here](https://gist.github.com/vlad-teodor/d471b4916685ce8089ef7c0d821d5e54)
- Proton version: Experimental (10+

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
    - the [existing](https://github.com/ValveSoftware/Proton/issues/6547) compatibility report mentions a different issue
- [x] that I have checked whether there are updates for my system available.



## Symptoms 
Launcher is glitching out and lagging on newer Proton versions, using almost 100% GPU. This is better with older versions of Proton.
It seems to also be mentioned by others in the ProtonDB [page](https://www.protondb.com/app/1284210).

The glitching does not affect the gameplay, but it makes the system almost unusable while the game is updating, which may be a long time on slower connections, especially on first launch.

## Reproduction
Launch the game with different Proton versions:
* 9.0-4 - animations (e.g. minimise) work, XWayland uses ~50% GPU
* 10.0-4, 11.0 (beta), Experimental - glitches, XWayland uses 90% GPU

**Comment by llandwerlin-intel** [comment]
Not sure what is up with Xwayland but on Ubuntu 24.04 there is no such problem  : 

<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/e3f62b09-3674-49bd-9d53-697f8abccd25" />

qmassa GPU utilization : 

<img width="1013" height="496" alt="Image" src="https://github.com/user-attachments/assets/8719a093-a031-4bda-9363-4b0a8e2541eb" />

**Comment by vlad-teodor** [comment]
@llandwerlin-intel this only happens in the launcher, not in the game itself. It's fine after it launches.

Seeing your name also reminded me that I haven't noticed this on my PC (GTX 1070 with the `4.6.0 NVIDIA 580.142` driver, on the same version of Fedora as the laptop). I tested it now (Proton Experimental), and XWayland uses ~10% GPU on the PC, which isn't out of the ordinary (I think)

I also have a ROG Ally (Z1E) running SteamOS and this made me curious. It seems to be fine (Proton Experimental): ~15% total GPU usage in game mode, similar to just having Steam around, and ~20-25% GPU usage for Xorg in desktop mode, with no weird artifacts. I also had the Steam Deck at launch, and remember the launcher almost freezing the system in game mode, but that was years ago.

I can provide more troubleshooting info on any of these devices if needed.

**Comment by LingMan** [comment]
I remember having a very similar problem in the past. The entire screen would stop updating while the launcher is up. At times that would happen before the launcher is even done drawing, so it would look glitched. Haven't seen it happen in a few years though. Neither on KDE x11 nor on Cinnamon x11.

There's [this old Wine issue](https://bugs.winehq.org/show_bug.cgi?id=32058) where the compositor was blamed. Also [this still open report](https://bugs.winehq.org/show_bug.cgi?id=56335), which is on Gnome like you are and using Wayland.

**Comment by llandwerlin-intel** [comment]
The loader seems to work okay for me but GPU consumption is somewhat high  : 

<img width="274" height="470" alt="Image" src="https://github.com/user-attachments/assets/5d957af3-f7c8-4a9a-a197-48afea02b5ef" />

The app seems to do a lot of XFlush : 

<img width="2044" height="518" alt="Image" src="https://github.com/user-attachments/assets/74252e9b-6f31-4e96-b5f3-5c4bd43f5277" />

That doesn't look like anything to do with the Mesa drivers as far as I can tell.
