### ISSUE TITLE
Sifu (2138710)

### ISSUE THREAD

**Issue by liu2g** [ValveSoftware/Proton#6657]
# Compatibility Report
- Name of the game with compatibility issues: Sifu
- Steam AppID of the game: 2138710

## System Information
- Steam Deck (Beta Channel)
- Proton version: Proton Experimental

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-2138710.log](https://github.com/ValveSoftware/Proton/files/11119595/steam-2138710.log)

## Symptoms 
Game freezes under certain conditions.

## Reproduction
One reproducible condition is after entering a map and being able to control the character, go into menu and switch between the menu tabs.
After a few actions of switching tabs, the game freezes around the `CHARACTER` tab.

![image](https://user-images.githubusercontent.com/55007630/229062830-42d5565a-d32a-4b60-8120-6c7e207aff3d.png)

From a cursory search, it seems other conditions include gameplay time around 20 minutes.

**Comment by JackMcCallum** [comment]
I also have been having issues with this. Although I find it just randomly freezes typically after about 30 mins of gameplay. It freezes beyond recovery and forces me to reboot the game, very annoying especially if I'm on a good run :(

**Comment by ffrasisti** [comment]
Oh, and I was just about to buy this to play on deck. Guess I'll wait, given the nature of the game this can kill your level pass run

**Comment by JackMcCallum** [comment]
Yes, i have been playing it exclusively on deck and it performs extremely well, except for this one issue sadly

**Comment by ffrasisti** [comment]
Works great except for this can confirm, I have a log but im guessing its the same as OPs. Can go into deck and upload if necessary

**Comment by ffrasisti** [comment]
has this been fixeD?

**Comment by JackMcCallum** [comment]
Maybe, the other night I was able to play it for quite some time, I'll give it a go later im the week again and see, if not don't expect a proton fix to fix this anytime soon, these that's get triaged and backlogged

**Comment by FearlessSpiff** [comment]
New to the deck. I don’t even have the mini videos in the skill tree (they look like crt tv test pictures) besides having this freeze issue. Do I need to use another proton version?

**Comment by liu2g** [comment]
Just tried this on my desktop and it looks like this issue is still reproducible on Proton Experimental and the new Proton 8.0

**Comment by ffrasisti** [comment]
Damn. I was hoping it would go in 8

**Comment by liu2g** [comment]
~~I just tried with [GE-Proton-8-2](https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/GE-Proton8-2) with the originally mentioned reproduction method and it looks like it was fixed. I haven't tried with long time game session though~~

Update: I ran it again today and it again started freezing...I should have bought a lottery yesterday

**Comment by festinuz** [comment]
I can still reproduce the issue Steam deck with either Proton 8.0-2 or GE Proton 8.2: I load the level, I open the pause menu, and I rotate through all submenus a couple of times. Usually, two times is enough to get the issue

**Comment by liu2g** [comment]
Yeah I guess I was very lucky yesterday...managed to freeze again today

**Comment by ffrasisti** [comment]
Is valve looking into this?

**Comment by melo0187** [comment]
To make things worse the game is now deck verified as playable óÒ
Only  things mentioned are controller unfriendly launcher and difficult to read text. Hard to trust deck verified program at this point.
Haven't played the game yet but the character menus don't sound optional. So no one would be able to finish this game on Deck/Linux. Calling this playable is unjustified.

**Comment by Flip535** [comment]
Would love to see this get fixed!

**Comment by melo0187** [comment]
Game is currently on sale, but there is no way to tell if problems still persist.
There is no game update out, so that is no reason to hope for any improvement.
Maybe Proton updates solved the issue by now, but without any activity on this issue and no new reports on protondb that is just guessing/hoping.

@liu2z2 you described a reproduction. Can this be performed quickly after installing the game or do I need to get through a prologue or something?
Would hate to buy the game and notice that it is still broken after 2 or more hours in without any option to refund...

**Comment by melo0187** [comment]
So I just gave this a try on my Linux Desktop (Ubuntu 23.04) and can confirm the the problems still persist.

When navigating the in game menus switching to the character tab will still crash the game. This happens both with Proton 8.0.2 and Experimental.

When using Proton Hotfix the menu crash issue seems to be solved.
However, when beating the first boss the game crashes again.

So in 110 minutes of playtime I encountered 7 crashes irrc.
In this state I didn't even bother trying to play the game on my Steam Deck.

**Comment by ZoopOTheGoop** [comment]
I'm not able to repro this personally, either on proton 8.0-2 or Proton GE 8-6. Menu cycling works find and I beat the first level with no crash.

How long does it take in-game to crash? I've finished this game on PS5 so I'm fairly good at the first level and basically speedran it for verification purposes, so it's possible the issues don't show until a certain amount of time? It seems like 30 minutes was suggested above until the menu method was found.

Edit: Ah, found it, you can force the behavior with `STEAM_DECK=1` so it's definitely deck-related

**Comment by melo0187** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/6657#issuecomment-1624336582

All crashes I mentioned were on Linux desktop.

About the menu crashes: My impression was that the character tab leads to crashes after having spent XP on a skill.
This was with Proton 8.0-2 and Experimental (at the 28th of June). As I said using Proton Hotfix (still on the 28th of June) I was not able to reproduce the menu related crashes anymore, but when beating Fajar the game got stuck. Meaning the music kept playing but nothing else was happening and a crash dialog window appeared in the background...
I can not retest with Proton GE, since my test session was just short of 2h and I decided to request a refund.

I presume you did beat Fajar for your verification when you say "I beat the first level". Was this with Proton 8.0-2?
That would leave us with contradicting experiences meaning we are overlooking some other involved party...
If you were using Proton GE 8-6, that would be the recommended Proton version to use for the time being.

**Comment by ffrasisti** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/6657#issuecomment-1624336582

Is this still not working well on deck?

**Comment by liu2g** [comment]
Sorry everyone I took a break from this game recently. As of now testing on Proton Experimental, the bug is still reproducible on my desktop and Steam Deck

**Comment by rubengees** [comment]
I also have (had) this problem on Linux Desktop. For me, the performance become gradually worse every time I visited the character or death screen until it completely freezes. It is also consistently reproducable - switching the tabs in the menu quickly leads to the freeze.

I tried different settings and **disabling DLSS** removed the issue completely. I can now play the game for hours without any issue. I am very sure it's DLSS because once I enable it (without any other change), the issue reproduces again.

I'm not sure about non-nvidia configurations though since it seems to happen there also and DLSS is not available in the first place.

**Comment by Edumadaluk** [comment]
Same issue.

---

Sifu (2138710) freezes On Steam Deck

Issue transferred from https://github.com/ValveSoftware/Proton/issues/7184.
@Edumadaluk posted on 2023-10-20T20:28:53:

Compatibility Report

Name of the game with compatibility issues: Sifu
Steam AppID of the game: 2138710
System Information

Steam Deck (Beta Channel)
Proton version: Proton Experimental/GE/8
I confirm:

 that I haven't found an existing compatibility report for this game.
 that I have checked whether there are updates for my system available.
[steam-2138710.log](https://github.com/ValveSoftware/Proton/files/11119595/steam-2138710.log)

Symptoms

Game freezes under certain conditions. On character tab.

Reproduction

One reproducible condition is after entering a map and being able to control the character, go into menu and switch between the menu tabs.
After a few actions of switching tabs, the game freezes around the CHARACTER tab.

**Comment by kisak-valve** [comment]
Hello @Edumadaluk, it looks like you've configured Proton Experimental to its experimental-7.0 beta branch. This isn't particularly useful for troubleshooting because it's about 6 months out of date. Can you share a Proton log from a newer Proton build?

**Comment by Edumadaluk** [comment]
Hello, I’ve tried proton GE, Experimental and 8.14... same issue and a lot of people with the same problem in protondb.comAtt, EduardoEm 20 de out. de 2023, à(s) 18:19, kisak-valve ***@***.***> escreveu:﻿
Hello @Edumadaluk, it looks like you've configured Proton Experimental to its experimental-7.0 beta branch. This isn't particularly useful for troubleshooting because it's about 6 months out of date. Can you share a Proton log from a newer Proton build?

**Comment by Edumadaluk** [comment]
Hello, [@kisak-valve](https://github.com/kisak-valve) I’ve tried proton GE 8-14,GE  8-20,  Experimental and 8.0-4…same issue and a lot of people with the same problem in protondb.com.

[steam-2138710.log](https://github.com/ValveSoftware/Proton/files/13059466/steam-2138710.log)

**Comment by Edumadaluk** [comment]
@kisak-valve Why don’t you answer my reports? This game isn’t Steam deck compatible.

This game should not be listed as verified.

**Comment by gprovostqa** [comment]
Same as above, the game crashes instantly when using the menu on the Character tab. Reproduced with no compatibility changes and then on Proton 8.0-4. 

It shouldn't be Steam Deck Verified if something as basic as using menus make it crash.

**Comment by ffrasisti** [comment]
Wait. The menu bug has not been solved???

**Comment by Edumadaluk** [comment]
> Wait. The menu bug has not been solved???

Nope.

**Comment by ThisNekoGuy** [comment]
## System Information
- GPU: RX 7800 XT
- Video driver version: Mesa 23.3.0-rc5 (RADV)
- Kernel version: [6.5.12-tkg-pds-gentoo-gcc-zen2](https://github.com/frogging-family/linux-tkg)
- Link to full system information: [Gist](https://gist.github.com/ThisNekoGuy/fb8ef1f4146fc0598019446736fc6e52)
- Proton version: 8.0-4
- Window Manager: Kwin 5.27.9

Log: [steam-2138710.log](https://github.com/ValveSoftware/Proton/files/13471441/steam-2138710.log)

## Symptoms 
The game has an issue with crashing after completing area bosses; encountering these crashes is pretty much unavoidable on desktop Linux. This possibly causes the player to miss content immediately following.

An error window appears talking something about Vulkan in `winevulkan/loader_thunks.c` on line 5517?

<details><summary>Error Message Screenshot:</summary>

![Screenshot_20231127_011943](https://github.com/ValveSoftware/Proton/assets/28468662/c6b82f64-a960-4d26-819b-bb9da7597d47.27.9)
</details>

EDIT: ~~It doesn't happen with GE-Proton 8-25, so this is definitely a Proton bug of some sort~~
Nevermind, it can still happen; just had it happen with the second boss instead

**Comment by EyBmY** [comment]
It's been almost 2 years since the last comment so I'll bump this to make sure this issue doesn't get lost in the void unsolved.

I just bought the game and I'm facing the same issue everyone else has been facing for over 2 years. The game randomly freezes randomly.

Operating System: Arch Linux 
KDE Plasma Version: 6.4.2
KDE Frameworks Version: 6.15.0
Qt Version: 6.9.1
Kernel Version: 6.15.4-zen2-1-zen (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 5700G with Radeon Graphics
Memory: 64 GB of RAM (58.2 GB usable)
Graphics Processor 1: AMD Radeon RX 7800 XT
Graphics Processor 2: AMD Radeon Graphics
Manufacturer: Micro-Star International Co., Ltd.
Product Name: MS-7C56
System Version: 6.0

Tried Proton Experimental, Proton Hotfix, Proton 9, and Proton GE. Nothing helped.

**Comment by EyBmY** [comment]
It's been almost 2 years since the last comment so I'll bump this to make sure this issue doesn't get lost in the void unsolved.

I just bought the game and I'm facing the same issue everyone else has been facing for over 2 years. The game freezes when navigating around in the menu.

Operating System: Arch Linux 
KDE Plasma Version: 6.4.2
KDE Frameworks Version: 6.15.0
Qt Version: 6.9.1
Kernel Version: 6.15.4-zen2-1-zen (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 5700G with Radeon Graphics
Memory: 64 GB of RAM (58.2 GB usable)
Graphics Processor 1: AMD Radeon RX 7800 XT
Graphics Processor 2: AMD Radeon Graphics
Manufacturer: Micro-Star International Co., Ltd.
Product Name: MS-7C56
System Version: 6.0

Tried Proton Experimental, Proton Hotfix, Proton 9, and Proton GE. Nothing helped.

**Comment by EyBmY** [comment]
It's been almost 2 years since the last comment so I'll bump this to make sure this issue doesn't get lost in the void unsolved.

I just bought the game and I'm facing the same issue everyone else has been facing for over 2 years. The game freezes when navigating around in the menu.

Operating System: Arch Linux 
KDE Plasma Version: 6.4.2
KDE Frameworks Version: 6.15.0
Qt Version: 6.9.1
Kernel Version: 6.15.4-zen2-1-zen (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 5700G with Radeon Graphics
Memory: 64 GB of RAM (58.2 GB usable)
Graphics Processor 1: AMD Radeon RX 7800 XT
Graphics Processor 2: AMD Radeon Graphics
Manufacturer: Micro-Star International Co., Ltd.
Product Name: MS-7C56
System Version: 6.0

It seems that using "Proton Hotfix" in combination with editing the `/.../steamapps/compatdata/2138710/pfx/drive_c/users/steamuser/AppData/Local/Sifu/Saved/Config/WindowsClient/Engine.ini` file fixes the issue by adding this to the bottom:

```
[SomeOtherSection]
SomeOtherSetting=1

[/script/engine.renderersettings]
r.CreateShadersOnLoad=1
```

**Comment by yazuc** [comment]
Hi people, I don't know if anyone is still facing these issues, what solved for me was to rename the folder Movies to _Movies, there seems to be a problem with the responsible part of the game that reproduces the videos of combos, also, some other interactions that happen in-game, so until this is not properly fixed, you can do this to workaround

**Comment by Vythica** [comment]
> Hi people, I don't know if anyone is still facing these issues, what solved for me was to rename the folder Movies to _Movies, there seems to be a problem with the responsible part of the game that reproduces the videos of combos, also, some other interactions that happen in-game, so until this is not properly fixed, you can do this to workaround

I created this account specifically to thank you. I've been trying to make this game work properly for months. I'm gonna miss some cool transitions and quality of life in skill tree.

I also had a hunch that it was those video in the skill tree. Whenever the video is about to replay the game freezes.

**Comment by simifor** [comment]
@yazuc @Vythica The game is working fine on my end, got to the first shrine and repeatedly opened the skill tree and browse through the options.  So I think there are a few things worth checking.
1. Is shader cache enabled? If not, it should be, on Settings > Downloads > Enable Shader Pre-Caching 
2. If it is still crashing, run this command on your terminal: `steam steam://unlockh264/` and open the game again
3. If the issue persists, give as much information as you can about your setup (cpu, gpu, driver version, proton versions you tried) and a log for the game, changing the game's launch parameter to `PROTON_LOG=1 %command%` and run the game until the issue manifests, you'll get a text file in your home folder called `steam-2138710.log`
