### ISSUE TITLE
After Gnome 44 update, some Proton games fail to show their window's buffer correctly

### ISSUE THREAD

**Issue by BlueGoliath** [ValveSoftware/Proton#6760]
After updating to the newest Gnome version(44), some games no longer display their buffers correctly. The window will be a graphically glitched snapshot of whatever was being viewed on-screen when the game's window was created. The game still responds to keyboard inputs just fine.

Proton version: GE 8.2
Games: Metro Exodus, Metro Redux.

**Comment by mbriar** [comment]
This could be a xwayland bug exposed by newer gnome and might be fixed by https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/1107

**Comment by trinukso** [comment]
In ArchLinux it happens to me exactly the same way. Steam installed by flathub. I am using X11 with the NVIDIA driver.

Games: Forza Horizon 4 (windowed), God of War (windowed) and RE2 (windowed).

**Comment by BlueGoliath** [comment]
> This could be a xwayland bug exposed by newer gnome and might be fixed by https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/1107

I'm on Xorg just like @trinukso.

**Comment by BlueGoliath** [comment]
Is there any workaround for this?

**Comment by shrimptrimp** [comment]
Also on ArchLinux, same issue happens with Monster Hunter World on windowed and non-windowed on every version of proton, other games like Witcher 3 work just fine. On Steam Runtime and the `nvidia` driver. My window is just entirely invisible, but audio and input is still there. I did have some issues with MHW before with it not launching at all and having to delete the WINE prefix, now it does this. I am also on X11.

```
gilbert@archlinux 
OS: Arch Linux x86_64 
Kernel: 6.3.2-arch1-1 
Packages: 905 (pacman), 7 (flatpak) 
Shell: bash 5.1.16 
Resolution: 1280x1024, 1920x1080 
DE: GNOME 44.1 
WM: Mutter 
WM Theme: Adwaita 
Theme: Adwaita [GTK2/3] 
Icons: hicolor [GTK2/3] 
Terminal: kgx 
CPU: Intel i7-7700 (8) @ 4.200GHz 
GPU: NVIDIA GeForce GTX 1080 
Memory: 8329MiB / 15928MiB
```

**Comment by antonTroyan** [comment]
Roll back updates helped.
By this instruction 
https://linuxconfig.org/how-to-rollback-pacman-updates-in-arch-linux
![image](https://github.com/ValveSoftware/Proton/assets/32644076/494a5fc4-c73f-4044-ab57-43d9bfa89e6b)

**Comment by BlueGoliath** [comment]
This bug has been fixed in Mutter 44.2, which Arch has now. If anyone is having issues, update and restart.

**Comment by antonTroyan** [comment]
Issue is not resolved in manjaro linux. Mutter 44.2 fixed problem but can get it only from unstable branch. Current version in manjaro 44.1.
Any advises?

**Comment by NotMurPh** [comment]
this issue still exist on bspwm with the game Hunt: Showdown i check on dwm and it was working fine
