### ISSUE TITLE
Kingdom Come Deliverance (379430)

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#692]
Occurs on proton 3.7.3 and 3.7.4 installed with steam

Logs from proton default logging config:
[steam-prune-379430.log](https://github.com/ValveSoftware/Proton/files/2321739/steam-prune-379430.log)

Each time I've seen the system crash, I've seen the following lines in journalctl:
```
Aug 24 17:37:37 HOSTNAME kernel: [drm:amdgpu_job_timedout [amdgpu]] *ERROR* ring gfx timeout, last signaled seq=64337, last emitted seq=64339
Aug 24 17:37:37 HOSTNAME kernel: [drm] GPU recovery disabled.
```

A journalctl log from when I left the machine running after the initial hang:
[journalctl-crash-379430.log](https://github.com/ValveSoftware/Proton/files/2321753/journalctl-crash-379430.log)

Finally a workaround to get the game to get past black screen:
> Needed to copy d3dcompiler_46.dll and d3dcompiler_47.dll 
> from: 
> ~/.steam/steam/steamapps/common/KingdomComeDeliverance/Bin/Win64Shared/ 
> to: 
> ~/.steam/steam/steamapps/common/KingdomComeDeliverance/Bin/Win64/ 

Further, this game DOES work under wine 3.12 staging, with DXVK 0.64 (Configured with Lutris)
[dxvk--lutris.txt](https://github.com/ValveSoftware/Proton/files/2321757/dxvk--lutris.txt)

When i use the above configuration, I do not see the errors described above.

Game logs for those who care:
[Launcher.log](https://github.com/ValveSoftware/Proton/files/2321778/Launcher.log)
[kcd.log](https://github.com/ValveSoftware/Proton/files/2321779/kcd.log)

System Specs, short:
```
Ubuntu 18.04
AMD RX 480x w/ amdgpu-pro-18.30-633530 (--pro flag enabled)
Linux HOSTNAME 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Desktop environment: i3wm
```

System Specs, long:
[steam-system-report.log](https://github.com/ValveSoftware/Proton/files/2321785/steam-system-report.log)

**Comment by ghost** [comment]
Copying from my other comment, 

> I went so far for my issue posted: #692 as to replace all the bin files in the Proton directory with my configuration from my working Lutris install. However, for me that did not fix the problem. 

That leads me to believe that the issue is related to something Proton is setting on top of wine, not wine itself.

**Comment by ghost** [comment]
I've filled out the https://github.com/ValveSoftware/Proton/wiki/Stable google report link to reflect my testing.

**Comment by ghost** [comment]
@kisak-valve I found the issue, It is due to a bug regarding my system and esync
https://github.com/zfigura/wine/blob/esync/README.esync

I Just got it to run with the flag `PROTON_NO_ESYNC` I tried the WINE flag `WINEESSYNC` which did not work.

I read the readme, but forgot you guys use custom environment variables.

What do you want to do here? For my consideration it is fixed, but I'm unsure how to proceed. Fact is my system crashed when I was running with the default configuration.

**Comment by jarrard** [comment]
I get a infinite loading screen before main menu with the loading indicator animated on the bottom right. CPU cycle sits at 9% forever. 

That's with proton, no issues with wine/dxvk in general. 

Someone mentioned LLVM 7.0 is needed but not sure, only 6.0.1 is available.

**Comment by ghost** [comment]
@jarrard try: what I mentioned above: 

>I Just got it to run with the flag PROTON_NO_ESYNC

https://github.com/ValveSoftware/Proton#runtime-config-options

**Comment by jarrard** [comment]
Yes that does appear to work, not sure what esync is meant to do.

Also for some reason on my 4k setup I can't seem to select 1440p as a option, bit annoying. (in any steam game)

2560x1440 is a desktop resolution I can use elsewhere. Seems steam play limits to either 4k or 1080p, not a great choice range.

-5 beta of Proton has resolved the missing resolution options between 1080p and 2160p, now I can play the game at 1440p and 60-80fps, thought there is likely slowdowns in certain areas due to optimization issues with the game.

**Comment by kuraleb** [comment]
I edit file ~/.steam/steam/steamapps/common/Proton 3.7/user_settings.by removing the comment character string:
    "PROTON_NO_ESYNC": "1", 
and 
    "PROTON_USE_WINED3D11": "1",

After that, the game started and the menu was loaded.
But there are no textures

**Comment by jarrard** [comment]
this was resolved weeks ago and was related to max open files limit which you need to increase for esync to work. Most people have it too small so this problem continuously comes up!

**Comment by kuraleb** [comment]
> this was resolved weeks ago and was related to max open files limit which you need to increase for esync to work. Most people have it too small so this problem continuously comes up!

How can I solve this problem specifically in my case?

**Comment by kisak-valve** [comment]
Hello @kuraleb, give https://github.com/zfigura/wine/blob/esync/README.esync a read.

**Comment by kuraleb** [comment]
> Hello @kuraleb, give https://github.com/zfigura/wine/blob/esync/README.esync a read.

Thanks. After increasing the simultaneously opening files, the game crashes with an error: "memory allocation failed"

**Comment by jarrard** [comment]
what does ulimit -aH say? below is mine.

```
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 63179
max locked memory       (kbytes, -l) 1024
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048576
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) 63179
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

**Comment by kuraleb** [comment]
> Hello @kuraleb, give https://github.com/zfigura/wine/blob/esync/README.esync a read.

Thanks. After increasing the simultaneously opening files, the game crashes with an error: "memory allocation failed"

> ulimit -aH

`
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 46298
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048576
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) 16384
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
`

**Comment by kuraleb** [comment]
> what does ulimit -aH say? below is mine.
> 
> ```
> core file size          (blocks, -c) unlimited
> data seg size           (kbytes, -d) unlimited
> scheduling priority             (-e) 0
> file size               (blocks, -f) unlimited
> pending signals                 (-i) 63179
> max locked memory       (kbytes, -l) 1024
> max memory size         (kbytes, -m) unlimited
> open files                      (-n) 1048576
> pipe size            (512 bytes, -p) 8
> POSIX message queues     (bytes, -q) 819200
> real-time priority              (-r) 0
> stack size              (kbytes, -s) unlimited
> cpu time               (seconds, -t) unlimited
> max user processes              (-u) 63179
> virtual memory          (kbytes, -v) unlimited
> file locks                      (-x) unlimited
> ```
```
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 46298
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048576
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) 16384
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

**Comment by jarrard** [comment]
Well the only real major difference is max locked memory and max user processes. I'm not sure if those can be changed or if that would help.

**Comment by kuraleb** [comment]
> Well the only real major difference is max locked memory and max user processes. I'm not sure if those can be changed or if that would help.

I adjusted the settings. Unfortunately it did not help

**Comment by jarrard** [comment]
and if you disable ESYNC now does the game still work or has increasing open file limit introduced this new error?

Could be a issue specific to your configuration and not a general problem that we might all encounter.

To me it sounds like your trying to play the game on hardware that is below the minimal requirement, such as your GPU not having enough VRAM thus causing these allocation memory errors or missing textures (kinda the same thing).

**Comment by kuraleb** [comment]
> and if you disable ESYNC now does the game still work or has increasing open file limit introduced this new error?
> 
> Could be a issue specific to your configuration and not a general problem that we might all encounter.
> 
> To me it sounds like your trying to play the game on hardware that is below the minimal requirement, such as your GPU not having enough VRAM thus causing these allocation memory errors or missing textures (kinda the same thing).

NVIDIA Corporation GK208BM [GeForce 920M] (rev a1)
2Gb VRAM

ESYNC disabled, now the game does not get hung up, but it also crashes

And on the Wine game worked without departures.

**Comment by jarrard** [comment]
Yes, however that could be because many things are being avoided from loading, like certain graphical features, or wine could be lying about available memory hence missing textures.

2GB VRAM is pretty low, and I think the 920M is slower then a 660 which is the minimal. To make matters worse the 920M is a MOBILE gpu which introduces some other issues I believe. 

I think in your particular case, the solution would be to create a dual boot situation and use Windows to try this game out vs attempting it on proton under Linux. Your hardware specs are just so minimal and this game is VERY demanding.

**Comment by kuraleb** [comment]
> Yes, however that could be because many things are being avoided form loading, like certain graphical features, or wine could be lying about available memory hence missing textures.
> 
> 2GB VRAM is pretty low, and I think the 920M is slower then a 660 which is the minimal. To make matters worse the 920M is a MOBILE gpu which introduces some other issues I believe.
> 
> I think in your particular case, the solution would be to create a dual boot situation and use Windows to try this game out vs attempting it on proton under Linux. Your hardware specs are just so minimal and this game is VERY demanding.

This game works for me and under the Wine and Windows. On the same hardware. 8 fps, but it worked.

And a Proton is faced with similar problems

**Comment by jarrard** [comment]
I thought you said just above that under Wine it doesn't render in all the textures?

The issue here is that people with reasonably decent hardware seem to be having no problems now provided they set things up right. 

So unless you can find someone with a 960M or something who is experiencing similar issues then there might not be much that can be done at this point in time.

**Comment by kuraleb** [comment]
> 
> 
> I thought you said just above that under Wine it doesn't render in all the textures?
> 
> The issue here is that people with reasonably decent hardware seem to be having no problems now provided they set things up right.
> 
> So unless you can find someone with a 960M or something who is experiencing similar issues then there might not be much that can be done at this point in time.

At me on the wine works with all textures.
10-15 fps

**Comment by jarrard** [comment]
only thing you can do is a apitrace and see what comes of it.

**Comment by aw-was-here** [comment]
> what does ulimit -aH say? below is mine.

Be aware that on systemd-based machines, ulimit is a lie.  systemd's cgroup settings will override them unless it is specifically configured otherwise.

**Comment by kisak-valve** [comment]
Kingdom Come Deliverance: Weird frame stutter after hr of play, fps is ok but.

Issue transferred from https://github.com/ValveSoftware/Proton/issues/2215.
@jarrard posted on 2019-01-14T05:27:05:

# Compatibility Report
- Kingdom Come Deliverance
- 379430

## System Information
- GPU: 1080Ti
- Driver/LLVM version: 415.22.05
- Kernel version: 4.19/4.20
- Specs: https://gist.github.com/jarrard/69d7c752fae460acba60d77d189649d1
- Proton version: 3.16-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Steam log (just to main menu then back out again.)
[steam-379430.log](https://github.com/ValveSoftware/Proton/files/2754086/steam-379430.log)


## Symptoms 
After about a hour or so of game-play a weird issue occurs when looking around that causes mouse stutter, however frame-rate is otherwise fine. Game is unplayable when it does this.

## Reproduction
Play for a sufficient amount of time.

***
@jarrard commented on 2019-01-14T06:40:42

If anyone else gets this issue (likely NVIDIA related) then please do comment. It seems pretty consistent with about 1-2hrs worth of play time when it happens.

**Comment by AsciiWolf** [comment]
Is the dll copy workaround still needed?

**Comment by jarrard** [comment]
in the Win64Shared folder thing? yes I believe so.

**Comment by AsciiWolf** [comment]
Is there any way to fix this directly in Proton? KCD works great under Proton and this is the only thing that prevents it from running out-of-box.

**Comment by jarrard** [comment]
Dunno, but it seems the games exe can't navigate to where the original DLL files are located and that is likely a underlying Wine directory pathing error. 

Perhaps a full error log on load up will reveal more on exactly what is going wrong for it to default back to the core exe directory and not the Shared folder.

PS. It should be noted that this isn't the only game where DLL locations have problems, I can't remember which others off the top of my head however.

**Comment by kaimast** [comment]
I seem to only be able to run the game with Proton 3.7. All other versions freeze at the initial flash screen. I wonder if anybody else has this issue?

**Comment by jarrard** [comment]
Sorry mine seems fine at 3.16.6 beta, been experimenting with the new adaptivesync drivers 418.30, makes KCD playable at 4k under Linux, pretty surprised. 
Does require some graphical tweaking and running on mostly medium settings. Also the nexus mod optimized graphics presets helps (there is a small flicker bug with the optz fog setting however)

**Comment by AsciiWolf** [comment]
@kaimast I had the same issue on Fedora 29 with RX 580 and Flatpak version of Steam. This was in the log: `wine: Call from 0x7b44af1c to unimplemented function amd_ags_x64.dll.agsGetCrossfireGPUCount, aborting`

Changing the Proton version to 3.7-8 did not help, however copying `amd_ags_x64.dll` from _Win64Shared_ to _Win64_ fixed the issue and Kingdom Come now runs fine on my system. :-)

**Comment by kattjevfel** [comment]
To get this to work for me I had to set PROTON_USE_WINED3D to 1, otherwise it would just hang at the startup splash, using 3.16.6 I only got a black screen.

FPS is absolute rubbish though, 10fps at lowest settings 1080p (around 50-60fps on windows on medium-high, 1440p)

Proton: 4.2-1
GPU: GTX 1080
Driver: nvidia 418.56-5
Kernel: 5.0.5
[System information](https://gist.github.com/Kattus/f6a2c64408cf1ede46580fe960c4990c)
[steam-379430.log](https://github.com/ValveSoftware/Proton/files/3035692/steam-379430.log)

**Comment by astillich** [comment]
About the input stutteer: I have this issue, too. Each time I move the mouse, Proton loads and unloads dinput8.dll. After doing this a lot of times, something seems to slow down DLL loading (?) and cause the stutter.

`
48621.964:0024:0025:trace:module:LdrAddRefDll (L"dinput8.dll") ldr.LoadCount: 2
48621.964:0024:0025:trace:module:LdrUnloadDll (0x7f6fd19f0000)
48621.964:0024:0025:trace:module:LdrUnloadDll (L"dinput8.dll") - START
48621.964:0024:0025:trace:module:MODULE_DecRefCount (L"dinput8.dll") ldr.LoadCount: 1
48621.964:0024:0025:trace:module:LdrUnloadDll END
48621.965:0024:0025:trace:module:LdrGetDllHandle L"C:\\windows\\system32\\dinput8.dll" -> 0x7f6fd19f0000 (load path L"Z:\\home\\torque\\.steam\\steam\\steamapps\\common\\KingdomComeDeliverance\\Bin\\Win64;C:\\Program Files (x86)\\Steam;C:
\\windows\\system32;C:\\windows\\system;C:\\windows;.;C:\\windows\\system32;C:\\windows;C:\\windows\\system32\\wbem")
48621.965:0024:0025:trace:module:LdrAddRefDll (L"dinput8.dll") ldr.LoadCount: 2
48621.965:0024:0025:trace:module:LdrUnloadDll (0x7f6fd19f0000)
48621.965:0024:0025:trace:module:LdrUnloadDll (L"dinput8.dll") - START
48621.965:0024:0025:trace:module:MODULE_DecRefCount (L"dinput8.dll") ldr.LoadCount: 1
48621.965:0024:0025:trace:module:LdrUnloadDll END
48621.965:0024:0025:trace:module:LdrGetDllHandle L"C:\\windows\\system32\\dinput8.dll" -> 0x7f6fd19f0000 (load path L"Z:\\home\\torque\\.steam\\steam\\steamapps\\common\\KingdomComeDeliverance\\Bin\\Win64;C:\\Program Files (x86)\\Steam;C:\\windows\\system32;C:\\windows\\system;C:\\windows;.;C:\\windows\\system32;C:\\windows;C:\\windows\\system32\\wbem")
48621.965:0024:0025:trace:module:LdrAddRefDll (L"dinput8.dll") ldr.LoadCount: 2
48621.965:0024:0025:trace:module:LdrUnloadDll (0x7f6fd19f0000)
48621.965:0024:0025:trace:module:LdrUnloadDll (L"dinput8.dll") - START
`
<...>

**Comment by jarrard** [comment]
Once the next DLC hits I'll probably get back into trying KCD out, not sure if the stutter issue exists or how well it runs with 4.2. 

Also if you use PROTON_USE_WINED3D=1 then that effectively disables DXVK, keep that in mind when getting terrible FPS. 
Eventually Wine itself will use Vulkan for DirectX and it won't be a issue but for now its using terrible OpenGL wrapping which is ok for DX9 and below but BAD for DX11 games!

**Comment by m0stly** [comment]
Edit: Performance issues fixed in official Proton 4.11-1. Custom proton no longer required.

~~There is a large performance issue with 4.2-9 (and earlier that I tested) since 1.9 of game that is fixed by custom proton build: [Proton-4.11-GE-1](https://github.com/GloriousEggroll/proton-ge-custom/releases).~~  

~~I get:~~
~~- 45 fps with official proton 4.2-9.~~
~~- 90 fps using [Proton-4.11-GE-1](https://github.com/GloriousEggroll/proton-ge-custom/releases).~~

~~When looking at GPU clocks using 4.2-9 these are unusually low, GPU boosting as expected with custom proton.~~
~~Updating DXVK does not resolve, unable to narrow down further.~~

~~I know of 1 other Vega user and 1 Nvidia user reporting this build fixes performance issue.~~

~~- GPU: RX Vega 56~~
~~- Driver/LLVM version: 19.1.2 & 19.2.0-devel + ACO~~
~~- Kernel version: 5.2.1-arch1-1-ARCH~~
~~- [Gist](https://gist.github.com/m0stly/292637ca288c30ca932e312aa98a790a)~~
~~- Proton version: 4.2-9~~

**Comment by AsciiWolf** [comment]
Fedora 30, GNOME 3.32 (Wayland), Mesa 19.1.2, AMD RX 580, Proton 4.11, [workaround](https://github.com/ValveSoftware/Proton/issues/692#issuecomment-460063245) applied, "Very High" preset.

Kingdom Come runs absolutely amazing with Proton 4.11! With Proton 4.2, I had around 8 - 18 fps, with Proton 4.11, I get 28 - 40 fps, sometimes even 50+ fps.

**Comment by kaimast** [comment]
Does it work for you without setting PROTON_USE_WINED3D to 1?

For me it still hangs at the startup splash using proton 4.11 and not using vulkan results in horrible FPS.

**Comment by kattjevfel** [comment]
Works for me with the workaround (copying amd_ags_x64.dll), get 30-60 FPS on medium, 1080p.
Arch Linux, Plasma 5.16.4 (xorg), nvidia 430.40, GTX 1080, Proton 4.11-2
[steam-379430.log](https://github.com/ValveSoftware/Proton/files/3534410/steam-379430.log)

**Comment by jarrard** [comment]
you should get over 60fps at 1080p with gtx1080!

**Comment by kattjevfel** [comment]
@jarrard no idea what I got on windows, but I normally play in 1440p anyway and all I can remember is that the FPS was crap no matter what..

**Comment by jarrard** [comment]
Yeah KCD needs vulkan and/or major optimisations.

**Comment by jarrard** [comment]
I have an annoying issue with this when running 1800p with dual monitor. 
My mouse will get stuck moving right towards my second monitor. The old stuck mouse pan issue basically. Can't seem to resolve this one however, this is on plasma5. 

EDIT: Figured it out, its some proton/game glitch where it doesn't correctly resize the game-screen and you end up with cut off bits, and when you minimise it breaks protons ability to capture the mouse. 

You can reset the behaviour in-game by changing down and up a resolution, with a bit of fiddling and luck you can get it to switch correctly without needing to minimise (where it messes up the mouse capture).

Possible proton needs some help detecting when a game is minimised or when a mouse looses game window capture while window is focused.  Could be a unique issue to kwin also... (and dual monitor setups)

NOTE: KCD is quite dicey even under windows where it will resize desktop app windows because it forces screen to some 720p mode or something.. its a bit of a mess, shame the developers are not resolving these issues!  (they know about them btw)

**Comment by kaimast** [comment]
Same result with DXVK on proton 4.11-4: The game keeps getting stuck on the splash screen :/

**Comment by kattjevfel** [comment]
@kaimast Even with copying the dlls as mentioned above?

**Comment by kaimast** [comment]
Oh you're right. After copying all DLLs, not just the d3dcompiler ones, it works for me. 

`cp Win64Shared/*.dll Win64`

**Comment by jarrard** [comment]
splash screen getting stuck is often a issue with esync/fsync and also filelimits, plus incorrectly setting up your NTFS drive which has KCD on it. (proton itself should never be installed on a NTFS also, be sure its in your home steam folder correctly)

**Comment by xorgy** [comment]
I get this message on the splash screen by default in Proton 4.2.

> Unsupported Graphics Card detected.
> A GPU with support for D3D FeatureLevel 11.0 is required.

![Unsupported Graphics Card detected. A GPU with support for D3D FeatureLevel 11.0 is required.](https://user-images.githubusercontent.com/1272018/69174720-40979880-0afa-11ea-9a49-20c9060da3a3.png)

**Comment by kaimast** [comment]
> I get this message on the splash screen by default in Proton 4.2.
> 
> > Unsupported Graphics Card detected.
> > A GPU with support for D3D FeatureLevel 11.0 is required.
> 
> ![Unsupported Graphics Card detected. A GPU with support for D3D FeatureLevel 11.0 is required.](https://user-images.githubusercontent.com/1272018/69174720-40979880-0afa-11ea-9a49-20c9060da3a3.png)

What GPU are you using? It might not support certain OpenGL /Vulkan extensions needed for DX11.

**Comment by jarrard** [comment]
I wouldn't play this game on anything less than a RX480 / GTX960. 
It's a VERY demanding game and isn't all that greatly optimized atm. Hopefully it gets upgraded to vulkan api sometime.

**Comment by xorgy** [comment]
> What GPU are you using? It might not support certain OpenGL /Vulkan extensions needed for DX11.

I'm using a Radeon VII with RadeonSI and RADV (Mesa 19.2.4). I previously successfully launched KCD on a Radeon WX 7100 some time back though I no longer have access to that system to see if it's a software regression or a hardware difference.

**Comment by xorgy** [comment]
@kaimast
> What GPU are you using? It might not support certain OpenGL /Vulkan extensions needed for DX11.

I'm using a Radeon VII with RadeonSI and RADV (Mesa 19.2.4). I previously successfully launched KCD on a Radeon WX 7100 some time back though I no longer have access to that system to see if it's a software regression or a hardware difference.

**Comment by jarrard** [comment]
I remember there being some early issues with Radeon 7 cards. Can you update to bleeding edge mesa?

**Comment by kisak-valve** [comment]
Hello @xorgy, please verify you have both the 64 bit and 32 bit variants of mesa's vulkan drivers (like `mesa-vulkan-drivers mesa-vulkan-drivers:i386`) from your package manager.

**Comment by xorgy** [comment]
> Hello @xorgy, please verify you have both the 64 bit and 32 bit variants of mesa's vulkan drivers (like `mesa-vulkan-drivers mesa-vulkan-drivers:i386`) from your package manager.

That wasn't the problem, though I changed a Steam setting (the default Proton) and it inexplicably deleted KCD (the whole thing), then reinstalled it; then it started working. I love when evidence is destroyed automatically.

**Comment by jarrard** [comment]
Yeah sometimes proton itself can install incorrectly. For example on my system it keeps installing to NTFS on new distro installs, never defaults to the .steam folder path. Proton doesn't like that.

**Comment by Patola** [comment]
Hi, I just want to include my [gamingonlinux post](https://www.gamingonlinux.com/forum/topic/4157) here so that it can be seen by more people. Kingdom Come: Deliverance works correctly, BUT its performance is horrible. My post:

Hi all,

Anyone playing Kingdom Come: Deliverance -- https://store.steampowered.com/app/379430 -- on Linux via Steam Play? The game is great but its performance is horrible. I am trying to get as much performance as I can while preserving detail and high quality of textures, because even using the high resolution textures my GPU is seldom used above 4GB.

I have a RTX 2070 SUPER 8 GB and even then I can't get higher than 20 fps on the Rattay Tourney setting. It oscillates between 12 and 18 and sometimes goes up to 20. 2560x1080p, ultrawide, fullscreen.

I am not using any DXVK/PROTON variables (so, I am not using WINED3D11) and my launch options only has gamemoderun %command%. I run more than a hundred other games via proton with a very high framerate, including classics like The Witcher 3 and No Man's Sky.

What I have already done:

- Disabled motion blur. It helps a little.

- Tried changing drivers, from 435.21 to 440.26 (graphics-drivers ppa -- https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa). No noticeable change except that in the first minutes it stutters a little (maybe recompiling shaders?).

- Tried the Valve fsync kernel -- https://steamcommunity.com/app/221410/discussions/0/3158631000006906163/ -- to use fsync instead of esync. Confirmed it was running ("fsync: up and running" on ~/.steam/error.log). No noticeable change.

- Used the console to change "r_BatchType" -- https://www.protondb.com/app/379430#JgHjecc_a9 -- between 0 and 1. No noticeable change.

- Used Feral's gamemode -- https://github.com/FeralInteractive/gamemode -- (added gamemoderun to the launch parameters, confirmed it was launching this way). No noticeable change.

- Used Proton-GE (Proton-4.19-GE-1 -- https://github.com/GloriousEggroll/proton-ge-custom/releases), confirmed it was launching correctly under this version. No noticeable change either!

- Toggled amongst windowed fullscreen, fullscreen and windowed modes, but I already run the game under a window manager (LXDE + Openbox) that does not use compositing -- https://dquinton.github.io/debian-install/config/lxde-openbox.html#8 -- so that should not really make a difference. There was no noticeable difference indeed.

Any other tips on what I can do to improve performance without losing detail? It is of note that according to DXVK HUD I am using the GPU at 100% capacity during the game, except during the intermissions of course.

My setup:
========
System:    Host: risadinha Kernel: 5.0.0-23-lowlatency x86_64 bits: 64 Desktop: LXDE (Openbox 3.6.1)
           Distro: Ubuntu 18.04.3 LTS
Machine:   Device: desktop Mobo: ASUSTeK model: PRIME B350-PLUS v: Rev X.0x serial: N/A
           UEFI: American Megatrends v: 5220 date: 09/12/2019
CPU:       8 core AMD Ryzen 7 2700 Eight-Core (-MT-MCP-) speed/max: 2873/3400 MHz
Graphics:  Card: NVIDIA Device 1e84
           Display Server: x11 (X.Org 1.19.6 ) driver: nvidia Resolution: 2560x1080@144.00hz
           OpenGL: renderer: GeForce RTX 2070 SUPER/PCIe/SSE2 version: 4.6.0 NVIDIA 440.26
Network:   Card: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller driver: r8169
Drives:    HDD Total Size: 8241.7GB (86.3% used)
Info:      Processes: 424 Uptime: 5:01 Memory: 4311.6/32161.0MB Client: Shell (zsh) inxi: 2.3.56 

After @doitsujin asked me for more details, including my in-game settings:
My in-game settings:
Graphics settings: Resolution: 2560 x 1080
Window Mode: Fullscreen
Overall image quality: custom
HD Textures: On
Show FPS: Off
VSync: Off
Vertical FOV: 75

Advanced Graphics Settings:
Antialiasing: SMAA 1TX
Object Quality: Very High
Game effects: High
Lighting: High
Particles: High
Physics: High
Postprocess quality: High
Shader quality: High
Shadows: High
Textures: High
Water details: High
Volumetric effects detail: High
Vegetation detail: High:
Object distance: (about 2/3 of bar)
LOD distance: (about 1/3 of bar)
Vegetation draw distance: (about 1/3 of bar)
Motion Blur: Off

I used both nvidia-smi and nvidia-settings to get the GPU utilization from moment to moment and it was between 98-100% all the time. Curiously, as I am typing now, with the game minimized, nvidia-settings is telling me GPU utilization is fluctuating between 91% and 100%.

I have screenshots of all settings and nvidia-settings and nvidia-smi if you need.

**Comment by xorgy** [comment]
@Patola For a datapoint, I'd like to just say that I get excellent performance when running KCD on RADV on my Radeon VII; often at or near my 165Hz refresh rate at 1440p, never below about 100fps except during initial shader compilation. I'm running ordinary stable Mesa releases on Archlinux with a 5.3 series kernel.

If you are having performance that bad, it is probably an issue specific to your card/drivers/compositing window manager/something else, and not a general issue with KCD on Proton.

**Comment by Patola** [comment]
> @Patola For a datapoint, I'd like to just say that I get excellent performance when running KCD on RADV on my Radeon VII; often at or near my 165Hz refresh rate at 1440p, never below about 100fps except during initial shader compilation. I'm running ordinary stable Mesa releases on Archlinux with a 5.3 series kernel.
> 
> If you are having performance that bad, it is probably an issue specific to your card/drivers/compositing window manager/something else, and not a general issue with KCD on Proton.

I don't think so, my experience is shared by other people who use NVIDIA and I have tried changing driver versions a couple times, as I told in my post. As I also said on the same post, I use a Window Manager without compositing. And as I also said in that post, other games work great - I get more than 200 fps on RE2 and RE7, for example, and close to 100 on the Witcher 3 on ultra. I have more than 100 proton games installed, all but KCD working with full performance.

And this seems something specifically introduced in 1.9 release of the game. I will see if I can get some time to install the last 1.8 patch to see if the performance gets better, but of course almost everybody who buys this game to be played on proton will still use the latest 1.9.4, so if it is indeed some difference from the Windows drivers (which perform great as I have read), it's better to fix that in proton.

**Comment by Patola** [comment]
To try and give more info... Here's the steam-379430.log I get when I run the game with PROTON_LOG=1, under Proton 4.11-9.
[steam-379430.log](https://github.com/ValveSoftware/Proton/files/3907732/steam-379430.log)

**Comment by xorgy** [comment]
@Patola 
> I don't think so, my experience is shared by other people who use NVIDIA...

That's kinda what I meant to say, without sending out the "NVIDIA's driver is fickle and opaque" vibes that start flame wars. The issue you're describing is at least specific to NVIDIA's Vulkan Driver combined with DXVK combined with the current release of the game.

**Comment by jarrard** [comment]
Proton-GE can often cause a massive fps cap of about 43ish fps with this game. Try switching to normal proton, test (no need to delete container), then if that fixes the issue try switching back to GE. 

I have experienced this terrible performance issue myself and it was just a matter of doing the above to resolve it.

The only benefit for using proton-GE is it switches the keyboard to US or something which allows console use. It might also fix some key bindings, I dunno.

**Comment by Patola** [comment]
> Proton-GE can often cause a massive fps cap of about 43ish fps with this game. Try switching to normal proton, test (no need to delete container), then if that fixes the issue try switching back to GE.

Thanks, but I have tried that not one time, but multiple times. And to different versions of proton and proton-GE too.

> 
> I have experienced this terrible performance issue myself and it was just a matter of doing the above to resolve it.

Do you also have a NVIDIA? Which one? How many FPS do you get, what are your settings in-game?

> 
> The only benefit for using proton-GE is it switches the keyboard to US or something which allows console use. It might also fix some key bindings, I dunno.

I didn't notice this difference. I was able to use the console under Proton, I think.

**Comment by jarrard** [comment]
For starters, I have a 1080TI latest drivers, my configuration is going to be wildly different to yours, I play with medium to high settings with SMAA+CAS from reshade(If I remember correctly) AT 4k I get 40-50fps, at 1800p I get 50-60fps (what I use atm).

I have a console issue because my keyboard is not US based, its a Spanish English one, can cause issues at times for some games.  Bought it because it was less then half price of the English version one.


PS. I also use mods, custom user.cfg, and optimized graphics mod

**Comment by Patola** [comment]
Which ones are the latest drivers? Production drivers 440.26 / 440.36 or beta drivers 435.21 / 435.27 ? What's the page of these optimized graphics mod?

**Comment by jarrard** [comment]
440.31 release drivers
https://www.nexusmods.com/kingdomcomedeliverance/mods/743
READ THE INSTRUCTIONS, MOST PEOPLE DON'T AND HAVE ISSUES!

<details><summary>My user.cfg file (-- text is excluded)</summary><p>

```
-- Needs +exec user.cfg in steam launch options
-- Bow reticle

wh_pl_showfirecursor=1

-- Better Targetting

wh_cs_playermaxopponentdistancetolock = 8
wh_cs_playermaxopponentdistancetounlock = 8
wh_cs_playerunlocktimeout = 0
wh_cs_playerverticalunlockdelay = 0
wh_cs_playerhorizontalunlockdelay = 0
wh_cs_playerlockopponentanglebias = 2
wh_cs_playermaxopponentangletolock = 0.8
wh_cs_playermaxopponentangletounlock = 0.8
wh_cs_playerinputcombatunlockdelay = 0
wh_cs_playerinputcursorunlockdistance = 0.05
wh_cs_playerinputlockingtolerance = 20
wh_cs_playerinputlockareawidth = 0.6
wh_cs_playerinputmouseunlockxthreshold = 60
wh_cs_playerinputmouseunlockmintime = 0
wh_cs_playerinputmouseunlockreturntime = 1.5
wh_cs_playerinputmouseunlockminoppangle = 20

-- Ambient Occlusion Fix

r_ssdo=1
r_ssdoAmountAmbient=1.4
r_ssdoAmountDirect=2
r_ssdoAmountReflection=4
r_ssdoHalfRes=2
r_ssdoRadius=0.04
r_ssdoRadiusMin=0.07
r_ssdoRadiusMax=0.1
e_svoTI_SSAOAmount=1.545
e_svoTI_SpecularAmplifier=0.82
e_svoTI_TemporalFilteringBase=1
e_svoTI_MinReflectance=0.19
e_svoTI_DiffuseAmplifier=1.12

-- Shadow fix

r_ShadowsAdaptionMin = 1.12
r_ShadowsAdaptionSize = 1.28
r_ShadowsAdaptionRangeClamp = 0.008

-- testing, maxfps set so GPU doesn't overheat

r_TexMaxAnisotropy = 16
r_antialiasingMode = 3
-- r_antialiasingTAASharpening = 1.3
r_sharpening = 0
r_fullscreen = 1
sys_maxfps = 64
```

</p></details>

**Comment by lwho** [comment]
The update from Proton 4.11-10 to 4.11-11 has caused a severe performance regression for me. Where previously I got between 30 and 60 fps I now hardly get 5 fps. I put a self-compiled 4.11-10 into compatibilitytools.d and by using that it's back to normal, so definitely caused by 4.11-11.

GPU: Nvidia GTX 1660 Super
Driver: Nvidia 440.44
CPU: i5-3450 (3.1Ghz)
RAM: 16 GB
Distro: Kubuntu 18.04

user.cfg:
```
wh_pl_showfirecursor=1
sys_budget_videomem=6000
sys_budget_sysmem=12000
r_TexturesStreamPoolSize=2048
e_ShadowsPoolSize=1024
r_MotionBlur=0
sys_maxfps=30
```

**Comment by kisak-valve** [comment]
Hello @lwho, with Proton 4.11-11, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and drag and drop the generated $HOME/steam-$APPID.log into the comment box.

**Comment by lwho** [comment]
[steam-379430.log](https://github.com/ValveSoftware/Proton/files/3990569/steam-379430.log)
(with Proton 4.11-11 run until the main menu; up to 7 fps there)

**Comment by kisak-valve** [comment]
Possible line of interest from the log: `err:   D3D11: Cannot map a device-local image`

**Comment by troylights** [comment]
Major performance regression with KCD using Proton 4.11-11 compared to older 4.11 versions.
Previously, I got 77-79 fps at the main menu while now I am getting 38-40.  In-game framerates (Sasau town and area) in the 20s to 30s, though I can get in the 50s if I look up at the sky.  This is at least 50 % lower than what I experienced in earlier Proton 4.11 versions (over 50 hours of gameplay).

Game settings: 1080p, everything on 'high' except medium LOD and shadows, HD sound and textures, 'medium' AA and motion blur.  Settings have not been changed for over 40 hours of play time.

System configuration:  Ryzen 3 1300x @ 3.6 GHz, RX 580 8 GB, 16 GB DDR4 3200 RAM, 1080p 144Hz adaptive sync monitor,
Ubuntu 18.04, 5.0.0-37-lowlatency, Mesa 19.3-ACO (Valve PPA), Feral Interactive's Gamemode (launch option 'gamemoderun %command%').

**Comment by ghost** [comment]
Only get to try with Proton 4.11-11 so I cannot say that the performance get worse, but it's is terrible nonetheless,  I can't get pass 40s fps even on low settings.
Although, when I try enabling fsync, the game runs immensely better.
[screenshot + settings](https://imgur.com/a/cJsSiwu)
1080p with HD Texture

Specs: Ryzen 2200G, RX570 4GB, 8GB DDR4 2400 RAM.
Manjaro 5.4.3-arch1-1-fsync

**Comment by jarrard** [comment]
tried with proton-421-ge-2 and well it ran about 1fps lol. Not sure what the issue was, didn't investigate but yeah its broken atm :(

See if I can get fsync installed and going. Tho I don't see why that should be the fix.

**Comment by jarrard** [comment]
It seems after messing with the graphics settings and changing resolution the performance jumped back up, which was about 44fps on the main menu scene at 4k with medium to high settings. 

In game I normally run at 1800p to try and gain a extra 10fps to make up for lost performance by running it via proton and not on native windows.

Keep in mind I'm using a 1080TI, so the issue with general performance regressions might be mostly hitting AMD users.

**Comment by Patola** [comment]
No news about the performance problem of KCD 1.9 and greater?

**Comment by jarrard** [comment]
I dunno if I'm experiencing it, try changing resolutions up and down etc.. I think its partially a game bug. 

Just tested this out and there does appear to be maybe a performance issue. At 1800p I was getting 25-27fps but normally I get above 50fps in the same area. Not sure what to think.

**Comment by jarrard** [comment]
YEP Changed resolution from 1440p 1800p 2160p, virtually no difference in performance/framerate, something is going on here for sure! 

Ok I seem to have fixed it, a few things to note.
1) When proton updated it decided it would exist on my NTFS drive from now on, this is bad! 
2) I deleted the prefix folder (back up saves) and rebuilt it again with the correct proton version selected (which now exists in my ext4 home folder as it should be!)

Now the fps does change when switching between resolutions and is on par with what I got before. With my 1080TI and Medium to high settings @ girlfriends house whatever her name is outside rattay, 
1440p ~66fps
1800p ~50fps
2160p ~40fps

The framerate swings in this game are pretty crazy at times depending on where you are and which direction your looking, I've tried to advocate for getting Vulkan happening from the developers but it kept falling on deaf ears, their not interested in upgrading the engine sadly :(

This game is built on cryengine, which supports vulkan!

**Comment by Patola** [comment]
Tried reinstalling. Even tried to remove remaining shader caches and such and then installed and configured it all from scratch without any mods whatsoever. SAME THING. Same framerate. :-( On the Rattay Tourney, less than 20 fps. That's ludicrous.

**Comment by jarrard** [comment]
What resolution? 
I am using the optimized_graphic_presets mod but it doesn't give you that much better fps (maybe 5fps)

The only other thing worth mentioning is I'm using a fsync kernel version (linux-zen). You could also try installing Proton-GE or Proton-TKG builds and test them out to see what happens. 

Something is definitely going wrong, it would be helpful if other people chimed in on their experiences.

**Comment by Patola** [comment]
2560x1080, same one as I said in "my setup" post [here](https://github.com/ValveSoftware/Proton/issues/692#issuecomment-560029901) -- what changed is that now I am using NVIDIA driver 440.44.

**Comment by jarrard** [comment]
Yeah I would say you should be getting like 80FPS or close to.  I wonder if NVAPI is somehow being enabled in your case.

**Comment by Patola** [comment]
For some reason performance is now good. Not sure if it is due to the updated nvidia driver or proton itself. Framerate at the Rattay Tourney is exactly double of what is was before. The game is much smoother now, without any difference in the graphical settings. Proton 4.11-12. Also tried Proton 5.0 but the game does not run under it.

**Comment by AsciiWolf** [comment]
@Patola What happened when you tried to run Kingdom Come with Proton 5.0? Was there any error?

**Comment by Patola** [comment]
No. It stays a while in the "launching" state then finishes. The screen doesn't even blank. I am attaching the proton logfile for you to see.
[steam-379430.log](https://github.com/ValveSoftware/Proton/files/4176145/steam-379430.log)

**Comment by AsciiWolf** [comment]
Interesting. From the log it really seems to be caused by some Wine regression. However, it also looks like you don't have proper Vulkan support.

**Comment by Patola** [comment]
> Interesting. From the log it really seems to be caused by some Wine regression. However, it also looks like you don't have proper Vulkan support.

What? Haha. That's absurd. I use Vulkan since the very beginning and I have almost 200 installed games using dxvk and also lots of native games using the Vulkan API. I use Valve's fsync kernel and my ulimit nofiles is 1048576 just in case esync is used. I am using NVIDIA driver 440.59 and I often turn the "Enable Graphics API Visual Indicator" on nvidia-settings on, so that I can see the game is using Vulkan. I also often use the DXVK HUD which only works with Vulkan.

**Comment by kattjevfel** [comment]
@Patola do you have any previous workarounds active? Like the one to make it work in 4.11. I just installed KCD and it runs fine without any modifications on my end.

[system info](https://gist.github.com/Kattus/5472c7bb338a39c77e165451d7a3c2c5) tl;dr: Ryzen 1600X + GTX1080, nvidia 440.59
[steam-379430.log](https://github.com/ValveSoftware/Proton/files/4177664/steam-379430.log)

**Comment by Patola** [comment]
> @Patola do you have any previous workarounds active? Like the one to make it work in 4.11. I just installed KCD and it runs fine without any modifications on my end.
> 
> [system info](https://gist.github.com/Kattus/5472c7bb338a39c77e165451d7a3c2c5) tl;dr: Ryzen 1600X + GTX1080, nvidia 440.59
> [steam-379430.log](https://github.com/ValveSoftware/Proton/files/4177664/steam-379430.log)

No. I wasn't even aware of these workarounds until you said it (I went on to see it on protondb).

**Comment by AsciiWolf** [comment]
<details><summary>KCD runs great with latest Proton 5.0-5 on AMD RX 580 with Mesa 20.0.1, however I have noticed a smaller graphical glitch:</summary><p>

![flickering](https://user-images.githubusercontent.com/2339930/79152470-908a3b00-7dcc-11ea-8205-c0c3ea3492c5.gif)

</p></details>

**Comment by kisak-valve** [comment]
@AsciiWolf, please do not "veto" a moderator edit. Your gif was not removed, it can be shown when clicking on your comment.

**Comment by AsciiWolf** [comment]
@kisak-valve Oops, I did not notice my post was edited by you. Sorry for reverting your edit.

**Comment by AsciiWolf** [comment]
Another issue that I just noticed is that I cannot draw a bow. I have both bow and arrows equipped, but pressing "2" to draw a bow does nothing. Do someone else have this issue with KCD under Proton? As far as I know, this should work fine. It can be some configuration issue on my side, but I was not able to workaround this issue so far.

**edit:** It was caused by a non-English keyboard layout. Remapping the sword/bow keys to F1 and F2 fixed the issue.

**Comment by AsciiWolf** [comment]
> 
> KCD runs great with latest Proton 5.0-5 on AMD RX 580 with Mesa 20.0.1, however I have noticed a smaller graphical glitch:

I just found out that the same issue also happens when running the game on Windows. So, this is definitely a game issue, not a Proton/DXVK/Mesa one. :-)

**Comment by toczownik** [comment]
I have trouble going to sleep during the second quest in Talmberg. When I confirm length of sleep, the game freezes. I tried sleeping in other places, but sleeping is blocked in the home town. I bought the game this week, so I can't say whether it's something new or not.
My setup:
- Lenovo Legion Y540 (GTX 1650, i7-9750H @ 2.60GHz, 16GB)
- Pop!_OS 20.04
- kernel 5.4.0-7642-generic
- nvidia driver 450.66
- same results with proton 5.0-9 and 4.11.

The log also says that something is wrong with gameoverlayrenderer.so, but the overlay works without any bugs.
[steam-379430.log](https://github.com/ValveSoftware/Proton/files/5318785/steam-379430.log)

**Comment by jarrard** [comment]
Been testing this game out with 6800XT and still experience odd framerate issues.

The silver mine has a overlook towards the prologue area is a good testing area. Sometimes if I stand there the fps will dip to 30-35, if I exit game and reload to exact spot I can get over 60fps... but waiting a minute and it drops to 35fps again...

I just can't figure out what is going on with this game, I suspect wine/proton is flipping out over something and kills the performance randomly.

So right now my game is flipping between 25 and 60+ fps (vsync is on). There isn't a explanation for it. 

UPDATE: After doing some reason it seems the engine is just not happy with AMD GPU's. Have yet to find a fix to the bad performance.  On average my 1080TI ran better then this 6800XT with this game.

**Comment by jarrard** [comment]
After extensive testing I've come to believe KCD has a LOD _(LevelOfDetail Model/Object)_ loading issue where it does not cull or unload lods.  I believe this to affect AMD users the most. 

There are areas of the game where it appear to have issues regardless, but after testing many proton versions and e/f-syncs on/off, and different compilers (aoc/llvm), the issue remained! Which was where walking around would reduce fps performance rapidly so instead of getting 60+ fps you'd get 20-35fps in many areas. (and the fps hit would linger)

There were areas that gave the worse performance in game and I was able to save in the exact spot and reload the game and got my max vsync framerate provided I didn't move about too much. As soon as I walked over to a heavy LOD area and then walked back to the exact original spot, I'd lost 20-30fps or more.

My conclusion is that there is a fundamental game engine bug occurring that probably can't be fixed at the driver end.

NVIDIA users probably don't experience the same issue. I only had a 1080TI prior to this which is not a good 4k test case since it struggled to maintain over 40fps most times anyway. 
Maybe I'll switch back to NVIDIA come next GPU generation and see what happens. 

KCD is no longer being worked on so there won't be any AMD GPU related patches or fixes, this issue is what we get. 

PS. Yes this same exact problem is present under Windows10 last time I tried. _I have not tested with the past couple AMD driver updates. Will need to do that sometime._  **Is not related to GPU core/mem clocking bugs, I tested for that also.**

**Savefile below:** _Its at the plateau silver mine quarry, if you move to the north-side and overlook the river and starting town its very LOD heavy. Looking side to side and up or down can change the FPS performance dramatically, but you will notice the performance hit can remain as you move back to the original save position. 
This is evidence of the game struggling to correctly cull loaded in scenery inc lod data. There are many more areas you can test, but this is probably one of the most obvious examples of the issue._

With AMD cards (Navi+ in particular), depending on where you look can dramatically affect performance even when no perceived detail has changed. Its very random and patchy problem which leads one to believe the game is struggling to cull lod/data correctly for some reason. 

[exit.whs.zip](https://github.com/ValveSoftware/Proton/files/5885390/exit.whs.zip)

It MAY be worth opening a ticket over on AMD's bug forum/tracker. But given this is a old game, I very much doubt they will care. _(it can also be a cryengine issue as I've read mentions of NAVI users having issues with all cryengine games)_


AND that concludes my KCD Navi2 experience. I won't be updating this unless it magically gets resolved under Windows with a driver update, which won't help Linux users but would at least signal that it can be fixed driver side... (unlikely tbh)....

**Comment by jarrard** [comment]
Tested under windows10 with latest AMD driver. Couldn't get the problem to materialize. 

Settings the same, this is the exact viewpoint and area that would murder fps under proton for unexplained reasons. I have FPS capped at 61 here due to vsync. Under linux it would get between 25-40fps at this viewpoint. 

Note FPS is 61 (win10) which my monitor is 60hz and I cap it due to tearing. Actual fps could be decently higher but unlikely to be above 75-80fps...
![win10screenshot](https://user-images.githubusercontent.com/17428910/106361710-34020780-636f-11eb-8e17-89379f261670.jpg)

**Comment by matty-r** [comment]
I've experienced the exact same issues. Previously running with an nVidia GTX 1080ti I would get nearly consistent 100 FPS, i've since upgraded to an AMD RX 6900 XT and barely able to reach 50-60 FPS in most locations.

**Comment by jarrard** [comment]
KCD isn't the only game affected, but its one of the easier ones to test thanks to its mostly static environments and world. 

I've noticed the issue in GTA5 for example, in spots where the FPS would tank (testing at 4k which shows the issue the most).  Then directly compared it to windows which has no such issue at all. 

I believe I also had this issue in CP2077 but that game has performance issues built in and such so it was really hard to nail down what was causing it most the time. (the game or driver/gpu/mesa)

**Comment by jarrard** [comment]
For completion-ism here is a screenshot of how it runs on Linux, same settings. I have tried different mesa versions, difference window rules such as with and without compositor etc... Lots of things tried. Sometimes it will be 35fps but is pretty random patchy performance.

Note FPS is 25fps. Game is not enjoyable with this performance issue. 
![KCD Linux Performance Issue 6800xt](https://user-images.githubusercontent.com/17428910/107015692-f5e06a00-67ec-11eb-9729-8dd0d868b012.jpg)

**Comment by matty-r** [comment]
I've learnt this is a problem with AMD GPUs and CryEngine games, and had been for years. This also affects Windows. Unfortunately it's AMD not caring about it and not fixing the issue, and likely never will. It's been around since the Vega 64. 

I've returned my card. Pretty garbage.

**Comment by jarrard** [comment]
Having e/f sync enabled and using newer proton versions such as experimental can yield a extra 9fps or so. Still WAY too slow to be playable, even if its patchy, having the game randomly dip down to 25-35fps every time you turn around or look in a specific direction is beyond frustrating. 

> This also affects Windows. Unfortunately it's AMD not caring about it and not fixing the issue

The latest AMD windows10 drivers appeared to have fixed this issue. I posted a screenshot as evidence, but who knows if their next driver update will break KCD or cryengine games again.. Seems the fix isn't in for Linux mesa amdgpu drivers... if its the same problem (which I'm pretty sure it is, whatever it is...)

There may also be issues with Unity3D games, but I've yet to fully confirm that. 
Only Unity3D games I've tested recently were Battletech and Pillars2. But they also have a slew of other issues to consider when performance testing making the overall process difficult to do basic problem isolation. 

Eventually I might consider getting my second ITX system up and running and slap a decent NVIDIA card in it for testing purposes.

**Comment by matty-r** [comment]
Ah well - I've given up on it. I've never had issues like this with NVIDIA so I'll just wait and get a 3080 at some point.

**Comment by Patola** [comment]
what's e/f sync?

**Comment by jarrard** [comment]
> what's e/f sync?

Its file esync and fsync, for the most part it helps improve performance in most games but can sometimes cause issues. Its enabled by default normally. 
PROTON_NO_ESYNC=1 PROTON_NO_FSYNC=1 %command%, can be used to disable them in steam, for testing. 

You can also use RADV_DEBUG=llvm if you think ACO compiler is a issue, but for me, KCD seems to work fine with ACO and llvm only causes increased stutter. 

I'm wondering if it will be worth doing a apitrace under win10 and then proton in this one example of the game having a performance issue (ref screenshots). I really don't know if that can help at all...

**Comment by Patola** [comment]
Ahh, yes. I know what fsync and esync are. It's just the way you have mentioned it, it looked like something akin to vsync or freesync.
I will make tests with my RX 6800 XT, but as I have commented on this bug report, there was a time when NVIDIA had a performance hit on the game, and it just changed overnight, doubling the framerate. I will stick to AMD though because of the open-source drivers and async reprojection (for VR), but I surely wish the drivers could catch up with nvidia on this regard. Performance in Star Citizen seems to suffer from it too -- though it's not on Steam, so I reckon this might be offtopic.

**Comment by jarrard** [comment]
Star Citizens performance issues might one day go away when they finally move to Vulkan API (its being worked on). If we're lucky. 
_Keep in mind SC is using Lumberyard which is a open-source version of cryengine or something done by Amazon whom seem to be failing in the game-dev department lately..._ 

KCD will get no such update even thought cryengine has a fully working vulkan api for use now. 

**UPDATE: Tested with latest proton-tkg to see if wine6.2 helped anything and the same weird behavior happened. This time I used Rattay upper township near the exit bridge next to the tournament area to test.**

**I was able to walk around for 30seconds at 60+ fps but within a minute it hit some magical wall and performance fell to around 38fps or less and was extremely erratic (up/down like a yoyo).**  _There was no visual detection of LOD change, so wasn't a assets loading in issue. Game is on a NVMe also._ 

**I will continue to test now and again, clearing shader cache each time and maybe testing LLVM and ACO. But its clear there is a bug happening somewhere for AMDGPU and this game. Possibly not all AMD GPU's suffer from this issue but certainly it seems to affect the RDNA cards.**

NOTE: _After clearing shader cache files. The game is for the most part playable and fps performance is normally ok. Its only specific areas where your overlooking landscape from elevated positions that has a major fps drop. But keep in mind this performance drop can, once triggered, follow you around like the plague to areas where you were getting much higher fps._

_The performance tanking doesn't appear to occur under windows dx11 with latest AMD drivers, at least not at this serve level if at all._

**Comment by ipr** [comment]
Works fine on Proton 7.0, Mesa 21.3.5 and kernel 5.16.11

**Comment by solgzr** [comment]
Proton Experimental, RX 6500 XT, Kernel 5.17.4, Mesa 22.0.2, OpenSUSE Tumbleweed, I'm getting graphical artifacts, red shimmering everywhere:

![Screenshot_20220427_165837](https://user-images.githubusercontent.com/59263827/165536611-5593e9e7-1318-45b1-8937-ffbd3a1b1c84.png)

What could cause this, first time I've encountered something like this with Proton?

**Comment by kisak-valve** [comment]
Hello @solargazr, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.) Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by solgzr** [comment]
Hi @kisak-valve as you requested, Steam log attached and [gist system summary.](https://gist.githubusercontent.com/solargazr/eaffd1c446c980a10d100452c1057383/raw/b5f8318fd39d787984d437e511e325a09332f3c3/steam%2520system%2520summary)

I use KDE with Wayland session, but I had to copy the info in x11, as the information does not copy to clipboard in Wayland (just in case it shows up it the system summary).

[steam-379430.log](https://github.com/ValveSoftware/Proton/files/8572866/steam-379430.log)

**Comment by solgzr** [comment]
@kisak-valve 

I managed to solve the problem: It's caused by forcing anisotropic filtering with env var RADV_TEX_ANISO=16, I completely forgot I had it set globally for other games. For some reason this game does not play well with RADV anisotropic filtering.

**Comment by jarrard** [comment]
Yeah sometimes games have issues with anisotropic filtering even thought it should be able to do x16 for free these days. I've come across a couple games that halve or more their performance with that setting.

**Comment by solgzr** [comment]
> Yeah sometimes games have issues with anisotropic filtering even thought it should be able to do x16 for free these days. I've come across a couple games that halve or more their performance with that setting.

I usually disable ingame aniso, and force it from the driver, some games benefit from it visually, for example GTA V and Arma3. But I've never encountered this kind of artifacting, I first thought it was corrupted shader caching.

But I'm also happy to report the KCD perfomance with Proton Experimental is _excellent_, I'm playing it with ultra and HD textures.

**Comment by soleofthesea** [comment]
I'm running into an issue where the game will sometimes have no audio if I alt-tab out of the game. Luckily another alt-tab seems to fix it.

**Comment by MasonProtter** [comment]
After updating my nvidia driver to 550.144.03 today, I'm now getting a black screen after the opening cinematic that never resolves. Can't get into the game. 

Nvidia 3070
kernel v6.12.4-1
proton: I tried all of hotfix, experimental, and 9.0-4

________

Edit: downgrading to 550.135 has solved the issue for me.
