### ISSUE TITLE
Game's audio causes craclking when using recent pipewire. Easily reproducible on Helldivers 2 (553850), but also happens on Returnal (1649240)

### ISSUE THREAD

**Issue by braiam** [ValveSoftware/Proton#7568]
This issue is independent of Proton version, since pipewire since version 0.3.67 [has implemented tighter latency timings](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/3098). There are multiple reports of Wine/Proton apps having issues ([1](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/3309), 2, 3). I've found that on a default installation, Helldivers 2 seems to reliably produce these results without having to do any other steps.

Using a workaround that changes pipewire-pulse timings to the previous default mitigates this issue, but doesn't totally resolves it:

```
pulse.properties = {
    pulse.min.req          = 256/48000
    pulse.min.frag         = 256/48000
    pulse.min.quantum      = 256/48000
}
```

While we can claim that the issue is pipewire, native apps/games don't seem to have issues with these configurations. I'm not sure what component or at what level of the chain it should be coordinated, but when pipewire 0.3.67 starts hitting stable channels among distributions, these issues would become more prevalent and commonplace.

**Comment by UbuntuGaming** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/7568#issue-2177211417

Hello, I was looking around for a helldivers 2 issue i'm having (unrelated to this post) & i came across your post. I don't know if this is a similar issue but currently attempting to use EasyEffects on pipewire with some of the more demanding effects (libebur128) causes strange timing/latency originated audio phenomenons, on some applications it also does it with EasyEffects disabled. Adjusting PULSE_LATENCY_MSEC environment variable solves the issue. Have you tried using PULSE_LATENCY_MSEC=60 %command%? 
if this doesn't work with this issue sorry for the noise.

**Comment by gabriele2000** [comment]
I fixed this problem long ago.
Follow this comment that I made on reddit a while ago: https://www.reddit.com/r/linux_gaming/comments/1gy347h/comment/lylqijj/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by braiam** [comment]
Yeah, I've seen that before, still doesn't fix the crackling in PoE2 with Vulkan.
