### ISSUE TITLE
Nvidia+Wayland+Proton+Vulkan , Some games locked to refresh rate

### ISSUE THREAD

**Issue by zoobporsor** [ValveSoftware/Proton#7896]
# Compatibility Report
- Name of the game with compatibility issues:
Doom 2016
Quake 2 RTX
and probably a few others

- Steam AppID of the game:
379720
1089130
## System Information
- GPU: Nvidia RTX2080ti
- Video driver version:  Nvidia 555.58.02
- Kernel version:  Linux 6.9.9-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/zoobporsor/5a68a0bf7ad1b1e84f743d3310c94726/):
- Proton version: Proton Experimental

## I confirm:
- [ yes] that I haven't found an existing compatibility report for this game.
- [ yes] that I have checked whether there are updates for my system available.

 
[steam-379720.log](https://github.com/user-attachments/files/16203114/steam-379720.log)

## Symptoms 

It seems like SOME (but not all) Proton+Vulkan+Wayland specific, games are restricted to refresh rate, despite forcing off Vsync in both KDE Plasma and even using Mangohud to further enforce No vsync. 
If I switch those games to OpenGL, or DirectX mode, the frame cap goes away
If I switch to X11, the cap also goes away. It is due to the specific combo Proton+Vulkan+Wayland.

Non-steam vulkan apps, such as vkcube has no frame limit

While other games like Doom 2016, and Quake 2 RTX, will always restrict FPS to Refresh rate ONLY using Proton+Vulkan+Wayland.  eg (60, 144, 165) 
I know Doom 2016 has a Hard cap of 200fps, but still it will not exceed any refresh rate before that. eg; if i set refresh rate to 60, Doom 2016 will not exceed 60 with Vulkan+Proton+Wayland and vsync set to off. 

Weirdly, it is not all Vulkan+Proton+Wayland steam games. 
Other Vulkan+Proton+Wayland games such as Doom 64  and Hellpoint, has no frame limit.

So it is some combination of SOME games + Vulkan+Proton+Wayland causing the issue of restricted framerate.

It is an issue because It feels like input lag to have restricted framerate like this, and moreover it seems like it is an enforced Vsync on this specific combination and games, that I would like to disable for better responsiveness. 

## Reproduction
Use Nvidia(?)  Latest
Use KDE Plasma (?) Latest , make sure Allow tearing is checked on Plasma Display configuration 
Use Wayland
Enable steam play
Launch Doom 2016 or Quake 2 RTX (among other vulkan+proton games?) 
Disable vsync, framerate still locked to refresh rate 
If you switch off Vulkan, frame limit goes away. 
If you switch to X11, frame limit also goes away.
It should also go away on Vulkan+Wayland+Proton, though. for some reason it is restricted with this combo and feels like forced Vsync still.

**Comment by CosmicSavant** [comment]
I have the same issue with Total War Warhammer 3 through Proton. It seems FPS locked to 58 on Wayland, both gnome and plasma. Whereas on X11 it isn't, both gnome and plasma.

In my case this was fixed by making a dxvk.conf in the executable directory with the dxgi.syncInterval = 0
line. Which is strange as the display is a 240hz, it's also set to this frequency through the display driver and respective desktop configuration gui's.

This particular game, also failed to start after having set display resolution in game, meaning I had to delete and reset settings after each startup. With the above line, this was no longer necessary. Without it, the game would crash when setting resolution.

**Comment by zoobporsor** [comment]
oh thats interesting
however when I tried putting dxvk.conf inside for example Quake 2 RTX folder where the executable is,  the framecap still exists. I cannot find any way to remove it on some games still, except for not using Wayland or Vulkan, or KDE.

**Comment by Bulletdust** [comment]
I experience the exact same issue running Quake II RTX under Wayland, the FPS is limited to 60fps even though vsync is disabled and 'Screen tearing in full screen windows' is set to enabled under KDE Display Configuration.

If anyone's got a solution, I'm happy to try it.

**Comment by LethalManBoob** [comment]
still and issue...

**Comment by M1gael** [comment]
I would like to add that i am having the issue but the inverse . Specifically on one of the games OP mentioned . Doom 2016 can go right up to 200fps , but not any of the framecap commands work .
Steam flatpak
Proton GE Latest
Tried all framecap commands i could find that work on other titles.

**Comment by Rebootcomputa** [comment]
Yep, same with Doom The Dark Ages, I wrote a post before seeing this one, regardless of settings on Plasma display or Game settings only way for FPS to go above 144FPS on my monitor is to select Windowed Mode. 

Was able to reproduce this on Doom Eternal, Indiana Jones The Great Circle and new Doom. Shame since id games always ran well on my system specially on Vulkan.

Running a Nvidia 4080 super with 575 Driver, on Kubuntu 25.04 Wayland.

**Comment by Bulletdust** [comment]
> I would like to add that i am having the issue but the inverse . Specifically on one of the games OP mentioned . Doom 2016 can go right up to 200fps , but not any of the framecap commands work . Steam flatpak Proton GE Latest Tried all framecap commands i could find that work on other titles.

This has been a problem under Wayland regarding certain titles for as long as I can remember. Fallout 4 locks FPS to my monitor's refresh rate, as does Quake 2 RTX.

As a result I'm still rocking X11 and everything just works as intended.

**Comment by kodatarule** [comment]
Possibly related to: https://forums.developer.nvidia.com/t/nvidia-bug-kde-wayland-games-are-force-vsynced/237880/47

**Comment by Eispala** [comment]
Happens to me aswell in Doom Eternal.

Workarounds:
- Play in Windowed Mode
- Play in any resolution that is not the desktop resolution 

I think that when "present from compute" is disabled, it caps to screen refreshrate, if "present from compute" is enabled it will cap to 2x of the screen refreshrate.

Somehow, if the FPS exceed the FPS cap by a large margin, it seems to not cap it, e.g. if i get above 300ish FPS in Doom Eternal, it will not cap to 240.
But if i get 290 Fps it will cap to 240 instead

In some other games it is not an issue, like Path of Exile 1 just works and Shapez 2 also works.

Rtx 4080, driver version 570.153.02, Kernel 6.14, Wayland

**Comment by kodatarule** [comment]
My observation so far is that it only happens if the game is native Vulkan, in addition this seems to only affect nvidia drivers so perhaps it is best to report findings on their forums.

EDIT: For reference this also affects cs2 in both xwayland and wayland, that is a native linux game running on native vulkan(not dxvk).

**Comment by Rebootcomputa** [comment]
so way around this was to run Steam with gamescope integration, since running games with gamescope would just fail to load, I just run the entire of steam with gamescope with the following settings in terminal: gamescope -W 3840 -H 2160 -f -r 480 --hdr-enabled env ENABLE_GAMESCOPE_WSI=1 DXVK_HDR=1 steam basically 4K resolution + HDR + 240 FPS cap tested it in multiple games so far DOOMs work not the most elegant solution I know.

**Comment by ninetailedtori** [comment]
Observing this in Warframe too, and both KCD games.

**Comment by Isaac-Clarke** [comment]
> My observation so far is that it only happens if the game is native Vulkan, in addition this seems to only affect nvidia drivers so perhaps it is best to report findings on their forums.
> 
> EDIT: For reference this also affects cs2 in both xwayland and wayland, that is a native linux game running on native vulkan(not dxvk).

This sad observation may also be the sad truth.
[I don't even play these games that often anymore, but since checking out if my computer still works properly is something I am compelled to do,] I have also noticed something similar to this myself.

Now that somebody else said it out loud it makes somewhat more sense, even if it's not completely proven.

Here are the results of my **DOOM 1 + 2** tests showing what you basically said.
https://steamcommunity.com/sharedfiles/filedetails/?id=3529093337

Also, connecting to this issue https://github.com/doitsujin/dxvk/issues/4895 **SOME** Source-Engine-1 games present this problem, like Portal 2.
[I can't properly recall **ALL the games** with this problem](https://www.reddit.com/r/linux_gaming/comments/1kldsmp/proven_source_engine_gives_less_frames_with_the/), evenmore because both Fedora KDE and my RTX 2070's drivers and maybe even Steam got some update, **BUT**:
If I turn Vsync-Triple-Buffering ON and OFF when **Portal 2** is TRULLY FullScreen, at some point (when it's ON) the cap disappears and I can play "uncapped" (still Vsynced) at FullScreen.

### I do not believe that this is a problem on Valve's side, it may be a problem with the Wayland and/or KDE side.

**Comment by twigcipher42** [comment]
I am pretty sure it happened in Gnome Wayland also.  So not KDE specific.

**Comment by ninetailedtori** [comment]
It might be a Wayland issue, but I reckon it's something to do with the general composition pipeline as related to the prior KDE fix, likely something they've done there that other WMs don't do. Running with proton-GE on gamescope, everything is flawless completely, so it's being made to work fine there, but I suppose it would haha~

**Comment by Tarzan-1740** [comment]
Same symptom here, and I can add a clean driver A/B that isolates it to the NVIDIA 610 branch.

RTX 4080 SUPER, CachyOS kernel 7.1.2, Hyprland 0.55.4 (Wayland), 165 Hz displays. On driver 610.43.02 (open modules) every DXVK/vkd3d-proton title presents at exactly 165 fps with VSync off — tested Stellar Blade (vkd3d-proton) and Hollow Knight (DXVK) — while native Vulkan (CS2) and GL (glxgears, also via zink) run uncapped. Reproduced with Proton Hotfix, proton-cachyos-11.0, GE-Proton11-1 and GE-Proton10-34, both through XWayland and with `PROTON_ENABLE_WAYLAND=1` (winewayland verified loaded), so it is not the Proton build nor the window-system path. `VKD3D_DISABLE_EXTENSIONS=VK_KHR_present_wait` and `VK_NV_low_latency2` don't help.

Driver A/B on the same kernel/compositor/Proton: 580.173.02 (proprietary) = uncapped (224 fps, 95% GPU) → 610.43.02 = pinned to 165 → rollback to 580.173.02 = uncapped again immediately.

Reported to NVIDIA in the 610 feedback thread: https://forums.developer.nvidia.com/t/610-release-feedback-discussion/371356/151
