### ISSUE TITLE
Call of Duty: Black Ops (42700)

### ISSUE THREAD

**Issue by SteveHeist** [ValveSoftware/Proton#790]
I cannot for the life of me get Call of Duty: Black Ops to launch. I have tried most every workaround I can find online, using winetricks to install d3dx9, vcrun2005, vcrun2008, disable GLSL, create two DLL overrides for both dsound & d3dx9_43 (in an effort to use the wine-builtin one I installed as opposed to the Black Ops native versions). I even went so far as to try the compatdata from Call of Duty: World At War (10090), because it works fine. Nothing, just briefly "Running", and a silent death, maybe sometimes syncing.

Has there been any meaningful progress by anybody else getting the game to launch, or any further ideas? I have all my logs on Google Docs (for "Find..." searchability), and an example on Pastebin as well, if you think that'll help.

**Comment by kisak-valve** [comment]
Hello @SteveHeist, please copy your system information from steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. Additionally, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and drag and drop the generated $HOME/steam-$APPID.log into the comment box.

**Comment by SteveHeist** [comment]
https://gist.github.com/SteveHeist/1f51e113d17ac6bb8224c70a926d6508 (System Info .gist.)
[steam-42700.log](https://github.com/ValveSoftware/Proton/files/2325988/steam-42700.log)

**Comment by kisak-valve** [comment]
You may have better luck with padoka's bleeding edge ppa instead of padoka's stable ppa.

**Comment by SteveHeist** [comment]
Can you pass me the "sudo add-apt-repository" for that? I can't find it.

**Comment by kisak-valve** [comment]
Info at https://launchpad.net/~paulo-miguel-dias/+archive/ubuntu/mesa.

**Comment by SteveHeist** [comment]
Thank you! If replacing the GPU drivers doesn't work, I'll put a new .log here, correct? Would I need to update the gist as well?

**Comment by SteveHeist** [comment]
Still nothing. New log: 
[steam-42700.log](https://github.com/ValveSoftware/Proton/files/2326056/steam-42700.log)

**Comment by SteveHeist** [comment]
For some cross-comparison, I tried redoing the winetricks install for d3dx9, vcrun2005 & vcrun2008, as well as setting up the DLL override for dsound and setting the "Windows Version" to XP. Still nothing, but that *should* provide a reasonably different log to see if we're getting anywhere.
[steam-42700.log](https://github.com/ValveSoftware/Proton/files/2326089/steam-42700.log)

**Comment by SteveHeist** [comment]
I've spent the last few days nose-to-the-grindstone with another person's help, and we still couldn't get it to boot. Here's the most recent log:
[steam-42700.log](https://github.com/ValveSoftware/Proton/files/2331256/steam-42700.log)

**Comment by tunanachos** [comment]
Doesn't work on Manjaro linux either (unsurprisingly) - oddly enough I've seen this be installed on Ubuntu years ago and it looked playable.

Odd that with all this new stuff coming out these games remain an issue (I imagine every modern CoD from that last 10 years will have the same issues).

**Comment by 999gary** [comment]
Advanced Warfare works, mw3 works, and black ops 1 works fine on wine 3.0 and up, just not proton

**Comment by SteveHeist** [comment]
@999gary Out of curiousity - when you say it "works fine", do you mean you got the in-game audio working, or no? If so, and I know it divulges from the point of this Issue thread, but how? I can't get the audio working.

**Comment by 999gary** [comment]
@SteveHeist I've played bo1 for years without changing anything and everything has always worked, even with different distros, so I cant really help you there. Sorry :/

**Comment by SteveHeist** [comment]
Just gonna update this - I got it working in Lutris.

Wine 3.16-staging, although it did run with esync as well.
Winecfg set to Windows XP.
DXVK 0.80 is enabled, but I don't think that does anything for D3D9.
Audio is set to ALSA because PulseAudio doesn't agree with it.

**Comment by IanTrudel** [comment]
This is working great on Lutris with tkg-wine-4.1 (Winesteam).

The noticeable difference in the installation is that DirectX installer fails on Steam because it cannot register xact. Unfortunately, it seems winetricks/protontricks also fails to install xact. Anyone has the same problem?

[C:\Windows\Logs\DXError.log](https://github.com/ValveSoftware/Proton/files/2896236/DXError.log)

There also seems to be a problem with libFAudio.so:

`002d:err:module:load_builtin_dll failed to load .so lib for builtin L"xactengine3_0.dll": libFAudio.so: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type`

**Comment by dpusceddu** [comment]
With newer Wine runners (4.12), the game seems to crash when starting a match. Audio works.
Older ones (for example 4.1) start the match fine, but with no audio and terrible performance (lots of stuttering)

EDIT: I managed to make audio work in older wine versions and the match not crash in newer versions. I did it with winetricks xact, faudio, directmusic. I have no idea which one actually did it.
However, the game still stutters too much, the multiplayer is unplayable.

**Comment by mathew2214** [comment]
it seems this game wont launch due to CEG. a cracked exe file would be required for proton to run this game. (#753)

**Comment by Sporif** [comment]
For me the multiplayer version installs and launches out of the box with 4.11-12, but the single player installs and then crashes right after a window opens. This also happens with Winesteam, but the single player used to work a while ago so I have no idea what's wrong there. 

But for some reason both fail to launch with 5.0-1.

This is regardless of whether I'm using d9vk or wined3d. Also the multiplayer stutters much more than running it through Winesteam.

**Comment by Sporif** [comment]
OK for some reason now the single player also works with 4.11-12. But 5.0-2 still doesn't work with either.

**Comment by echaskaris** [comment]
@Sporif How did you get it work, out of the box? I can't get it to work.

**Comment by Sporif** [comment]
@echaskaris No idea, it just works out of the box for me.

**Comment by echaskaris** [comment]
@Sporif Distro?

**Comment by Sporif** [comment]
@echaskaris Arch + i3

**Comment by tunanachos** [comment]
> @echaskaris Arch + i3

Can you provide evidence? Nobody on proton can get it to work https://www.protondb.com/app/42700 

And I'm using Manjaro+i3wm and it refuses to launch? Could you give us a screenshot or any more info? Would be very helpful & thanks for your time.

**Comment by Sporif** [comment]
@tunanachos Unfortunately it doesn't work anymore. It's really weird, I've tried different dxvk and proton versions and all launch but only show a blank window with a dxvk submission error/device lost.

**Comment by tunanachos** [comment]
Bummer - well thanks for updating anyway.

**Comment by anirrudh** [comment]
Is there any interest in fixing this? A couple friends have been on me and I refuse to run windows nor have the time to setup VFIO. I hope this is fixable.

Edit: for anyone reading this, look at @mathew2214's comment above. I guess all we can do is wait at this point. It does work when installed via wine, but proton would obviously mean much, much better performance.

**Comment by loopdel0op** [comment]
i was playing bo1 on lutris with a config profile that someone made. a few days ago i tried to run it with proton and it worked out of the box with much better performance than lutris. Like mouse was smooth af. now it doesnt work for some reason.

**Comment by loopdel0op** [comment]
I  got it now. if i run the game on lutris with this profile https://lutris.net/games/call-of-duty-black-ops/ and then if i run it with proton it WORKS!!!

edit: i am back from playing it, everything on steam is on default options regarding bo1. When i launch the lutris version it will crash after the intro and will go to desktop. Be warned your desktop resolution will be changed to 800x600 if you wont change it from the config file.

config file is on STEAMLIBRARY/steamapps/common/bo1foldername/players/config
commands are very similar to source engines ones

So it is simple just run bo1 with the lutris profile. it might crash or work but performance will not be that good on lutris. After running it from lutris close wine steam and lutris and run it from steam. just press the play button. if i reboot it wont work so you need to repeat this everytime you play :/

**Comment by Road-Drum** [comment]
> I got it now. if i run the game on lutris with this profile https://lutris.net/games/call-of-duty-black-ops/ and then if i run it with proton it WORKS!!!

I can't see the profile. can you copy and paste the changes that needs to be applied to steam with the profile?

**Comment by mathew2214** [comment]
i can confirm it runs on Proton, without lutris, once CEG is out of the way. Proton runs BO1 flawlessly, its simply a matter of Valve supporting one of their own services. 
Valve, please make CEG on Linux.

**Comment by tunanachos** [comment]
> i can confirm it runs on Proton, without lutris, once CEG is out of the way. Proton runs BO1 flawlessly, its simply a matter of Valve supporting one of their own services. 
> Valve, please make CEG on Linux. 

Hey there, sorry to be very dumb here but are you saying you've got black ops 1 working on Proton? If so, could you explain what you did and how you did it? If not forgive my mistake.

**Comment by mathew2214** [comment]
> > i can confirm it runs on Proton, without lutris, once CEG is out of the way. Proton runs BO1 flawlessly, its simply a matter of Valve supporting one of their own services.
> > Valve, please make CEG on Linux.
> 
> Hey there, sorry to be very dumb here but are you saying you've got black ops 1 working on Proton? If so, could you explain what you did and how you did it? If not forgive my mistake.

i used a custom launcher to bypass CEG. I'm not comfortable sharing details as doing so could be interpreted as encouraging/enabling piracy. i could not play multiplayer, only singleplayer. this confirms that BO1 would run perfectly under Proton should Valve ever decide to support their own DRM (CEG) on their own platform (Steam), with their own compatibility tool (Proton).

**Comment by kisak-valve** [comment]
Call Of Duty: Black Ops will not start: Acer Nitro 5; Ubuntu 20.04 LTS; GTX 1050

Issue transferred from https://github.com/ValveSoftware/Proton/issues/4633.
@tptignor posted on 2021-02-18T00:26:23:

# Compatibility Report
- Name of the game with compatibility issues: Call Of Duty: Black Ops
- Steam AppID of the game: 42700

## System Information
- GPU:  GeForce GTX 1050
- Driver/LLVM version:  nvidia-driver-460
- Kernel version:  5.8.0-41-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/tptignor/b87d4a1685a55e6e4c962e9a82276881
- Proton version:experimental-5.13-20210217

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.


[steam-42700.log](https://github.com/ValveSoftware/Proton/files/5999382/steam-42700.log)


## Symptoms 

The game fails to start. There is a cryptic exception in the log.

## Reproduction

Double click on Play in the Steam window.

**Comment by caseif** [comment]
I can confirm that the game now launches and runs without any issues on my system using the latest Steam client beta and Proton Experimental.

**Comment by serebit** [comment]
Same here. Can't launch the Ascension zombies map though.

**Comment by tunanachos** [comment]
Hm, not for me. I'm using Manjaro with i3wm. 

I've just logged into Steam & updated the latest version of Proton (experimental) but when I attempt to launch Black Ops _(or Black Ops: Multiplayer)_ it says _"launching"_ and then _"Running"_ for a few seconds before failing to do anything else. 

I have launched Steam in a terminal and will upload the output text _(from the moment I attempt to launch the game to the moment it closes itself)_ to this post.

Any help would be **greatly** appreciated because I have missed playing this game sorely since switching to Linux _(almost 7 years ago!)_.

Thanks in advance!

[BlopsOutput.docx](https://github.com/ValveSoftware/Proton/files/7439865/BlopsOutput.docx)
.


EDIT: 

Forgive me, I hadn't updated to the Steam Beta - I now have Black Ops 1 playing on Linux... So far I'm only on the title screen but... I'm so happy :) thank-you

**Comment by Road-Drum** [comment]
can confirm the game launches on Proton with both Proton Experimental and Steam Beta. Though as a precaution I rebuild `~STEAMAPP_DIR/compatdata/42700` from older Proton Experimental. Difference in behavior on stable client and beta client is on beta client, an additional window pops up saying completing installation and I noticed a command prompt was initiated with Proton's wine during that process

DLC (Rezurrection) is detected and works fine though I only tried Nacht der Untoten solo as co-op lobby is empty at the time of writing

Will try other CEG game that I own (Prototype 2)

**Comment by echaskaris** [comment]
Game now launches, but performance is subpar with stutters, could be my FX CPU though...

**Comment by serebit** [comment]
@Fenteale
> > Call of Duty: Black Ops works totally fine now, minus one oddity that's also present if you attempt to run a cracked CEG-less EXE—the Ascension zombies map refuses to load. The game crashes if you try to start up that map.
> 
> IIRC This has been an issue forever even with just a completely normal windows install. The Ascension dlc for some reason crashes if you don't have the Multiplayer component installed, try it again after installing the multiplayer.
> 
> Just tested the singleplayer campaign in Black Ops for myself. Everything worked great! I was even able to unlock achievements.

I do have the Multiplayer component installed. If you're correct, then it's probably due to the fact that Multiplayer and Zombies get installed in different prefixes.

**Comment by Fenteale** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/790#issuecomment-954839622

Ahhh, that might be it. Might have to test by doing some symlinks. I'll try it myself in a bit.

**Comment by Fenteale** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/790#issuecomment-955146669

Just tested now. I tried for fun running Ascension with just the singleplayer installed. Instant crash when it starts. I installed the multiplayer, booted it up to the main menu, quit then started up the singleplayer again.
I tried to load into Ascension and it just worked for me, I didn't have to tweak anything else. Maybe you have to run the multiplayer once?

I only have the Ascension DLC so I can't check any of the other ones.

**Comment by SergeyLatyshev** [comment]
It seems like the game crashes on start when I turn MangoHud on and works when I disable it.
[steam-42700-crash.zip](https://github.com/ValveSoftware/Proton/files/7449220/steam-42700-crash.zip)
[steam-42700-nocrash.zip](https://github.com/ValveSoftware/Proton/files/7449221/steam-42700-nocrash.zip)

**Comment by kisak-valve** [comment]
Hello @SergeyLatyshev, in your log, `s.exe: ../MangoHud-0.6.6-1/subprojects/imgui/imgui.cpp:6420: void ImGui::SetCurrentFont(ImFont*): Проверочное утверждение «font && font->IsLoaded()» не выполнено` looks like something to report to the MangoHud issue tracker for @flightlessmango to ponder.

**Comment by mathew2214** [comment]
on steam client beta, and proton-experimental. i cannot get this game to launch. 
system info and proton logs: https://gist.github.com/mathew2214/4925fe8bc52647fc3b6219a072a4252b

**Comment by tunanachos** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/790#issuecomment-955168911

Oddly enough all the maps work for me (zombies). Call Of The Dead is INCREDIBLY choppy/low FPS (I'm assuming it's the weather in the map because when there is a snowstorm the FPS drops).

Oddly enough when connecting to MP servers I often get "lost connection to host". Also, when I validate the game files almost always 2 files are missing.... 

While it nice to be able to play Black Ops 1 after all these years there are certainly a few issues still prevalent with this game. Not to diminish the results.

**Comment by NikoBellicRU** [comment]
Zombies at least the 1st map worked great as well as the campaign but it seemed to be missing some background sound not sure tho.

The biggest issues i found was the steam overlay takes 3-5sec to open when pressed and on the menu in both mp and sp on the friends tab the fps drops from 91 to ~ 55 fps.
[steam-42700.log](https://github.com/ValveSoftware/Proton/files/7490480/steam-42700.log)

EDIT: Also noticed that the mouse movement is very choppy in comparison to the gamepad.

**Comment by tunanachos** [comment]
I would also like to add that the mouse movement (at least for me on my computer) is very "choppy". This is related to Black Ops 1 because playing Black Ops II the mouse is fine (nice and smooth).

I have fiddled with the settings as best I can but cannot fix this issue, it makes playing on MP and Zombies quick tricky. Can anyone else confirm this issue?

**Comment by tunanachos** [comment]
There was an update today _(to Proton experimental)_ and there has been a regression in the sound _(menu noises, battle noises.. things like bullets, footsteps and explosions are missing but killstreak noises remain working)_.

Reverting back to 6.3-7 'fixes' these regressions.

**Comment by Seltyk** [comment]
I can also confirm that Black Ops works with Proton 6.3-7 on Steam beta. Campaign and zombies both work, mouse is *slightly* choppy, multiplayer loads but cannot connect to servers. Proton Experimental cannot play most sound effects, as tunanachos reported.

**Comment by tunanachos** [comment]
@wundrweapon Good news! You *can* play on multiplayer servers. 

However, I've found you need to _"verify integrity of game files..."_ almost every time you have played/want to play CoD:BO _(at least, I've found this helps)_.

 Often I'll get _"2 files failed to verify"_... No idea what those files are but give it a go and see if it works.

More often than not when attempting to connect to a server on MP I get _"lost connection to host"_ _(assuming that's what has stopped you connecting to servers?)_ but upon doing some Googling it seems this could be an issue with the game itself and **not** Steam/Linux/Proton. Could be wrong!

Additionally Co-op Zombies / DLC works well, although I get terrible mouse issues aiming _(almost as if the sensitivity is being changed)_ which aren't prevalent when using a game-pad *(Logitech F310 Wired Gamepad)*.

Some maps cause HUGE losses to FPS when looking in certain areas, even with lowest settings. Although I am questioning if this could be again poor optimization of them game itself and not an issue with Steam/Linux/Proton.

Hope this helps.

**Comment by NikoBellicRU** [comment]
![Screenshot_20220227_033222](https://user-images.githubusercontent.com/50124155/155889133-e16ed5ae-d023-4301-b1b8-5928885032f1.png)

Used to have 90 fps lock even on wine steam but now its performing not that great and need to turn off shadows to be more close to what i used to play.

Tried on manjaro with and without flatpak / fedora kinoite and Proton 7.1 / 7.1 GE / Experimental bleeding-edge

Also for some reason this game crashes if i have mangohud command "mangohud MANGOHUD_CONFIG=full %command%"

[steam-42700.log](https://github.com/ValveSoftware/Proton/files/8148917/steam-42700.log)

**Comment by mathew2214** [comment]
game runs at decent framrate. but the input is inaccurate and unresponsive, to the point the game is unplayable.

**Comment by mathew2214** [comment]
game no longer runs at all with Proton experimental

**Comment by CSahajdacny** [comment]
Have you tried to rename the 42700 compatdata folder to  42700_backup,  so Steam can create a new 42700 compatdata folder?
I do that every time I try a new Proton version.

**Comment by kisak-valve** [comment]
Call of Duty Black Ops Stuttering

Issue transferred from https://github.com/ValveSoftware/Proton/issues/6010.
@ColdTrilogy posted on 2022-07-19T03:46:52:

Whenever I play Call of Duty Black Ops often the game stutters and frames drop also btw I am on Linux Mint and I tried all version of proton and the game either didn't launch or it stutters during game play.

**Comment by kodatarule** [comment]
Can you please try to disable esync and fsync and update us if the stuttering is observed, I seem to have the same with this title.
@ColdTrilogy

**Comment by AQDuck97** [comment]
I'm unable to launch neither MP or SP with similar looking logs on any Proton version from Proton 6 to Experimental (BE).
I get a bit further with SP (safe mode message), MP just crashes immediately.
Also tried some Proton-8 GEs
42700 is SP 
42710 is MP

[steam-42700.log](https://github.com/ValveSoftware/Proton/files/13329341/steam-42700.log)
[steam-42710.log](https://github.com/ValveSoftware/Proton/files/13329342/steam-42710.log)

**Comment by AQDuck97** [comment]
I can add that they also fail to launch on Steam Deck, all Proton versions from 7 tested

[steam-42710.log](https://github.com/ValveSoftware/Proton/files/13465454/steam-42710.log)

**Comment by nokia8801** [comment]
Neither 42700 or 42710 is launching anymore. Lots of people have the same issue in Steam discussions. Tried many Proton versions, reinstalled, quit, restarted, nothing works. Game just won't launch. When I click play, it says "Updating executable" and then it fails, displays "Play" again.

**Comment by airbud2** [comment]
doesn't launch. tried every version of proton including latest GE

**Comment by nokia8801** [comment]
Is there gonna be anyone looking at this? Game simply won't launch, immediately shows "Play" again after launching. Now window, no nothing. Tried almost every Proton version and fork, with and without Steam Runtime. Nothing will work.

It's a 15 year old game, servers will die soon anyways, please let us enjoy the multiplayer again before that happens.

There is nothing in the logs to indicate why this is happening. Neither 42700 (sp) or 42710 (mp) is launching.

**Comment by PotatoAndSickle** [comment]
As of proton 10.0-3 mouse stuttering is still present. behaviour is as follows 

Any fps above 60 will cause a constant stuffer / inconsistent mouse movements
Locking the fps to 60 using the in-game menu fixes the issue only if the games fps holds at 60 if it dips down to 59-58 then stuttering reappears 

See more info [here](https://www.reddit.com/r/linux_gaming/comments/1dp1xe6/options_for_improving_black_ops_1_2_mouse_issues/)

**Comment by nokia8801** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/790#issuecomment-3546453635

You have to use a relatively newer kernel where the schedulers issues are resolved and also use a Proton fork that uses NTsync. Linux 6.14+ and GE-Proton with NTsync fixes these mouse issues. Otherwise BO1 is unplayable.

**Comment by PotatoAndSickle** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/790#issuecomment-3546543500

ive used GE with NTsync and a 6.17 kernel  which significantly improves this issue. however it is still present. 

Both wayland and xwayland yield the same results. 

Edit: Fedora 43 KDE is the distro

**Comment by PotatoAndSickle** [comment]
### Lighting issues with certain parts of the campaign example bellow.

![Image](https://github.com/user-attachments/assets/8b46d732-e06f-4b01-81f6-30889b13a4c4)

Steamlog: [steam-42700.log](https://github.com/user-attachments/files/23737232/steam-42700.log)

**Comment by nokia8801** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/790#issuecomment-3573697762

Yes, that's a known issue on modern hardware, even on Windows. Been the same case for years. Tunnel characters are dark.

https://www.pcgamingwiki.com/wiki/Call_of_Duty:_Black_Ops#Dark_characters_on_.22Victor_Charlie.22_.26_.22Vorkuta.22_level

Try using `PROTON_USE_WINED3D=1 %command%` and see if it still happens. If it does, it's a game issue as it always has been.

If it doesn't happen with WineD3D but happens with DXVK, then it's best reported to DXVK.

**Comment by PotatoAndSickle** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/790#issuecomment-3574206364

I don’t remember seeing this bug on windows last time i played it, but you are right its a game specific issue. 

I fixed it however by opening **config.cfg** and finding the line `seta r_allow_intz "1"` and setting it to `"0"`.
and line `seta r_allow_null_rt "1"` and setting it to `"0"`. As per that pcgamer wiki link you sent.

**Results:** 

![Image](https://github.com/user-attachments/assets/6cd0959b-a0a4-41ac-8606-9aa1c4e240fb)

**Comment by TheTedder** [comment]
I'm having an issue I haven't seen anyone mention in this thread. When I try to change my keybinds via the settings menu, it registers every key as numlock. Any idea how to fix this? This happens in Proton Experimental and also Proton GE and Proton EM. My Steam info: https://gist.github.com/TheTedder/1ec01ffab652e6979c1b5142a940fe65

**Comment by nokia8801** [comment]
> I'm having an issue I haven't seen anyone mention in this thread. When I try to change my keybinds via the settings menu, it registers every key as numlock. Any idea how to fix this? This happens in Proton Experimental and also Proton GE and Proton EM. My Steam info: https://gist.github.com/TheTedder/1ec01ffab652e6979c1b5142a940fe65

That used to happen to me too. It got magically fixed by itself.

I recommend running the game natively on Wayland with EM Proton using `PROTON_ENABLE_WAYLAND=1 %command%`

**Comment by TheTedder** [comment]
> I recommend running the game natively on Wayland with EM Proton using PROTON_ENABLE_WAYLAND=1 %command%

That's what I'm doing actually. The issue happens whether I use `PROTON_ENABLE_WAYLAND=1` or not. It's not stopping me from playing the game because I can edit the config manually but it is an annoyance.
