### ISSUE TITLE
The Last of Us™ Part II Remastered (2531310)

### ISSUE THREAD

**Issue by jeisom** [ValveSoftware/Proton#8585]
# Compatibility Report
- Name of the game with compatibility issues: The Last Of US Part 2 Remastered
- Steam AppID of the game: 2531310

## System Information
- GPU: RTX 4080
- - Video driver version: nvidia 570.23.07
- Kernel version: 6.13.9
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: Experimental/9.0-4/Hotfix

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
Launcher Runs and once Play is press it crashes.

Tried with DLSS enabled/FSR enabled  Windowed and fullscreen.

## Reproduction
Press Play in Launcher

[steam-2531310.log](https://github.com/user-attachments/files/19592056/steam-2531310.log)

**Comment by urbenlegend** [comment]
@jeisom As with most recent Sony ports that use the PSN overlay, the game fails to launch without the `SteamDeck=1 %command%` launch parameter. Sony uses that variable to disable the PSN overlay which doesn't work on Linux. Setting that parameter gets the game to launch successfully for me.

However, I am seeing major graphical glitches whenever Shadow Quality -> Ambient Shadows is set to anything besides `Off`. Ambient shadows show up as large, blotchy circular shadows around objects. Some shader error perhaps?

![Image](https://github.com/user-attachments/assets/27dc24c4-5529-42f4-bb11-907511e73a93)

If Joel's body is overlapping those shadows, the outline of his body becomes blocky too.
![Image](https://github.com/user-attachments/assets/5a64b705-a449-4dd1-89bf-5b71d841907b)

Here's my system info: https://gist.github.com/urbenlegend/82b715a164b949ce351b4c4a7bb76be5
I am using Proton Experimental.

**Comment by ghost** [comment]
I am experiencing the same issue as @jeisom on Fedora, with an RTX 3080 TI. 
I used the SteamDeck=1 %command% option, but the game crashes in the same way.
Takes a couple seconds longer to crash. Dunno if thats meaningful at all.

**Comment by kisak-valve** [comment]
The Last of Us™ Part II Remastered

Issue transferred from https://github.com/ValveSoftware/Proton/issues/8586.
@witchlliee posted on 2025-04-03T18:34:50:

# Compatibility Report
- Name of the game with compatibility issues: The Last of Us™ Part II Remastered
- Steam AppID of the game: 2531310

## System Information
- GPU: RX 6650 XT
- Video driver version: Mesa  25.0.3-2
- Kernel version: Linux 6.14.0-4-cachyos
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: Proton Experimental (Bleeding Edge)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

 

[steam-2531310.tar.gz](https://github.com/user-attachments/files/19592649/steam-2531310.tar.gz)

## Symptoms 
Audio crackling/stuttering. Changing an Audio Option to traditional helps a bit but the problem still persist.

## Reproduction

**Comment by jeisom** [comment]
> [@jeisom](https://github.com/jeisom) As with most recent Sony ports that use the PSN overlay, the game fails to launch without the `SteamDeck=1 %command%` launch parameter. Sony uses that variable to disable the PSN overlay which doesn't work on Linux. Setting that parameter gets the game to launch successfully for me.

Thanks. That go it running.

**Comment by urbenlegend** [comment]
@jeisom, do you see the same issues that I am seeing with Ambient Shadows?

**Comment by tomicul** [comment]
@urbenlegend I have the same issues

**Comment by jeisom** [comment]
> [@jeisom](https://github.com/jeisom), do you see the same issues that I am seeing with Ambient Shadows?

No, I am not.  I used the High preset + Aniscopic 16x.  Maybe try the nvidia vulkan beta(570.23.07)?

**Comment by tomicul** [comment]
@jeisom how can you try nvidia vulkan beta(570.23.07)?

**Comment by jeisom** [comment]
> [@jeisom](https://github.com/jeisom) how can you try nvidia vulkan beta(570.23.07)?

The driver is here [Nvidia vulkan driver ](https://developer.nvidia.com/vulkan-driver)  Proper installation can depend on your distro though.

**Comment by johnhutchinson99** [comment]
> I am experiencing the same issue as [@jeisom](https://github.com/jeisom) on Fedora, with an RTX 3080 TI. I used the SteamDeck=1 %command% option, but the game crashes in the same way. Takes a couple seconds longer to crash. Dunno if thats meaningful at all.

Ended up installing Ubuntu instead of Fedora and SteamDeck=1 in the options. Working fine now. Not sure why.
Had the same shadow issue, but I ended up just turning Shadow Details down to Low.
Hopefully a fix comes out for that.

**Comment by momanx** [comment]
Seemingly ignores the SteamDeck=1 variable in my case. Despite launching with it (quadruple checked), refuses to run citing lack of the Playstation SDK.

**Comment by burchetted** [comment]
Same issue on fedora for me

### **Compatibility Report**
Name of the game with compatibility issues: The Last Of US Part 2 Remastered
Steam AppID of the game: 2531310
### **System** Information
GPU: AMD RADEON 7800XT
Video driver version: amdgpu
Kernel version: 6.13.9-200.fc41.x86_64 
Proton version: Experimental/9.0-4/Hotfix

**Comment by pedrovp161** [comment]
The "solution" for the shadows issue: https://www.reddit.com/r/linux_gaming/comments/1jqzjba/the_last_of_us_2_on_arch_linux_nvidia_gpu/

Same issue on arch for me

Compatibility Report
Name of the game with compatibility issues: The Last Of US Part 2 Remastered
Steam AppID of the game: 2531310

System Information
GPU: NVIDIA GeForce RTX 3060 Ti Lite Hash Rate [Discrete]
Video driver version: 570.133.07
Kernel version: 6.13.8-arch1-1
Proton version: 9.0-4

**Comment by momanx** [comment]
As a complete aside, anyone have any luck getting DualSense haptic feedback working? It does seem like a similar situation to Death Stranding DC (see [#5900](https://github.com/ValveSoftware/Proton/issues/5900#issuecomment-1159353927) and related discussion). Adaptive triggers are functional both wire and wireless, but since the game expects haptic vibrations, both wired and wireless modes produce no vibration whatsoever, "traditional" or HD rumble.

**Comment by o-schneider** [comment]
I stumbled here from a reddit post that talked about broken Ambient Shadows on nvidia in this game. I actually have the same issue in Part I with a 2080 Ti. I could work around it by using the closed driver and disabling GSP. I made a report  on nvidia's forum as I think it's an issue in the driver. The thread is here: https://forums.developer.nvidia.com/t/broken-ambient-shadows-in-the-last-of-us-part-i-with-gsp/327956.

**Comment by urbenlegend** [comment]
I am already using the closed driver with GSP off to workaround some performance issues with KDE and I am still getting the shadow issues.

**Comment by WandersenCS** [comment]
I have tested the vulkan beta drivers and disabled GSP on my RTX3080TI just to be sure and still have the shadow issue, if Ambient Shadows are set higher than off. I used Proton Experimental Bleeding Edge, Proton Hotfix and Proton-GE9-27 and cleared shadercache inbetween testings.

I don't remember having the issue with the first part when I played it back on release, so my bet is on driver issue here. Maybe even only for certain cards, but I am only speculating.

**Comment by dylanwe** [comment]
My game also keeps crashing, even with `SteamDeck=1 %command%`. I'm using:
- OS: Fedora 41 (Workstation Edition)
- GPU: AMD ATI Radeon RX 7700 XT
- CPU: AMD Ryzen 5 7600
- Memory: 32GB
- DE: GNOME 47.5
- Kernel: 6.13.9

[steam-2531310.log](https://gist.github.com/dylanwe/e07dc6f7dcee1d6b90ebcc48d9bed25d)

**Comment by reed-smout** [comment]
I am also experiencing the same issue as @dylanwe and have a similar setup if that helps:

- OS: Fedora 42 Beta (Silverblue)
- GPU: AMD Radeon RX 6800
- CPU: AMD Ryzen 5 3600
- Memory: 32GB
- DE: Gnome 48
- Kernel: 6.14.0

I am using the Flatpak version of Steam and have tried a variety of proton versions. It seems that the launch options aren't being respected as `MANGOHUD=1` does not make the overlay appear. This might be a separate issue (causing `SteamDeck=1` not to be set and therefore the game to crash)

[steam-2531310.log](https://github.com/user-attachments/files/19613880/steam-2531310.log)

**Comment by dylanwe** [comment]
@NZRosto you could try using the RPM version of steam, that worked for me.

**Comment by Rhatz** [comment]
does anyone knows what this log means

**Comment by reed-smout** [comment]
@dylanwe just tried using the RPM overlayed with `rpm-ostree` and it's running now. Clearly something about the Flatpak version causes it to not work, although it should be noted this is the first game that I've had any issues running past the usual protondb tricks. Also of note I haven't experienced any issues with the shadows, but perhaps that's just an Nvidia thing.

**Comment by tomicul** [comment]
Upgraded nvidia driver to 570.124.04. That solved the ambient shadows bug

**Comment by urbenlegend** [comment]
@tomicul Hmm, I am getting the ambient shadow bug with 570.133.07. Did it regress then?

**Comment by tomicul** [comment]
> [@tomicul](https://github.com/tomicul) Hmm, I am getting the ambient shadow bug with 570.133.07. Did it regress then?

Honestly I don't know. I've just upgraded my nvidia driver to 570 from 560 and that solved it, for me.

**Comment by pedrovp161** [comment]
> Upgraded nvidia driver to 570.124.04. That solved the ambient shadows bug


 What is you gpu and system settings? Maybe I have to downgrade mine

**Comment by tomicul** [comment]
Here's my config: 
OS -> Ubuntu 24.10
CPU -> AMD Ryzen 9 7945HX
GPU -> RTX 4060 Mobile
Memory -> 32 GB
Kernel -> 6.11.0-21-generic
All system settings and driver settings are default.

**Comment by burchetted** [comment]
> [@NZRosto](https://github.com/NZRosto) you could try using the RPM version of steam, that worked for me.

I tried the RPM version and I do at least get an error now. Compatibility tool failed.

![Image](https://github.com/user-attachments/assets/37e31753-9a9c-4e01-92d5-959af49b2e41)

![Image](https://github.com/user-attachments/assets/43dcf167-6a52-4a44-97fd-80325086d59e)

**Comment by burchetted** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/8585#issuecomment-2784744061

After verifying the game cache AND switching to the rpmfusion-steam-nonfree version the game launches and works without a problem so far.

Steam version 1.0.0.82 (Working) rpm-fusion-nonfree
Steam version 1.0.0.81 (not working) flathub


![Image](https://github.com/user-attachments/assets/e51e7c58-01df-4540-82c0-d406e8ffb24d)

**Comment by tommy-max** [comment]
--- **System Information for Bug Report** ---

**Hardware:**

* **CPU:** Intel Core i9-13900K (13th Gen, 24 cores / 32 threads)
* **GPU:** AMD Radeon RX 7900 XTX
* **GPU Driver Version:** Mesa RADV 25.0.3-arch1.1
* **RAM:** 64 GB DDR5 @ 5600 MT/s (2x 32 GB Corsair CMK64GX5M2B5600Z40)
* **Motherboard:** Gigabyte Z690 AORUS MASTER
* **BIOS Version:** F23 (Date: 09.03.2023)
* **Storage (OS/Applications Drive):** NVMe SSD, filesystem: Ext4
* **Power Supply (PSU):** NZXT C1200
* **Monitor(s):** 3440x1440 @ 180Hz

**Software:**

* **Operating System:** Arch Linux
* **Kernel Version:** 6.13.8-arch1-1
* **Affected Application/Game:** The Last of Us Part II Remastered
* **Compatibility Layer:** Proton Experimental, Proton 9.0.4, GE-Proton
* **Desktop Environment / Window Manager:** KDE Plasma / Wayland

**Issue Description:**

The problem occurs when attempting to launch **The Last of Us Part II Remastered** on **Arch Linux** using **Flatpak Steam** with various **Proton versions** (including **Proton Experimental**, **Proton 9.0.4**, and **GE-Proton**). The game **crashes on launch**, and no specific error message appears. The issue persists despite testing multiple Proton versions and ensuring that all the required dependencies and permissions are set.

### **Steps Taken So Far:**

1. **Proton Version Testing:**
   - **Proton Experimental**
   - **Proton 9.0.4**
   - **GE-Proton**
   
   All Proton versions resulted in the same crash issue at startup.

2. **Permissions Check:**
   The Flatpak Steam has been granted filesystem access to all necessary directories, but the issue persists.

3. **Proton Debugging:**
   Enabling `PROTON_LOG=1` provided detailed logs, which indicated potential issues related to missing libraries or incompatibility at game startup.

4. **Game Library Location:**
   The game is located on an external drive mounted via `/run/media/`, but this did not seem to be the root cause of the issue, as the crash happens even with the correct path configurations.

5. **Launch Options:**
   Multiple launch options have been tested, including disabling ESYNC and experimenting with different Proton settings, but the game still crashes during initialization.

### **Problem Summary:**
When attempting to launch **The Last of Us Part II Remastered** on **Steam (Flatpak)**, the game crashes immediately upon start, regardless of the Proton version used. Despite setting the correct permissions and paths, the crash persists with no specific error message. The issue is isolated to this game, and other titles appear to function as expected.

[steam-2531310.log](https://github.com/user-attachments/files/19650475/steam-2531310.log)

**Comment by tommy-max** [comment]
It seems there was a write access issue with the newly added Steam library. After fixing that, the problem was resolved and the game is now running.

**Comment by DeadSuperHero** [comment]
**--- System Information for Bug Report ---**

**Hardware**

- **CPU:** 32 × AMD Ryzen 9 7950X 16-Core Processor
- **GPU:** AMD Radeon RX 6700 XT
- **GPU Driver Version:** 24.2.8-1ubuntu1~24.10.1
- **RAM:** 64 GB DDR5 @ 5600 MT/s (2x 32 GB Corsair CMK64GX5M2B5600Z40)
- **Storage (OS/Applications Drive):** NVMe SSD, filesystem: Ext4
- **Monitor(s):** 1920 x 1080 @ 144Hz

**Software:**

- **Operating System:** Ubuntu 24.10
- **Kernel Version:** 6.11.0-21-generic (64-bit)
- **Affected Application/Game:** The Last of Us Part II Remastered
- **Compatibility Layer:** Proton Experimental, Proton Hotfix, Proton 9.0.4, GE-Proton-9-27
- **Desktop Environment / Window Manager:** KDE Plasma / Wayland

**Issue Description:**
For the record, I am using Steam Flatpak. Despite being able to get into the game's launcher, the actual game itself starts as a black screen for a few seconds, prior to crashing to desktop.

**Steps Taken:**
I have attempted using different version of Proton, including `Proton Experimental`, `Proton Hotfix`, `Proton 9-04`, and `ProtonGE 9-27`. All of these suffer from the exact same problem. I also attempted to use the `SteamDeck=1 %command%` trick, but the problem persists.

My best guess here is that maybe Ubuntu's Mesa drivers are out of date? It might be worth attempting to use upstream kisak Mesa packages for my distro version...

Update: Attempted to upgrade to latest `kisak` Mesa packages, problem still persists...

**Comment by DeadSuperHero** [comment]
Digging through the logs, a few things stand out...

`3737.789:012c:01fc:err:seh:NtRaiseException Unhandled exception code c0000409 flags 1 addr 0x142866989`

`err:xrandr:xrandr14_get_adapters Failed to get adapters`

`4064.991:0130:0214:err:vkd3d-proton:vkd3d_file_map_read_only: Failed to MapViewOfFile for vkd3d-proton.cache.write.`

Will continue to experiment.

**Comment by ghost** [comment]
--- System Information for Bug Report ---

**Hardware**

    CPU: AMD Ryzen 7 7700X 8-Core Processor
    GPU: NVIDIA GeForce RTX 4070
    GPU Driver Version: 4.6.0 NVIDIA 570.133.07
    RAM: 32 GB
    Storage (OS/Applications Drive): NVMe SSD, filesystem: ext4
    Monitor(s): 3840 x 2160 @ 4k 144hz

**Software:**

    Operating System: Nobara Linux Official NVIDIA ISO
    Kernel Version: 6.14.2-200.nobara.fc41.x86_64
    Affected Application/Game: The Last of Us Part II Remastered
    Compatibility Layer: Proton Experimental, Proton Hotfix, Proton 9.0.4, GE-Proton-9-27, Proton 8.0.5, Proton 7.0.6
    Desktop Environment / Window Manager: KDE Plasma / Wayland

**Issue Description:**
I was able to get into the game's launcher, but upon starting it the game goes into a black screen prior to crashing to desktop.

**Steps Taken:**
I have used many variants of Proton and I have used many launch options. I used SteamDeck=1 %command% & PROTON_HIDE_NVIDIA_GPU=1 %command%. I've used them together and alone on each proton variant that I have listed under the Software heading. I've also used the following launch options:
A: DXVK_ASYNC=1 DXVK_STATE_CACHE=0 PROTON_NO_FSYNC=1 PROTON_NO_ESYNC=1 PROTON_HIDE_NVIDIA_GPU=0 %command%
B: PROTON_HIDE_NVIDIA_GPU=1 DXVK_NVAPI_DISABLE=1 RADV_PERFTEST=aco %command%
C: PROTON_LOG=1 PROTON_USE_WINED3D=0 DXVK_ASYNC=1 __GL_SHADER_DISK_CACHE_SKIP_CLEANUP=1 mangohud %command%
D: PROTON_LOG=1 PROTON_NO_ESYNC=1 PROTON_NO_FSYNC=1 DXVK_NVAPI_ENABLE=0 %command%

I have attached a proton log using proton experimental with the SteamDeck=1 command. 

[steam-2531310.log](https://github.com/user-attachments/files/19723306/steam-2531310.log)

**Comment by czM1K3** [comment]
# Compatibility Report

## System Information
- GPU: AMD RX 580
- Video driver version: 25.0.3
- Kernel version: 6.14.1
- Link to full system information report as [Gist](https://gist.github.com/): [https://gist.github.com/czM1K3/f0343a2ecf7ef037e98913aa0a8c2f27](https://gist.github.com/czM1K3/f0343a2ecf7ef037e98913aa0a8c2f27)
- Proton version: Proton 9, Proton Hotfix, GE-Proton 9-27

## Symptoms
The game starts normally to the menu, I can go to guitar mode and models preview just fine. But when I want to enter story mode or No Return, the game crashes when on loading screen, but with few exceptions. Some chapters of the game starts just fine, some crashes. On my other computer with RX 6600 I don't get any crashes.

## Reproduction
Start the game and start story or No Return mode. I have tested these chapters:

### Chapters that crash
- Prologue
- The Chalet
- Packing Up
- The Gate
- Downtown
- Eastbrook Elementary
- Capitol Hill
- Channel 13
- The Tunnels
- The Theatre

### Chapters that don't crash
- Waking Up
- The Overlook
- Patrol
- The Horde
- The Birthday Gift

Also I would say, that this guy has the same issue: [https://www.youtube.com/watch?v=9z1U9_RlN3g](https://www.youtube.com/watch?v=9z1U9_RlN3g)

[steam-2531310.log](https://github.com/user-attachments/files/19727365/steam-2531310.log)

Edit: Now I tried it with GE-Proton 10-1 and it doesn't crash anymore. (On up to date Arch Linux)

**Comment by DeadSuperHero** [comment]
Big update: switching from the Flatpak version of Steam to the .deb package seems to have made all the difference. I'm not entirely sure why, but the game now works really well.

**Comment by tritri301** [comment]
> It seems there was a write access issue with the newly added Steam library. After fixing that, the problem was resolved and the game is now running.

How did you fix it exactly? I can't get the flatpak steam version to launch and since I'm on an immutable distro, it's my only option

**Comment by tommy-max** [comment]
> > It seems there was a write access issue with the newly added Steam library. After fixing that, the problem was resolved and the game is now running.
> 
> How did you fix it exactly? I can't get the flatpak steam version to launch and since I'm on an immutable distro, it's my only option

I Mount the Filesystem with this option defaults,user,rw,nofail,exec 0 0
And set the SteamLibary to this Permissions 

sudo chmod 755 /path/SteamLibary
sudo chown $USER:$USER /path/SteamLibary

**Comment by mickflemm** [comment]
Same here, tried various tricks mentioned here but the game crashes after the launcher. I'm on no-multilib Gentoo with flatpak, a custom 6.12 kernel config and an Radeon RX 6650 XT. With the same setup Part 1 worked great, I finished Part 1 and wanted to play Part 2 but no joy :-(

**Comment by urbenlegend** [comment]
Today's update seems to have completely broken NVAPI. Specifying `PROTON_DISABLE_NVAPI=0` now causes the game to completely crash when clicking Play in the launcher.

Good news is that the ambient shadows issue seems to have been resolved.

**Comment by Doomguy1364** [comment]
Compatibility Report:
- Name of the game with compatibility issues: The Last Of Us Part II
- Steam AppID of the game: 2531310

System Information:
- GPU: 7900 XTX
- Video driver version: Mesa 25.0.3
- Kernel version: 6.14.2-arch1-1
- Link to full system information report: https://gist.github.com/Doomguy1364/8df388cd250f4509426476b57702292a
- Proton version: Proton Experimental

## I confirm:
- [ X] that I haven't found an existing compatibility report for this game.
- [ X] that I have checked whether there are updates for my system available.

[steam-2531310.log](https://github.com/user-attachments/files/19796754/steam-2531310.log)

Symptoms:

Going back to the main menu/winning a run/dying in the side game mode "No Return" with Abby or any character under her in character select/in her home base will return to you to a black screen until the game is force closed; This does not happen with Ellie or any character from her home base!

I have tested on windows 11 with the same hardware and this issue is only present on Linux via proton.

Reproduction:
Always, Select Abby or any character under her in no return, click return to main menu/die/win run, will always return you to a black screen that needs to be force closed.


Video Evidence of the issue:
https://youtu.be/Oj7e9vow7xc

**Comment by TiagoOrl** [comment]
Today, with patch 1.2, even with SteamDeck=1, the games crashes on startup on Pop OS 22.04 with nvidia RTX 3060 laptop

**Comment by Doomguy1364** [comment]
> Today, with patch 1.2, even with SteamDeck=1, the games crashes on startup on Pop OS 22.04 with nvidia RTX 3060 laptop

I've seen other Nvidia users not able to play the game since this patch on the steam discussions, PROTON_HIDE_NVIDIA_GPU=1 should let you play, keep in mind you won't be able to use DLSS.

**Comment by urbenlegend** [comment]
Seems to me NVAPI is the culprit for the crash. NVAPI was working fine before today's game patch. I've attached my Proton log capturing the crash. Launch parameters were `PROTON_LOG=1 PROTON_DISABLE_NVAPI=0 SteamDeck=1 %command%`

[steam-2531310.log](https://github.com/user-attachments/files/19805914/steam-2531310.log)

My untrained eye is drawn to the assertion below:
```
35442.617:0130:0134:info:nvapi64:<-NvAPI_GPU_GetGpuCoreCount: No implementation
35442.617:0130:0134:warn:debugstr:OutputDebugStringA "\n******************************************************************************\n*** ASSERTION: NVAPI_OK == status\n***\n***  Function: ndgi::Adapter::InitPerfInfo\n***      File: ndlib/render/ndgi/win/ndgi-adapter-table-win.cpp\n***      Line: 917\n***     Built: \n***********************"...
35442.617:0130:0134:trace:seh:dispatch_exception code=40010006 flags=0 addr=00006FFFFFC1CF97 ip=6fffffc1cf97
35442.617:0130:0134:trace:seh:dispatch_exception  info[0]=0000000000000154
35442.617:0130:0134:trace:seh:dispatch_exception  info[1]=00000000001199c0
35442.617:0130:0134:warn:seh:dispatch_exception "\n******************************************************************************\n*** ASSERTION: NVAPI_OK == status\n***\n***  Function: ndgi::Adapter::InitPerfInfo\n***      File: ndlib/render/ndgi/win/ndgi-adapter-table-win.cpp\n***      Line: 917\n***     Built: \n***********************"...
```

**Comment by Saancreed** [comment]
@urbenlegend You're probably using outdated dxvk-nvapi because [I added a workaround specifically for this nonsense two weeks ago](https://github.com/jp7677/dxvk-nvapi/commit/17342694868e661589e3f10012fd56a0936bc5db).

Try switching to bleeding edge maybe.

**Comment by TiagoOrl** [comment]
> > Today, with patch 1.2, even with SteamDeck=1, the games crashes on startup on Pop OS 22.04 with nvidia RTX 3060 laptop
> 
> I've seen other Nvidia users not able to play the game since this patch on the steam discussions, PROTON_HIDE_NVIDIA_GPU=1 should let you play, keep in mind you won't be able to use DLSS.

I've tried with PROTON_DISABLE_NVAPI=0 and worked.

**Comment by urbenlegend** [comment]
> Try switching to bleeding edge maybe.

Thanks @Saancreed for the heads up and the fix! Bleeding edge makes it work again. So good to have DLSS and Reflex back :D

**Comment by Hicks79** [comment]
Does anyone else freeze the game as soon as the gameplay starts (one minute later).

Maybe it's a bug after patch 1.2.

Edit: I had 550.120 driver envidia, I had updated right now to 570, probably that was the problem.
Edit2: its perfect now!

**Comment by danbarretto** [comment]
# Compatibility Report
Name of the game with compatibility issues: The Last of Us™ Part II Remastered
Steam AppID of the game: 2531310
## System Information
* CPU: AMD Ryzen™ 7 5800H with Radeon™ Graphics × 16
* GPU: RTX 3050 Laptop 4GB
* Video driver version: 570.133.07
* Kernel version: Linux 6.5.6-300.fc39.x86_64
* OS: Fedora 42
* Proton version: Proton Experimental (Bleeding Edge)
* Link to full system report: https://gist.github.com/danbarretto/f4b9a7fa613833ca7658a4115868e706
## I confirm:


- [x] that I haven't found an existing compatibility report for this game.

- [x] that I have checked whether there are updates for my system available.

[steam-2531310.log](https://github.com/user-attachments/files/19835369/steam-2531310.log)

## Symptoms
The game starts normally, rendering around 30-50 fps on the menu screen and around 100-150 fps on the loading screen. However, as soon as the story begins, it drops to 1-2 fps making the game unplayable. This happens only when using the NVidia GPU. When using the Radeon integrated graphics I was able to render the game with around 30 fps using FSR at 720p.

**Comment by Doomguy1364** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/8585#issuecomment-2813265651

Putting your texture settings to Medium or lower seems to be a temporary work around for this bug!

**Comment by nagaoo0** [comment]
Same issue on my side 

Latest drivers 
Rtx 4080
Fedora 42

**Comment by structnull** [comment]
> # Compatibility Report
> 
> Name of the game with compatibility issues: The Last of Us™ Part II Remastered Steam AppID of the game: 2531310
> ## System Information
> 
>     * CPU: AMD Ryzen™ 7 5800H with Radeon™ Graphics × 16
> 
>     * GPU: RTX 3050 Laptop 4GB
> 

> The game starts normally, rendering around 30-50 fps on the menu screen and around 100-150 fps on the loading screen. However, as soon as the story begins, it drops to 1-2 fps making the game unplayable. This happens only when using the NVidia GPU. When using the Radeon integrated graphics I was able to render the game with around 30 fps using FSR at 720p.


Same issue here with the same gpu and same scenario where it is impossible to play the story as it is 1-3 fps when starting the story mode

**Comment by codeweaverwill** [comment]
I was able to repro the ~1 FPS ingame on a 3060 Ti. Seems to be caused by using too much VRAM. Here's the issue I think it's running into: https://github.com/HansKristian-Work/vkd3d-proton/issues/1476

Try turning down your graphics settings, turning off DLSS/FSR, or turning off Dynamic Resolution Scaling.

You can monitor VRAM usage of your Nvidia card by running: `watch nvidia-smi`

**Comment by structnull** [comment]
> Try turning down your graphics settings, turning off DLSS/FSR, or turning off Dynamic Resolution Scaling.

Doing this doesn't actually solve the issue — the game  uses around 2.8 GB of VRAM out of 4 GB on my rtx3050m  at 720p resolution with all settings set to very low. When starting the story, the game still runs at just 1–2 FPS.

**Comment by davernos** [comment]
# Compatibility Report
- Name of the game with compatibility issues: The Last of Us™ Part II Remastered
- Steam AppID of the game: 2531310

## System Information
- GPU: AMD Radeon RX 7800 XT
- Video driver version:  Mesa 25.1.1
- Kernel version: 6.14.8-200.nobara.fc42.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/davernos/e350558b532a5177af62dedaee2ad726
- Proton version: Tried all of them

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

Game is not starting. I've tried multiple proton versions, and launch parameters (PROTON_LOG=1 PROTON_DISABLE_NVAPI=0 SteamDeck=1 %command%) without success. I can see the launcher, black screen for some seconds after clicking on Play, and it returns me back to Steam.

[steam-2531310.log](https://github.com/user-attachments/files/20498972/steam-2531310.log)

**Comment by urbenlegend** [comment]
@davernos Not sure if it's related to your crash, but you should not be trying to enable NVAPI with PROTON_DISABLE_NVAPI=0. You have an AMD GPU not an Nvidia one.

You also don't need SteamDeck=1 anymore. It was necessary during launch but works fine with out it now.

**Comment by simifor** [comment]
@davernos does the initial launcher appear for you? I tried with a rdna2 card, mesa git and mesa 25.1.1 to match yours but had no issue with the game.

Just in case, does `PROTON_SET_GAME_DRIVE=1 %command%` help?

**Comment by davernos** [comment]
> [@davernos](https://github.com/davernos) Not sure if it's related to your crash, but you should not be trying to enable NVAPI with PROTON_DISABLE_NVAPI=0. You have an AMD GPU not an Nvidia one.
> 
> You also don't need SteamDeck=1 anymore. It was necessary during launch but works fine with out it now.

@urbenlegend Thanks for letting me now. I tried many options at this point :)



> [@davernos](https://github.com/davernos) does the initial launcher appear for you? I tried with a rdna2 card, mesa git and mesa 25.1.1 to match yours but had no issue with the game.
> 
> Just in case, does `PROTON_SET_GAME_DRIVE=1 %command%` help?

@simifor That was it! Game is starting now. Yes, I had the initial launcher showing all the time.
What is PROTON_SET_GAME_DRIVE doing exactly? Never used it before.

**Comment by simifor** [comment]
@davernos it affects how disk information is queried, in your case it's possible the length of the path for your game is too long

**Comment by bennetthermanoff** [comment]
@simifor Can confirm that `PROTON_SET_GAME_DRIVE=1` was also a fix for my startup crashess on atomic fedora/flatpak steam

**Comment by NTMan** [comment]
The game crashes every time when I tried to continue the campaign.

![Image](https://github.com/user-attachments/assets/52cdb5a1-c56b-4f65-b430-915a73176a8a)

## System Information
- GPU: AMD Radeon 7900XTX
- Video driver version: [Mesa 25.2.0-devel](https://gitlab.freedesktop.org/mesa/mesa/-/commit/3bd85064d438fcef59e7ef588507b561e16d06f6)
- Kernel version: 6.16-rc1
- Link to full system information report as [Gist](https://gist.github.com/NTMan/33cca4906328793206218192820779ec)
- Proton version: 1748966679 experimental-10.0-20250603b

Proton log: [steam-2531310.zip](https://github.com/user-attachments/files/20730233/steam-2531310.zip)

Workaround with `PROTON_SET_GAME_DRIVE=1 %command%` didn't help, but with `SteamDeck=1 %command%` I can continue the campaign.

For reproduction you can use my save: [Naughty Dog.zip](https://github.com/user-attachments/files/20738201/Naughty.Dog.zip)

Just select STORY->CONTINUE (Hillcrest)

![Image](https://github.com/user-attachments/assets/b66fe2de-f951-428e-9b82-f2b6900582fe)

Or load manual save Seattle Day 2 - Hillcrest (MANUAL SAVE 6)

![Image](https://github.com/user-attachments/assets/f3574384-4606-4df7-a95b-c1ed75443d9f)

**Comment by kisak-valve** [comment]
The last of us part 2 remastered steam sond problems

Issue transferred from https://github.com/ValveSoftware/Proton/issues/8864.
@Frelidon posted on 2025-06-28T21:10:20:

# Compatibility Report
- Name of the game with compatibility issues: The Last of Us Part II remastered
- Steam AppID of the game: 2531310

## System Information
- GPU: < RX 7800XT >
- Video driver version: < 4.6 (Compatibility Profile) Mesa 25.1.4 >
- Kernel version: < 6.15.3-201.nobara.fc42.x86_64 (64-bit) >
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: Proton Hotfix

## I confirm:
- [Yes ] that I haven't found an existing compatibility report for this game.
- [Yes ] that I have checked whether there are updates for my system available.



## Symptoms 
Hi, I have a problem with the sound scratching in the last of us part 2 remastered steam. I found this fix on Reddit and it helps.  

pw-metadata -n settings 0 clock.force-rate 48000 && pw-metadata -n settings 0 clock.force-quantum 500

https://www.reddit.com/r/linux_gaming/comments/1htxdig/audio_crackles_nobara_41/?tl=de

Unfortunately, I don't know if the operating system or Proton is causing the error. I've also started an article on Nobara.

https://github.com/Nobara-Project/nobara-core-packages/issues/60

Gist: 
https://gist.github.com/Frelidon/287ab146ce26d3f1d26d4377e0050f59

**Comment by Hicks79** [comment]
I haven't played in a while, but I think I'm now experiencing a frame drop to 2-4.

Also imposible to play.

Edit: Okay, somehow the shadown had been set to high, and the texture (now in trilinear) works better at around 40 fps.
Edit 2: in hillcrest there is a huge drop in fps; I don't think you can play like before.

**Comment by VirtualBoost** [comment]
Has anyone experienced this? Tried switching proton versions, graphics settings, turning on and off DLSS, etc., but nothing works.

<img width="3840" height="2160" alt="Image" src="https://github.com/user-attachments/assets/33e626ba-bb08-42e6-8f54-a62682c79c0a" />

**Comment by kisak-valve** [comment]
Hello @VirtualBoost, that looks like something which should be reported to your video driver vendor. Please copy the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by simifor** [comment]
@VirtualBoost couldnt get the same effect on my end with a 4060m with nvidia 580.105 on plasma wayland. Tried with proton experimental, going through all graphic presets, switching between dlss and other upscaling methods. I'm kinda curious if the glitch is tied to that snow effect and if the game would look normal in other areas

**Comment by VirtualBoost** [comment]
[gist](https://gist.github.com/VirtualBoost/d66ea70f7841ca70ae41a4c1f1c38a4b)

Link to my gist can be found here.

EDIT: It seems to happen from any volumetric effect in the game, like the dust/particles that gathers around your characters flashlight, or from smoke when the characters are smoking, etc., so I will embed a few more screenshots. 

I am using the latest driver, 590.48.01, so maybe a roll back to the latest 580 could fix it?

https://i.ibb.co/4wLJ6ssX/Sk-rmbild-20251221-122918.png

https://i.ibb.co/93S3hggs/Sk-rmbild-20251221-123031.png

**Comment by urbenlegend** [comment]
@VirtualBoost I am getting the exact same issue in the Flooded City:

![Image](https://github.com/user-attachments/assets/b6973840-e912-40c0-977d-1a77ecff5390)

[Steam Runtime Diagnostics](https://gist.github.com/urbenlegend/a407051f9b28f1aecf5143d74f6375b1)

```
Operating System: Arch Linux 
KDE Plasma Version: 6.5.4
KDE Frameworks Version: 6.21.0
Qt Version: 6.10.1
Kernel Version: 6.18.2-arch2-1 (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 9800X3D 8-Core Processor
Memory: 64 GiB of RAM (62.4 GiB usable)
Graphics Processor: NVIDIA GeForce RTX 3090 w/ 590.48.01 drivers (nvidia-open)
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: X870E AORUS ELITE WIFI7
```

I can provide the save files if necessary.

**Comment by X6205** [comment]
My two cents when running this game

CPU: Ryzen 7 3700X with 32 GB RAM
GPU: AMD Radeon RX 9060 XT 16GB
Driver/LLVM version: Kisak Mesa 25.3.3
Kernel version: 6.17 OEM on Ubuntu 24.04
Proton version: Experimental and latest Proton GE

Everything seems to be fine, including forced FSR4 with ProtonGE, but this time is audio weird. I have Pipewire virtual surround sink 7.1 (hesuvi) with Atmos.wav preset. No matter what i choose in game audio settings, surround effect is not quite right. Even first game, ported by Iron Galaxy has this thing OK, but here no matter what choices i combine in settings, surround effect is weird with strange soundstage. Propably problem with middleware or something else is going on..

**Comment by Spyros33** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/8585#issuecomment-3678405345

  It is most likely caused by the nvidia driver , i am dualbooting with another os with older nvidia driver and there are no issues at all!I could bet it is the 590 driver that breaks things. In 590 driver and cachy os it is exactly like the photos you posted , no matter the settings there is this chekerboard thing!In pop os with older driver all perfect!

**Comment by Darsh-A** [comment]
> I haven't played in a while, but I think I'm now experiencing a frame drop to 2-4.
> 
> Also imposible to play.
> 
> Edit: Okay, somehow the shadown had been set to high, and the texture (now in trilinear) works better at around 40 fps. Edit 2: in hillcrest there is a huge drop in fps; I don't think you can play like before.

@Hicks79 how did you solve the 2-4 fps issue, was it due to iGPU+dGPU?

**Comment by Hicks79** [comment]
> > I haven't played in a while, but I think I'm now experiencing a frame drop to 2-4.
> > Also imposible to play.
> > Edit: Okay, somehow the shadown had been set to high, and the texture (now in trilinear) works better at around 40 fps. Edit 2: in hillcrest there is a huge drop in fps; I don't think you can play like before.
> 
> [@Hicks79](https://github.com/Hicks79) how did you solve the 2-4 fps issue, was it due to iGPU+dGPU?

The only solution has been to lower the graphics quality to “medium”; before, I could easily set it to “high” without any issues.

Now, on “high,” I'm getting about 2 FPS; I'm not sure if this is a regression in Proton.

**Comment by davgar99** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/8585#issuecomment-3706353408

I can confirm this is an Nvidia driver related issue because I'm also experiencing it with the latest driver Ver. 595.58.03. Also, Nvidia seems to know about it according to their forums, but I'm not sure if they're working on a fix for it.

Update: please report this problem to Nvidia on their forums so they can fix the issue. [Here](https://forums.developer.nvidia.com/t/595-release-feedback-discussion/362561)

[Nvidia Forums](https://forums.developer.nvidia.com/t/590-release-feedback-discussion/353310/310)
[Reddit](https://www.reddit.com/r/linux_gaming/comments/1qcbdkv/the_last_of_us_part_ii_blocky_shadowstextures/)

**Comment by SoloSaravanan** [comment]
> I haven't played in a while, but I think I'm now experiencing a frame drop to 2-4.
> 
> Also imposible to play.
> 
> Edit: Okay, somehow the shadown had been set to high, and the texture (now in trilinear) works better at around 40 fps. Edit 2: in hillcrest there is a huge drop in fps; I don't think you can play like before.


Adding this PROTON_HIDE_NVIDIA_GPU=1 SteamDeck=1 %command% makes the game playable but DLSS will not work and still there is the artifacts.

![Image](https://github.com/user-attachments/assets/e5c11548-db50-4f06-bdb6-23ef4735a443)

**Comment by kisak-valve** [comment]
The Last of Us™ Part II Remastered (2531310)

Issue transferred from https://github.com/ValveSoftware/Proton/issues/9666.
@pvlvld posted on 2026-04-13T16:10:25:

# Compatibility Report
- Name of the game with compatibility issues: The Last of Us™ Part II Remastered
- Steam AppID of the game: 2531310

## System Information
- GPU: RX 6800 XT
- Video driver version: Mesa 26.0 / 26.1
- Kernel version: 6.19
- full system information [Gist](https://gist.github.com/pvlvld/bace80ca8f4f7f347cfc5a44a057bef8)
- Proton version: 10 / Experimental / Hotfix

## I confirm:
- [x] that I haven't found an existing compatibility report for this game. (diff hardware / problem)
- [x] that I have checked whether there are updates for my system available.

Proton log:
[steam-2531310.log](https://github.com/user-attachments/files/26681037/steam-2531310.log)

## Symptoms
Getting an underloaded CPU & GPU (both ~25%), which results in 10-20 fps with absolutely any graphics settings, no difference.
Other games work flawlessly on my setup out of the box.

I've tried:
- clean game reinstall, including pfx
- installing the latest mesa-git
- installing  amdonly-gaming-* packages
- gamemode & gamescope
- diff schedulers
- updating & resetting bios
- disabling iGPU
- a ton of ENV's, only noticeable one is the "VKD3D_CONFIG=nodxr", +5-10fps
- gave up and installed Windows as a dual-boot (sad one), resulting in ~90fps with "very high" (maxed out) graphics preset w/o any FSR / frame-gen, native FHD resolution.

No effect env's:
SteamDeck=1
VKD3D_DISABLE_EXTENSIONS=VK_EXT_descriptor_buffer
ENABLE_GAMESCOPE_WSI=1
VKD3D_FEATURE_LEVEL=12_2 / 12_1 / 12_0
...

**Comment by simifor** [comment]
@pvlvld tried with a rx 6600 and 5700x3d. Two set of settings, high preset + quality FSR3 at 2k, and very low preset + fsr3 ultra performance at 2k, this with proton 9, 10 and experimental, with mesa 26.0.2, 26.0.4 and mesa git compiled today, without any extra launch parameters. This on plasma wayland.

At the tested location I was always using 99% of the gpu, and ran at 70s fps at high settings at 150s fps at low settings. Of course, performance is going to depend on the scene, but there's a large performance delta between your system and mine despite me having the worse card.

Are you sure you haven't changed anything else in your system that might be affecting performance? Do you have any other dx12 games that you can check to see if its performance is oddly low as well?

**Comment by pvlvld** [comment]
@simofor
the same problem:
Mafia: The Old Country
STALKER 2 (playable, but really low fps)
downloading Hogwarts Legacy, will update this msg

good / better than on windows:
Star Wars Jidi: Survivor
RDR2 (dx12 / vulcan - the same)
Shadow of the Tomb Raider
PEAK
Hellblade: Senua's Sacrifice
The Dark Pictures Anthology

Any others worth a check?
https://steamcommunity.com/id/pvlvld/

Probably a better way would be installing steam on the Live CD and mounting ssd with games?! To verify, that it's not my system setup to be blamed?

**Comment by simifor** [comment]
@pvlvld I think what you have in hand is enough for the time being. For reference, it might be useful to have some data on gpu and cpu usage in these games with something like mangohud.

I just noticed that you installed the last of us on an external partition, is it ext4 or a different format?

**Comment by pvlvld** [comment]
> I just noticed that you installed the last of us on an external partition, is it ext4 or a different format?

Currently on the ntfs, before that it was on the nvme ext4, the same that my system on.
No difference.
Will check mangohud on those.

UPD:
Hogwarts Legacy ultra + rt, no fsr, FHD - runs perfectly.
100% GPU utilization, ~50% CPU
Jedi Survivor is the same

**Comment by simifor** [comment]
@pvlvld still no repro on my end, regarding mounting a live session, the problem with that is that the session itself would run on ram, there's a chance this might degrade performance a bit, but if you have the option to, I think it's worth trying. I also think your gpu stats would be more useful when talking about the games that are running slow, alongside things like clockspeed as well.

Also upload the result of `sudo dmesg` after running a slow game, maybe kernel logs will give us some extra information.

**Comment by pvlvld** [comment]
@simifor, fixed.
Checked dmesg, and it was screaming about resizebar.
Bios:
Above 4G Decoding -> Enabled
Re-Size BAR Support -> Auto / Enabled

Don't think that it was disabled at the first run, but maybe it was fixed with a bios update / reset.
(s2h b550m, updated to f19)

@kisak-valve https://github.com/ValveSoftware/Proton/issues/8585#issuecomment-4237903334 resolved.

**Comment by tr1xem** [comment]
Any updates regarding this? I have a 4050 and still facing this bug of smoke being checkers pattern 

<img width="1919" height="1079" alt="Image" src="https://github.com/user-attachments/assets/5bd7f66e-36b8-4adb-a57e-ef18a1c93ed4" />

**Comment by simifor** [comment]
@tr1xem please share your display and graphics settings for the game, and a save file close to a point where the issue can be reliably triggered

**Comment by tr1xem** [comment]
Here are the logs
[launch.log](https://github.com/user-attachments/files/30854516/launch.log)
Graphic Setting is in game medium 
This bug happens in every settings across all dlss fsr xess and taa

<img width="1919" height="1079" alt="Image" src="https://github.com/user-attachments/assets/8c7cf687-5670-47b0-9a00-ef75ed79b01e" />
example here is it with proton experimental 11-0 (details can be found in top left corner)

**Comment by ltwell** [comment]
I found that if downgrade nvidia driver verison to 580.178.04  every thing work as expected.

**Comment by simifor** [comment]
@ltwell If the issue only happens with newer nvidia drivers, then it should be reported to them https://forums.developer.nvidia.com/c/gpu-graphics/linux/148
