### ISSUE TITLE
Command & Conquer™ Generals Zero Hour (2732960)

### ISSUE THREAD

**Issue by freezer255** [ValveSoftware/Proton#8824]
# Compatibility Report
- Name of the game with compatibility issues: Command Conquer Generals Zero Hour and Command Conquer Generals
- Steam AppID of the game: 2732960

## System Information
- GPU: RX 9060XT
- Video driver version: Mesa 25.1.3 
- Kernel version: Linux 6.15.2-2-cachyos
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: proton hotfix,proton 9.0.4,proton 10 beta and Ge proton 10.4

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

[steam-2732960.log](https://github.com/user-attachments/files/20781923/steam-2732960.log)

## Reproduction
Just start the game with a rx 9060xt,other games work fine.

**Comment by codeweaverwill** [comment]
I found that on my machine the game hangs on the black window for a couple minutes before reaching gameplay. If you give it a few minutes, does the game ever load?

**Comment by freezer255** [comment]
Ok that actually works. The problem is a message appears and asks to close the process. I did click wait and the message came back,after 5 times of clicking wait I gave up because I thought the game is freezed. But it appears that was not the case and I have to click wait for a few minutes and then the game starts. Is there no easy way to stop the message or make it wait longer till it appears ? , thanks anyways guys

**Comment by freezer255** [comment]
Nice, proton 10 beta fixed the problem, thank you !

**Comment by JN19aban** [comment]
I have the same problem black screen on start of the game after update to `Nvidia drivers 580.82.07`. The audio is working but black screen only.....  Was working ok up to `Nvidia drivers 570.172.08`......

**Comment by kisak-valve** [comment]
Hello @JN19aban, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options, reproduce the regression, and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.) Also, please copy the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by JN19aban** [comment]
Ok @kisak-valve the link is below:

https://gist.github.com/JN19aban/769d95147f787f8a8f29822c8286d241

**Comment by Wedge009** [comment]
I thought I had reported this previously, but apparently not - maybe because the game itself has been largely fine in my experience. The news reporter FMVs don't play at all when running in Proton - granted, they don't add much since one only really notices they're missing if they've played it on Windows previously, but for whatever reason they simply don't play at all through Proton.

Going off recollection, Proton 9 worked well enough, and current Proton 10 resolves the black screen on Alt-Tab issue.

Regarding the original report, I'm also running amdgpu but on Ubuntu. Looking at [ProtonDB](https://www.protondb.com/app/2732960), seems more users have success than not, with Proton.

**Comment by Wedge009** [comment]
On initial installation, I recall it also helps to manually set the resolution in `Options.ini` - even trying a fresh installation on Windows just now I had to do this, or use `-win` to start in windowed mode to stop it from crashing with the 'serious error' mentioned on [PC Gaming Wiki](https://www.pcgamingwiki.com/wiki/Command_%26_Conquer:_Generals#Technical_Difficulties.2FSerious_Error).

`<steam installation>/steamapps/compatdata/2732960/pfx/drive_c/users/steamuser/Documents/Command and Conquer Generals Zero Hour Data/Options.ini`

**Comment by Wedge009** [comment]
> The news reporter FMVs don't play at all when running in Proton - granted, they don't add much since one only really notices they're missing if they've played it on Windows previously, but for whatever reason they simply don't play at all through Proton.

This may be related to high resolution rather than the fault of Proton - I just replicated this in Windows with a UHD display, whereas Windows with QHD displays the FMV okay.

**Comment by Wedge009** [comment]
There's a **regression in Proton 11** where custom scenarios and missions downloaded from the workshop are no longer found. Reverting to Proton 10 resolves this. There's also a minor cosmetic issue where vertical lines are visible on menu item buttons in Proton 11.

The same applies to the base game C&C Generals (2229870) which doesn't appear to have a dedicated issue report.

**Comment by codeweaverwill** [comment]
> There's a **regression in Proton 11** where custom scenarios and missions downloaded from the workshop are no longer found. Reverting to Proton 10 resolves this. There's also a minor cosmetic issue where vertical lines are visible on menu item buttons in Proton 11.

Ah, I believe this is due to game drive changes in 11. Using the launch option `PROTON_SET_GAME_DRIVE=0 %command%` should resolve the issue. Will look into it.

**Comment by Wedge009** [comment]
Thanks for the quick response. Confirming the set-drive option restores the Proton 10 behaviour. The cosmetic issue is still present and while not ideal, it's just cosmetic.

**Comment by codeweaverwill** [comment]
> The cosmetic issue is still present and while not ideal, it's just cosmetic.

`WINE_DISABLE_FULLSCREEN_HACK=1` seems to fix the cosmetic issue. Also looking into that.

**Comment by Wedge009** [comment]
Not sure what's going on. I had `PROTON_SET_GAME_DRIVE=0 WINE_DISABLE_FULLSCREEN_HACK=1 %command%`. Whether the Wine hack was present or not, I see the vertical lines on the menu buttons. But switching to another window and then returning to the game, the buttons look 'clean' again.

The game drive issue feels higher priority to me.
