### ISSUE TITLE
Blade & Soul NEO (3669060)

### ISSUE THREAD

**Issue by Hadrianneue** [ValveSoftware/Proton#8873]
# Compatibility Report
- Name of the game with compatibility issues: Blade & Soul NEO
- Steam AppID of the game: 3669060

## System Information
- GPU: RX 9070 XT
- Video driver version: Mesa git
- Kernel version: Linux ian-endeavouros 6.16.0-rc3-1-mainline #1 SMP PREEMPT_DYNAMIC Mon, 23 Jun 2025 16:45:21 +0000 x86_64 GNU/Linux
- Link to full system information report as [Gist](https://gist.github.com/Hadrianneue/c68e6d87dfcff37653a1aad0f5ca0477):
- Proton version: Proton Experimental

## I confirm:
- [X ] that I haven't found an existing compatibility report for this game.
- [X ] that I have checked whether there are updates for my system available.

[steam-3669060.zip](https://github.com/user-attachments/files/20989161/steam-3669060.zip)

## Symptoms 
Game Crashes with message:

![Image](https://github.com/user-attachments/assets/7dd54281-5381-4d2d-89f1-f4d34dcb4c86)

## Reproduction
Launch game and it should crash after the message above

**Comment by Hadrianneue** [comment]
Manually installing [webview2](https://developer.microsoft.com/en-us/microsoft-edge/webview2/?form=MA13LH#download) allows me to accept terms and make a pin passcode, but it crashes on the character creation screen

![Image](https://github.com/user-attachments/assets/d11e6148-c343-4fa0-9025-69fe5691ec2f)

[steam-3669060.zip](https://github.com/user-attachments/files/20990296/steam-3669060.zip)

**Comment by Hadrianneue** [comment]
Okay game seems to be working with GE-Proton10-7 after i disabled wine exports with protontricks  
1) `protontricks -c "wine control" 3669060`
2)  on the staging tab check "hide wine exports..." and click on ok.

I also installed d3dcompiler_47 (with `protontricks 3669060 --gui`) and set windows version to 11 (first command), but i don't think neither of these are necessary.

There is still one lingering problem, opening settings in-game crashes, you can change settings while on the character selection screen
yet another log, should contain info about the crashing that happens when opening in-game settings
[steam-3669060.zip](https://github.com/user-attachments/files/20991715/steam-3669060.zip)

**Comment by Nurgiel** [comment]
I see [GE-Proton10-8 Released](https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/GE-Proton10-8) has:

add protonfixes for Blade & Soul NEO -- game is now playable but there is a known crash in-game when you open the settings. Opening the settings at character select works fine

---

Thank you sir!

**Comment by robstarmcdonald** [comment]
Hello @Nurgiel the using of Proton-GE just to play the game is not what were looking for.

But I hope it still functions on that version.

**Comment by nazgulsenpai** [comment]
> I see [GE-Proton10-8 Released](https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/GE-Proton10-8) has:
> 
> add protonfixes for Blade & Soul NEO -- game is now playable but there is a known crash in-game when you open the settings. Opening the settings at character select works fine
> 
> Thank you sir!

After lots of experimentation (and I'm not exactly sure which one of these things worked) I got the options menu to load in game. 

In Protontricks I have enabled:
-devenum
-dotnet48
-dpvoice
-dxdiagn
-pdh
-powershell

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/49a163c9-06bc-4898-976b-223a8c0653ee" />
edit: added powershell, it didn't show up in the list but i did install it

**Comment by GloriousEggroll** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/8873#issuecomment-3458358141

dotnet48 was the missing puzzle piece!
also need to disable xalia so that you dont get a million popups during dotnet48 install.

**Comment by nazgulsenpai** [comment]
Thanks GE! That has bugged me for a while. The 10-24 protonfix is working!

**Comment by GloriousEggroll** [comment]
looks like its busted again in proton-experimental. game does not open. needs bisecting

**Comment by kisak-valve** [comment]
Hello @GloriousEggroll, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options, reproduce the regression, and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.)

**Comment by GloriousEggroll** [comment]
broken log:

[steam-3669060-1.tar.gz](https://github.com/user-attachments/files/24172718/steam-3669060-1.tar.gz)

working log:

[steam-3669060.tar.gz](https://github.com/user-attachments/files/24172721/steam-3669060.tar.gz)

main difference:

```
1156552.332:0164:0174:err:ole:CoGetContextToken apartment not initialised
```
```
1156552.401:0164:0168:fixme:combase:RoGetActivationFactory (L"Windows.Foundation.Diagnostics.AsyncCausalityTracer", {50850b26-267e-451b-a890-ab6a370245ee}, 000000000011DF28): semi-stub
1156552.401:0164:0168:err:combase:RoGetActivationFactory Failed to find library for L"Windows.Foundation.Diagnostics.AsyncCausalityTracer"
```
these does not occur in the working log

GE-Proton10-25 still works, but the wine commit from that build now says "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository." which means someone rebased and force-pushed upstream, so I can't see what they changed within that commit tree. I hit this same problem when bisecting Heroes of Newerth Reborn (which also broke). Luckily for that I found an old post that said it needed gdiplus in winetricks and that worked. Sadly adding gdiplus does not resolve the issue here.

**Comment by GloriousEggroll** [comment]
fixed in experimental by 
https://github.com/ValveSoftware/wine/commit/3cd5fd2799a9a78199a16b795568eed488f5f533

**Comment by robstarmcdonald** [comment]
> fixed in experimental by [ValveSoftware/wine@3cd5fd2](https://github.com/ValveSoftware/wine/commit/3cd5fd2799a9a78199a16b795568eed488f5f533)

I just checked the game again, I'm still having issues, even with Proton Experimental, sorry.
