### ISSUE TITLE
Project Cars 2 (378860)

### ISSUE THREAD

**Issue by leillo1975** [ValveSoftware/Proton#908]
It installs prerequisites and it executes showing the first screens and then it get blocked.
With wine the game runs in menus, but fails when load a race.

https://gist.github.com/leillo1975/93f3b9ee02cb2b47e8de00dfe40f6957

**EDIT:** The game crash to desktop when try to get a online list of games

**Comment by kisak-valve** [comment]
Hello @leillo1975, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and drag and drop the generated $HOME/steam-$APPID.log into the comment box.

**Comment by leillo1975** [comment]
[steam-378860.log](https://github.com/ValveSoftware/Proton/files/2332692/steam-378860.log)

**Comment by leillo1975** [comment]
Today, I started again the game with Proton 3.7.6Beta and now it works in menus, but when I try to start a a race it crashes during loading. This is my last log:

[steam-378860.log](https://github.com/ValveSoftware/Proton/files/2364168/steam-378860.log)

The problem is the same with 3.7.3

**Comment by ah-** [comment]
The loading crash is in the process of being fixed, follow https://github.com/doitsujin/dxvk/issues/641 for details. Runs perfectly now for me, hopefully everything will be out in the near future.

![screenshot from 2018-09-16 20-21-53](https://user-images.githubusercontent.com/1349849/45600042-39ed2d00-b9ee-11e8-8ee9-3153cf8c2c00.png)

**Comment by leillo1975** [comment]
Thanks a lot, @ah- it's very complicated for me compiling, but I see that @doitsujin  will take care of this problem. Can you share the file that you compiled to replace PCars2.exe? Perhaps in a close future we can enjoy this fantastic game on Linux without this fixes.
Only one thing, I see that you are quite adept at fixing problems. You I don't have idea if you own Project Cars 1. It works perfect with proton, even with Force Feedback in my G27, but I have an notice when the game try to save the profile and the progress. 
I opened an issue about this P.Cars 1 problem:
https://github.com/ValveSoftware/Proton/issues/244

**Comment by ah-** [comment]
Haha, if you can't wait then place the two dlls in the attachment in $HOME/.steam/steam/steamapps/common/Proton 3.7/dist/lib64/wine/dxvk and it should run.

[pcars.zip](https://github.com/ValveSoftware/Proton/files/2386943/pcars.zip)

Sorry, don't have Project Cars 1, and not quite enough time to go and debug that. Just really wanted to get Project Cars 2 working :)

**Comment by leillo1975** [comment]
@ah- You are my man!!! It works. Thanks a lot
The game is playable now!
There are a problem, it has nothing to do with this, it's a proton problem. I can use my Logitech G27 wheel, calibrate it (pedals included), but the force feedback don't work (in PCars1 works)

**Comment by whizse** [comment]
You can use WINEDEBUG with +dinput to log what FF effects the game is trying to use. On my system I get a lot of
"Effect gain requested but no effect gain functionality present." and
"Sample period requested but no sample period functionality present." and none of those effects are implemented in the driver. I sadly think the lack of force feedback in the game is just incomplete drivers.

**Comment by leillo1975** [comment]
It's a pity. There are a lot of games  I suspect that have the same problem... Great games like rfactor2 or Automobilista. At least Assetto Corsa, and AC Competizione works well

**Comment by leillo1975** [comment]
I don't have idea of developing, debuggin and this kind of things, but Maybe this project has something to do with the subject ....
https://steamcommunity.com/groups/linuxff/discussions/0/405692224235574471/

I think that Valve could take a look of this problems with wheels on Linux. A lot of racing games could be benefit by a more complete drivers

**Comment by mimattr** [comment]
# Whitelist Request
- Name of the game to be whitelisted: **Project Cars 2 Demo**
- Steam AppID of the game: **737770**

## System Information
- GPU: **GTX 970**
- Driver/LLVM version: **NVIDIA 396.54**
- Kernel version: **4.4.0-135-generic**
- [Link to full system information report as Gist](https://gist.github.com/mimattr/b0b7f46366e31e254460b9593ce87e51)
- Proton version: **3.7-6 Beta**

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options)
      are necessary to run the game.
- [x] that no workarounds other than the mentioned ones are necessary:
  1. **General:** Minimum requirement **DXVK 0.80** (doitsujin/dxvk@19408f0ebede526a1aad2a594b3b25619d1737e5)

## Issues
- [x] I haven't experienced any issues.
- [ ] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are
      remaining issues.

**Comment by kisak-valve** [comment]
Hello @mimattr, the request to switch this to a white list request is denied because a demo counts as an independent test case for Proton and is not a reliable indicator of compatibility with the full game version.
Additionally, the tested Proton version must be an unmodified version from Steam.

**Comment by mimattr** [comment]
Appreciate the explanation @kisak-valve and apologies for any confusion, a separate ticket has now been created (#1603)

As an aside it's great to see a title with [planned native SteamOS support](https://web.archive.org/web/20150625005340/http://www.wmdportal.com/projects/project-cars-2) finally working on Linux! :wink:

**Comment by leillo1975** [comment]
Please Valve, fix feedback in wheels

**Comment by leillo1975** [comment]
FIXED!!!!!!!!!!!!!!!!!!!!

It works perfect, with Force Feedback in my G27 Wheel! Thanks a lot, Valve! :)))

**Comment by whizse** [comment]
@leillo1975  That's very interesting! The demo (at least for me) still doesn't work with FF. Was it a game update or Proton update that fixed it? If possible, could you try the demo as well?

**Comment by leillo1975** [comment]
There is an beta update of proton (3.7.7 Beta). With this version the game now runs without fixes and with Force Feedback. Play Online make the game crash. 
About F.Feedback: if you make an Alt-Tab, this feature get lost

**Comment by leillo1975** [comment]
One question, two days ago the game was updated, and now I don't have force feedback. Can you say me if yoy have the same issue?

Thanks

**Comment by madbad** [comment]
I'm experiencing the same "Missing Force Feedback" issue after the game update, it worked before the update.

**Comment by ah-** [comment]
Still works for me, I do have working FF via https://github.com/atar-axis/xpadneo.

**Comment by leillo1975** [comment]
@ah- what controller you use?

**Comment by ah-** [comment]
It's a recent Xbox controller, not quite sure what the exact model is.

**Comment by leillo1975** [comment]
Our problem is with Logitech Wheels.

**Comment by madbad** [comment]
Do anyone else also get stuck at 75% loading when trying to get into a race with AI ?

**Comment by leillo1975** [comment]
After the last Proton beta (3.16-4Beta)  PCars2 works online and don't crash to desktop. Unfortunately, after game's update one month ago , Force Feedback stills missing. Please Valve, take a look on this. It's a great game

**Comment by kisak-valve** [comment]
Project CARS 2 (378860)

Issue transferred from https://github.com/ValveSoftware/Proton/issues/1889.
@GottaSlay posted on 2018-11-02T17:36:21:

# Compatibility Report
- Name of the game with compatibility issues: Project CARS 2 
- Steam AppID of the game: 378860

## System Information
- GPU: RX580 
- Driver/LLVM version: Driver Version:  4.4 (Compatibility Profile) Mesa 18.2.3 - padoka PPA
- Kernel version: 4.19
- Link to full system information report as [Gist] https://gist.github.com/GottaSlay/66874aaaf2ecfc3d5d0e56cbb1e481e4
- Proton version: 3.16-4 Beta

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.


[steam-378860.log](https://github.com/ValveSoftware/Proton/files/2543529/steam-378860.log)


## Symptoms:
Game crashes on launch.


## Reproduction:
Just try to launch the game.

**Comment by leotada** [comment]
> Do anyone else also get stuck at 75% loading when trying to get into a race with AI ?

@madbad 
Yes in Fedora 29, it worked applying this option to true:
PROTON_NO_ESYNC=1

**Comment by leotada** [comment]
For me Logitech G27 not works the pedals right, only the wheel and without FF.

**Comment by leillo1975** [comment]
> For me Logitech G27 not works the pedals right, only the wheel and without FF.

What distro and Proton version you are using?

I would like to post here a link to a thread in the Project Cars 2 official Forums if you want to participate:

http://forum.projectcarsgame.com/showthread.php?65098-Multiplayer-with-Linux-Steam-Play-Proton

**Comment by leotada** [comment]
> > For me Logitech G27 not works the pedals right, only the wheel and without FF.
> 
> What distro and Proton version you are using?

Sorry, worked after I have configured manually all the triggers in the game. Fedora 29, 3.16.

**Comment by seibacks** [comment]
> One question, two days ago the game was updated, and now I don't have force feedback. Can you say me if yoy have the same issue?
> 
> Thanks

you can download the previous version of project cars 2 (in which the FFB was working) using this trick:

https://www.reddit.com/r/Steam/comments/611h5e/guide_how_to_download_older_versions_of_a_game_on/

I am really curious if is a game fault or a proton fault, let me know if that works for you

EDIT: in this case the download command should be:

`download_depot 378860 378861 4000032546361002812`

this should download the september 10 version of the game

**Comment by leillo1975** [comment]
> > One question, two days ago the game was updated, and now I don't have force feedback. Can you say me if yoy have the same issue?
> > Thanks
> 
> you can download the previous version of project cars 2 (in which the FFB was working) using this trick:
> 
> https://www.reddit.com/r/Steam/comments/611h5e/guide_how_to_download_older_versions_of_a_game_on/
> 
> I am really curious if is a game fault or a proton fault, let me know if that works for you
> 
> EDIT: in this case the download command should be:
> 
> `download_depot 378860 378861 4000032546361002812`
> 
> this should download the september 10 version of the game

I try to download it, but In don't have enought space in my home directory. I don't know If I could download it to another location (my games are in another disk)

**Comment by seibacks** [comment]
> > > One question, two days ago the game was updated, and now I don't have force feedback. Can you say me if yoy have the same issue?
> > > Thanks
> > 
> > 
> > you can download the previous version of project cars 2 (in which the FFB was working) using this trick:
> > https://www.reddit.com/r/Steam/comments/611h5e/guide_how_to_download_older_versions_of_a_game_on/
> > I am really curious if is a game fault or a proton fault, let me know if that works for you
> > EDIT: in this case the download command should be:
> > `download_depot 378860 378861 4000032546361002812`
> > this should download the september 10 version of the game
> 
> I try to download it, but In don't have enought space in my home directory. I don't know If I could download it to another location (my games are in another disk)

hhhmmm... maybe creating a symbolic link in the place where steam is downloading the content to a folder in your other disk???

**Comment by leillo1975** [comment]
> > One question, two days ago the game was updated, and now I don't have force feedback. Can you say me if yoy have the same issue?
> > Thanks
> 
> you can download the previous version of project cars 2 (in which the FFB was working) using this trick:
> 
> https://www.reddit.com/r/Steam/comments/611h5e/guide_how_to_download_older_versions_of_a_game_on/
> 
> I am really curious if is a game fault or a proton fault, let me know if that works for you
> 
> EDIT: in this case the download command should be:
> 
> `download_depot 378860 378861 4000032546361002812`
> 
> this should download the september 10 version of the game

IT WORKS!!!!!
With the previus version Force Feedback works fine. I think that Linux users should pressure PCars2 developers to make the game work again with a new patch. I made a thread on P.Cars forum to ask for this. Please show your support:
http://forum.projectcarsgame.com/showthread.php?65547-Broken-compatibility-with-F-Feedback-in-Steam-Play-Proton-(Linux)-with-latest-patch&p=1550570#post1550570

**Comment by seibacks** [comment]
> > > One question, two days ago the game was updated, and now I don't have force feedback. Can you say me if yoy have the same issue?
> > > Thanks
> > 
> > 
> > you can download the previous version of project cars 2 (in which the FFB was working) using this trick:
> > https://www.reddit.com/r/Steam/comments/611h5e/guide_how_to_download_older_versions_of_a_game_on/
> > I am really curious if is a game fault or a proton fault, let me know if that works for you
> > EDIT: in this case the download command should be:
> > `download_depot 378860 378861 4000032546361002812`
> > this should download the september 10 version of the game
> 
> IT WORKS!!!!!
> With the previus version Force Feedback works fine. I think that Linux users should pressure PCars2 developers to make the game work again with a new patch. I made a thread on P.Cars forum to ask for this. Please show your support:
> http://forum.projectcarsgame.com/showthread.php?65547-Broken-compatibility-with-F-Feedback-in-Steam-Play-Proton-(Linux)-with-latest-patch&p=1550570#post1550570

NICE !!!

Anyway I think valve can solve the issue through proton, the developers of PC2 are not going to make changes in the game because of a linux issue...



> Do anyone else also get stuck at 75% loading when trying to get into a race with AI ?

I had this problem with the demo version, and even some crashes, I fixed all these issues rising the FD limit:
https://forum.manjaro.org/t/increase-fd-limits-to-let-steam-play-works-reliably/56270

**Comment by madbad** [comment]
> > Do anyone else also get stuck at 75% loading when trying to get into a race with AI ?
> 
> I had this problem with the demo version, and even some crashes, I fixed all these issues rising the FD limit:
> https://forum.manjaro.org/t/increase-fd-limits-to-let-steam-play-works-reliably/56270

Great, this solved the problem for me.

Now the only issue remaining is the missing ForceFeedback (I will give a try on downloading the old pCars2 version since it was working with that).

**Comment by seibacks** [comment]
I can confirm it after buy the full game:

ForceFeedback working on Project cars 2 - 1.7.0.0

ForceFeedback NOT working on Project cars 2 - 1.7.1.0

**Comment by xpander69** [comment]
Same issue here. FFB doesn't work
log reveals that:

```
107214.718:002f:006d:err:dinput:effect_Download SDL_HapticNewEffect failed (Effect type 128): Haptic: Effect not supported by haptic device.
107214.734:002f:006d:err:dinput:effect_Download SDL_HapticNewEffect failed (Effect type 128): Haptic: Effect not supported by haptic device.
```
i tried to search what this effect type 128 is, but didnt find anything. I guess i have to downgrade to older version also. The Game works superbly other than that. Just need my FFB


edit: ok managed to downgrade to 2 months old version. FFB works great. What an enjoyable experience.
However like mentioned already, alt+tab will kill FFB again, have to restart the game.

the same Haptic Effect type 128 errors are still on the log, so that doesnt break the FFB on the newer version i guess, theres something else.

**Comment by seibacks** [comment]
There's a huge difference between playing with and without Force Feedback, for me is a mandatory feature...

I found this (related with dirt 4, but also with FFB): https://github.com/ValveSoftware/Proton/issues/992#issuecomment-441951034

Apparently in wine 3.20 it works, but it doesn't explain why is working with the previous version of PC2 and not with the latest... maybe is working with a specific implementation of FFB??? really weird...

**Comment by leillo1975** [comment]
> Apparently in wine 3.20 it works, but it doesn't explain why is working with the previous version of PC2 and not with the latest... maybe is working with a specific implementation of FFB??? really weird...

We'll have to wait for Proton to upgrade to version 3.20.

**Comment by wleoncio** [comment]
> I can confirm it after buy the full game:
> 
> ForceFeedback working on Project cars 2 - 1.7.0.0
> 
> ForceFeedback NOT working on Project cars 2 - 1.7.1.0

Came here to second this. On the other hand, online works with 1.7.1.0 and breaks with 1.7.0.0. I'd rather have FFB, so I'm keeping the game downgraded, but it sucks having to choose. Moreover, 1.7.0.0 crahes sometimes, either before the start screen or when starting an event. I am using Ubuntu 18.04, Nvidia GTX 650 Ti BOOST with proprietary drivers and a Logitech Driving Force GT wheel.

**Comment by kisak-valve** [comment]
Project Cars 2 photo mode not working

Issue transferred from https://github.com/ValveSoftware/Proton/issues/2217.
@wleoncio posted on 2019-01-14T16:43:15:

# Compatibility Report
- Name of the game with compatibility issues: Project Cars 2
- Steam AppID of the game: 378860

## System Information
- GPU: Nvidia GTX 650 Ti Boost
- Driver/LLVM version: nvidia 396.54
- Kernel version: 4.15.0-43-generic
- Proton version: 3.16-6 Beta
- System information gist: https://gist.github.com/wleoncio/39f777969041c7ee5cb2075e2294d683

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

Proton log gist: https://gist.github.com/wleoncio/41ad3c33d0459d54a95cbe312028ecbe

## Symptoms

Photo mode does not work

## Reproduction

1. Start the game and get on track (game mode doesn't matter)
2. Pause the game and choose "photo mode"
3. Try to take a photo by pressing "take photo" or pressing the left mouse button

(alternatively)
1. Start the game and go to "private testing", then "vehicle select"
2. Choose "Showroom" and "Photo mode"
3. Try to take a photo by pressing "take photo" or pressing the left mouse button

Instead of taking the photo, the game temporarily freezes, with the shutter sound repeating indefinitely. Pressing "Esc" goes back to "photo mode" and game can be played normally. Photo is not taken, as it won't show up in "My Profile / Images" and the "Snap snap snap" achievement for taking a photo doesn't pop up.
[steam-378860.log](https://github.com/ValveSoftware/Proton/files/2756122/steam-378860.log)
***
@wleoncio commented on 2019-01-14T17:05:15

I've also tried with nvidia driver 415.25 and game version 1.7.1 (OP using 1.7.0) with same results.

**Comment by Kreyren** [comment]
any ETA on force feedback?

**Comment by viggy96** [comment]
I haven't been able to launch the game recently, possibly due to a game update, though not sure of the cause. I'm running Ubuntu, Radeon VII GPU, and Padoka Stable Mesa. I've been able to run this game before on my setup.

**Comment by leillo1975** [comment]
Force Feedback stills not working with the last version of Proton (4.2)

**Comment by xpander69** [comment]
Yeah, confirming, no go with 4.2 for me either and no go with custom proton-tkg 4.4.r8  either. Something with native steam client killing the FFB? as the FFB works fine with regular wine 4.1 to 4.4

edit: Whoops wrong post. I was thinking its Dirt Rally 2.0 issue. Don't mind me. But probably both have similar issue anyway.

**Comment by leillo1975** [comment]
> Yeah, confirming, no go with 4.2 for me either and no go with custom proton-tkg 4.4.r8 either. Something with native steam client killing the FFB? as the FFB works fine with regular wine 4.1 to 4.4
> 
> edit: Whoops wrong post. I was thinking its Dirt Rally 2.0 issue. Don't mind me. But probably both have similar issue anyway.

@xpander69 , you have Force Feedback with Wine in this game?

**Comment by xpander69** [comment]
> > Yeah, confirming, no go with 4.2 for me either and no go with custom proton-tkg 4.4.r8 either. Something with native steam client killing the FFB? as the FFB works fine with regular wine 4.1 to 4.4
> > edit: Whoops wrong post. I was thinking its Dirt Rally 2.0 issue. Don't mind me. But probably both have similar issue anyway.
> 
> @xpander69 , you have Force Feedback with Wine in this game?

yes i had (with wine-staging 4.2). but i haven't tested now, i was posting in the wrong place, thinking it was Dirt Rally 2.0

**Comment by seibacks** [comment]
Same here, still no FFB with proton 4.2 on the latest version of the game.

Still works on the old version of the game.

**Comment by viggy96** [comment]
I get the following error in when trying to run Project Cars 2: 
```
>0 0x00007fe21036615b SDL_GL_UnloadLibrary+0xa9eb() in libsdl2-2.0.so.0 (0x00007fe21069e624)
0x00007fe21036615b SDL_GL_UnloadLibrary+0xa9eb in libsdl2-2.0.so.0: movzwl	0x0000000000000002(%rsi),%eax

```
The game runs fine when I run it with wine steam via Lutris.

**Comment by pipnina** [comment]
I just got PCars2 and can confirm that my Logitech G29 works with FFB in PCars1, but PCars2 it is broken. Though I have not noticed any other issues in the short time I've played.
I tried to use the steam console (by typing steam://open/console/ into my web browser) and downloading the older version, but it just says that it is downloading the package without queuing an actual download. Am I maybe doing something wrong?

**Comment by wleoncio** [comment]
> I tried to use the steam console (by typing steam://open/console/ into my web browser) and downloading the older version, but it just says that it is downloading the package without queuing an actual download. Am I maybe doing something wrong?

According to [the previously-mentioned source](https://www.reddit.com/r/Steam/comments/611h5e/guide_how_to_download_older_versions_of_a_game_on/) as well as my own experience, "[y]ou won't see any indication of [download] progress, but you can tell it's downloading by looking at the network usage on your downloads page". Do you see any download activity? Other than that and the occasional console message, you won't see any other indication that the game is downloading. There's no population of a download queue, but the download should be triggered.

**Comment by pipnina** [comment]
I've just looked in the game's files, and noticed dlls relating to Easy Anti-Cheat. Is there any risk of being banned in this game if I try to join an online lobby and the anti-cheat flips out? I've heard that EAC behaves very badly with WINE/Proton and would rather work on the safe side of things.

**Comment by wardbox** [comment]
The force feedback issue persists. I'm downgrading now to an old version to see if that works as well. Confirmed that Project Cars 1 force feedback works fine.

Using G920.

Update: Downgrade to recommended version of Project Cars 2 does return force feedback.  Unfortunately, it's still really light even on maximum settings.  In Project Cars 1 it is far more pronounced.

**Comment by viggy96** [comment]
@kisak-valve Here's a crash log for Project Cars 2. This game used to run with Proton, I don't know what happened. 
[steam-378860.log](https://github.com/ValveSoftware/Proton/files/3061105/steam-378860.log)

**Comment by ah-** [comment]
Still runs fine for me @viggy96

**Comment by pipnina** [comment]
Same. Runs fine for me as well @viggy96 . Maybe try re-downloading or making sure your system is up to date (and rebooting)?

**Comment by viggy96** [comment]
@ah- @pipnina @kisak-valve Reinstalling the game has no effect. However, I can run the game with wine steam via Lutris. The error appears to be something to do with the version of libsdl2 that Steam is loading.

**Comment by viggy96** [comment]
Same issue when using Proton 4.2-3. I've tried installing a backport libSDL2, version 2.0.9, from ppa:cybermax-dexter/sdl2-backport, but it didn't help.

**Comment by kisak-valve** [comment]
Ferrari FGT 3in1 not working in Project cars 2 (378860)

Issue transferred from https://github.com/ValveSoftware/Proton/issues/2560.
@s7relok posted on 2019-04-19T18:36:14:

# Compatibility Report
- Name of the game with compatibility issues: Project Cars 2
- Steam AppID of the game: 378860

## System Information
- GPU: 1070TI
- Driver/LLVM version: Proprietary Nvidia 418
- Kernel version: 4.18 ubuntu hwe
- Link to full system information report as [Gist](https://gist.github.com/): (not at home, can complete later, basically, up to date KDE neon 18.04 (ubuntu 18.04 with UTD KDE packages) with HWE stack installed, 8700k, 32GB RAM, 1070Ti with 418 proprietary driver, / installed on RAID 0 NVME SSDs and /home installed on a raid 0 SATA SSDs, linux  kernel 4.18)
- Proton version: 3.16

## I confirm:
- [X ] that I haven't found an existing compatibility report for this game. (not for this problem)
(game is working, and keyboard controls works well, not tested with controllers like xbox controller bc I don't have one)
- [X] that I have checked whether there are updates for my system available.



## Symptoms 
Thrustmaster Ferrari FGT 3in1 is not recognized correctly

## Reproduction

Plug the wheel, start the game, start a race. Depending of the controller options in steam, the wheel, pedal or both are not working. The wheel works well in native game like F1 2017 and perfectly recognized by the system (all axis and buttons working in the KDE controller test). Already tried calibration and controller management options in steam. No option gives acceptable behaviour (pedals, wheel or both have no action in game)

**Comment by viggy96** [comment]
@kisak-valve I think I've figured it out another bit of the issue I'm having. My Corsair mouse is being recognised by Steam as some sort of controller, you can see in the terminal output:

```
Local Device Found
  type: 1b1c 1b2e
  path: sdl://1
  serial_number:  - 0
  Manufacturer: 
  Product:      ckb1: Corsair Gaming M65 Pro RGB Mouse vKB
  Release:      306
  Interface:    -1

Local Device Found
  type: 1b1c 1b2e
  path: sdl://2
  serial_number:  - 0
  Manufacturer: 
  Product:      ckb1: Corsair Gaming M65 Pro RGB Mouse vM
  Release:      306
  Interface:    -1
```

When I don't have my Corsair gaming mouse plugged in, and just use a regular mouse, this game runs fine. It appears that we may need to blacklist some devices from being detected as "controllers" and being passed to the game as such.

**Comment by necrophcodr** [comment]
I can confirm that the FFB issue with latest version of Proton available in Steam and latest version of Project Cars 2 as of writing.

I've tried downgrading the game, however unfortunately that results in either the game hanging forever when loading a stage, or crashing to desktop entirely, both without any messages or log information to speak of, that differ from that of playing the latest version of the game without FFB.

This is with a Logitech G29 on Ubuntu 18.10.

**Comment by APersonH** [comment]
The game refuses to lauch for me, even when disabeling esync. Log: 
[steam-378860.log](https://github.com/ValveSoftware/Proton/files/3241175/steam-378860.log)

**Comment by kisak-valve** [comment]
Hello @APersonH, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

Does any vulkan application like `vulkaninfo` work? Your log hints that there is a video driver issue.
```
Xlib:  extension "NV-GLX" missing on display ":0".
err:vulkan:wine_vk_instance_load_physical_devices Failed to enumerate physical devices, res=-3
err:vulkan:wine_vkCreateInstance Failed to load physical devices, res=-3
```

**Comment by APersonH** [comment]
Gist: https://gist.github.com/APersonH/3eb9c00209eba1d0a066a27baed98803
vulkaninfo returns this:
```
andreas@Bob:~$ vulkaninfo
Xlib:  extension "NV-GLX" missing on display ":0".
"==========
VULKANINFO
"==========

Vulkan Instance Version: 1.1.101

/build/vulkan-tools-_xrZWD/vulkan-tools-1.1.101.0+dfsg1/vulkaninfo/vulkaninfo.c:5028: failed with VK_ERROR_INITIALIZATION_FAILED
```

**Comment by kisak-valve** [comment]
It's strange to see the xlib line, but in any case, please check that the `mesa-vulkan-drivers` and `mesa-vulkan-drivers:i386` packages are installed with something like `apt policy mesa-vulkan-drivers mesa-vulkan-drivers:i386` and install them with `sudo apt install mesa-vulkan-drivers mesa-vulkan-drivers:i386` if they are not installed.

**Comment by APersonH** [comment]
Thank you, this seems to have worked! :-)

**Comment by leillo1975** [comment]
with Proton 4.11-1 the FFB problem persists.

[steam-378860.log](https://github.com/ValveSoftware/Proton/files/3453407/steam-378860.log)

**Comment by petersmi** [comment]
I installed the demo last night with Proton 4.2-9, driving with a Logitech G920.  I was getting spring centering in the menus, but no FFB during play.  Checked out the hid debugging info from the kernel driver, and noticed that it was sending good force data, but the direction parameter was causing it to zero out.  I hacked out the angle calc in the driver, and FFB worked fine after that.  Tried the full game, and it's been working great(after setting nofile limit super high to get rid of hangs)

@leillo1975, is it recognizing your wheel at all?  I wasn't able to get a reliable steam-*.log when I was initially looking at this because of the eventfd issue and my nofile limit set too low, but when I was trying to get ACC to work, it had a lot more wheel info in the log than I see in yours.

The drivers for these wheels do seem rather poor, at least for the G920.  It looks like there was a fair bit of work recently on the hid-logitech-hidpp module, but it breaks FFB entirely on my wheel after kernel 5.2, not recognizing it as an HID++ device at all anymore.

**Comment by saipathuri** [comment]
@petersmi how did you change the angle calculation in the driver?

**Comment by petersmi** [comment]
in the hidpp_ff_upload_effect function in drivers/hid/hid-logitech-hidpp.c
under the FF_CONSTANT case
I commented out the line:
          force = (effect->u.constant.level * fixp_sin16((effect->direction * 360) >> 16)) >> 15;
and replaced it with
          force = force = effect->u.constant.level;
The direction value I get from PC2 was getting zero'd out by the sine.  Dividing direction by 2 works as well, but then other games would get reduced force.

I'm not sure where the real 'bug' is in the chain until it gets to this point.  My assumption is the windows drivers don't care about the angle for these wheels, and the games don't have to pass good values, but that's just a wild guess.  So for this driver, maybe there should be a HIDPP_QUIRK_CLASS_G920 test for this angle calc like there is in a few other places in the module.

I've been meaning to check out what this guy has been working on:
https://steamcommunity.com/groups/linuxff/discussions/0/405692224235574471
since my wheel is completely borked with kernel >=5.2.0, but haven't gotten around to it yet.

**Comment by mimattr** [comment]
# Compatibility Report

## System Information
- GPU: **RTX 2060**
- Driver/LLVM version: **NVIDIA 430.40**
- Kernel version: **5.0.0-25-generic**
- [Link to full system information report as Gist](https://gist.github.com/mimattr/b0b7f46366e31e254460b9593ce87e51)
- Proton version: **4.11-3**
- SteamVR version: **1.7.12**

## I confirm:
- [x] that I have checked whether there are updates for my system available.

[steam-378860.log](https://gist.github.com/mimattr/23393695858e995cc74a22987bcabafb) (dropped frames, application exit)
[steam-378860.log.zip](https://github.com/ValveSoftware/Proton/files/3562590/steam-378860.log.zip) (dropped frames, application freeze)
[vrcompositor.txt](https://gist.github.com/mimattr/219c602479442a46ddf6bed9cae74925)

## Symptoms
Consistent visual stuttering/dropped frames followed by application freeze at race start using **SteamVR**, unless manually exited within a few seconds (tested with **Valve Index Headset**)

![Screenshot](https://i.imgur.com/fB52E6u.png)

Note the incorrect frame times, perhaps this is related to [@Zamundaaa's report](https://github.com/ValveSoftware/SteamVR-for-Linux/issues/226)?

## Reproduction
1. Select the title within your `Library` using the Steam client and press the `Play` button
1. `Launch Project CARS 2 in Steam VR mode`
1. Select `QUICK PLAY` > `CUSTOM RACE` > `START` from the title screen and wait for the race to start

**Comment by guustflater** [comment]
> # Compatibility Report
> ## System Information
> * GPU: **RTX 2060**
> * Driver/LLVM version: **NVIDIA 430.40**
> * Kernel version: **5.0.0-25-generic**
> * [Link to full system information report as Gist](https://gist.github.com/mimattr/b0b7f46366e31e254460b9593ce87e51)
> * Proton version: **4.11-3**
> * SteamVR version: **1.7.12**
> 
> ## I confirm:
> * [x]  that I have checked whether there are updates for my system available.
> 
> [steam-378860.log](https://gist.github.com/mimattr/23393695858e995cc74a22987bcabafb) (dropped frames, application exit)
> [steam-378860.log.zip](https://github.com/ValveSoftware/Proton/files/3562590/steam-378860.log.zip) (dropped frames, application freeze)
> [vrcompositor.txt](https://gist.github.com/mimattr/219c602479442a46ddf6bed9cae74925)
> 
> ## Symptoms
> Consistent visual stuttering/dropped frames followed by application freeze at race start using **SteamVR**, unless manually exited within a few seconds (tested with **Valve Index Headset**)
> 
> ![Screenshot](https://camo.githubusercontent.com/6d1c26399885977171ca6aa54444b1de34e3060c/68747470733a2f2f692e696d6775722e636f6d2f664235324536752e706e67)
> 
> Note the incorrect frame times, perhaps this is related to [@Zamundaaa's report](https://github.com/ValveSoftware/SteamVR-for-Linux/issues/226)?
> 
> ## Reproduction
> 1. Select the title within your `Library` using the Steam client and press the `Play` button
> 2. `Launch Project CARS 2 in Steam VR mode`
> 3. Select `QUICK PLAY` > `CUSTOM RACE` > `START` from the title screen and wait for the race to start

VR doesn't crash for me but it's so slow that its unplayable on an AMD rx 580 with the latest valve mesa aco installed on Ubuntu 19.04 proton version 4.11-3 and the latest steam vr beta. The rest of the game works fine.

**Comment by Termuellinator** [comment]
i'm noticing that the steam client closes when exiting PC2 since the last two or three steam beta-updates. Haven't noticed it on other games. Can anybody confirm?

**Comment by StefanTT** [comment]
Force feedback is still broken on Arch with latest proton (4.11-7 ?).

VR with index works fine. Sometimes it has unusable stuttering, but after restarting Steam and the game it is fine again.

**Comment by leillo1975** [comment]
> Force feedback is still broken on Arch with latest proton (4.11-7 ?).
> 
> VR with index works fine. Sometimes it has unusable stuttering, but after restarting Steam and the game it is fine again.

Still broken for me too. What's your wheel model?
Since a few days there are a new project to collect ffb data from the wheels and games. It's a @berarma project, like [Oversteer](https://github.com/berarma/oversteer),  and it's called Ffbtools. You can find it here:
https://github.com/berarma/ffbtools

Its use is very easy, in the launch preferences of the Steam game you only have to write something like this:
`/home/user/ffbtools/bin/FfbLogIoCalls.sh /dev/input/eventX /home/user/FFBLog -- %command%`

**Comment by StefanTT** [comment]
I have a Logitech Driving Force GT.

Thank you for the hint with ffbtools, I found it after writing my comment. I will test it tonight or tomorrow. As the  fix in ffbtools already was reported to help in Dirt 2.0 I have hopes that it helps in my case too. I will report back here.

**Comment by mkasprzak** [comment]
I have tested Project Cars 2 + ffbtools + G29 today and it does not help. 
Log from FfbLogIoCalls.sh (1 min car drive, standard FFB settings):
000000000000: > IOCTL: Query force feedback features.
000000000037: 16, < Constant Gain Autocenter
000000111991: > IOCTL: Query force feedback features.
000000112002: 16, < Constant Gain Autocenter
000000112129: > IOCTL: Query force feedback features.
000000112135: 16, < Constant Gain Autocenter
000000112153: > IOCTL: Query force feedback features.
000000112155: 16, < Constant Gain Autocenter
000000112164: > IOCTL: Query force feedback features.
000000112167: 16, < Constant Gain Autocenter
000000112170: > IOCTL: Get maximum number of simultaneous effects in memory.
000000112173: < 0, effects: 16
000000113773: > WRITE: Set autocenter strength (0).
000000113793: < 24
000000113824: > WRITE: Set autocenter strength (0).
000000113830: < 24
000000365049: > WRITE: Set autocenter strength (0).
000000365065: < 24
000000365092: > WRITE: Set autocenter strength (0).
000000365100: < 24

**Comment by leillo1975** [comment]
I think I found a regression (@kisak-valve ) on the last version of Proton (4.11-7) with the force feedback feature. Today I downgrade **Project Cars 2** (https://github.com/ValveSoftware/Proton/issues/908#issuecomment-480472147) to the previous version before the October 2018 update.

With the last version, the ffb don't work, but downgrading to 4.2-9, 3.16-9 or 3.7.8 the feedback is back again. This problem is not only related to this game because I found that:
- **Project Cars 1** ( https://github.com/ValveSoftware/Proton/issues/244 ) has the same problem, and the ffb of this game was working in previous versions.
- **Wreckfest** ( https://github.com/ValveSoftware/Proton/issues/758 ) lost ffb and has problems with calibration. With 4.2-9 everything runs great.
- **GT Legends** ( https://github.com/ValveSoftware/Proton/issues/2728 ) only has ffb when you crash your car, but with 4.11-7 this effect is lost
- **RACE 07** ( https://github.com/ValveSoftware/Proton/issues/1212 ) has the same problem that GT Legends (same developer)

Please, take a look on this

Here is a Log of Project Cars 2 (downgraded) working with Force Feedback in proton 4.2-9:

```
000000000000: > IOCTL: Query force feedback features.
000000000065: 16, < Constant Gain Autocenter
000000087932: > IOCTL: Query force feedback features.
000000087951: 16, < Constant Gain Autocenter
000000088166: > IOCTL: Query force feedback features.
000000088177: 16, < Constant Gain Autocenter
000000088182: > IOCTL: Query force feedback features.
000000088188: 16, < Constant Gain Autocenter
000000088209: > IOCTL: Query force feedback features.
000000088215: 16, < Constant Gain Autocenter
000000088220: > IOCTL: Get maximum number of simultaneous effects in memory.
000000088226: < 0, effects: 16
000000120424: > IOCTL: Query force feedback features.
000000120453: 16, < Constant Gain Autocenter
000000120480: > IOCTL: Query force feedback features.
000000120485: 16, < Constant Gain Autocenter
000000120496: > IOCTL: Query force feedback features.
000000120501: 16, < Constant Gain Autocenter
000000120504: > IOCTL: Get maximum number of simultaneous effects in memory.
000000120508: < 0, effects: 16
000000120624: > WRITE: Set autocenter strength (0).
000000120646: < 24
000000120696: > WRITE: Set autocenter strength (0).
000000120714: < 24
000000415225: > IOCTL: Query force feedback features.
000000415245: 16, < Constant Gain Autocenter
000000415272: > IOCTL: Query force feedback features.
000000415276: 16, < Constant Gain Autocenter
000000415287: > IOCTL: Query force feedback features.
000000415291: 16, < Constant Gain Autocenter
000000415295: > IOCTL: Get maximum number of simultaneous effects in memory.
000000415299: < 0, effects: 16
000000415382: > WRITE: Set autocenter strength (0).
000000415397: < 24
000000415457: > WRITE: Set autocenter strength (0).
000000415468: < 24
000034371281: > IOCTL: Upload effect to device id: -1 dir: 90 type: FF_CONSTANT, trigger(button:302, interval:32767), replay(length:0, delay:0), params: { level:0, attack_length:0, attack_level:0, fade_length:0, fade_level:0 }
000034371302: < 0, id: 0
000034375572: > WRITE: Play effect (Id: 0,  2147483647)
000034375624: < 24
000037812777: > IOCTL: Upload effect to device id: -1 dir: 90 type: FF_CONSTANT, trigger(button:302, interval:32767), replay(length:0, delay:0), params: { level:0, attack_length:0, attack_level:0, fade_length:0, fade_level:0 }
000037812797: < 0, id: 0
000037819380: > WRITE: Play effect (Id: 0,  2147483647)
000037819449: < 24
000042553391: > IOCTL: Upload effect to device id: 0 dir: 90 type: FF_CONSTANT, trigger(button:302, interval:32767), replay(length:0, delay:0), params: { level:2536, attack_length:0, attack_level:0, fade_length:0, fade_level:0 }
000042553435: < 0, id: 0
000042557657: > IOCTL: Upload effect to device id: 0 dir: 90 type: FF_CONSTANT, trigger(button:302, interval:32767), replay(length:0, delay:0), params: { level:-8736, attack_length:0, attack_level:0, fade_length:0, fade_level:0 }
000042557821: < 0, id: 0
000042562054: > IOCTL: Upload effect to device id: 0 dir: 90 type: FF_CONSTANT, trigger(button:302, interval:32767), replay(length:0, delay:0), params: { level:-7900, attack_length:0, attack_level:0, fade_length:0, fade_level:0 }
000042562079: < 0, id: 0
000042566488: > IOCTL: Upload effect to device id: 0 dir: 90 type: FF_CONSTANT, trigger(button:302, interval:32767), replay(length:0, delay:0), params: { level:-7271, attack_length:0, attack_level:0, fade_length:0, fade_level:0 }
000042566517: < 0, id: 0
000042570943: > IOCTL: Upload effect to device id: 0 dir: 90 type: FF_CONSTANT, trigger(button:302, interval:32767), replay(length:0, delay:0), params: { level:-5898, attack_length:0, attack_level:0, fade_length:0, fade_level:0 }
000042570970: < 0, id: 0
000042575276: > IOCTL: Upload effect to device id: 0 dir: 90 type: FF_CONSTANT, trigger(button:302, interval:32767), replay(length:0, delay:0), params: { level:-4741, attack_length:0, attack_level:0, fade_length:0, fade_level:0 }
000042575304: < 0, id: 0
000042579613: > IOCTL: Upload effect to device id: 0 dir: 90 type: FF_CONSTANT, trigger(button:302, interval:32767), replay(length:0, delay:0), params: { level:-3988, attack_length:0, attack_level:0, fade_length:0, fade_level:0 }
000042579650: < 0, id: 0
000042583827: > IOCTL: Upload effect to device id: 0 dir: 90 type: FF_CONSTANT, trigger(button:302, interval:32767), replay(length:0, delay:0), params: { level:-3133, attack_length:0, attack_level:0, fade_length:0, fade_level:0 }
000042583864: < 0, id: 0
000042588709: > IOCTL: Upload effect to device id: 0 dir: 90 type: FF_CONSTANT, trigger(button:302, interval:32767), replay(length:0, delay:0), params: { level:-501, attack_length:0, attack_level:0, fade_length:0, fade_level:0 }
000042588736: < 0, id: 0
.
.
.......
[FFBLogPC2-4.2-9.log](https://github.com/ValveSoftware/Proton/files/3736103/FFBLogPC2-4.2-9.log)

```

**Comment by StefanTT** [comment]
Here is my log output of Project Cars 2 with Proton 4.11-7
```
000000188520: > IOCTL: Get maximum number of simultaneous effects in memory.
000000188522: < 0, effects: 16
000000189498: > WRITE: Set autocenter strength (0).
000000189508: < 24
000000189534: > WRITE: Set autocenter strength (0).
000000189537: < 24
000000440264: > WRITE: Set autocenter strength (0).
000000440280: < 24
000000440301: > WRITE: Set autocenter strength (0).
000000440304: < 24
```
Force feedback is still disabled when using the fix script.
Switching to Proton 4.2-9 does not help.

**Comment by leillo1975** [comment]
Ffb only works on the downgraded version of Pcars2

**Comment by mkasprzak** [comment]
I confirm what @leillo1975 discovered. Downgrade of Project Cars 2 (steam console: download_depot 378860 378861 4000032546361002812) + downgrade of Proton to version 4.2-9 fixes/enables FFB on G29.

**Comment by berarma** [comment]
I've found what the problem is with the latest versions of the game. The FFB effects sent have a direction vector. The Logitech driver scales the level of the effect using the horizontal component of that vector and ignoring the vertical component. The latest versions of the game send effects with a vector pointing down (180º), thus with a null horizontal component. This cancels the effect.

I'm not sure where the problem is. It seems like the direction vector was originally implemented with joysticks in mind, and it has been implemented for wheels in a way that Proton or maybe the games were not expecting. We should maybe look at what Proton is doing, or maybe review what this direction vector should be doing. There's no API documentation that I know of explaining how this direction vector should work for wheels.

I've implemented a workaround to show how FFB starts working when the direction vector is changed from 180º to 90º. You can find it at https://gihub.com/berarma/ffbtools. The command to launch the game should be (changing the device path if needed):

`ffbwrap --direction-fix /dev/input/by-id/usb-Logitech_G29_Driving_Force_Racing_Wheel-event-joystick -- %command%`

This is not a proper fix. We need to understand what's wrong and fix it either in Proton or the kernel driver.

**Comment by leillo1975** [comment]
I can confirm that last version of Project Cars 2 with Proton 4.2-9 works with the @berarma fix, and is really great. Now is not needed to downgrade the game. Thanks a lot again. You fixed Dirt Rally 2 some days ago, and now this game.

**Comment by berarma** [comment]
@petersmi I just read your comment. We've reached the same conclusion and implemented a similar workaround. There seems to be no one that is aware of these problems. Someone will have to step forward and do the work to document the API and fix bugs. You can join us if you want to. See my comment above.

**Comment by StefanTT** [comment]
Yep, downgrade, proton 4.2-9, and the FfbFixUpdate.sh are required to get consistent force feedback.

**Comment by mkasprzak** [comment]
I updated PC 2 to newest version and tried to use @berarma  ffbwrap to fix FFB (still using Proton 4.2-9), does not work for me.
Code location:
 /home/mkasprza/Projects/ffbtools/
Build cmd:
~/Projects/ffbtools$ make -j6
My "SET LAUNCH OPTIONS...": /home/mkasprza/Projects/ffbtools/bin/ffbwrap --direction-fix /dev/input/by-id/usb-Logitech_G29_Driving_Force_Racing_Wheel-event-joystick -- %command%
I'm missing something  ?

**Comment by leillo1975** [comment]
I don't see nothing strange. I suppose that your wheel is a G29...

What's the terminal output when you compile ffbtools?

**Comment by mkasprzak** [comment]
I was missing gcc-multilib and libffbwrapper-i386.so failed to build. Everything works now :D

**Comment by vhakulinen** [comment]
ffbtools makes force feedback work on pc2 here too (with proton 4.2-9).

**Comment by leillo1975** [comment]
New version of Proton (4.11-8) stills breaking Force Feedback in a lot of racing games. With ffbtools don't work.
Other games like:
[-Project Cars 1](https://github.com/ValveSoftware/Proton/issues/244)
[-RACE 07](https://github.com/ValveSoftware/Proton/issues/1212)
[-GT Legends](https://github.com/ValveSoftware/Proton/issues/2728)


https://github.com/ValveSoftware/Proton/issues/3194

**Comment by nelg** [comment]
I can also confirm that compiling @berarma's fix and setting `ffbwrap --direction-fix /dev/input/by-id/usb-Logitech_G29_Driving_Force_Racing_Wheel-event-joystick -- %command% ` in the launch options made it work for me.

**Comment by jakub-pluciennik** [comment]
@berarma Thank you, thank you, and once again thanks! :) I can confirm, that your fix is working with Project Cars 2 on Ubuntu 18.04 with Proton 4.11.9. I am using Logitech_Driving_Force_Pro :+1:

**Comment by SilverLuke** [comment]
I have a problem with my G29 using Proton 4.11.9 and the @berarma's fix.
The force feedback works good, but the "rev lights" on the steering wheel don't work.
I can turn on the lights using `echo 1 > /sys/bus/hid/drivers/logitech/<id>/leds/<id>::RPM<number 1-5>/brightness`, but when I play the lights don't work.

**Comment by berarma** [comment]
@SilverLuke There's no way to make the leds work. It's not implemented in Wine nor Proton.

**Comment by leillo1975** [comment]
With the last version of proton (4.11-10), the game has a good Force Feedback. Good Work!

Now you just have to fix it when you do Alt-Tab and go back to the game. It hangs and the screen remains black.

**Comment by wleoncio** [comment]
> With the last version of proton (4.11-10), the game has a good Force Feedback. Good Work!

Wait, does this mean FFB works out-of-the-box, now? No need to keep PC2 downgraded?

**Comment by vhakulinen** [comment]
Worked for me.

**Comment by leillo1975** [comment]
> > With the last version of proton (4.11-10), the game has a good Force Feedback. Good Work!
> 
> Wait, does this mean FFB works out-of-the-box, now? No need to keep PC2 downgraded?

Yes, absolutely (thanks @berarma )

**Comment by StefanTT** [comment]
Works fine for me with 4.11-10, the latest version of PC2, a DF-GT wheel, and the modified logitech kernel driver (from ... berama?). Did not test it with the vanilla kernel driver.

**Comment by leillo1975** [comment]
> Works fine for me with 4.11-10, the latest version of PC2, a DF-GT wheel, and the modified logitech kernel driver (from ... berama?). Did not test it with the vanilla kernel driver.

I think you don't need to install the @berarma [driver module for kernel](https://github.com/berarma/new-lg4ff) for this game, but if you want to play games like [rFactor2](https://github.com/ValveSoftware/Proton/issues/245), [Automobilista](https://github.com/ValveSoftware/Proton/issues/246) or [RACE 07](https://github.com/ValveSoftware/Proton/issues/1212) (and [more](https://github.com/ValveSoftware/Proton/issues/3194)), you must use it to get Force Feedback, because this driver activates a lot of effects that are used by this games.

**Comment by vhakulinen** [comment]
PC2 has working force feedback without ffbtools or any extra kernel modules (for me at least). Running Ubuntu 18.04 (with padoka PPA).

**Comment by leillo1975** [comment]
When I said "thanks @berarma", on this occasion it was not for creating the new driver, but because [he was involved in the resolution of this and another FFB issues.](https://github.com/ValveSoftware/wine/pull/70)

**Comment by leillo1975** [comment]
I don't know if in other message of this thread this problem was posted, but if you do an Alt-Tab, the game hangs in a Black Screen.

**Comment by StefanTT** [comment]
@leillo1975:  %command% -windowed -borderless

**Comment by StefanTT** [comment]
Unfortunately VR is broken for me with proton-4.11-11, it hangs /crashes when entering the car when the track is loaded.

Anybody else experienced this problem?

It worked with 4.11-10. Unfortunately I do not have this version at hands to double check, but it still works with 4.2.9. The GE builds usually fail to initialize the graphics device when selecting VR upon game start. So I am a bit lost here at the moment.

**Comment by kisak-valve** [comment]
Hello @StefanTT, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options, reproduce the crash, and drag and drop the generated $HOME/steam-$APPID.log into the comment box.

**Comment by StefanTT** [comment]
[steam-378860.log](https://github.com/ValveSoftware/Proton/files/3989687/steam-378860.log)
I have added lines where the race track is being loaded and where I killed the program.

What I noticed is that SteamVR sometimes shows a popup that it has crashed. Only sometimes because most of the desktop hangs at this moment and I have to start my magic kill script to fix it.

System is 5.4.5-arch1-1, nvidia 440.44-4, SteamVR beta 1.9.15.

_Edit_: using the non-beta branch of SteamVR (which is also 1.9.15) does not make a difference
_Edit 2_: using the linux_temp branch of SteamVR (1.8.21) also does not help

**Comment by azampatti** [comment]
Good work on getting this included to the official supported branch!
I've swapped the proton to 4.11-11 and removed all the FFBWRAP commands and it's working almost perfect.

"Almost" due to one issue I'm experiencing, maybe there's a way that can be fixed or worked around.

I run PCARS2 with "borderless" option (simulating full screen) as it helps with OBS performance, but I found that every time I Alt-TAB out of the game, when I come back, FFB stops working.

Any suggestions for me to try to workaround this issue?

thanks!

**Comment by leillo1975** [comment]
> Good work on getting this included to the official supported branch!
> I've swapped the proton to 4.11-11 and removed all the FFBWRAP commands and it's working almost perfect.

Give thanks to @berarma, the creator of [Oversteer](https://github.com/berarma/oversteer), [ffbtools](https://github.com/berarma/ffbtools) and [new-lg4ff](https://github.com/berarma/new-lg4ff), for help proton devs to [fix](https://github.com/ValveSoftware/wine/pull/70) the ffb.

**Comment by StefanTT** [comment]
Quick note: VR is still broken with proton-4.11-12 and SteamVR beta 10.10.2
(see my messages above for details)

**Comment by mimattr** [comment]
> Quick note: VR is still broken with proton-4.11-12 and SteamVR beta 10.10.2

Also experiencing VR issues, reported on the [DXVK tracker](https://github.com/doitsujin/dxvk/issues/1333)

**Comment by mimattr** [comment]
> VR is still broken with proton-4.11-12 and SteamVR beta 10.10.2

@StefanTT Also experiencing VR issues, reported on the [DXVK tracker](https://github.com/doitsujin/dxvk/issues/1333)

**Comment by kisak-valve** [comment]
[BUG] Project Cars 2 freezes loading into a race

Issue transferred from https://github.com/ValveSoftware/SteamVR-for-Linux/issues/325.
@kalrach posted on 2020-04-05T03:35:06:

Description:
When attempting to load into a custom race, Project Cars 2 will load into the cockpit but then freeze unable to take any additional input. The only way to exit is to hit [Alt]-[F4] or kill the application. In some instances the game causes SteamVR itself to crash with a prompt saying that the minimum SteamVR version required is SteamVR version 1.10.1.

To Reproduce:
Attempt to load any custom race in Project Cars 2 in VR mode. Once loaded in the game will render the initial cockpit view and then freeze, not being able to take any further inputs requiring user intervention to kill the application or for the game to crash and take SteamVR with it.

System Information:
- uname -a Output: Linux helius 5.5.13-1-MANJARO #1 SMP PREEMPT Wed Mar 25 17:14:28 UTC 2020 x86_64 GNU/Linux
- Distribution: Manjaro
- SteamVR version: 1.10.32
- Steam client version:  steam-runtime_0.20200318.2
- Opted into Steam client beta?: No
- CPU: Intel Core i9-9900K
- GPU: NVIDIA RTX2080
- Ram: 16GB
- Graphics driver version: NVIDIA  440.64
- Gist for SteamVR System Information: https://gist.github.com/kalrach/2d2c5e3a17b69f926ef252a024ffb25a

Additional Notes:
The game menu only shows up on the flat monitor and requires the user to control the game from the flat monitor. Attempts to control the game from SteamVR desktop view also causes the game to freeze and crash.

**Comment by StefanTT** [comment]
It works for me when I use Proton 4.2.9. However, this version requires an older version of Project Cars 2. See above in this thread for how to downgrade the game.

SteamVR desktop view does not work anywhere / anytime, AFAIK. At least for me.

**Comment by leillo1975** [comment]
> It works for me when I use Proton 4.2.9. However, this version requires an older version of Project Cars 2. See above in this thread for how to downgrade the game.

I can't say nothing about VR, because I don't own a headset, but sometime ago is not needed to downgrade the game, and since Proton 4.11-10 FFB is fixed.

**Comment by StefanTT** [comment]
4.2.9 needs the downgrade, from 4.11 on you do not need it. Unfortunately pcars2 VR is broken for me too since 4.11.

**Comment by mimattr** [comment]
> When attempting to load into a custom race, Project Cars 2 will load into the cockpit but then freeze unable to take any additional input. The only way to exit is to hit [Alt]-[F4] or kill the application.

Confirmed, this behaviour is also consistent with **Automobilista 2** #3748 (both using [MADNESS Engine](https://www.slightlymadstudios.com/madness))

> The game menu only shows up on the flat monitor and requires the user to control the game from the flat monitor.

Confirmed, as above and also reported on the [DXVK issue tracker](https://github.com/doitsujin/dxvk/issues/1333#issuecomment-575601837)

Hopefully @aeikum can shed some light on this long-standing issue?

## System Information
- GPU: **RTX 2060**
- Driver/LLVM version: **NVIDIA 440.82**
- Kernel version: **5.3.0-46-generic**
- [Link to full system information report as Gist](https://gist.github.com/mimattr/b0b7f46366e31e254460b9593ce87e51)
- Proton version: **5.0-6 RC3**
- SteamVR version: **1.11.7**

## I confirm:
- [x] that I have checked whether there are updates for my system available.

* [steam-378860.ubuntu1910_steamvr.log](https://github.com/ValveSoftware/Proton/files/4464208/steam-378860.ubuntu1910_steamvr.log) (SteamVR issue)
* [steam-378860.ubuntu1910.log](https://github.com/ValveSoftware/Proton/files/4464209/steam-378860.ubuntu1910.log) (works as expected)

## Reproduction
1. Select the title within your `Library` using the Steam client and press the `Play` button
1. `Launch Project CARS 2 in Steam VR mode`
1. Select `QUICK PLAY` > `CUSTOM RACE` > `START` from the title screen and wait for the race to start

**Comment by ghost** [comment]
# Compatibility Report
- Name of the game with compatibility issues: Project CARS 2
- Steam AppID of the game: 378860

## System Information
- GPU: RX 570
- Driver/LLVM version: 4.6 (Compatibility Profile) Mesa 20.0.4
- Kernel version: 5.4.0-33-generic
- Link to full system information report as [Gist](https://gist.github.com/):https://gist.github.com/meta-level/0ad564020e65750c34ae5fa2c653cda9
- Proton version: Proton-5.0-7

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.
[steam-378860.log](https://github.com/ValveSoftware/Proton/files/4731356/steam-378860.log)



## Symptoms 
Game doesn't start at all.

## Reproduction
1. Go to the Library
2. Click the Play button
3. Select 'Play Project CARS 2'

**Comment by ManoaNosea** [comment]
for some reason I don't have FFB in this game with new-lg4ff, same thing with automobilista 2, wine control show the effects but in the games there is nothing :x
in GRID and F1 2010 it working no problem

**Comment by berarma** [comment]
> for some reason I don't have FFB in this game with new-lg4ff, same thing with automobilista 2, wine control show the effects but in the games there is nothing :x
> in GRID and F1 2010 it working no problem

Which Proton version are you using? You should try with the latest.

**Comment by ManoaNosea** [comment]
5.0-5, wine 5.5, kerenal 5.5.5, slackware 14.1, driving force GT, nvidea 440.64, 780 Ti, Xorg 1.20.8

**Comment by ManoaNosea** [comment]
also tested 5.0-3 with wine 5.2 same problem :x
tested DXVK several versions like 1.6.1, 1.7 no changes (I guess not suposed to be becuase DXVK only doing the graphics)

**Comment by StefanTT** [comment]
@kisak-valve is there any chance to get a Proton 4.11-10 version from somewhere?
Because this is the last version where the game worked in VR (without downgrading the game)
Downgrading Proton with steamcmd does not work, it reports the manifests as not available.

It is still one of the best racing games in VR. I have to play the old version which tends to crash regularily between races. I would really appreciate the help (and others probably too).

**Comment by wleoncio** [comment]
> @kisak-valve is there any chance to get a Proton 4.11-10 version from somewhere?

You can get the source code [here](https://github.com/ValveSoftware/Proton/releases/tag/proton-4.11-10); it contains a README file with building instructions. I'll try that myself ASAP, can barely wait to test PC2 with opentrack! :crossed_fingers:

**Comment by StefanTT** [comment]
Thanks @wleoncio. I already tried it. Unfortunately it did not work. Building the current 5.0.x version works fine but I did not get 4.11-10 to build. Please report back - or contact me directly - if you succeed in building it.

**Comment by StefanTT** [comment]
For those who is coming here to download the old version of pcars2 to get VR running: the version is no longer available for download - this does not work anymore: download_depot 378860 378861 4000032546361002812

@wleoncio did you succeed in compiling 4.11-10 ?

**Comment by wleoncio** [comment]
> @wleoncio did you succeed in compiling 4.11-10 ?

Sorry, no news on my side. I didn't try compiling yet, but I did find time to try a couple of builds from https://github.com/GloriousEggroll/proton-ge-custom. No dice.

**Comment by mimattr** [comment]
@kalrach @StefanTT Can also confirm this application still fails to launch successfully and now crashes SteamVR during the initial _"Namco Bandai"_ loading/startup screen and requires a Force Quit (`Alt` + `F4`)

## System Information
- GPU: **RTX 2060**
- Driver/LLVM version: **NVIDIA 455.38**
- Kernel version: **5.4.0-53-generic**
- [Link to full system information report as Gist](https://gist.github.com/mimattr/b0b7f46366e31e254460b9593ce87e51)
- Proton version: **5.13-2 RC3**
- SteamVR version: **1.15.7**

## I confirm:
- [x] that I have checked whether there are updates for my system available.

[steam-378860.log](https://github.com/ValveSoftware/Proton/files/5539289/steam-378860.log)

## Reproduction
1. Select the title within your `Library` using the Steam client and press the `Play` button
1. `Launch Project CARS 2 in Steam VR mode`

**Comment by kisak-valve** [comment]
Pacing issue with Project Cars 2 (id 378860)

Issue transferred from https://github.com/ValveSoftware/Proton/issues/4537.
@RalfVB posted on 2021-01-11T15:28:08:



CPU: i7
RAM: 16Gb
GPU: GTX1050ti (driver version 460.32.03)
Proton: 5.13-4

I've never been able to get the game running smoothly. I set all the graphics options to the lowest possible and disabled all post processing effects. I also tried using libstrangle to enforce 60fps, with didn't help.

What happens is that, every 10 seconds or so, the game goes into 'slow motion' for a couple of seconds, and then 'catches up' by going very fast briefly, making the game very difficult to play.

The game has a platinum rating on ProtonDB, and a friend (with comparable specs) is able to run the game just fine as well.

Perhaps anyone else is experiencing the same issue?

**Comment by leillo1975** [comment]
For me the game works perfect. I only have to say that with the 460.32.03 driver, I have problems with [rFactor 2](https://github.com/ValveSoftware/Proton/issues/245#issuecomment-757020531), giving me very low framerates. Changing to 450, everything works as usual.
Do you had the same problem with other nvidia driver versions?

**Comment by ghost** [comment]
Yes, I've had the game for a while now and upgraded my drivers several times since then.

In the meantime I found [this](https://steamcommunity.com/app/378860/discussions/1/1520386297685743221/?l=portuguese&ctp=2) - it describes the exact same problem on near-exact same specs, and proposes a solution. I'll try this and let you know if this solved it.

**Comment by ghost** [comment]
So the solution proposed is to use the -fpscap command line option. I've tried several values. Using -fpscap 30 with the lowest possible graphics settings, the problem appears to be entirely gone, but it doesn't make for a very nice experience, obviously.

Increasing the graphics quality moderately reintroduces the problem, so there's not much left for me to do except conclude that the game just doesn't like my particular hardware configuration. Oh well.

**Comment by azampatti** [comment]
> So the solution proposed is to use the -fpscap command line option. I've tried several values. Using -fpscap 30 with the lowest possible graphics settings, the problem appears to be entirely gone, but it doesn't make for a very nice experience, obviously.
> 
> Increasing the graphics quality moderately reintroduces the problem, so there's not much left for me to do except conclude that the game just doesn't like my particular hardware configuration. Oh well.

Do you have vSync enabled? If so, try disabling it and run it without -fpscap

**Comment by dllu** [comment]
I am finding that Project Cars 2 is completely stuck at the Bandai Namco loading screen in SteamVR mode (with Valve Index) with NVIDIA RTX 3090. On the other hand it worked fine a few weeks ago in VR with AMD Radeon RX 6800 (see: [my protondb review](https://www.protondb.com/app/378860#PFXiUg1gX2)). It also seems to work without VR, at least loading into the main menus without problems (I haven't tried a race yet). It seems the regression is either due to nvidia drivers or, less likely, a change in the proton version used.

Relevant hardware info (as you can see I am on Arch Linux with the latest nvidia drivers 465.27):

```
Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Ryzen 9 3900X 12-Core Processor            
[... skipped ...]
Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.12.1-arch1-1
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12011000
    X Window Manager:  i3
    Steam Runtime Version:  steam-runtime_0.20210317.0

Video Card:
    Driver:  NVIDIA Corporation NVIDIA GeForce RTX 3090/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 465.27
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x2204
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  3840 x 2160
    Desktop Resolution: 3840 x 2160
    Primary Display Size: 23.62" x 13.39" (27.13" diag)
                                            60.0cm x 34.0cm (68.9cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 24576 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
```

I have verified the integrity of all game files. If someone can help me out that would be greatly appreciated.

**Comment by mimattr** [comment]
> I am finding that Project Cars 2 is completely stuck at the Bandai Namco loading screen in SteamVR mode

@dllu Can you launch the game using `PROTON_LOG=1 %command%` and provide the generated `$HOME/steam-378860.log` file to help diagnose the issue?

Thanks

**Comment by dllu** [comment]
Here is the error log: [steam-378860.log](https://github.com/ValveSoftware/Proton/files/6481489/steam-378860.log)

This time it was displaying Slightly Mad Studios when it hung.

**Comment by kisak-valve** [comment]
Project Cars 2, Steam says running but game does not launch.

Issue transferred from https://github.com/ValveSoftware/Proton/issues/5038.
@azsxwazsx posted on 2021-08-01T09:14:43:

# Compatibility Report
- Name of the game with compatibility issues: Project Cars 2
- Steam AppID of the game: 378860

## System Information
- GPU: AMD RX 580
- Driver/LLVM version: 4.6 (Compatibility Profile) Mesa 21.1.5, amdgpu
- Kernel version: 5.10.53-1
- Link to full system information report: 
      https://gist.github.com/azsxwazsx/43c2d12de121c14a4e58dc151994727c
- Proton version: proton 6.3-5, proton 5.13-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.


## Symptoms 
After pressing the start/launch, steam shows the game launched and running, but actually the game did not launch at all.
No crash, no error,no window, no nothing. Only steam says the game is running.
Here is the log:
[steam-378860.log](https://github.com/ValveSoftware/Proton/files/6912411/steam-378860.log)


## Reproduction
Install the game and launch.

Everyone says the game works out of the box and I cannot find related discussion my problem.

**Comment by leillo1975** [comment]
In the last Proton Experimental, there are a fix for Alt-Tab issue for [Project Cars 3](https://github.com/ValveSoftware/Proton/issues/4888). This game uses the same engine (Madness) that [Automobilista 2](https://github.com/ValveSoftware/Proton/issues/3748) and this game


Using Proton Experimental, and a Logitech G29 with new-lg4ff, after doing Alt-Tab, the game reacts to the wheel, but it looses a lot of effects, and seems there are not FFB (if you move the wheel quckly you feel the counter-steer). Same problem in Automobilista 2.
@aeikum

**Comment by cain05** [comment]
> In the last Proton Experimental, there are a fix for Alt-Tab issue for [Project Cars 3](https://github.com/ValveSoftware/Proton/issues/4888). This game uses the same engine (Madness) that [Automobilista 2](https://github.com/ValveSoftware/Proton/issues/3748) and this game
> 
> Using Proton Experimental, and a Logitech G29 with new-lg4ff, after doing Alt-Tab, the game reacts to the wheel, but it looses a lot of effects, and seems there are not FFB (if you move the wheel quckly you feel the counter-steer). Same problem in Automobilista 2. @aeikum

I think there's something wonky with FFB in general with this game and Proton.  I tried Proton Experimental today with my G920 and the FFB didn't feel right at all, felt like it was randomly pulling to one side or the other.  I stopped my car with the brake and clutch in and the wheel started spinning all the way one way, then all the way the other and keep repeating that pattern indefinitely.  Game is pretty much unplayable because of this.

**Comment by kisak-valve** [comment]
Project Cars 2 no FFB Logitech G27

Issue transferred from https://github.com/ValveSoftware/Proton/issues/10101.
@ricktimmis posted on 2026-08-28T16:44:54:

# Compatibility Report
- Project Cars 2
- Steam AppID of the game: 378860

## System Information
- Steam Machine - SteamOS 3.8.16 Build: 20260716.1
- Video driver version: 
- Kernel version: 6.16.12-valve24.5-1-neptune-616-gb2f7cfe85e45 (64bit~)
- Proton version: Stock version with the machine, I think it's 11.02

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.



## Symptoms 

No Force Feedback at all. 

hardware: Logitech G27 plus separate pedals, wheel works in American Truck Simulator.

Two, the smoking-gun log lines:
- HID joystick device usage FB not implemented, and the repeating fixme:dinput:dinput_device_Escape ... stub!

Already tried: Proton versions 7.0-4, 8.0, 9.0, Hot Fix, Experimental. 

PROTON_DISABLE_HIDRAW=1, in-game Legacy mode, recalibration. Input works, FFB does not.

I checked lsmod and  lg4ff is not loaded, but hid_logitech plus ff_memless are.

## Reproduction

New Steam Machine, Logitech G27 and Project Cars 2 - The same is true for Project Cars as well

**Comment by ricktimmis** [comment]
I installed Automobilista2 in an attempt to get a racing game with FFB working on my NEW Steam Machine. Unfortunately I got exactly  the same result as my prior post above. https://github.com/ValveSoftware/Proton/issues/908#issuecomment-5455362675 

Now, on my KFocus Kubuntu Machine with Steam both these games work perfectly, and that includes FFB. On that machine I have the new-lg4ff kernel module installed. 

Logs for Automobilista2 report very similar dinput issues, and I am speculating its the lack of lg4ff module that is the cause.

```
29631.618:0180:01f8:fixme:dinput:dinput_device_Escape iface 000000000C078080, escape 000000003347FC08 stub!
29631.620:0180:02fc:trace:seh:dispatch_exception rip=00006fffffbfd947 rsp=000000005c4ffd80 rbp=0000000000000000 eflags=00000202
29631.620:0180:02fc:trace:unwind:RtlVirtualUnwind2 type 1 base 6fffffbf0000 rip 6fffffbfd947 rva d947 rsp 5c4ffd80
29631.651:0180:01f8:fixme:dinput:dinput_device_Escape iface 000000000C078080, escape 000000003347FC08 stub!
29631.696:0180:01f8:fixme:dinput:dinput_device_Escape iface 000000000C078080, escape 000000003347FC08 stub!
29632.087:0180:0184:fixme:dinput:dinput_device_Escape iface 000000000C078080, escape 000000000010FA18 stub!
```

I didn't know, or couldn't find where else to post this, but hopefully someone reads it and thinks, Ah right, let me ask the Steam Machine Product team if they're building with new-lg4ff installed and available.

Hope that I'm right, and that this is the fix you need.
HTH
Rick
